### ISSUE TITLE
x86 SIMD codes would cause text relocations

### ISSUE THREAD

**Issue by he1l0** [libjpeg-turbo/libjpeg-turbo#105]
From API level 23, shared objects must not contain text relocations for Android. But the x86 SIMD code in libjpeg-turbo would cause text relocations and forbidden shared objects to be load.
Details could be found in http://android-developers.blogspot.com/2016/06/android-changes-for-ndk-developers.html

To deal with text relocation in assembly codes, this would be helpful: https://wiki.gentoo.org/wiki/Hardened/Textrels_Guide

**Comment by seven332** [comment]
Add this to your Android.mk file.

```makefile
ifeq ($(TARGET_ARCH_ABI), x86)
    LOCAL_ASMFLAGS := -DELF -DPIC
endif
```

**Comment by dcommander** [comment]
Hopefully that fixes the issue that the OP was having.  Otherwise, I have no clue how to fix it.
