### ISSUE TITLE
Possible problem with MSVS 2015 and not using TJSAMP_GRAY on tjCompress2.

### ISSUE THREAD

**Issue by GhostTyper** [libjpeg-turbo/libjpeg-turbo#110]
This is my first try with libjpeg-turbo and TurboJPEG API, so this may be a mistake of mine - if so, i'm sorry to bother you. I have a strange behaviour when using (for example) `TJSAMP_444` on `tjCompress2` with non static lib x86 on MSVS 2015. `TJSAMP_GRAY` instead is working fine.

Because `TJSAMP_GRAY` is working fine i'm unsure if this is 100% my fault, so i'm writing here. I described everything in detail here:

http://stackoverflow.com/questions/39950457/turbojpeg-api-from-libjpeg-turbo-1-5-1-vc-exe-produces-wrong-output

I guess it's some mistake with my settings or with MSVC 2015, because writing a C#-program and P-Invoking the precompiled dll works just fine. I hope someone will get whats wrong just by looking on the images in the linked post above.

**Comment by dcommander** [comment]
Add `_O_BINARY` to the _wopen() flags.

**Comment by GhostTyper** [comment]
Thank you.

I am so ashamed that I donated 25 USD to the project. Excuse me for bothering you.

**Comment by dcommander** [comment]
I always appreciate donations.  :)  No bother.
