### ISSUE TITLE
exif data not updated

### ISSUE THREAD

**Issue by Ndolam** [libjpeg-turbo/libjpeg-turbo#129]
jpegtran -copy all -rotate 90 IMG_4603.JPG >! a.jpg
does not update the Pixel X Dimension or Pixel Y Dimension, which means
that after the rotation, the exif data does not agree with the image.
At least for the one picture I rotated.

**Comment by dcommander** [comment]
libjpeg-turbo doesn't properly handle EXIF data in general.  Doing so would require the use of an external library.  See:

https://sourceforge.net/p/libjpeg-turbo/mailman/message/32235491/

**Comment by dcommander** [comment]
The preferred workaround seems to be to use exiftran:

**Comment by dcommander** [comment]
See also:
https://sourceforge.net/p/libjpeg-turbo/discussion/1086868/thread/8fa77876/

**Comment by Ndolam** [comment]
On Sat, Dec 10, 2016 at 15:52 (-0800), DRC wrote:

> libjpeg-turbo doesn't properly handle EXIF data in general.  Doing so would require the use of an external library.  See:

> https://sourceforge.net/p/libjpeg-turbo/mailman/message/32235491/


On Sat, Dec 10, 2016 at 15:55 (-0800), DRC wrote:

> See also:
> https://sourceforge.net/p/libjpeg-turbo/discussion/1086868/thread/8fa77876/


Thanks for the information.

**Comment by dcommander** [comment]
Actually, if I understand correctly, this might have been fixed in the recent 1.5.2 release.  Refer to https://github.com/libjpeg-turbo/libjpeg-turbo/commit/a0b7de9a47358a19b31db447dbf02b488463eb7e.  And sorry for misunderstanding what you were asking.
