### ISSUE TITLE
Different scanlines with and without memory sanitizer

### ISSUE THREAD

**Issue by realtim** [libjpeg-turbo/libjpeg-turbo#139]
Consider the program that reads jpeg file, calculates crc (or any hash function) of each scanline and prints it. Like this:
```
#include <stdio.h>
#include <turbojpeg/jpeglib.h>
#include <zlib.h>

int main(int argc, char **argv) {
  struct jpeg_decompress_struct cinfo;
  struct jpeg_error_mgr std_err;
  FILE *infile;
  JSAMPARRAY buffer;
  int row_stride;
  
  if (argc > 1 && (infile = fopen(argv[1], "r"))) {

    cinfo.err=jpeg_std_error(&std_err);
    jpeg_create_decompress(&cinfo);
    jpeg_stdio_src(&cinfo, infile);
    (void) jpeg_read_header(&cinfo,TRUE);
    cinfo.dct_method=JDCT_FLOAT;
    (void) jpeg_start_decompress(&cinfo);
    row_stride = cinfo.output_width * cinfo.output_components;
    buffer = (*cinfo.mem->alloc_sarray) ((j_common_ptr) &cinfo, JPOOL_IMAGE, row_stride, 1);

		while (cinfo.output_scanline < cinfo.output_height) {
			(void) jpeg_read_scanlines(&cinfo, buffer, 1);
      printf("%ld\n", crc32(0, (unsigned const char *)buffer[0], row_stride*sizeof(JSAMPLE)));
		}
		(void) jpeg_finish_decompress(&cinfo);
		jpeg_destroy_decompress(&cinfo);
		fclose(infile);

  } else {
    printf("Args problem. Usage: %s filename\n", argv[0]);
    return 1;
  }
}
```
The output will differ (though not all lines usually) between the program compiled normally and the program compiled with `-fsanitize=memory`. I used clang++ 3.7.1 and clang++ 3.9. The result is the same.

I tested several jpeg files I found nearby with nearly similar results. Example:
https://c2.staticflickr.com/4/3002/2616555911_658a4abd85_b.jpg ([origin](https://www.flickr.com/photos/jcapaldi/2616555911))

Update: I don't use SIMD in MSAN build. 
> The SSE/SSE2 floating point DCT implementation in libjpeg-turbo is ever so slightly more accurate than the implementation in libjpeg v6b, but not by any amount perceptible to human vision (generally in the range of 0.01 to 0.08 dB gain in PNSR.)

Probably means it's not a bug but a feature?

**Comment by dcommander** [comment]
Exactly.  The floating point DCT results will differ slightly in the non-SIMD vs. SIMD cases.  That has nothing to do with the use of MSAN.  In general, it is very difficult to guarantee bitwise-identical results with the floating point DCT.  For the most part, that DCT algorithm is a legacy feature.  The quality advantages it has vs. the slow integer DCT are imperceptible.
