### ISSUE TITLE
libjpeg-turbo as JPEG reference software?

### ISSUE THREAD

**Issue by thorfdbg** [libjpeg-turbo/libjpeg-turbo#148]
Darrell,

sorry for contacting you in this rather unconventional way, but I was not able to find a valid email address.

libjpeg-turbo is certainly the most prominent and most-used implementation of the JPEG standard, and as such the most important lossy still image compression deployed on the world. Now, strangely enough, "we", namely the ISO standardization group behind JPEG, also named JPEG (more formally SC29WG1), have long missed the creation of a formal "ISO reference" for a JPEG implementation, of which libjpeg-turbo would be of course an excellent candidate.

To give you an idea: A "reference software" is a code that points users and vendors to a piece of software that tells them "how JPEG is supposed to be done correctly", it is a guidance for JPEG technology.  Currently, there simply is no such code.

Now, recently, we started an activity that will, hopefully, result in the creation of such a standard, and created for that a "draft call for proposals" asking for input or contribution in this direction.

Now, certainly, libjpeg-turbo is the de-facto reference as far as JPEG implementations are concerned, and you are certainly a very knowledgable person in this area, so I would be very glad if you could comment on or even respond to our "draft call for proposals" for such a reference software - which you find here on the official JPEG webpage:

https://jpeg.org/items/20170413_cfp_jpeg_reference_software.html

I would be very happy if you as the libjpeg-turbo maintainer would respond to this "draft" call, or even better, would be able to contribute your software as a candidate for such a reference software.

If you have further questions, please contact me by mail at richter AT tik uni-stuttgart DOT de.

Best regards,

Thomas Richter

**Comment by dcommander** [comment]
Answered on libjpeg-turbo-devel:
https://sourceforge.net/p/libjpeg-turbo/mailman/libjpeg-turbo-devel/thread/9a3ff9fd-1494-a66d-e3a8-7c5496b6a7fd%40tik.uni-stuttgart.de/#msg35807472
