### ISSUE TITLE
Uninitialized values in the parsing and processing of jpeg files

### ISSUE THREAD

**Issue by gaa-cifasis** [libjpeg-turbo/libjpeg-turbo#15]
Hello,

I have found some uninitialized values in the parsing and processing of jpeg files using libjpeg-turbo (tested in Ubuntu 14.04 using libjpeg-turbo 8.0.2). According to valgrind, these values are coming from a heap allocation, so they can potentially allow to leak some private information from previously free buffers. (this is a particularly bad problem in big applications like browsers). A small test case is available here:

https://gist.github.com/gaa-cifasis/c759307cbc0936562b72/raw/dca16e5867adb02c4f6629aee5fbccb1eeb6c33a/uninitialized.jpeg.gz

and the complete valgrind report is here:

$ valgrind --track-origins=yes djpeg uninitialized.jpeg > /dev/null

Corrupt JPEG data: premature end of data segment
==5414== Syscall param write(buf) points to uninitialised byte(s)
==5414==    at 0x5177870: __write_nocancel (syscall-template.S:81)
==5414==    by 0x5105002: _IO_file_write@@GLIBC_2.2.5 (fileops.c:1261)
==5414==    by 0x51064DB: _IO_do_write@@GLIBC_2.2.5 (fileops.c:538)
==5414==    by 0x510488F: _IO_file_sync@@GLIBC_2.2.5 (fileops.c:892)
==5414==    by 0x50F9F51: fflush (iofflush.c:41)
==5414==    by 0x404214: ??? (in /usr/bin/djpeg)
==5414==    by 0x4013B9: ??? (in /usr/bin/djpeg)
==5414==    by 0x50ADEC4: (below main) (libc-start.c:287)
==5414==  Address 0x4026034 is not stack'd, malloc'd or (recently) free'd
==5414==  Uninitialised value was created by a heap allocation
==5414==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==5414==    by 0x4E639F3: alloc_large (in /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2)
==5414==    by 0x4E63C56: alloc_sarray (in /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2)
==5414==    by 0x4E534A7: jinit_d_main_controller (in /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2)
==5414==    by 0x4E56AF5: jinit_master_decompress (in /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2)
==5414==    by 0x4E4D4E4: jpeg_start_decompress (in /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2)
==5414==    by 0x401356: ??? (in /usr/bin/djpeg)
==5414==    by 0x50ADEC4: (below main) (libc-start.c:287)

This test case was found using QuickFuzz

Regards,
Gustavo

**Comment by dcommander** [comment]
I've seen this before, but it was due to valgrind not properly detecting that the SSE2 instructions are initializing the buffer in question.  Can you confirm whether this issue occurs when the library is built with `--without-simd`?  I strongly suspect that it doesn't.

**Comment by dcommander** [comment]
Also note that there is no such thing as "libjpeg-turbo 8.0.2."  8.0.2 is the API version that the library supports when built with `--with-jpeg8`, but that version number tells me nothing about the actual version of the code you were using.

**Comment by gaa-cifasis** [comment]
> I've seen this before, but it was due to valgrind not properly detecting that the SSE2 instructions are initializing the buffer in question. Can you confirm whether this issue occurs when the library is built with --without-simd? I strongly suspect that it doesn't.

Let's try to rebuild.. 

> Also note that there is no such thing as "libjpeg-turbo 8.0.2." 8.0.2 is the API version that the library supports when built with --with-jpeg8, but that version number tells me nothing about the actual version of the code you were using.

Sorry about that. I'm using the package libjpeg-turbo8 1.3.0-0ubuntu2 in 64_x86.

**Comment by gaa-cifasis** [comment]
As you suspected, there is no issue recompiling with --without-simd . Thanks for the quick response. Now i will use the recompiled version for more testing.

**Comment by mayeut** [comment]
@dcommander,

I think I ran into this today.

> I've seen this before, but it was due to valgrind not properly detecting that the SSE2 instructions are initializing the buffer in question. Can you confirm whether this issue occurs when the library is built with --without-simd? I strongly suspect that it doesn't.

Do you have more information at hand about which SSE2 instruction, a more detailed analysis ?
It would be a good thing not to get this valgrind error if possible so I though I'd asked before digging into this.

**Comment by dcommander** [comment]
Unfortunately not.  Sorry.

**Comment by mayeut** [comment]
Ok, thanks.
