### ISSUE TITLE
Does tjTransform support -progressive and -copy ?

### ISSUE THREAD

**Issue by samson-wang** [libjpeg-turbo/libjpeg-turbo#153]
The jpegtran program has the -progressive and -copy arguments. However, the `tjTransform` function seems to support only crop, rotate, scale, flip and other operations that will modify the image?

**Comment by dcommander** [comment]
Not at the moment, but it would be straightforward to add those as transform options.  The TurboJPEG API has evolved purely in response to user demand, so basically I add things to it only when people ask.  :)

**Comment by samson-wang** [comment]
@dcommander  
Fantastic! Thank you!
So we will see the feature soon?

**Comment by dcommander** [comment]
I don't know.  I was awarded an R&D grant for next-gen development of libjpeg-turbo back in February, but thus far the money has not arrived, and that is stalling development right now.

**Comment by samson-wang** [comment]
Oops... It's June.

**Comment by dcommander** [comment]
I'm doing everything I can.  There is no other source of funding for this project, and I can no longer afford to take projects on a pro bono basis.

**Comment by samson-wang** [comment]
Agree.
I'm not quite familiar with the JPEG coding system. So I can't help you right now.
Hope that the fund comes soon.

**Comment by dcommander** [comment]
A flag for enabling progressive coding has been implemented in the dev branch (TurboVNC 1.6 evolving.)  Regarding `-copy`, the tjTransform() function already copies all markers, so I need to understand exactly what you're trying to accomplish.  Do you want it to not copy markers at all?  Copy just the comments?

**Comment by samson-wang** [comment]
@dcommander  Thank you very much for your update. 
I now process lots of pictures. So I want to make the image smaller by `-copy none -progressive`. In addition, transformed images can be better de-duplicated by their md5.
My pipeline now all written in python. If the options added to the `tjTransform`. It will be much more efficient and elegant.
Thank you again for your help.

**Comment by dcommander** [comment]
OK, that makes sense.  I will implement a new transform option for disabling the copying of markers, since the default behavior is to copy all of them.

**Comment by samson-wang** [comment]
I have tried your update.
Works greaaaaaat. Thanks!
Waiting for the `copy` option!

**Comment by dcommander** [comment]
Implemented in dev.
