### ISSUE TITLE
powerpc cross-compile with gcc-7.1 fails

### ISSUE THREAD

**Issue by rwmacleod** [libjpeg-turbo/libjpeg-turbo#159]
I'm not sure if there's anthing for people working on this project to do but as an FYI:

Using the Yocto build system and oe-core/master, to build for qemuppc, I see:

| powerpc-oe-linux-libtool: compile:  powerpc-oe-linux-gcc -m32 -mhard-float -mcpu=7400 -mno-spe --sysroot=/ala-lpggp22/rmacleod/src/distro/yocto/b/ljp/tmp-glibc/work/ppc7400-oe-linux/libjpeg-turbo/1_1.5.1-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../libjpeg-turbo-1.5.1/simd -I.. -I../../libjpeg-turbo-1.5.1 -Wall -maltivec -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/ala-lpggp22/rmacleod/src/distro/yocto/b/ljp/tmp-glibc/work/ppc7400-oe-linux/libjpeg-turbo/1_1.5.1-r0=/usr/src/debug/libjpeg-turbo/1_1.5.1-r0 -fdebug-prefix-map=/ala-lpggp22/rmacleod/src/distro/yocto/b/ljp/tmp-glibc/work/ppc7400-oe-linux/libjpeg-turbo/1_1.5.1-r0/recipe-sysroot-native= -fdebug-prefix-map=/ala-lpggp22/rmacleod/src/distro/yocto/b/ljp/tmp-glibc/work/ppc7400-oe-linux/libjpeg-turbo/1_1.5.1-r0/recipe-sysroot= -c ../../libjpeg-turbo-1.5.1/simd/jdcolor-altivec.c  -fPIC -DPIC -o .libs/libsimd_altivec_la-jdcolor-altivec.o
| In file included from ../../libjpeg-turbo-1.5.1/simd/jdcolor-altivec.c:42:0:
| ../../libjpeg-turbo-1.5.1/simd/jdcolext-altivec.c: In function 'jsimd_ycc_rgb_convert_altivec':
| ../../libjpeg-turbo-1.5.1/simd/jdcolext-altivec.c:222:17: internal compiler error: Segmentation fault
|            edgeh = vec_ld(min(num_cols - 1, RGB_PIXELSIZE * 16), outptr);
|            ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| In file included from ../../libjpeg-turbo-1.5.1/simd/jdmerge-altivec.c:42:0:
| ../../libjpeg-turbo-1.5.1/simd/jdmrgext-altivec.c: In function 'jsimd_h2v1_merged_upsample_altivec':
| ../../libjpeg-turbo-1.5.1/simd/jdmrgext-altivec.c:247:17: internal compiler error: Segmentation fault
|            edgeh = vec_ld(min(num_cols - 1, RGB_PIXELSIZE * 16), outptr);
|            ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Bug open for Yocto and Gcc:
https://bugzilla.yoctoproject.org/show_bug.cgi?id=11754
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81317

I've tried 1.5.2 and as the altivec code hasn't changed, the bug hasn't either. :)
Gcc is ICEing over the first arg to vec_ld(min(num_cols - 1, RGB_PIXELSIZE * 16), outptr);
as explained in the gcc defect report.

**Comment by dcommander** [comment]
OK, keep us posted. If there is something I can do to work around it in our code, I'm happy to do so.

**Comment by dcommander** [comment]
Closing as SEP, but please add further details if/when it becomes fixed externally.
