### ISSUE TITLE
Provision of jar with embedded build of the library

### ISSUE THREAD

**Issue by rleigh-codelibre** [libjpeg-turbo/libjpeg-turbo#160]
Hi,

For many years, the OME Bio-Formats package has used a "fork" of turbojpeg (from 1.2.1).  The code changes amount to doing this:

```
diff --git a/java/org/libjpegturbo/turbojpeg/TJLoader.java.in b/java/org/libjpegturbo/turbojpeg/TJLoader.java.in
index 8397780..26f7c02 100644
--- a/java/org/libjpegturbo/turbojpeg/TJLoader.java.in
+++ b/java/org/libjpegturbo/turbojpeg/TJLoader.java.in
@@ -30,6 +30,6 @@ package org.libjpegturbo.turbojpeg;
 
 final class TJLoader {
   static void load() {
-    System.loadLibrary("@TURBOJPEG_DLL_NAME@");
+    //System.loadLibrary("@TURBOJPEG_DLL_NAME@");
   }
 }
```

and then in the turbojpeg.jar:

```
% jar tfv target/ome-turbojpeg-0.1.0-SNAPSHOT.jar 
   576 Fri Jul 21 11:37:02 BST 2017 META-INF/MANIFEST.MF
     0 Fri Jul 21 11:37:02 BST 2017 META-INF/
     0 Fri Jul 21 11:36:58 BST 2017 META-INF/lib/
     0 Fri Jul 21 11:36:58 BST 2017 META-INF/lib/linux_32/
     0 Fri Jul 21 11:36:58 BST 2017 META-INF/lib/linux_64/
     0 Fri Jul 21 11:36:58 BST 2017 META-INF/lib/osx_64/
     0 Fri Jul 21 11:36:58 BST 2017 META-INF/lib/osx_32/
     0 Fri Jul 21 11:36:58 BST 2017 META-INF/lib/windows_64/
     0 Fri Jul 21 11:36:58 BST 2017 META-INF/lib/windows_32/
     0 Fri Jul 21 11:36:58 BST 2017 META-INF/lib/osx_ppc/
     0 Fri Jul 21 11:37:00 BST 2017 org/
     0 Fri Jul 21 11:37:00 BST 2017 org/libjpegturbo/
     0 Fri Jul 21 11:37:00 BST 2017 org/libjpegturbo/turbojpeg/
     0 Fri Jul 21 11:37:02 BST 2017 META-INF/maven/
     0 Fri Jul 21 11:37:02 BST 2017 META-INF/maven/org.openmicroscopy/
     0 Fri Jul 21 11:37:02 BST 2017 META-INF/maven/org.openmicroscopy/ome-turbojpeg/
449499 Fri Jul 21 11:36:58 BST 2017 META-INF/lib/linux_32/libturbojpeg.so
352704 Fri Jul 21 11:36:58 BST 2017 META-INF/lib/linux_64/libturbojpeg.so
325912 Fri Jul 21 11:36:58 BST 2017 META-INF/lib/osx_64/libturbojpeg.dylib
349184 Fri Jul 21 11:36:58 BST 2017 META-INF/lib/windows_32/turbojpeg.dll
381440 Fri Jul 21 11:36:58 BST 2017 META-INF/lib/windows_64/turbojpeg.dll
   106 Fri Jul 21 11:37:00 BST 2017 META-INF/maven/org.openmicroscopy/ome-turbojpeg/pom.properties
786272 Fri Jul 21 11:36:58 BST 2017 META-INF/lib/osx_32/libturbojpeg.dylib
786272 Fri Jul 21 11:36:58 BST 2017 META-INF/lib/osx_ppc/libturbojpeg.dylib
  1179 Fri Jul 21 11:37:00 BST 2017 org/libjpegturbo/turbojpeg/TJScalingFactor.class
  7412 Fri Jul 21 11:37:00 BST 2017 org/libjpegturbo/turbojpeg/TJCompressor.class
  1600 Fri Jul 21 11:37:00 BST 2017 org/libjpegturbo/turbojpeg/TJTransform.class
   349 Fri Jul 21 11:37:00 BST 2017 org/libjpegturbo/turbojpeg/TJLoader.class
  7949 Fri Jul 21 11:37:00 BST 2017 org/libjpegturbo/turbojpeg/TJDecompressor.class
  2822 Fri Jul 21 11:37:00 BST 2017 org/libjpegturbo/turbojpeg/TJ.class
   317 Fri Jul 21 11:37:00 BST 2017 org/libjpegturbo/turbojpeg/TJCustomFilter.class
  2437 Fri Jul 21 11:37:00 BST 2017 org/libjpegturbo/turbojpeg/TJTransformer.class
 12381 Fri Jul 21 11:36:50 BST 2017 META-INF/maven/org.openmicroscopy/ome-turbojpeg/pom.xml
```

See [this git repo](https://github.com/rleigh-codelibre/ome-turbojpeg/tree/maven) for the source corresponding to the above build; and [this repo](https://github.com/openmicroscopy/bioformats/tree/1afe69300994822fc2723b34996fa7f6153ae725/components/forks/turbojpeg) for its origin (the former is a filter-branch of the latter to restrict the history to just the turbojpeg changes; but the above diff is what it boils down to in terms of code changes).

The change here is the addition of prebuilt libjpeg-turbo libraries for various platforms which means the jar can be directly consumed by Java codebases without the need to manually install the libjpeg-turbo shared library at the system level, which can greatly ease deployment complexity (at the expense of requiring an appropriate DLL in the jar).

I'd like to eliminate our fork and custom builds as much as possible.  Some questions relating to the above:

- are there any builds of the vanilla jar on maven central or anywhere else?  I didn't see anything on your download page, but I may have missed it.
- are there any builds provided by yourselves or anyone else which provide a jar with embedded versions of the libraries?  I didn't see anything on maven central.
- would it be possible to make the `System.loadLibrary()` call conditional somehow, so that it will fall back to the embedded library if a system copy is not present?  (Or vice versa, depending upon which you prefer.)  This would allow third-parties like ourselves to bundle copies of the libraries for the platforms we support without needing to patch the sources.  I'm afraid I'm not a Java JNI expert, so I'd have to look in more detail at any subtleties involved here.

Are there any other details to consider?

Edit: Just FYI we're using a separate library called [native-lib-loader](https://github.com/scijava/native-lib-loader) to do the loading of these libraries before using turbojpeg.

From the point of view of our usage of turbojpeg what we would really like to be able to do is to selectively *disable* the use of `System.loadLibrary()` in `TJLoader.load()` when we already loaded a native library, otherwise use the system copy.  Is there any way we could provide this information e.g. through a system properly with `System.setProperty()` or some other means?  If we could do this, we could use turbojpeg unpatched, and then provide a supplementary jar containing the binary builds.

Thanks,
Roger

**Comment by dcommander** [comment]
Our project doesn't use Maven Central.  However, our official builds do provide a zip file with pre-built JARs containing the TurboJPEG shared libraries for 32-bit and 64-bit Linux, Windows, and OS X.  For instance:  https://sourceforge.net/projects/libjpeg-turbo/files/1.5.2/libjpeg-turbo-1.5.2-jws.zip.  I deploy those JARs with my own product (TurboVNC), which can deliver its client software via Java Web Start.

If that doesn't meet your needs, then I am open to either:
* Producing a single JAR file containing the aforementioned libraries, as well as the TurboJPEG Java classes.  This would be produced as a supplemental package during official builds, in much the same way that the aforementioned zip file is produced.  However, note that I could not produce the same exact results as your JAR file.  I wouldn't be able to include any of the Maven stuff or OS X PPC code.
* Making the `System.loadlibrary()` call optional.  This would be quite easy to do with a CMake/configure option.

**Comment by dcommander** [comment]
But actually, can't you already override `system.library.path`?  I guess maybe I don't understand how you are able to get the TurboJPEG shared libraries to load at all without using `System.loadlibrary()`.  I've never distributed a combined JAR such as the one you're distributing.  I've always used JWS, which generally has you deploy the Java and native code in separate JARs.

**Comment by dcommander** [comment]
How do you want to proceed with this?

**Comment by rleigh-codelibre** [comment]
I'm pretty sure we can use `java.library.path` on our side which would avoid the need for any changes to the existing `turbojpeg` jar behaviour.  It means changes to another third-party jar which complicates things a little, but I think that should solve the problem simply and portably, so I think this issue can probably be closed.

Thanks,
Roger
