### ISSUE TITLE
tjCompressFromYUV

### ISSUE THREAD

**Issue by q979713444** [libjpeg-turbo/libjpeg-turbo#161]
tjCompressFromYUV function conversion nv21 data for the grayscale map, lost color，what is the matter?

**Comment by dcommander** [comment]
Not sure.  You're going to have to be more specific.  I don't understand what "conversion nv21 data for the grayscale map" means.

**Comment by q979713444** [comment]
Thanks, I have solved it.   nv21(YUV420SP)  to  I420

**Comment by q979713444** [comment]
Now I am having a new problem，When the function tjCompressFromYUV is executed for a while, the crash occurs in Android 。
`JNIEXPORT jint JNICALL Java_com_sensetime_libjpegturbo_TurboJpegLib_yuv2jpeg
  (JNIEnv * env, jclass jclazz, jbyteArray nv21, jint width, jint height,
		  jint subsample, jbyteArray jpeg,jint quality,jint flags){

	tjhandle handle = NULL;
	int padding = 1; // 1或4均可，但不能是0
	int ret = 0;

	if((handle=tjInitCompress())==NULL){
		LOGI("tjInitCompress error");
		return 1001;
	}

//	if(env->GetArrayLength(jpeg) < (jsize)tjBufSizeYUV2(width, padding, height, subsample)){
//		LOGI("Destination buffer is not large enough");
//		return 1002;
//	}

	unsigned char *srcBuf = (unsigned char *)env->GetPrimitiveArrayCritical(nv21, 0);
	unsigned char *jpegBuf = (unsigned char *)env->GetPrimitiveArrayCritical(jpeg, 0);
	unsigned long compressSize;

	ret = tjCompressFromYUV(handle, srcBuf, width, padding, height,
			subsample, &jpegBuf, &compressSize, quality, flags); // may crash 

	tjDestroy(handle);
	env->ReleasePrimitiveArrayCritical(nv21, srcBuf, 0);
	env->ReleasePrimitiveArrayCritical(jpeg, jpegBuf, 0);
//	tjFree(jpegBuf);
//	jpegBuf=srcBuf=NULL;

	if (ret < 0) {
		LOGI("compress to jpeg failed: %d\n",ret);
		return ret;
	}
	return compressSize;
}`

**Comment by dcommander** [comment]
We already provide Java/JNI interface classes for all of the TurboJPEG functions, including `tjCompressFromYUV()`.  To compress from a 4:2:0 YUV image with width W and height H, you would do something like this;

```
int strides[3] = { W, W / 2, W / 2 };
YUVImage yuvImage = new YUVImage(W, strides, H, TJ.SAMP_420);
TJCompressor tjc = new TJCompressor();
tjc.setSourceImage(yuvImage);
tjc.setJPEGQuality(whatever_you_want);
jpegImage = tjc.compress(0);
```
Refer to [the complete TurboJPEG Java API documentation](https://cdn.rawgit.com/libjpeg-turbo/libjpeg-turbo/master/java/doc/index.html) for further details.

If you wish to continue using your own JNI interface:
The likely cause of the crashes is that the size of the JPEG buffer isn't large enough, and the underlying libjpeg API is re-allocating the buffer.  You can't re-allocate a Java buffer in JNI, so the only way to use TurboJPEG C functions from Java is to pre-allocate a byte buffer in Java using the worst-case size calculation (refer to: [the documentation of the TJ.bufSize() method](https://cdn.rawgit.com/libjpeg-turbo/libjpeg-turbo/master/java/doc/org/libjpegturbo/turbojpeg/TJ.html#bufSize(int,%20int,%20int))) and then pass `TJFLAG_NOREALLOC` to the TurboJPEG C function.  Or you could just borrow the code from turbojpeg-jni.c and save yourself a lot of trouble.
