### ISSUE TITLE
CMake 3.9.0: Deprecation Warning

### ISSUE THREAD

**Issue by Johnex** [libjpeg-turbo/libjpeg-turbo#164]
Using the latest CMake 3.9.0, i am getting the following deprecation warning:

> CMake Deprecation Warning at CMakeLists.txt:8 (cmake_policy):
>   The OLD behavior for policy CMP0022 will be removed from a future version
>   of CMake.
> 
>   The cmake-policies(7) manual explains that the OLD behaviors of all
>   policies are deprecated and that a policy should be set to OLD only under
>   specific short-term circumstances.  Projects should be ported to the NEW
>   behavior and not rely on setting a policy to OLD.

**Comment by dcommander** [comment]
The new build unified CMake build system in dev already fixes this.
