### ISSUE TITLE
Moving mailing lists -- FEEDBACK REQUESTED FROM COMMUNITY

### ISSUE THREAD

**Issue by dcommander** [libjpeg-turbo/libjpeg-turbo#165]
SourceForge is being evil again.  They removed the ability for project admins to view/manage the members of mailing lists, which was the final straw (I can't even send mail to my own mailing lists using my SourceForge e-mail address anymore.)  I've already moved my other project mailing lists (VirtualGL and TurboVNC) to Google Groups, but given that this project has a much broader reach, I wanted to solicit feedback from the community.  In particular, I realize that Google is banned in some countries that are heavy users of libjpeg-turbo, so I welcome all suggestions for how to migrate this aspect of our project to a platform other than SourceForge.  Please comment here.

If I don't hear any feedback in a timely manner, I will proceed with migrating to Google Groups.

**Comment by smasherprog** [comment]
google groups is a good place.. I never did like sourceforge

**Comment by dcommander** [comment]
I still think their file release system has a lot of advantages over any other, although at this point, using that site only for file releases and nothing else probably doesn't make a lot of sense.  I have to keep the SF project active in order to retain the "institutional memory" of the project-- i.e. the old bug reports, discussions, and mailing list archives that I occasionally need to refer to when solving a problem-- but I would like to eventually just use SF as a mirror and not rely on it for any project services.

**Comment by totaam** [comment]
-1 for google groups, I find their web UI is as bad as SF.
(but I'm not sure what to recommend instead)

**Comment by dcommander** [comment]
There is always the possibility of running Mailman on my own server, at libjpeg-turbo.org, but I'd rather not do that, as it represents a single point of failure.  And I agree that Google Groups' UI is not ideal, but I don't know of many other solutions that are cloud-based.

**Comment by totaam** [comment]
+1 for mailman, although it is a single point of failure and it has maintenance costs, it is also a lot more usable than the other options.
If you find a better cloud-based solution, I would be interested in moving some lists myself.

**Comment by dcommander** [comment]
My main concern is preserving the institutional memory of the project, and that means hosting the list on a platform that isn't specifically tied to me.  libjpeg-turbo.org is hosted on a server that I pay for, so if I went away, the server would as well.

**Comment by vtorri** [comment]
look  here : http://savannah.nongnu.org/maintenance/WhyChooseSavannah/ especially all the links at the bottom

**Comment by dcommander** [comment]
From that list, only LaunchPad seems like it would be a good fit for our project MLs, but unfortunately their site appears to be broken and wouldn't let me log in.

![screen shot 2017-08-20 at 9 03 05 am](https://user-images.githubusercontent.com/651941/29495505-8091c6aa-8586-11e7-832f-a8142c77c84f.png)

Hopefully that's a temporary issue, and I can continue evaluating their site once it's fixed.

**Comment by dcommander** [comment]
With all due respect to the anti-Google crowd, I needed to move forward on this, and since my other OSS projects are using Google Groups, it was easiest for me to do so with libjpeg-turbo as well.  It ain't perfect, but it's better than SourceForge.  None of the other proposed solutions panned out, and running MailMan on libjpeg-turbo.org isn't an option because that domain is on a server that I personally run, and I want critical project infrastructure to reside on servers with more fault tolerance.

**Comment by dcommander** [comment]
https://libjpeg-turbo.org/About/MailingLists
