### ISSUE TITLE
How to use LIBJPEG_TURBO_VERSION constant?

### ISSUE THREAD

**Issue by homm** [libjpeg-turbo/libjpeg-turbo#166]
Trying to check libjpeg turbo version somehow.

```c
#if defined(LIBJPEG_TURBO_VERSION)
printf("defined\n");
#endif

defined
```

```c
printf("%s\n", LIBJPEG_TURBO_VERSION);
libImaging/JpegDecode.c:123:20: error: too many decimal points in number
```

```c
#if LIBJPEG_TURBO_VERSION > 1.3
printf("defined\n");
#endif

libImaging/JpegDecode.c:123:5: error: too many decimal points in number
 #if LIBJPEG_TURBO_VERSION > 1.3
     ^
libImaging/JpegDecode.c:123:33: error: floating constant in preprocessor expression
 #if LIBJPEG_TURBO_VERSION > 1.3
                             ^
```

```c
#if LIBJPEG_TURBO_VERSION > 1.3
printf("defined\n");
#endif

libImaging/JpegDecode.c:123:5: error: too many decimal points in number
 #if LIBJPEG_TURBO_VERSION > 1.3.0
     ^
libImaging/JpegDecode.c:123:29: error: too many decimal points in number
 #if LIBJPEG_TURBO_VERSION > 1.3.0
                             ^
```

```c
#if "LIBJPEG_TURBO_VERSION" > "1.5.0"
printf("defined\n");
#endif

libImaging/JpegDecode.c:123:5: error: token ""LIBJPEG_TURBO_VERSION"" is not valid in preprocessor expressions
 #if "LIBJPEG_TURBO_VERSION" > "1.5.0"
     ^
```

```bash
$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
```

I need to detect is current version >= 1.2.1. Is there any other way?

I know about `LIBJPEG_TURBO_VERSION_NUMBER`, but it was introduced in 1.5.0.

**Comment by dcommander** [comment]
Printing the version string is done like this:

```
#include <stdio.h>
#include "jconfig.h"

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

int main(void)
{
  printf("Version: %s\n", TOSTRING(LIBJPEG_TURBO_VERSION));
}
```

A similar trick would allow you to at least compare the version at run time, but unfortunately there is no way to compare strings lexically at compile time (hence the need for `LIBJPEG_TURBO_VERSION_NUMBER`.)  Since the `LIBJPEG_TURBO_VERSION` macro was introduced in 1.2.0, all you would really need to do is check that the macro exists and is not equal to "1.2.0", but I'm not sure how to do the latter (and I spent about 30 minutes googling it.)

**Comment by homm** [comment]
Wow, I don't understand how but `TOSTRING` and `STRINGIFY` actually works. I thing this should be enough for me. Thank you!

**Comment by dcommander** [comment]
To expand on my previous comment, standard C has no way of comparing strings at compile time (http://c-faq.com/cpp/ifstrcmp.html).  You would have to rely on a GNU built-in function, which isn't portable, or some other trick.  If you knew that turbojpeg.h was going to be available, for instance, you could check for the existence of both `LIBJPEG_TURBO_VERSION` and `TJFLAG_FASTDCT`.  The former was introduced in 1.2.0 and the latter in 1.2.1.  But that would only make sense if your software used the TurboJPEG API, which it doesn't appear to.

My only other suggestion would be to define different versions of the function-- one that supports the libjpeg-turbo colorspace extensions and one that doesn't-- and dispatch them at run time.  These two versions of the function could be included from the same source file (see jccolor.c for an example) without duplicating code.  At run time, you don't even need to check the version.  You can just try the colorspace conversion and fall back if it triggers the libjpeg error manager (refer to jcstest.c.)

Also, referencing https://github.com/python-pillow/Pillow/pull/1989#issuecomment-253448281, `JCS_RGB` means "use the compile-time values of `RGB_RED`, `RGB_GREEN`, `RGB_BLUE`, and `RGB_PIXELSIZE`."  libjpeg was originally designed such that those constants could be changed in particular implementations of the library, and libjpeg-turbo honors that design.  Even though the values have been set to make `JCS_RGB` and `JCS_EXT_RGB` equivalent in all modern implementations of libjpeg and libjpeg-turbo, technically an implementation would be within its rights to change those values, so software written to use the libjpeg API should not assume that `JCS_RGB` and `JCS_EXT_RGB` are equivalent.
