### ISSUE TITLE
powerpcspe build broken since 1.5.0

### ISSUE THREAD

**Issue by oerdnj** [libjpeg-turbo/libjpeg-turbo#172]
Hi,

the powerpcspe builds got broken since 1.5.0 release: https://buildd.debian.org/status/logs.php?pkg=libjpeg-turbo&arch=powerpcspe

The builds fail with `error: AltiVec and SPE instructions cannot coexist` in several places:

```
jcgray-altivec.c:1:0: error: AltiVec and SPE instructions cannot coexist
jsimd_powerpc.c:1:0: error: AltiVec and SPE instructions cannot coexist
jcsample-altivec.c:1:0: error: AltiVec and SPE instructions cannot coexist
jccolor-altivec.c:1:0: error: AltiVec and SPE instructions cannot coexist
```

**Comment by dcommander** [comment]
libjpeg-turbo 1.5 introduced AltiVec SIMD extensions, which are currently enabled for all powerpc* targets, but I guess not all powerpc* targets support those instructions.  You can add `--without-simd` to the configure command on powerpcspe builds to work around the problem temporarily.  If there is a way for the build system to auto-detect whether AltiVec instructions are supported at build time, I'm happy to add that enhancement, but I need a clue as to how to implement it.  I have no access to PowerPC SPE hardware and haven't even heard of that hardware until now.  Note that the relevant code is here: https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/configure.ac#L519-L522.  Maybe it's as simple as testing whether the host triplet matches "powerpc-*-*spe*", but it seems like a more robust approach would be to try compiling a simple AltiVec program before enabling the AltiVec SIMD extensions.  Honestly, I had no idea that there were PowerPC platforms that didn't support AltiVec.  IBM paid me to implement those extensions, and they've only been tested on POWER7 and POWER8 hardware.

**Comment by oerdnj** [comment]
I can live with `--without-simd ` on Debian. Coincidentally I could also get you a powerpcspe box if you are interested.

**Comment by dcommander** [comment]
If I could have SSH access to it for an hour or two, I think I could solve this problem the right way.

**Comment by oerdnj** [comment]
I will setup a Turris 1.x box with Debian chroot over the week (unfortunately, there are no build tools in the stock TurrisOS/OpenWRT system there). I would need your public SSH key signed by your GPG key (either here or in the mail).

**Comment by oerdnj** [comment]
Oh, and ... are you capable connecting to IPv6 hosts?

**Comment by dcommander** [comment]
Yes, I can connect to IPv6.  Please e-mail me:
https://libjpeg-turbo.org/About/Contact
and I will reply with my key.  You can use encrypted e-mail if you wish (my GPG key is at the link above.)
