### ISSUE TITLE
v1.4.1 does not install needed header file jinclude.h 

### ISSUE THREAD

**Issue by Corin-EU** [libjpeg-turbo/libjpeg-turbo#18]
As per the resolution of issue #17 

"libjpeg requires that you include jinclude.h before including jpeglib.h."

libjpeg-turbo v1.4.1 source has the file jinclude.h but does not install it from the make install command.

     export DESTDIR=/var/tmp/libjpeg-turbo

(just to put the test run installation into an obvious scratch directory)

     make V=1 install

     /bin/mkdir -p '/var/tmp/libjpeg-turbo/usr/local/X11R6/include'
      /usr/bin/install -c -m 644 jerror.h jmorecfg.h jpeglib.h turbojpeg.h '/var/tmp/libjpeg-turbo/usr  /local/X11R6/include'
      /bin/mkdir -p '/var/tmp/libjpeg-turbo/usr/local/X11R6/share/man/man1'
      /usr/bin/install -c -m 644 cjpeg.1 djpeg.1 jpegtran.1 rdjpgcom.1 wrjpgcom.1 '/var/tmp/libjpeg-turbo/usr/local/X11R6/share/man/man1'
      /bin/mkdir -p '/var/tmp/libjpeg-turbo/usr/local/X11R6/include'
     /usr/bin/install -c -m 644 jconfig.h '/var/tmp/libjpeg-turbo/usr/local/X11R6/include'
     make[2]: Leaving directory '/usr/src/build/libjpeg-turbo-1.4.1'

     ls -aFls /var/tmp/libjpeg-turbo/usr/local/X11R6/include/
     total 160
      4 drwxr-xr-x 2 root root  4096 2015-09-11 22:21 ./
      4 drwxr-xr-x 6 root root  4096 2015-09-11 22:21 ../
      4 -rw-r--r-- 1 root root  2211 2015-09-11 22:21 jconfig.h
     16 -rw-r--r-- 1 root root 15081 2015-09-11 22:21 jerror.h
     16 -rw-r--r-- 1 root root 13507 2015-09-11 22:21 jmorecfg.h
     52 -rw-r--r-- 1 root root 49594 2015-09-11 22:21 jpeglib.h
     64 -rw-r--r-- 1 root root 64668 2015-09-11 22:21 turbojpeg.h

So as you can see above, no jinclude.h file is installed.

Therefore jinclude.h needs to be added to the list of header files to install in the target include directory, appending it in Makefile.am to whichever is more appropriate of

     include_HEADERS = jerror.h jmorecfg.h jpeglib.h

or

     nodist_include_HEADERS = jconfig.h

**Comment by dcommander** [comment]
Again, inherited behavior.  But let me investigate further.  My response to the other issue may have been incorrect.

**Comment by dcommander** [comment]
I have updated my response to #17.  jinclude.h is intended to be an internal header file, so I was mistaken in my assertion that you should include that file.  In fact, the libjpeg API requires you to include stdio.h before including jpeglib.h.  That is legacy behavior, and the reasons behind it are no longer valid, but it was an intentional design decision, and breaking with that behavior means potentially breaking backward API compatibility with libjpeg.

**Comment by Corin-EU** [comment]
Thank your for you very speedy response on this issue and clarification of the problem.

As you have explained, the standard is that one must "include stdio.h before including jpeglib.h" and this is not happening in /usr/include/libmng_types.h  (a libmng header file) which includes jpeglib.h without any mention before or after of stdio.h.  So a bug report needs to be submitted to the libmng maintainers.

Thanks once again for your very helpful assistance in pinpointing the problem.
