### ISSUE TITLE
1920x1080 image decode takes long 19ms on S6 edge

### ISSUE THREAD

**Issue by Ideasrefined** [libjpeg-turbo/libjpeg-turbo#181]
My application requires grabbing of USB camera frames (1920x1080) , decode then manipulate and re-encode before saving.

What I am noticing is it takes 19ms on a phone as fast as Galaxy S6 edge to decode a single JPEG frame from the camera. I believe it is too slow given the power of the device.

Is there anything that I might have missed to optimize / move decoding to hardware or anything that might speedup the process ?

**Comment by dcommander** [comment]
Bearing in mind that libjpeg-turbo can only take advantage of a single core (multi-threaded JPEG encoding and decoding has to be implemented at the application level or using a higher-level API), the decompression performance I get on a 1.82 GHz Cortex-A57 core is in the neighborhood of 50-80 Mpixels/sec-- depending on the type of image, the level of chroma subsampling, etc.  What you're getting on a 2.1 GHz Cortex-A57 is ~109 Mpixels/sec, which is good performance for an ARM chip.

If you're using Android 7.0 or later, then libjpeg-turbo is used by the Android JPEG APIs as well.  Some Android phones have hardware-assisted JPEG decoding to supplement, but my understanding is that libjpeg-turbo tends to always be the fastest solution for smaller JPEGs, so phones that have hardware assist will only switch it on for large JPEG images.  However, there is a remote possibility that your phone might do that, so it would be worth benchmarking against the built-in Android JPEG API to see if you can get better performance that way.
