### ISSUE TITLE
windows x86 - visual studio 2010 Linking errors (Lib Version: 1.5.2)

### ISSUE THREAD

**Issue by StillWaters77** [libjpeg-turbo/libjpeg-turbo#184]
Hey,
i installed libjpeg-turbo with the installer (libjpeg-turbo-1.5.2-gcc) from sourceforge.
I tried linking it with my project. When i try running the application, the following message occurs:
`error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "___ms_vsnprintf" in Funktion "_snprintf.constprop.8".`
 I really dont know what ive done wrong, mainly because "nsprintf" is a "cstdio"-function.
Thanks in advance.

**Comment by dcommander** [comment]
Use the Visual Studio version of the SDK, not the GCC version.  The GCC version can only be used with MinGW.
