### ISSUE TITLE
Conan package for libjpeg-turbo

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [libjpeg-turbo/libjpeg-turbo#187]
Hello
Do you know about Conan package manager? Can you add Conan package for libjpeg-turbo and maintain it? Here you can find example of my conan recipe for libpng: https://github.com/ZaMaZaN4iK/conan-libpng

**Comment by dcommander** [comment]
In a word, no.  I don't get paid for my work on libjpeg-turbo unless it is specifically funded or unless it feeds into a funded development opportunity on one of my other open source products.  I have no need for Conan, and thus there is no impetus for me to spend my free time implementing a feature I won't personally use, nor is there sufficient demand for such a feature in the community to justify it.
