### ISSUE TITLE
use of jpeg_simple_progression on a large image results in a segmentation fault

### ISSUE THREAD

**Issue by beaudet** [libjpeg-turbo/libjpeg-turbo#189]
I work for a large museum and we have fairly large source images.  We're using the IIP Image Server to serve image tiles from pyramidal tiffs that use JPEG compression and dynamic on-the-fly resize for our web site with the IIIF Image API.  To allow images to render as quickly as possible, I've added a step to IIP Image Server to produce progressive JPEGs by calling jpeg_simple_progression( &cinfo ) prior to jpeg_start_compress (&cinfo, true).  That works fine except when the JPEG being generated with libjpeg-turbo is larger than a certain size.  I have yet to discover exactly what that size is because it's somewhat inconsistent but it's in the neighborhood of 1600x1600 pixels when the segfault starts happening.  To avoid this, I am skipping jpeg_simple_progression when the width or height of the resulting image exceeds 1024 pixels, but it sure would be nice to not have to worry about that.  Any chance of getting a near term fix for this?  I'm happy to provide any source images or source code if you think this has something to do with the underlying data.

**Comment by dcommander** [comment]
I seriously doubt that this is a bug in our code.  I can compress large progressive images just fine using cjpeg.  Is it possible that you are running into this issue with libtiff?
https://github.com/libjpeg-turbo/libjpeg-turbo/issues/162

**Comment by beaudet** [comment]
This problem is not specific to the 1.5 release of libjpeg-turbo so I doubt the hypothesis that it's tied to the support for cinfo.mem.max_memory_to_use that was introduced in version 1.5 (as per #162) is correct.  I have tried the default version that ships with RHEL6 (1.2.1) as well as installing the latest RPM for 1.5 and the segfault occurs regardless of the version used.  Also, in the particular code involved (see below), the operations are all libjpeg calls at that point and although libtiff could have certainly set some kind of library default, that library isn't involved in the creation of the JPEG from uncompressed raw memory at this point in the process.  Here's the code:

```
void JPEGCompressor::InitCompression( const RawTile& rawtile, unsigned int strip_height, unsigned long icc_profile_len, unsigned char *icc_profile_buf ) throw (string)
{

  // Do some initialisation
  dest = &dest_mgr;

  // Set up the correct width and height for this particular tile
  width = rawtile.width;
  height = rawtile.height;
  channels = rawtile.channels;


  // Make sure we only try to compress images with 1 or 3 channels
  if( ! ( (channels==1) || (channels==3) )  ){
    throw string( "JPEGCompressor: JPEG can only handle images of either 1 or 3 channels" );
  }

  // JPEG can only handle 8 bit data
  if( rawtile.bpc != 8 ) throw string( "JPEGCompressor: JPEG can only handle 8 bit images" );


  // We set up the normal JPEG error routines, then override error_exit.
  cinfo.err = jpeg_std_error( &jerr );


  // Overide the error_exit function with our own.
  // Hmmm, we have to do this assignment in C due to the strong type checking of C++
  //  or something like that. So, we use an extern "C" function declared at the top
  //  of this file and pass our arguments through this. I'm sure there's a better
  //  way of doing this, but this seems to work :/

  //   cinfo.err.error_exit = iip_error_exit;
  setup_error_functions( &cinfo );

  jpeg_create_compress( &cinfo );


  /* The destination object is made permanent so that multiple JPEG images
   * can be written to the same file without re-executing jpeg_stdio_dest.
   * This makes it dangerous to use this manager and a different destination
   * manager serially with the same JPEG object, because their private object
   * sizes may be different.  Caveat programmer.
   */
  if( !cinfo.dest ){
    // first time for this JPEG object?
    cinfo.dest = ( struct jpeg_destination_mgr* )
      ( *cinfo.mem->alloc_small )
      ( (j_common_ptr) &cinfo, JPOOL_PERMANENT, sizeof( iip_destination_mgr ) );
  }


  dest = (iip_dest_ptr) cinfo.dest;
  dest->pub.init_destination = iip_init_destination;
  //dest->pub.empty_output_buffer = iip_empty_output_buffer;
  dest->pub.term_destination = iip_term_destination;
  dest->strip_height = strip_height;

  cinfo.image_width = width;
  cinfo.image_height = height;
  cinfo.input_components = channels;
  cinfo.in_color_space = ( channels == 3 ? JCS_RGB : JCS_GRAYSCALE );
  jpeg_set_defaults( &cinfo );

  // Set compression point quality (highest, but possibly slower depending
  //  on hardware) - must do this after we've set the defaults!
  cinfo.dct_method = JDCT_FASTEST;

  jpeg_set_quality( &cinfo, Q, TRUE );

  /*************************************************************************
   for future support of JPEGs (progresive) and PNGs (interlaced) - @beaudet
   jpeg_simple_progression( &cinfo );
  *************************************************************************/
  // enable progressive jpeg support but only if the requested width and height
  // are relatively small - there's a bug in the progressive jpeg script that
  // causes a segfault when requesting images that are larger than a certain
  // size
  if ( width <= 1024 && height <= 1024 )
    jpeg_simple_progression( &cinfo );

  jpeg_start_compress( &cinfo, TRUE );


  // Copy the JPEG header data to our output tile buffer
  size_t datacount = dest->size - dest->pub.free_in_buffer;
  header_size = datacount;
  if( datacount > 0 ){
    memcpy( header, dest->buffer, datacount );
  }


  // Reset the pointers
  size_t mx = cinfo.image_width * strip_height * cinfo.input_components;
  dest->size = mx + MX;
  dest->pub.next_output_byte = dest->buffer;
  dest->pub.free_in_buffer = mx + MX;

  // Add an identifying comment
  jpeg_write_marker( &cinfo, JPEG_COM, (const JOCTET*) "Generated by IIPImage", 21 );

  // embed icc profile if one is supplied
  if ( icc_profile_buf != NULL )
    write_icc_profile( &cinfo, icc_profile_buf, icc_profile_len );

}

```

**Comment by beaudet** [comment]
Actually, I just entered some additional logging into the application and it seems to get through this function prior to the segfault, so the problem must be somewhere else.  Perhaps it has something to do with the size of the resulting image or something like that.  I'll do some more digging and report back.  Hopefully this is just a problem with the IIP code.

**Comment by beaudet** [comment]
It seems to be segfaulting in the call to jpeg_finish_compress( &cinfo ) but I think that's just an artifact of a memory corruption problem elsewhere that is occurring when progressive is used.  I tried switching out the simple progression with a custom scan file from rdswitch and I'm getting the same results not surprisingly.  This will take a lot more digging so I think I'm just going to leave progressive support out of IIP for now until I can return to study the problem in more depth.
