### ISSUE TITLE
fatal error: jconfig.h: No such file or directory

### ISSUE THREAD

**Issue by masonjames** [libjpeg-turbo/libjpeg-turbo#19]
Hiya folks,

Trying to run `nw-gyp rebuild --target="0.12.3"`

And I get the following:
`gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/pi/PopcornTV/node_modules/node-images/build'
  CC(target) Release/obj.target/libpng/gyp/third-party/libpng/png.o
  CC(target) Release/obj.target/libpng/gyp/third-party/libpng/pngerror.o
  CC(target) Release/obj.target/libpng/gyp/third-party/libpng/pngget.o
  CC(target) Release/obj.target/libpng/gyp/third-party/libpng/pngmem.o
  CC(target) Release/obj.target/libpng/gyp/third-party/libpng/pngpread.o
  CC(target) Release/obj.target/libpng/gyp/third-party/libpng/pngread.o
  CC(target) Release/obj.target/libpng/gyp/third-party/libpng/pngrio.o
  CC(target) Release/obj.target/libpng/gyp/third-party/libpng/pngrtran.o
  CC(target) Release/obj.target/libpng/gyp/third-party/libpng/pngrutil.o
  CC(target) Release/obj.target/libpng/gyp/third-party/libpng/pngset.o
  CC(target) Release/obj.target/libpng/gyp/third-party/libpng/pngtrans.o
  CC(target) Release/obj.target/libpng/gyp/third-party/libpng/pngwio.o
  CC(target) Release/obj.target/libpng/gyp/third-party/libpng/pngwrite.o
  CC(target) Release/obj.target/libpng/gyp/third-party/libpng/pngwtran.o
  CC(target) Release/obj.target/libpng/gyp/third-party/libpng/pngwutil.o
  AR(target) Release/obj.target/gyp/gyp/png.a
  COPY Release/png.a
  CC(target) Release/obj.target/libjpeg-turbo/gyp/third-party/libjpeg-turbo/bmp.o
In file included from ../gyp/third-party/libjpeg-turbo/cdjpeg.h:16:0,
                 from ../gyp/third-party/libjpeg-turbo/bmp.c:33:
../gyp/third-party/libjpeg-turbo/jinclude.h:22:65: fatal error: jconfig.h: No such file or directory
compilation terminated.
gyp/gyp/libjpeg-turbo.target.mk:161: recipe for target 'Release/obj.target/libjpeg-turbo/gyp/third-party/libjpeg-turbo/bmp.o' failed
make: *** [Release/obj.target/libjpeg-turbo/gyp/third-party/libjpeg-turbo/bmp.o] Error 1
make: Leaving directory '/home/pi/PopcornTV/node_modules/node-images/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/nw-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.1.6+
gyp ERR! command "node" "/usr/local/bin/nw-gyp" "rebuild" "--target=0.12.3"
gyp ERR! cwd /home/pi/PopcornTV/node_modules/node-images
gyp ERR! node -v v0.12.6
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok `

Not sure if the error is with the actual build or with nw-gyp.  It says "file not found".  If I look at the directory I can see there is no file there. I can manually add one (by changing the jconfig.h.in filename, but that just adds to further errors).

I'm hoping someone here can either help me fix this or point me to where I can learn more.  Your time is much appreciated!

**Comment by dcommander** [comment]
jconfig.h is automatically generated by the libjpeg-turbo build system, and its content depends on how libjpeg-turbo has been configured and on the specifics of the system on which you are building it.  It appears that the developers of whatever software you are trying to build did not properly integrate libjpeg-turbo into their source tree and build system.  IOW, not my circus and not my monkeys.

**Comment by masonjames** [comment]
I appreciate you taking the time to respond. Thanks :)
