### ISSUE TITLE
Strange compression result

### ISSUE THREAD

**Issue by StillWaters77** [libjpeg-turbo/libjpeg-turbo#191]
Hey, 
i ran into a strange problem using libjpeg-trubo:
When i try compressing the screenshot (640x480) i took, i get this result:
![image](https://user-images.githubusercontent.com/32618956/32795471-0ec1e17a-c96c-11e7-920e-cd9e4b994eb5.jpg)

The compression line in my code looks like this: `tjCompress2(comp, lpPixels, nScreenWidth, 0, nScreenHeight, TJPF_RGB, &compressedImage, &jpegSize, TJSAMP_444, 75, TJFLAG_FASTDCT);`

So the parameters i use are: 
`TJPF_RGB`
`TJSAMP_444`
`TJFLAG_FASTDCT`

As you can see, i am compressing with 75% quality. I also tested this with other qualities but somehow it everytime returns this strange result.

**Comment by dcommander** [comment]
Is the source image in packed RGB format?  That would be unusual for a screenshot.  If it's coming directly from the framebuffer, then the image is probably BGRA/BGRX, not RGB.

**Comment by StillWaters77** [comment]
Thanks for your reply!

The screenshot is simple BitBlt, but to get the raw data, i use ´GetDIBits´.
`BMInfo.bmiHeader.biCompression = BI_RGB;`
So i thought the image data had to be in RGB-Format?

I also tested BGRA/BGRX, BGR, but unfortunately i get almost the same result (Sometimes just the direction the colors fade is reversed).

I provide here the full code, just in case, i am doing something completely wrong:
https://gyazo.com/b75fbe7a1485dc0e5dca4fbc019f8fd3

**Comment by dcommander** [comment]
Try `TJPF_BGRX` and see if it works.  I can almost guarantee you that that's the problem.  I think Microsoft's documentation sometimes says "RGB" when it really means "BGRX".  I've run into that before.

**Comment by StillWaters77** [comment]
You again saved my day! Thank you really much! That solved my problem.

The reason why it hadnt worked first was, because i forgot to delete the picture.
