### ISSUE TITLE
Compile via VS2015 project

### ISSUE THREAD

**Issue by zqh1116** [libjpeg-turbo/libjpeg-turbo#193]
I tried to compile it via cmake. Because I'm poor in cmake, so failed to compile it.
I want to get VS2015 project.
Can you help me to make VS2015 project so that I can build libjpeg-turbo in VS2015?
Looking forward to hearing good news!
Regards.

**Comment by dcommander** [comment]
It is not my job to teach you how to use CMake.  Read our build instructions in BUILDING.md, and read the documentation for CMake.
