### ISSUE TITLE
jpeg_crop_scanline sometimes does not set up to decode the right iMCU columns 

### ISSUE THREAD

**Issue by LeonScroggins** [libjpeg-turbo/libjpeg-turbo#195]
I've attached the image that triggers it, and an example of the output. I am attempting to decode the image in four quadrants. The left half of the left quadrants are correct, and the right half are garbage. The left half of the right two quadrants show what should be in the right half of the left quadrants.

I noticed that in jpeg_crop_scanline, we determine how to choose which iMCU columns to decompress with the variable align:

  align = cinfo->_min_DCT_scaled_size * cinfo->max_h_samp_factor;

(https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/jdapistd.c#L193)
For the upper left quadrant, I noticed that this results in only selecting about a quarter of the iMCU columns, rather than a half, like I would expect. Just to confirm my suspicions, I tried dividing align by 2 (from 16 to 8). That made this particular image work, though it's not correct for all images. This image is a grayscale image, and I suppose has some other property that is not accounted for properly (some grayscale images work as expected).

![image](https://user-images.githubusercontent.com/13983895/33634176-4ee61d9a-d9e1-11e7-9ec2-0cbc7e7c75da.jpg)
![image jpg](https://user-images.githubusercontent.com/13983895/33634258-9bea95b2-d9e1-11e7-903b-3092470a4d61.png)

**Comment by dcommander** [comment]
!@%*&!@%*!@*%&!@*%!&@%*!&@%!*@%

<sigh>  OK, I'll look into it.  Dear Google, you owe me a lot of beers, dammit.

**Comment by dcommander** [comment]
The problem is that the image is grayscale, but it has been encoded in such a way that the horizontal & vertical sampling factors for the single (Y) plane are 2x2.  A quick workaround until I can find a more permanent fix is to re-encode the image using jpegtran:

```
jpegtran -copy all 33634176-4ee61d9a-d9e1-11e7-9ec2-0cbc7e7c75da.jpg >out.jpg
```

Then cropping should work properly on out.jpg.

**Comment by dcommander** [comment]
Fix pushed

**Comment by LeonScroggins** [comment]
Thanks for the quick fix!
