### ISSUE TITLE
How to use the latest version of libjpeg-turbo in Android?

### ISSUE THREAD

**Issue by hushengjun** [libjpeg-turbo/libjpeg-turbo#200]
I want to use it in the Android, but need to compile the NDK, I don't know those files is useful

**Comment by dcommander** [comment]
The latest version of BUILDING.md (https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/BUILDING.md) contains instructions that should work with NDK r16. The instructions in libjpeg-turbo 1.5.3 will only work with NDK r15 and earlier.
