### ISSUE TITLE
Memory Leaks with Mutithreads

### ISSUE THREAD

**Issue by KishoreVignesh** [libjpeg-turbo/libjpeg-turbo#206]
Using libturbojpeg with golang. I call the libturbojpeg c api directly. My usecase is only to read jpeg image and get the image in RGBA format. I find libturbojpeg exteremly fast than the built in golang decoder. 

    func MakeImageRGBAlibjpeg(data []byte) (im *image.RGBA, err error) {

	handle := C.tjInitDecompress()
	defer func() {
		C.tjDestroy(handle)
	}()

	if handle != nil {
		log.Println("jpeg initialized.")
	}

	cobjectData := C.CBytes(data)
	defer func() {
		C.free(cobjectData)
	}()

	// Now get Width and Height

	cobjectWidth := C.int(0)
	cobjectHeight := C.int(0)

	ret1 := C.tjDecompressHeader(handle, (*C.uchar)(cobjectData), C.ulong(len(data)), &cobjectWidth, &cobjectHeight)

	log.Println("Return tjDecompressHeader", ret1)
	log.Println("tjDecompressHeader WIDTH", cobjectWidth)
	log.Println("tjDecompressHeader HEIGHT", cobjectHeight)

	cstride := cobjectWidth * C.int(4)
	clength := (C.sizeof_uchar) * cstride * cobjectHeight
	cobjectRaw := C.malloc(C.size_t(clength))
	//scope.MarkCObject(cobjectRaw)
	defer func() {
		C.free(cobjectRaw)
	}()

	ret := C.tjDecompress2(handle,
		(*C.uchar)(cobjectData),
		C.ulong(len(data)),
		(*C.uchar)(cobjectRaw),
		cobjectWidth,
		cstride,
		cobjectHeight,
		C.TJPF_RGBA,
		C.int(0))

	im = image.NewRGBA(image.Rect(0, 0, int(cobjectWidth), int(cobjectHeight)))
	im.Pix = C.GoBytes((unsafe.Pointer)(cobjectRaw), clength)

	if int(ret) != 0 {
		log.Println("Turbojpeg problem decompressing the image, return code: ", ret, " error: ", C.GoString(C.tjGetErrorStr()))
	}

	return
    }

When i call the above method in multithreads. Lots of memory leak happens. I confirmed the issue with mcheck.h and mtrace

**Whats the Problem?**
Some functions of libturbojpeg leaks memory in mutlithreaded operation. 

**What the expected behaviour ?**
Either all the methods should be thread safe or Atleast in turbojpeg.h kindly add comments whether the method is thread safe or not. 

Note: Thanks for the Awesome Simple library.

**Comment by dcommander** [comment]
The TurboJPEG API is thread-safe as long as you do not use more than one instance of it per thread.  The same is true of the libjpeg API.  It appears that your code is creating a new TurboJPEG instance for each call to MakeImageRGBAlibjpeg(), so as long as you are calling that function in a data-parallel manner (i.e. you are ensuring that the inputs and outputs for any given invocation of the function do not overlap with the inputs and outputs for any other invocation of the function), then it should be thread-safe.  It appears that you are properly disposing of resources at the termination of the function, but I am not a Go programmer, so I don't know if there are any "gotchas" to having multiple defer statements.  Regardless, data-parallel decoding using the TurboJPEG API works fine from C and Java, so whatever is malfunctioning, it's malfunctioning at the Go level.

**Comment by KishoreVignesh** [comment]
@dcommander  Thanks for your time , Looks like its an Go Level Issue. Go threads are logical threads, So they are very lightweight. One Gothread is not one OS thread.  For people having the same issue. It can be solved by using runtime.LockOSThread() and runtime.UnlockOSThread()
