### ISSUE TITLE
Restructuring source directories -- FEEDBACK REQUESTED FROM COMMUNITY

### ISSUE THREAD

**Issue by dcommander** [libjpeg-turbo/libjpeg-turbo#226]
I've received several requests to restructure the source directory, to make it easier for new users to navigate.  This isn't going to land in 2.0.x, because the beta is about to be released, but I will consider it for future releases if I can get some good feedback from the community regarding how best to accomplish it.  When I look at other OSS imaging libraries, I find that:

- libpng structures its source tree much like we do, but of course they have much less source to deal with, so it doesn't appear as cluttered.
- libtiff keeps all of its source under **libtiff/**
- libgif keeps all of its source under **lib/**
- openjpeg keeps all of its source under **src/lib/** with various subdirectories
- libwebp keeps all of its source under **src/** with various subdirectories
- FFmpeg uses a different top-level directory for each component library.  The structure of the **libavcodec/** subdirectory specifically is very much like our existing source layout, except that it's one level deeper.

libjpeg-turbo requirements/preferences:
1. All of the code we forked from IJG (i.e. the code used to implement the libjpeg API) needs to be in the same directory, in order to facilitate comparing against the IJG's software (absolute requirement.)
2. It would be nice, but is not required, for the TurboJPEG API code to be in a separate directory from the libjpeg API code (soft preference.)
3. I would prefer strongly that all existing top-level directories (particularly **simd/** and **java/**) remain top-level directories.  There is already some code under those directories that is 2-4 levels deep, and I don't want it to be any deeper (hard preference.)

Possible approaches:
- Move libjpeg and TurboJPEG C source under **src/**.

    Problem: SIMD and Java sources are source code as well, so this naming convention wouldn't make much sense in light of (3) above.
- Move libjpeg API source under **libjpeg/** and TurboJPEG API source under **turbojpeg/** or **libturbojpeg/**.

    Problem: When new users see "libjpeg" and "turbojpeg" juxtaposed, they tend to assume incorrectly that only "turbojpeg" is accelerated (see also: https://libjpeg-turbo.org/About/TurboJPEG).  **libjpeg_api/** and **turbojpeg_api/** would work, but those are a bit awkward.  Unfortunately, neither libjpeg-turbo nor the TurboJPEG API can undergo a wholesale name change without FUBARing a lot of stuff, but this is me wishing out loud that they could.

    NOTE: I've also thought of using a directory called **ijg/** for the libjpeg source, but I do not want to give anyone the false impression that our project is in any way affiliated with the IJG.
- Hang the sense of (3) and move all source under **src/**, which would add a level of depth to the SIMD and Java code that I would prefer not to add.
- Compromise: Move the TurboJPEG source code and tests under **turbojpeg/** and leave the libjpeg source code in the top level.  This would at least make our source tree no more difficult to navigate than the IJG source tree.

    Problem: This reduces the visibility of the TurboJPEG API, which I don't want to do.

I am open to other suggestions, and in particular, I am interested to know if there are any accepted standards for this within the OSS community, or other imaging libraries with assembly, Java, and C source code or multiple APIs that I can use as models.

As usual, the default is to do nothing.  I don't personally consider this to be a huge problem, because GitHub displays the README file whenever you browse the top level of the source code.  However, I also understand how people who have never seen libjpeg before might be taken aback by so much source code at the top level, and we have certainly added a lot of source code relative to libjpeg that has exacerbated this problem.

**Comment by Johnex** [comment]
For me it was not much of an issue as a newbie getting the headers etc, but i do see others could have the issue.

For folders, that would be nice, adding build/ with cmake and java as subfolders.
You could also have a folder like "libjpeg_accelerated" and "turbojpeg-api" in maybe a src folder with their respective sources. That would let users know that libjpeg is also boosted.

Since its just the folder you can call it whatever, it won't really affect the branding of the entire project.

I do either way agree that the sources should be separated as much as possible, keeping the 20 year old mess in its own folder. The tjapi can have subfolders if needed similar to libwebp.

**Comment by dcommander** [comment]
I've pushed a branch called "directory_structure_experiment" that implements the second possible approach (using top-level directories **turbojpeg_api/** and **libjpeg_api/**.  It at least builds successfully, despite some awkwardness relating to cross-directory dependencies between the various modules.  Still looking for feedback.

**Comment by Johnex** [comment]
It already feels much cleaner. I can already see the README clearly compared to before.

**Comment by dcommander** [comment]
Yes, but there are other ways to achieve the same result.  I'm looking for more technical feedback regarding the pros and cons of various approaches.  This is just one of them.

**Comment by dcommander** [comment]
Sorry, but I am out of money (refer to https://libjpeg-turbo.org/About/Help.)  Moving forward, I will be forced to focus only on paying projects, so from here on, no new features will be implemented or accepted in libjpeg-turbo without funding to pay for my labor.  Given that this feature is very unlikely to be "sexy" enough to attract funded development, I am closing it as "won't implement."
