### ISSUE TITLE
Commits for AltiVec SIMD support and partial image decoding are missing in Git repository

### ISSUE THREAD

**Issue by dcommander** [libjpeg-turbo/libjpeg-turbo#23]
Unfortunately I screwed something up when I built the Git repository and applied fake merge data to properly represent all of my previous SVN cherry-picks.  Basically all of the trunk commits that were made prior to the Git migration and not cherry-picked onto 1.4.x (including the AltiVec and partial decode features) became orphaned.  I was able to recover them with the attached grafts file, but of course applying this grafts file permanently means that the object ID's after b6b30676a34621c49e6dc06d0a0668681bf2291a will change.  I don't know if there's anything for it other than to bite the bullet and rewrite the history.  I need those feature commits back in the log.

[grafts.txt](https://github.com/libjpeg-turbo/libjpeg-turbo/files/7111/grafts.txt)

**Comment by dcommander** [comment]
The history has been rewritten.  Sorry for any inconvenience.  If you have an existing sandbox checked out from the main libjpeg-turbo repository, then do the following to update it:

    git fetch --tags
    git checkout {branch}
    git rebase --onto origin/{branch} origin/{branch}-old

where `{branch}` is `master`, `1.4.x`, or `1.3.x`.  Do the above for each of those branches you have in your local sandbox (branches prior to 1.3.x are unaffected by this rewrite.)

If you have a sandbox checked out from a fork, then do the following the update it:

    git remote add upstream https://github.com/libjpeg-turbo/libjpeg-turbo.git
    git fetch --tags upstream
    git checkout {branch}
    git rebase --onto upstream/{branch} upstream/{branch}-old
    git push --all -f
    git push --tags -f

**Comment by dcommander** [comment]
@Enseed @pornel @komakai @jcowgill @loganaden @chandlerc @imazen

**Comment by pornel** [comment]
Thanks for sorting this out.
