### ISSUE TITLE
compiling with /MT instead of /MD generates a lot of linking errors

### ISSUE THREAD

**Issue by DavidBrenner3** [libjpeg-turbo/libjpeg-turbo#230]
Hi,

When building the project I'm using /MT instead of /MD so the binary would not need any other library (all included).
It worked for older versions...
I downloaded the latest version, changed the option and got these when trying to compile in VS2015 upd 2:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol _memset	jpeg	d:\libjpeg-turbo\Build\sharedlib\jcarith.obj	1	
Error	LNK2019	unresolved external symbol _memset referenced in function _master_selection	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdmaster.obj	1	
Error	LNK2001	unresolved external symbol _memset	jpeg	d:\libjpeg-turbo\Build\sharedlib\jutils.obj	1	
Error	LNK2001	unresolved external symbol _memset	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdarith.obj	1	
Error	LNK2001	unresolved external symbol _memset	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdapimin.obj	1	
Error	LNK2001	unresolved external symbol _memset	jpeg	d:\libjpeg-turbo\Build\sharedlib\jddctmgr.obj	1	
Error	LNK2001	unresolved external symbol _memset	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdhuff.obj	1	
Error	LNK2001	unresolved external symbol _memset	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdmarker.obj	1	
Error	LNK2001	unresolved external symbol _memset	jpeg	d:\libjpeg-turbo\Build\sharedlib\jcapimin.obj	1	
Error	LNK2001	unresolved external symbol _memset	jpeg	d:\libjpeg-turbo\Build\sharedlib\jchuff.obj	1	
Error	LNK2001	unresolved external symbol _memset	jpeg	d:\libjpeg-turbo\Build\sharedlib\jcparam.obj	1	
Error	LNK2001	unresolved external symbol _memset	jpeg	d:\libjpeg-turbo\Build\sharedlib\jcphuff.obj	1	
Error	LNK2001	unresolved external symbol __fltused	jpeg	d:\libjpeg-turbo\Build\sharedlib\jfdctflt.obj	1	
Error	LNK2001	unresolved external symbol __fltused	jpeg	d:\libjpeg-turbo\Build\sharedlib\jidctflt.obj	1	
Error	LNK2001	unresolved external symbol __fltused	jpeg	d:\libjpeg-turbo\Build\sharedlib\jcapimin.obj	1	
Error	LNK2001	unresolved external symbol __fltused	jpeg	d:\libjpeg-turbo\Build\sharedlib\jcdctmgr.obj	1	
Error	LNK2001	unresolved external symbol __fltused	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdapimin.obj	1	
Error	LNK2001	unresolved external symbol __fltused	jpeg	d:\libjpeg-turbo\Build\sharedlib\jddctmgr.obj	1	
Error	LNK2001	unresolved external symbol @__security_check_cookie@4	jpeg	d:\libjpeg-turbo\Build\sharedlib\jquant1.obj	1	
Error	LNK2001	unresolved external symbol @__security_check_cookie@4	jpeg	d:\libjpeg-turbo\Build\sharedlib\jquant2.obj	1	
Error	LNK2001	unresolved external symbol @__security_check_cookie@4	jpeg	d:\libjpeg-turbo\Build\sharedlib\jidctflt.obj	1	
Error	LNK2001	unresolved external symbol @__security_check_cookie@4	jpeg	d:\libjpeg-turbo\Build\sharedlib\jidctfst.obj	1	
Error	LNK2001	unresolved external symbol @__security_check_cookie@4	jpeg	d:\libjpeg-turbo\Build\sharedlib\jidctint.obj	1	
Error	LNK2001	unresolved external symbol @__security_check_cookie@4	jpeg	d:\libjpeg-turbo\Build\sharedlib\jidctred.obj	1	
Error	LNK2001	unresolved external symbol @__security_check_cookie@4	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdicc.obj	1	
Error	LNK2001	unresolved external symbol @__security_check_cookie@4	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdmarker.obj	1	
Error	LNK2001	unresolved external symbol @__security_check_cookie@4	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdphuff.obj	1	
Error	LNK2001	unresolved external symbol @__security_check_cookie@4	jpeg	d:\libjpeg-turbo\Build\sharedlib\jerror.obj	1	
Error	LNK2001	unresolved external symbol @__security_check_cookie@4	jpeg	d:\libjpeg-turbo\Build\sharedlib\jcphuff.obj	1	
Error	LNK2001	unresolved external symbol @__security_check_cookie@4	jpeg	d:\libjpeg-turbo\Build\sharedlib\jctrans.obj	1	
Error	LNK2001	unresolved external symbol @__security_check_cookie@4	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdcoefct.obj	1	
Error	LNK2001	unresolved external symbol @__security_check_cookie@4	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdhuff.obj	1	
Error	LNK2001	unresolved external symbol @__security_check_cookie@4	jpeg	d:\libjpeg-turbo\Build\sharedlib\jccoefct.obj	1	
Error	LNK2001	unresolved external symbol @__security_check_cookie@4	jpeg	d:\libjpeg-turbo\Build\sharedlib\jchuff.obj	1	
Error	LNK2001	unresolved external symbol @__security_check_cookie@4	jpeg	d:\libjpeg-turbo\Build\sharedlib\jcmarker.obj	1	
Error	LNK2001	unresolved external symbol @__security_check_cookie@4	jpeg	d:\libjpeg-turbo\Build\sharedlib\jcmaster.obj	1	
Error	LNK2001	unresolved external symbol ___security_cookie	jpeg	d:\libjpeg-turbo\Build\sharedlib\jquant1.obj	1	
Error	LNK2001	unresolved external symbol ___security_cookie	jpeg	d:\libjpeg-turbo\Build\sharedlib\jquant2.obj	1	
Error	LNK2001	unresolved external symbol ___security_cookie	jpeg	d:\libjpeg-turbo\Build\sharedlib\jidctflt.obj	1	
Error	LNK2001	unresolved external symbol ___security_cookie	jpeg	d:\libjpeg-turbo\Build\sharedlib\jidctfst.obj	1	
Error	LNK2001	unresolved external symbol ___security_cookie	jpeg	d:\libjpeg-turbo\Build\sharedlib\jidctint.obj	1	
Error	LNK2001	unresolved external symbol ___security_cookie	jpeg	d:\libjpeg-turbo\Build\sharedlib\jidctred.obj	1	
Error	LNK2001	unresolved external symbol ___security_cookie	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdicc.obj	1	
Error	LNK2001	unresolved external symbol ___security_cookie	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdmarker.obj	1	
Error	LNK2001	unresolved external symbol ___security_cookie	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdphuff.obj	1	
Error	LNK2001	unresolved external symbol ___security_cookie	jpeg	d:\libjpeg-turbo\Build\sharedlib\jerror.obj	1	
Error	LNK2001	unresolved external symbol ___security_cookie	jpeg	d:\libjpeg-turbo\Build\sharedlib\jcphuff.obj	1	
Error	LNK2001	unresolved external symbol ___security_cookie	jpeg	d:\libjpeg-turbo\Build\sharedlib\jctrans.obj	1	
Error	LNK2001	unresolved external symbol ___security_cookie	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdcoefct.obj	1	
Error	LNK2001	unresolved external symbol ___security_cookie	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdhuff.obj	1	
Error	LNK2001	unresolved external symbol ___security_cookie	jpeg	d:\libjpeg-turbo\Build\sharedlib\jccoefct.obj	1	
Error	LNK2001	unresolved external symbol ___security_cookie	jpeg	d:\libjpeg-turbo\Build\sharedlib\jchuff.obj	1	
Error	LNK2001	unresolved external symbol ___security_cookie	jpeg	d:\libjpeg-turbo\Build\sharedlib\jcmarker.obj	1	
Error	LNK2001	unresolved external symbol ___security_cookie	jpeg	d:\libjpeg-turbo\Build\sharedlib\jcmaster.obj	1	
Error	LNK2001	unresolved external symbol ___report_rangecheckfailure	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdicc.obj	1	
Error	LNK2001	unresolved external symbol ___report_rangecheckfailure	jpeg	d:\libjpeg-turbo\Build\sharedlib\jchuff.obj	1	
Error	LNK2001	unresolved external symbol ___report_rangecheckfailure	jpeg	d:\libjpeg-turbo\Build\sharedlib\jcmarker.obj	1	
Error	LNK2001	unresolved external symbol ___report_rangecheckfailure	jpeg	d:\libjpeg-turbo\Build\sharedlib\jcmaster.obj	1	
Error	LNK2001	unresolved external symbol ___report_rangecheckfailure	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdhuff.obj	1	
Error	LNK2019	unresolved external symbol _memcpy referenced in function _decode_mcu	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdhuff.obj	1	
Error	LNK2001	unresolved external symbol _memcpy	jpeg	d:\libjpeg-turbo\Build\sharedlib\jutils.obj	1	
Error	LNK2001	unresolved external symbol _memcpy	jpeg	d:\libjpeg-turbo\Build\sharedlib\jchuff.obj	1	
Error	LNK2001	unresolved external symbol _memcpy	jpeg	d:\libjpeg-turbo\Build\sharedlib\jcparam.obj	1	
Error	LNK2001	unresolved external symbol _memcpy	jpeg	d:\libjpeg-turbo\Build\sharedlib\jcprepct.obj	1	
Error	LNK2001	unresolved external symbol _memcpy	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdatadst.obj	1	
Error	LNK2019	unresolved external symbol _free referenced in function _empty_mem_output_buffer	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdatadst.obj	1	
Error	LNK2001	unresolved external symbol _free	jpeg	d:\libjpeg-turbo\Build\sharedlib\jmemnobs.obj	1	
Error	LNK2019	unresolved external symbol _malloc referenced in function _empty_mem_output_buffer	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdatadst.obj	1	
Error	LNK2001	unresolved external symbol _malloc	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdicc.obj	1	
Error	LNK2001	unresolved external symbol _malloc	jpeg	d:\libjpeg-turbo\Build\sharedlib\jmemnobs.obj	1	
Error	LNK2019	unresolved external symbol _ferror referenced in function _term_destination	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdatadst.obj	1	
Error	LNK2019	unresolved external symbol _fflush referenced in function _term_destination	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdatadst.obj	1	
Error	LNK2019	unresolved external symbol _fwrite referenced in function _empty_output_buffer	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdatadst.obj	1	
Error	LNK2019	unresolved external symbol _fread referenced in function _fill_input_buffer	jpeg	d:\libjpeg-turbo\Build\sharedlib\jdatasrc.obj	1	
Error	LNK2019	unresolved external symbol _exit referenced in function _error_exit	jpeg	d:\libjpeg-turbo\Build\sharedlib\jerror.obj	1	
Error	LNK2019	unresolved external symbol ___acrt_iob_func referenced in function _output_message	jpeg	d:\libjpeg-turbo\Build\sharedlib\jerror.obj	1	
Error	LNK2019	unresolved external symbol ___stdio_common_vfprintf referenced in function _fprintf	jpeg	d:\libjpeg-turbo\Build\sharedlib\jerror.obj	1	
Error	LNK2019	unresolved external symbol ___stdio_common_vsprintf referenced in function _sprintf	jpeg	d:\libjpeg-turbo\Build\sharedlib\jerror.obj	1	
Error	LNK2019	unresolved external symbol _getenv referenced in function _jinit_memory_mgr	jpeg	d:\libjpeg-turbo\Build\sharedlib\jmemmgr.obj	1	
Error	LNK2001	unresolved external symbol _getenv	jpeg	d:\libjpeg-turbo\Build\sharedlib\jsimd.obj	1	
Error	LNK2019	unresolved external symbol ___stdio_common_vsscanf referenced in function _sscanf	jpeg	d:\libjpeg-turbo\Build\sharedlib\jmemmgr.obj	1	
Error	LNK2001	unresolved external symbol __DllMainCRTStartup@12	jpeg	d:\libjpeg-turbo\Build\sharedlib\LINK	1	
Error	LNK1120	19 unresolved externals	jpeg	D:\libjpeg-turbo\Build\Release\jpeg62.dll	1	

How do I solve it?

Thank you in advance.

Best regards,
David.

**Comment by dcommander** [comment]
For now, try passing `-DWITH_CRT_DLL=1` to CMake when configuring the build.  I'll investigate whether is a deeper issue involved.

**Comment by DavidBrenner3** [comment]
It helped, it compiles ok now.
Thank you.

**Comment by dcommander** [comment]
Can't reproduce the problem, and since passing `-DWITH_CRT_DLL=1` worked around it for you, I'm not inclined to pursue the matter further.

**Comment by dcommander** [comment]
There are known issues associated with using the pre-built "official" libjpeg-turbo static libraries in Visual Studio 2015 projects (refer to #45), but doing a build completely from scratch with VC 2015 should work.  However, referring also to #203, there are some scenarios in which it is necessary to enable `WITH_CRT_DLL`, such as when building for the Windows Store.  It's unclear how you are trying to build the code, so you might be running into one of those scenarios.
