### ISSUE TITLE
Use-of-uninitialized-value (7274)

### ISSUE THREAD

**Issue by dlemstra** [libjpeg-turbo/libjpeg-turbo#238]
The @ImageMagick project is using https://github.com/google/oss-fuzz to find bugs in our own library and in libraries that we use. The fuzzer found an issue and we think this is an issue that should be resolved in the library that we use. This issue is posted under the url https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=7274 that is not publicly visible yet but added as a link for future reference. Below are the details of the issue that can be reproduced using the following technique: https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md

Stacktrace:
```
==1==WARNING: MemorySanitizer: use-of-uninitialized-value
--
  | #0 0x1c911a6 in htest_one_block libjpeg-turbo/jchuff.c:760:7
  | #1 0x1c911a6 in encode_mcu_gather libjpeg-turbo/jchuff.c:844
  | #2 0x1c6b0c6 in compress_output libjpeg-turbo/jccoefct.c:381:12
  | #3 0x1b7e794 in process_data_simple_main libjpeg-turbo/jcmainct.c:100:10
  | #4 0x1b7c9b9 in jpeg_write_scanlines libjpeg-turbo/jcapistd.c:109:3
  | #5 0x10a23b3 in WriteJPEGImage imagemagick/coders/jpeg.c:2782:18
  | #6 0x7d0b95 in WriteImage imagemagick/MagickCore/constitute.c:1124:14
  | #7 0x700e0b in ImageToBlob imagemagick/MagickCore/blob.c:1912:18
  | #8 0x7050be in ImagesToBlob imagemagick/MagickCore/blob.c:2300:14
  | #9 0x5cf796 in Magick::Image::write(Magick::Blob*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) imagemagick/Magick++/lib/Image.cpp:4910:8
  | #10 0x4a1e6a in LLVMFuzzerTestOneInput imagemagick/Magick++/fuzz/encoder_fuzzer.cc:56:11
  | #11 0x4ea393 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:528:13
  | #12 0x4a32f6 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
  | #13 0x4b5852 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:703:9
  | #14 0x4a2431 in main /src/libfuzzer/FuzzerMain.cpp:20:10
  | #15 0x7f01640f082f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/libc-start.c:291
  | #16 0x421df8 in _start
  |  
  | Uninitialized value was created by a heap allocation
  | #0 0x45f460 in __interceptor_malloc /src/llvm/projects/compiler-rt/lib/msan/msan_interceptors.cc:915
  | #1 0x1c3f555 in alloc_large libjpeg-turbo/jmemmgr.c:391:29
  | #2 0x1c3f555 in alloc_barray libjpeg-turbo/jmemmgr.c:527
  | #3 0x1c3f555 in realize_virt_arrays libjpeg-turbo/jmemmgr.c:741
  | #4 0x1b7d8eb in jinit_compress_master libjpeg-turbo/jcinit.c:70:3
  | #5 0x1b7c0f3 in jpeg_start_compress libjpeg-turbo/jcapistd.c:51:3
  | #6 0x109fe1d in WriteJPEGImage imagemagick/coders/jpeg.c:2612:3
  | #7 0x7d0b95 in WriteImage imagemagick/MagickCore/constitute.c:1124:14
  | #8 0x700e0b in ImageToBlob imagemagick/MagickCore/blob.c:1912:18
  | #9 0x7050be in ImagesToBlob imagemagick/MagickCore/blob.c:2300:14
  | #10 0x5cf796 in Magick::Image::write(Magick::Blob*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) imagemagick/Magick++/lib/Image.cpp:4910:8
  | #11 0x4a1e6a in LLVMFuzzerTestOneInput imagemagick/Magick++/fuzz/encoder_fuzzer.cc:56:11
  | #12 0x4ea393 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:528:13
  | #13 0x4a32f6 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
  | #14 0x4b5852 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:703:9
  | #15 0x4a2431 in main /src/libfuzzer/FuzzerMain.cpp:20:10
  | #16 0x7f01640f082f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/libc-start.c:291
```

Links:
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/2401e4d10c2749c5c260a711c3bde52163829505/jchuff.c#L760

Commit: 2401e4d10c2749c5c260a711c3bde52163829505
Testcase file: [clusterfuzz-testcase-minimized-encoder_jpg_fuzzer-4842845987930112.zip](https://github.com/libjpeg-turbo/libjpeg-turbo/files/1983431/clusterfuzz-testcase-minimized-encoder_jpg_fuzzer-4842845987930112.zip)

**Comment by dcommander** [comment]
Does the problem go away when you do `export JSIMD_NONE=1`?  If so, then it's a known false positive that is due to memory checkers (including valgrind) not properly detecting that our SIMD extensions have populated a particular memory location.

I tried to reproduce the problem with an MSAN build of libjpeg-turbo and the attached CF test case, but I could not do so.  I strongly dislike oss-fuzz, because it hides the mechanics of how libjpeg-turbo is being used when the problem occurs.  From reading your comment above, I can tell only that the problem occurs during compression, but it's impossible for me to tell which settings were used and how exactly libjpeg-turbo was invoked.

**Comment by dlemstra** [comment]
Is that a environment value or should we enable this at compile time? This is how we build the library: https://github.com/ImageMagick/ImageMagick/blob/master/Magick%2B%2B/fuzz/build.sh#L24. Should we compile the library differently?

**Comment by dcommander** [comment]
`JSIMD_NONE` is a run-time environment variable, hence the `export` command.  Set the environment variable as specified, and re-run the test.

**Comment by dcommander** [comment]
Please perform the test as I requested.

**Comment by dcommander** [comment]
Closed due to lack of response from submitter

**Comment by dlemstra** [comment]
It has been more than a year but I finally made time to take another good look at this. It turns out that setting `JSIMD_FORCENONE=1` resolved this issue.

**Comment by dcommander** [comment]
That is a known issue, then, and it has been reported numerous times in numerous forms over the years.  valgrind and other memory checkers don't do a very good job of tracking memory usage by low-level SIMD assembly instructions.
