### ISSUE TITLE
how can i avoid version

### ISSUE THREAD

**Issue by crisiscain** [libjpeg-turbo/libjpeg-turbo#239]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libjpeg.so.62" not found
I need libjpeg.so but not libjpeg.so.62, how can i avoid version infomation in build

**Comment by dcommander** [comment]
Your question makes no sense. Sorry, but you need to be more specific regarding what you are trying to do and how it is failing.

**Comment by dcommander** [comment]
Closing due to lack of response and clarity from submitter.  I can't read minds.  Sorry.
