### ISSUE TITLE
tjDecodeYUVPlanes fails when used outside of jpeg decoding

### ISSUE THREAD

**Issue by uzadow** [libjpeg-turbo/libjpeg-turbo#243]
Is `tjDecodeYUVPlanes` supposed to work on arbitrary non-compressed planar YUV images?

I'm getting the error message

  "Invalid progressive parameters Ss=1 Se=63 Ah=1 Al=0",

which seems to suggest that there is JPEG decoding happening somewhere inside the routine, and I see `jpeg_read_header()` being called inside the routine as well.

**Comment by dcommander** [comment]
tjunittest, which is invoked by `make test` and executed as part of our continuous integration process, calls `tjDecodeYUV()`, which is a wrapper for `tjDecodeYUVPlanes()`, so I know the function works in general.  You're going to have to provide more details regarding how you are calling the function, in order for me to diagnose what's wrong.

**Comment by uzadow** [comment]
Thanks for the quick reply. Looking at your unit tests, things really should be working ;-). I'll have a closer look at my code.

Sorry for the noise!

**Comment by dcommander** [comment]
Please keep me posted.  If there is a legitimate issue with the function, I want to fix it.

**Comment by dcommander** [comment]
Any update on this?
