### ISSUE TITLE
speed comparison vs libjpeg_simd-6b?

### ISSUE THREAD

**Issue by timotheecour** [libjpeg-turbo/libjpeg-turbo#246]
http://www.briancbecker.com/blog/2010/analysis-of-jpeg-decoding-speeds/ mentions libjpeg_simd-6b (http://cetus.sakura.ne.jp/softlab/jpeg-x86simd/jpegsimd.html) as the winner  (by a large margin) but doesn't mention libjpeg-turbo.

libjpeg-turbo also isn't mentioned under http://cetus.sakura.ne.jp/softlab/jpeg-x86simd/jpegsimd.html

How would these compare?

**Comment by dcommander** [comment]
That blog post predates our project (we became a project later in 2010), so there was no libjpeg-turbo to mention at the time.  libjpeg-turbo was originally based on libjpeg/SIMD, but we have added the following optimizations (referring just to x86[-64] and baseline JPEG here):

- Accelerated Huffman coding and decoding (both in C and assembly), which accounts for probably about 25-30% speedup on top of the SIMD code
- 64-bit SSE2 SIMD code (libjpeg/SIMD only had 32-bit SIMD code)
- AVX2 SIMD code, which accounts for ~15-20% overall speedup on AVX2-equipped processors, relative to versions of libjpeg-turbo that only supported SSE2 instructions

My gut would say that we're probably about 50% faster overall than libjpeg/SIMD when using 32-bit code (but maybe more.)  When using 64-bit code, which had no SIMD support under libjpeg/SIMD, libjpeg/SIMD performed similarly to libjpeg v6b, so the 2-6x speedup that we generally claim relative to libjpeg v6b should still apply.
