### ISSUE TITLE
No Support for JPEG 2000

### ISSUE THREAD

**Issue by samewal** [libjpeg-turbo/libjpeg-turbo#251]
Hi,

I am trying to decompress pixel data which is compressed in JPEG 2000 format. Your API's check for SOI which is 0xff 0xd8 in case of jpeg while 0xff 0x 4f in case of jpeg 2000. Below are APIs I am using and the error message:

API used-> tjDecompressHeader3
Error Message-> Not a JPEG file: starts with 0xff 0x4f

Please let me know if I am doing something wrong or libjpeg-turbo does not have support for JPEG200.

PS: Sorry of this is not the correct forum for clarification, I did not find any other place.

Regards
Sami Khan

**Comment by dcommander** [comment]
libjpeg-turbo does not, never has, and never will support JPEG 2000.

**Comment by dcommander** [comment]
To clarify my quick response (some of this info is also in [README.ijg](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/README.ijg)):

JPEG 2000, despite using the name "JPEG", is a completely different beast than the DCT-based JPEG standard that libjpeg-turbo and libjpeg support.  JPEG 2000 uses a [wavelet-based compression algorithm](https://en.wikipedia.org/wiki/Discrete_wavelet_transform) and a different form of entropy coding than "traditional" JPEG images, so it would be impossible to support it using any of the existing libjpeg code.  It belongs in a different library.  There are [several OSS solutions](https://en.wikipedia.org/wiki/JPEG_2000#Libraries) for compressing/decompressing JPEG 2000.
