### ISSUE TITLE
Excessive time required to read/reject JPEG file

### ISSUE THREAD

**Issue by bobfriesenhahn** [libjpeg-turbo/libjpeg-turbo#252]
This issue (see attached file) was discovered via Google's oss-fuzz while testing GraphicsMagick (oss-fuzz issue 9096). While the file is being read, there are a great many "Start Of Scan" traces and reading finally terminates with a "Bogus marker length" error.  I am not sure how to solve this issue outside of libjpeg itself.  Oss-fuzz runs the test under a timer and it takes over 25 seconds for their instrumented code to finish reading this file.  The problem will go away if libjpeg itself can provide a solution.

Please advise.

![oss-fuzz-9096](https://user-images.githubusercontent.com/40547492/41975030-3b5e2ad0-79df-11e8-80e2-41ac3bdaa7b3.jpg)

**Comment by dcommander** [comment]
From your description, this is the same issue that is labeled LJT-01-003 in this report:
https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf

Applications wishing to guard against the issue can set a limit on the number of progressive scans by using a progress monitor (the report includes sample code demonstrating how to do this.)  This is yet another case in which it is possible to craft a completely valid JPEG file that demonstrates the issue, so whereas you could work around most instances of it by treating libjpeg API warnings as fatal, there will still be some cases that do not generate warnings.  Limiting the number of progressive scans is the only known robust workaround.
