### ISSUE TITLE
build android so error 

### ISSUE THREAD

**Issue by xiaofengff** [libjpeg-turbo/libjpeg-turbo#254]
![qq 20180702154818](https://user-images.githubusercontent.com/25995549/42151369-61fb2c54-7e0f-11e8-9e61-3ec18543d862.png)
![qq 20180702154804](https://user-images.githubusercontent.com/25995549/42151380-661eb260-7e0f-11e8-8f3b-7eb9e598e934.png)

**Comment by dcommander** [comment]
Move 
```
cd /home/xioafeng/Documents/bin
```
above
```
cat <<EOF >toolchain.cmake
```
I just noticed that BUILDING.md erroneously put the `cd {build_directory}` command after the creation of toolchain.cmake.  That has been corrected.
