### ISSUE TITLE
license for contributions same as outbound license?

### ISSUE THREAD

**Issue by jlovejoy** [libjpeg-turbo/libjpeg-turbo#257]
Can you clarify if contributions are accepted under the same relevant license as applies to the specific file?

thanks

**Comment by dcommander** [comment]
Indeed they are, and only under that license.  Generally you should be able to just add your copyright to the relevant header, e.g.:

```
/*
 * jccolor.c
 *
 * This file was part of the Independent JPEG Group's software:
 * Copyright (C) 1991-1996, Thomas G. Lane.
 * libjpeg-turbo Modifications:
 * Copyright 2009 Pierre Ossman <ossman@cendio.se> for Cendio AB
 * Copyright (C) 2009-2012, 2015, D. R. Commander.
 * Copyright (C) 2014, MIPS Technologies, Inc., California.
 * Copyright (C) 2018, {Insert Name of New Developer or Organization Here}.
 * For conditions of distribution and use, see the accompanying README.ijg
 * file.
 *
 * This file contains input colorspace conversion routines.
 */
```

If you're under an IP agreement with an employer, then the developer name would be your employer.

**Comment by dcommander** [comment]
Why do you ask?

**Comment by dcommander** [comment]
Also please refer to #199 for descriptions of why it is problematic for me to accept major feature code from outside contributors without funding for my labor to integrate, test, and clean up that code.  When contributions are accepted, they can only be accepted under the existing licenses, but in order for major feature contributions to be acceptable as-is, they need to be well-written and conform to the stringent quality standards of libjpeg-turbo.  If I take a cursory look at the code and see problems, then I will push back on the contribution unless the contributor is willing to pay for my labor to fix the code.  I also ask that contributors contact me for a strategic discussion prior to embarking on any major feature development.

**Comment by jlovejoy** [comment]
thanks, that's helpful. And of course the code should conform to your standards for the project!

**Comment by dcommander** [comment]
What is the context for your query?  Do you have a specific feature contribution in mind?
