### ISSUE TITLE
How to decode into RGB arrays

### ISSUE THREAD

**Issue by xu932** [libjpeg-turbo/libjpeg-turbo#264]
I'm new to the API and I am looking for ways to decode a jpeg image into arrays of RGB values. I have a hard time on finding information from README and the API documentation. Can someone lead me to where I should start?

**Comment by dcommander** [comment]
Do you mean planar (a separate array for each R, G, and B component) or packed RGB (a single array in which the components appear in the order R, G, B, R, G, B, etc.)?

**Comment by xu932** [comment]
Either one is fine. I'm looking for implementing `libjpeg-turbo` (with proper license) in my own program which requires images to be decoded into RGB format in an efficient way. I'm really looking for the source code here.

**Comment by dcommander** [comment]
Look at tjexample.c.  It demonstrates how to use the TurboJPEG API to decode a JPEG image into a buffer with an arbitrary packed pixel layout (including RGB, BGR, RGBX, BGRX, etc.)  Also refer to the API documentation:
https://libjpeg-turbo.org/Documentation/Documentation
