### ISSUE TITLE
A problem has arisen when 1.5.0 change to 1.5.90 

### ISSUE THREAD

**Issue by GoldenStrawberry** [libjpeg-turbo/libjpeg-turbo#266]
A problem has arisen :
`C:\Users\YSZN_1\Desktop\159\jni>ndk-build

[armeabi-v7a] Compile arm    : jpeg-turbo2000_static <= turbojpeg.c

[armeabi-v7a] StaticLibrary  : libjpeg-turbo2000_static.a

[armeabi-v7a] SharedLibrary  : libjpeg-turbo2000.so

C:/Users/YSZN_1/Desktop/159/jni/libjpeg-turbo-1.5.90/turbojpeg.c:1984: error: undefined reference to 'jinit_read_bmp'

C:/Users/YSZN_1/Desktop/159/jni/libjpeg-turbo-1.5.90/turbojpeg.c:1988: error: undefined reference to 'jinit_read_ppm'

C:/Users/YSZN_1/Desktop/159/jni/libjpeg-turbo-1.5.90/turbojpeg.c:2076: error: undefined reference to 'jinit_write_ppm'

C:/Users/YSZN_1/Desktop/159/jni/libjpeg-turbo-1.5.90/turbojpeg.c:2072: error: undefined reference to 'jinit_write_bmp'

clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [C:/Users/YSZN_1/Desktop/159/obj/local/armeabi-v7a/libjpeg-turbo2000.so] Error 1`

I can compile successfully when I comment out these methods . 
I used 1.5.0 in the project code, and I changed it to 1.5.90.
I found the picture on the phone screen was mosaic.
Have you made any changes to the latest version of the code?

here my code :
`struct jpeg_decompress_struct dinfo;
	struct error_mgr jerr;
	dinfo.err = jpeg_std_error(&jerr.super);
	jerr.super.error_exit = _error_exit;

	if (setjmp(jerr.jmp)) {
		goto fail;
	}

	jpeg_create_decompress(&dinfo);
	jpeg_mem_src(&dinfo, in->data, in->actual_bytes/*in->data_bytes*/);	// XXX
	jpeg_read_header(&dinfo, TRUE);

	if (dinfo.dc_huff_tbl_ptrs[0] == NULL) {
		/* This frame is missing the Huffman tables: fill in the standard ones */
		insert_huff_tables(&dinfo);
	}

	dinfo.out_color_space = JCS_YCbCr;
	dinfo.dct_method = JDCT_IFAST; // JDCT_ISLOW ; //JDCT_IFAST;

	// start decompressor
	jpeg_start_decompress(&dinfo);

	// these dinfo.xxx valiables are only valid after jpeg_start_decompress
	const int row_stride = dinfo.output_width * dinfo.output_components;

	// allocate buffer
	register JSAMPARRAY buffer = (*dinfo.mem->alloc_sarray)
		((j_common_ptr) &dinfo, JPOOL_IMAGE, row_stride, MAX_READLINE);

	// local copy
	uint8_t *data = out->data;
	const int out_step = out->step;
    LOGW("HUWEI uvc_mjpeg2yuyv555555 = %f",getUtime());

	if (LIKELY(dinfo.output_height == out->height)) {
		for (; dinfo.output_scanline < dinfo.output_height ;) {
			// convert lines of mjpeg data to YCbCr
			num_scanlines = jpeg_read_scanlines(&dinfo, buffer, MAX_READLINE);
			// convert YCbCr to yuyv(YUV422)
			if(1){
                for (j = 0; j < num_scanlines; j++) {
                    yuyv = data + (lines_read + j) * out_step;
                    ycbcr = buffer[j];
                    for (i = 0; i < row_stride; i += 24) {	// step by YCbCr x 8 pixels = 3 x 8 bytes
                        YCbCr_YUYV_2(ycbcr + i, yuyv);
                        YCbCr_YUYV_2(ycbcr + i + 6, yuyv);
                        YCbCr_YUYV_2(ycbcr + i + 12, yuyv);
                        YCbCr_YUYV_2(ycbcr + i + 18, yuyv);
                    }
                }
			}
			lines_read += num_scanlines;
		}
		out->actual_bytes = in->width * in->height * 2;	// XXX
	}

	jpeg_finish_decompress(&dinfo);
	jpeg_destroy_decompress(&dinfo);`

I don't know what the problem is . help me !

**Comment by dcommander** [comment]
Yes, of course there are changes between 1.5.0 and 1.5.90, the latter of which is the beta release of 2.0.0 (refer to our versioning conventions here: https://libjpeg-turbo.org/DeveloperInfo/PreReleases.)  You are doing two major things incorrectly:

1. You are building the libjpeg-turbo code in a non-standard way.  Refer to BUILDING.md for our official build instructions.  If those instructions don't work, then I can help you with that, but if you insist on using your own build system and build procedure, then it is your responsibility to fix any problems with your build.
2. You are confusing the libjpeg API with the TurboJPEG API.  Your code appears to use the libjpeg API, but you are trying to build turbojpeg.c, which implements the TurboJPEG API.  Again, please use the official build instructions.

In general, posting a dump of technical output without explaining what you're trying to do and why is not going to result in a solution for your problem.  I cannot read your mind.  I have no idea why you're trying to compile turbojpeg.c into a library called "libjpeg-turbo2000".  That is so far removed from our official build procedure as to be unrecognizable.

**Comment by GoldenStrawberry** [comment]
Thank you for your answer. But I have a follow up question.
I'm going to unzip the mjpeg data from the camera onto the phone screen, and I've changed it twice. Mjpeg-> yuyv->RGBX, I find that it takes 30s-50s to decompress once, and the time of two transitions is beyond the 50s to reach 25fps. I tried to use the new version to reduce the decompression time. Am I using it wrong ？

**Comment by dcommander** [comment]
It is very unclear what you are trying to do, or what you are reporting.

Do you mean that the new version takes 30-50s to decompress and the old version doesn't?  If both versions perform that slowly, then either your code or your hardware platform is sub-optimal.  The first thing I would look at in your code is the color conversion.  If you are ultimately going to produce an RGBX image, then there is no need to convert to packed YUYV first, and that is probably wasting a lot of CPU cycles.  libjpeg-turbo can decode directly to RGBX.  If it is necessary to convert to packed YUYV for some reason, then you probably want to first decode to planar YUV (for instance, using `tjDecompressToYUVPlanes()` in the TurboJPEG API, or `jpeg_read_raw_data()` in the libjpeg API) and then convert that to packed YUYV.

I am still unclear as to why you posted a code sample above that uses the libjpeg API when you appeared to be trying to build the TurboJPEG API.  However, I can tell you that the code sample you posted above is not optimal.  When you use `JCS_YCbCr` as an output colorspace, that causes the library to decode the JPEG image to planar YUV first and then convert planar YUV to packed YUV.  If your ultimate goal is to generate packed YUYV pixels, then it doesn't make sense to first convert planar YUV to packed YUV.  Just decode directly to planar YUV and convert that to packed YUYV.  If your ultimate goal is to generate packed RGBX pixels, then use `JCS_EXT_RGBX` as an output colorspace and skip all of the intermediate YUV/YUYV stuff.  

You also haven't yet told me anything regarding what type of hardware and CPU you are using.  I can only surmise that you are using an Android phone, based on the fact that you appeared to be building with the NDK and you said "phone" just now.  You also haven't told me the size of the MJPEG file or the resolution of the MJPEG frames, which is a critical factor in performance.  Did I mention that I can't read your mind?

If only the 2.0.0 version performs sub-optimally, then that may be a bug, although I struggle to think of any change to the ARM code between 1.5.x and 2.0.x that might have caused it.

BTW, 2.0.0 is available now.  Please stop using 1.5.90, which was the beta for 2.0.0.

Unless you can demonstrate a performance _*regression*_, i.e. 2.0.0 performs more slowly than 1.5.x, then there is nothing more I can do for you here.  Optimizing your code isn't my job.

**Comment by GoldenStrawberry** [comment]
hi,
I adopted your suggestion : use JCS_EXT_RGBX as an output colorspace and skip all of the intermediate YUV/YUYV stuff.
I had a personal problem in the process of converting MJPEG to RGBX ,here my code :
       
```
```
dinfo.err = jpeg_std_error(&jerr.super);
	jerr.super.error_exit = _error_exit;
	if (setjmp(jerr.jmp)) {
		goto fail;
	}
```
static void _error_exit(j_common_ptr dinfo) {
	struct error_mgr *myerr = (struct error_mgr *) dinfo->err;
#ifdef NDEBUG
//#ifndef NDEBUG
#if (defined(ANDROID) || defined(__ANDROID__))
	char err_msg[1024];
	(*dinfo->err->format_message)(dinfo, err_msg);
	err_msg[1023] = 0;
	LOGW("err=%s", err_msg);
#else
	(*dinfo->err->output_message)(dinfo);
#endif
#endif
	longjmp(myerr->jmp, 1);
}
```
Print out some information sometimes and the picture is unstable，like:
```
Unsupported marker type  0xXX
Not a JPEG file: starts with 0xXX 0xXX
Bogus Huffman table definition
```
Does this mean that my data got wrong?
