### ISSUE TITLE
LICENSE missing the author

### ISSUE THREAD

**Issue by elincoln** [libjpeg-turbo/libjpeg-turbo#287]
The copyright notices are still just templated out: 

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/LICENSE.md#the-modified-3-clause-bsd-license
`Copyright (C)<YEAR> <AUTHOR>. All Rights Reserved.`

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/LICENSE.md#the-zlib-license 
`Copyright (C) <YEAR>, <AUTHOR>.`

**Comment by dcommander** [comment]
Because the author will be different for every source file.
