### ISSUE TITLE
cjpeg run fail

### ISSUE THREAD

**Issue by 781545872** [libjpeg-turbo/libjpeg-turbo#294]
When I use cjepg to compress an image, I always get 'Unrecognized input file format --- perhaps you need -targa'.
What I excute is './cjepg -quality 80 -outfile t1.jpeg t.jpeg'.
However, when I use the cjpeg from mozjepg,it works.

**Comment by dcommander** [comment]
mozjpeg is designed to produce the maximum compression for JPEG images, using algorithms that are extremely slow (like 50x slower than libjpeg-turbo in some cases.)  Thus, it makes sense for their version of cjpeg to allow recompression of existing JPEG images.  The version of cjpeg in libjpeg and libjpeg-turbo has never supported that feature.  You can use jpegtran to perform some lossless operations on existing JPEG images, including converting them to progressive Huffman encoding (which will improve the compression ratio at the expense of worse decompression performance.)
