### ISSUE TITLE
Similar pattern to OOB bug reported in #258

### ISSUE THREAD

**Issue by xiemaisi** [libjpeg-turbo/libjpeg-turbo#295]
[The fix](https://github.com/libjpeg-turbo/libjpeg-turbo/commit/9c78a04df4e44ef6487eee99c4258397f4fdca55) for #258 introduces a few bounds checks for accesses to `colormap` in `rdbmp.c`. In `rdtarga.c`, there seem to be similar accesses (starting [here](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/rdtarga.c#L204)) that don't appear to be bounds-checked. Should they be?

(I'll be the first to admit that I understand neither the code nor the Targa format well enough to judge whether this is an actual problem.)

**Comment by dcommander** [comment]
Probably yes, but before fixing the problem, I would like to see an image that triggers it.  It should be possible to craft such an image, by setting up a color map with an entry count < 256 and then introducing color index values that exceed the number of entries in the color map.

**Comment by dcommander** [comment]
Reproduced, fixed, and pushed.
