### ISSUE TITLE
ubuntu18.04 android 

### ISSUE THREAD

**Issue by xiaofengff** [libjpeg-turbo/libjpeg-turbo#299]
![image](https://user-images.githubusercontent.com/25995549/47351606-e9eb3f80-d6ea-11e8-9172-7d2bad818956.png)

![image](https://user-images.githubusercontent.com/25995549/47351716-2a4abd80-d6eb-11e8-8c83-b928aafcab2a.png)

**Comment by xiaofengff** [comment]
![image](https://user-images.githubusercontent.com/25995549/47351835-67af4b00-d6eb-11e8-86ff-cbdfabfcba0a.png)

This is the same error

**Comment by xiaofengff** [comment]
ok ndk error version

**Comment by dcommander** [comment]
I don't understand what you mean by "ok ndk error version."  Have you solved the problem?

**Comment by xiaofengff** [comment]
yes I found the cause of the mistake There are no lower versions in the latest NDK packages
