### ISSUE TITLE
wrong jpeg library version 62: caller expects 90 iOS

### ISSUE THREAD

**Issue by naveen4016** [libjpeg-turbo/libjpeg-turbo#303]
I'm using XCode 10.0 and mac OS 10.13.6 iPhone OS 12.0. Im using jpeg turbo for image decompression. Im currently using libturbojpeg.a that was built using jpeg-turbo version 2.0.1 v6b JPEG_LIB_VERSION 62. But it fails and showing the error "wrong jpeg library version 62: caller expects 90".

Please help me to solve this. Thanks in advance.

**Comment by dcommander** [comment]
That error means that you are somehow picking up libjpeg v9 headers from somewhere else.  Make sure you are using both the libjpeg-turbo headers and library.
