### ISSUE TITLE
Eliminate support for compilers w/o unsigned char (to improve performance & readability)

### ISSUE THREAD

**Issue by mkver** [libjpeg-turbo/libjpeg-turbo#317]
It seems to me that the code for writing bmp files in wrbmp.c has a bottleneck, namely [this loop](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/wrbmp.c#L464):
```
      for (col = dest->row_width; col > 0; col--) {
        putc(GETJSAMPLE(*data_ptr), outfile);
        data_ptr++;
}
```
I benchmarked this with a purely black picture. Relative to the time it takes for pnm output, the current libjpeg-turbo (compiled via MSYS2/MinGW x64) takes 16.1 times the time; when the loop is replaced by fwrite, this drops to 1.25 the time.

Here is the patch:
```
diff --git a/wrbmp.c b/wrbmp.c
index 38a64e87..5d2a7ea5 100644
--- a/wrbmp.c
+++ b/wrbmp.c
@@ -461,10 +461,7 @@ finish_output_bmp(j_decompress_ptr cinfo, djpeg_dest_ptr dinfo)
         ((j_common_ptr)cinfo, dest->whole_image, row - 1, (JDIMENSION)1,
          FALSE);
       data_ptr = image_ptr[0];
-      for (col = dest->row_width; col > 0; col--) {
-        putc(GETJSAMPLE(*data_ptr), outfile);
-        data_ptr++;
-      }
+      fwrite(data_ptr, 1, dest->row_width, outfile);
     }
     if (progress != NULL)
       progress->completed_extra_passes++;
```
The problem with this patch is that libjpeg-turbo seems to support systems where no unsigned char is available (this is pre-ANSI C if I am not mistaken) and I don't know what happens on such systems. C99 actually says that "For each object, size calls are made to the fputc function, taking the values (in order) from an array of unsigned char exactly overlaying the object.", so what happens on systems without unsigned chars would need to be tested. The only thing I can say is that everything works fine for me with the above patch applied.

**Comment by dcommander** [comment]
Yes, technically speaking, libjpeg-turbo has never supported platforms for which `HAVE_UNSIGNED_CHAR` is false, so removing all of that cruft would be a good thing to do for the next release.
