### ISSUE TITLE
Support for NV12 in tjDecodeYUV(Planes)

### ISSUE THREAD

**Issue by elwongest** [libjpeg-turbo/libjpeg-turbo#320]
First thank you for this API with great performance.

I am using turbojpeg in an application that connects multiple cameras for live view and recording using ffdshow/xvid codec. Performance is excellent with MJPEG streams. I'm working on optimizing H264 streams with high number of cameras.

For best performance, I use the LAV Video Decoder with HW acceleration to decode H264 into NV12. Then I perform a couple of transforms to be able to use tjDecodeYUVPlanes to convert into RGB frames. The transforms are trivial, but I think it would be great if tjDecodeYUV would support NV12 directly using SIMD extensions. And I don't know how to code with these :(

Transforms are:
1 - Deinterleave the UV plane into two planes U and V
2 - Renormalize the YUV from 16-235(NV12) to 0-255 (if I don't do this, contrast is bad)

Here's the C/C++ code for the deinterleave only.
tmpData is *ptr to NV12 buffer
pData is *ptr to RGB output buffer

int wxh = img_width * img_height;
BYTE *uvPlane = tmpData + wxh;
BYTE *uPlane = new BYTE[wxh / 4];
BYTE *vPlane = new BYTE[wxh / 4];
BYTE *srcPlanes[3] = { tmpData, uPlane, vPlane };

for (int i = 0; i < (wxh / 4); i++)
{
	uPlane[i] = *(uvPlane++);
	vPlane[i] = *(uvPlane++);
}
tjhandle _jpegDecompressor = tjInitDecompress();
tjDecodeYUVPlanes(_jpegDecompressor, (const unsigned char **)srcPlanes, 0, TJSAMP_420,
	pData, img_width, 0, img_height, TJPF_BGR, TJFLAG_BOTTOMUP);
tjDestroy(_jpegDecompressor);

If I do just the above, it works, but I black is not quite black, and colors are dim-ish. For the full conversion, I replace the for loop above with the following (I need to renormalize the Y plane as well so an extra for loop):

for (int i = 0; i < wxh; i++)
{
	tmpData[i] = YUV2RGB[tmpData[i]];
}
for (int i = 0; i < (wxh / 4); i++)
{
	uPlane[i] = YUV2RGB[*(uvPlane++)];
	vPlane[i] = YUV2RGB[*(uvPlane++)];
}

YUV2RGB is the following static const (formula is y=(x-16)*255/219, clamped at 0 and 255):
static const BYTE YUV2RGB[256] = { // YUV to RGB renormalization
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 1, 2, 3, 5, 6, 7, 8,	9, 10, 12, 13, 14, 15, 16, 17,
	19, 20, 21, 22, 23, 24, 26, 27, 28, 29, 30, 31, 33, 34, 35, 36,
	37, 38, 40, 41, 42, 43, 44, 45, 47, 48, 49, 50, 51, 52, 54, 55,
	56, 57, 58, 59, 61, 62, 63, 64, 65, 66, 68, 69, 70, 71, 72, 73,
	75, 76, 77, 78, 79, 80, 82, 83, 84, 85, 86, 87, 88, 90, 91, 92,
	93, 94, 95, 97, 98, 99, 100, 101, 102, 104, 105, 106, 107, 108, 109, 111,
	112, 113, 114, 115, 116, 118, 119, 120, 121, 122, 123, 125, 126, 127, 128, 129,
	130, 132, 133, 134, 135, 136, 137, 139, 140, 141, 142, 143, 144, 146, 147, 148,
	149, 150, 151, 153, 154, 155, 156, 157,	158, 160, 161, 162, 163, 164, 165, 167,
	168, 169, 170, 171, 172, 173, 175, 176, 177, 178, 179, 180, 182, 183, 184, 185,
	186, 187, 189, 190, 191, 192, 193, 194, 196, 197, 198, 199, 200, 201, 203, 204,
	205, 206, 207, 208, 210, 211, 212, 213, 214, 215, 217, 218, 219, 220, 221, 222,
	224, 225, 226, 227, 228, 229, 231, 232, 233, 234, 235, 236, 238, 239, 240, 241,
	242, 243, 245, 246, 247, 248, 249, 250, 252, 253, 254, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255 };

Consider this a suggestion. I have a working solution right now, but I think performance could be better using parallel coding and I don't know how to do that. Maybe this already exists somewhere else, but the turbojpeg API is so easy to use. I looked at ways to use NV12 without converting to RGB, but could not find directshow video encoders for recording to AVI/MPEG that like it.

Thanks

**Comment by elwongest** [comment]
After further investigation, converting NV12 to planar YUV is trivial enough that it's not going to improve performance much. I will find better optimization by making my application use YUV formats only, instead of RGB.

My challenge is to find a way to output YUV formats from a decoder to multiple renderers through Pin Tee in DirectShow. The graph builder is giving me a hard time with that...

**Comment by dcommander** [comment]
Sorry for the delay.  I was traveling with limited Internet access whenever you posted this.  Basically the YUV functions in the TurboJPEG API just expose the underlying planar YCbCr color conversion routines that are part of the JPEG compression/decompression pipeline.  As such, there is really no way for us to provide any support for YUV formats other than the ones that the JPEG format uses, since those are the only formats for which we have SIMD-accelerated conversion algorithms.  Anything outside of that would require a full-featured set of image processing primitives, which exceeds the scope of libjpeg-turbo (although-- just putting this out there-- I do develop such algorithms and other custom SIMD functions for companies on a contract basis.)

**Comment by elwongest** [comment]
Thanks for replying dcommander.
Sorry it took me so long to come back. We've moved our application to h264 for performance increase and only kept mjpeg for legacy support. Still use turbojpeg for rgb to yuv conversion. The api is simple and performance tough to beat.
