### ISSUE TITLE
No difference of performance between libturbojpeg and libjpeg8?

### ISSUE THREAD

**Issue by alanlilyan** [libjpeg-turbo/libjpeg-turbo#322]
Hi, I'm new to develop jpeg. Recently I find the library libturbojpeg, it said that libturbojpeg more 2-7 times speed than the libjpeg. I try to use both of them to decompress the same jpeg image which resolution is 1920x1080 RGB （3 channels）.

both of codes had pre-read the jpeg image into memory buffer.

libjpeg pseudocode:
1.jpeg_mem_src
2.jpeg_read_scanlines
3.jpeg_finish_decompress

libturbojpeg pseudocode:
1.tjDecompressInit
2.tjDecompressHeader
3.tjDecompress

In my testing:
On x86_64, both cost 10-15ms, the averages are very close.
On arm32, both cost 50-70ms, the averages are very close too.

I have checked the binary ELF file.
One only has the symbol from libjpeg8, the other has the symbol from the static library libturbojpeg.a.

I don't know what the  **real** difference between them.

Could anyone explain that? 
Thanks.

More:
Do compress testing, the same reuslt.

**Comment by dcommander** [comment]
Depending on which O/S you are using, there is a very good chance that libjpeg8 is already libjpeg-turbo. Few operating systems ship with the unaccelerated IJG inplementation these days.

**Comment by alanlilyan** [comment]
Thanks for your replying. "Few operating systems ship with the unaccelerated IJG inplementation these days." Is that meaning just use libjpeg8 or libjpeg9 is enough which had already accelerated with jpegturbo?

And in my new testing, the libjpeg62 is slower 20ms(average) than the libjpeg8 (Debian9 vs Ubuntu 16.04). I guess the libjpeg62 is too old and doesn't have the acceleration. Is that right?

**Comment by alanlilyan** [comment]
okay, it's hard for me to find out the difference between those historical versions. However, the result was clear. I would like to choose the libjpeg8 to do develop, maybe on Ubuntu.
Thanks for your answer.
