### ISSUE TITLE
tjDecompressHeader3 fails for images with subsampling on all components

### ISSUE THREAD

**Issue by jfolz** [libjpeg-turbo/libjpeg-turbo#323]
While testing my code based on the turbojpeg API I encountered a couple of weird images from ImageNet. `tjDecompressHeader3` reports "Could not determine subsampling type for JPEG image".
If I ignore this error and continue `tjDecompress2` does not complain and the output is fine.

Here's the verbose output of djpeg for [one of these images](https://user-images.githubusercontent.com/3245870/51305202-813a0780-1a3a-11e9-90f5-3da3c67501f3.JPEG):

Start of Image
JFIF APP0 marker: version 1.01, density 72x72  1
Define Quantization Table 0  precision 0
Define Quantization Table 1  precision 0
Start Of Frame 0xc0: width=480, height=360, components=3
    Component 1: 2hx1v q=0
    Component 2: 2hx1v q=1
    Component 3: 2hx1v q=1
Define Huffman Table 0x00
Define Huffman Table 0x10
Define Huffman Table 0x01
Define Huffman Table 0x11
Start Of Scan: 3 components
    Component 1: dc=0 ac=0
    Component 2: dc=1 ac=1
    Component 3: dc=1 ac=1
  Ss=0, Se=63, Ah=0, Al=0
End Of Image

It seems that all components have the same 2x1 sampling rate, so there is effectively no color subsampling.
I suppose it's safe to ignore the error, though the way I'm doing it right now is to check the message which isn't particularly elegant or robust.

**Comment by dcommander** [comment]
Should be an easy fix. `tjDecompressHeader3()` was only initially designed to handle “sane” subsampling configurations. As people have stumbled upon insane ones, I’ve had to extend the function to handle those as well. Stand by.

**Comment by jfolz** [comment]
Thanks a lot for the fix! Is there a scheduled date for the next release?

**Comment by dcommander** [comment]
February

**Comment by dcommander** [comment]
You can of course use the pre-release builds in the meantime:
https://libjpeg-turbo.org/DeveloperInfo/PreReleases
