### ISSUE TITLE
A fix version will be released?

### ISSUE THREAD

**Issue by Neustradamus** [libjpeg-turbo/libjpeg-turbo#330]
With 2.0.1 CVEs, it is planned to have a 2.0.2?

**Comment by dcommander** [comment]
Of course there will be a 2.0.2.  Please don't waste my time.

**Comment by Neustradamus** [comment]
Why it is already closed?

**Comment by dcommander** [comment]
Because I answered your question.  Yes, a bug-fix version will be released, probably this month, but I do not and cannot make any guarantees regarding release date.  It will be finished when it's finished.

**Comment by Neustradamus** [comment]
Thanks for 2.0.2!
-> https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/2.0.2
