### ISSUE TITLE
Don't call 'nasm /?' at cmake call time.

### ISSUE THREAD

**Issue by trofi** [libjpeg-turbo/libjpeg-turbo#332]
The bug is originally reported as:
    https://bugs.gentoo.org/670944
    https://bugzilla.nasm.us/show_bug.cgi?id=3392529

The problem:
    cmake calls `nasm` with unsupported `/?` option. On some versions of nasm this leads to '/?' file to be created. In a sandboxed environment this triggers out-of-sandbox access violation and build failure.

It looks like the problem stems from https://github.com/libjpeg-turbo/libjpeg-turbo/blob/4f943644e5bf7544f126ce1d23e430e649a82c41/simd/CMakeLists.txt#L41 where `enable_language(ASM_NASM)` is called.

`nasm` maintainer suggests not to pass unsupported arguments to nasm.

**Comment by dcommander** [comment]
So what am I supposed to do about it?  Sounds like a CMake bug.

**Comment by trofi** [comment]
I'm not very familiar with `cmake` semantics WRT `enable_language()` and don't feel to be in a position of pointing at the right places to fix it. As original report notes while `nasm` happens to be fixed there is no intention to support this use case. Thanks for confirming it's not a `libjpeg-turbo` own behaviour.

Filed https://gitlab.kitware.com/cmake/cmake/issues/18941 on `cmake` side.

**Comment by hpax** [comment]
Please use -v as documented. There is no -? option either.

**Comment by dcommander** [comment]
This is CMake's bug:
https://gitlab.kitware.com/cmake/cmake/issues/18941
Please address any further comments to them.  There is nothing we can do about this within our project, as the errant behavior is entirely within CMake's code.
