### ISSUE TITLE
2.0.2 fails test djpeg-shared-3x2-float-prog-cmp in 32-bit chroot on 64-bit PowerPC

### ISSUE THREAD

**Issue by awilfox** [libjpeg-turbo/libjpeg-turbo#344]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No

**Clear and concise description of the bug:**
```
 83/151 Test  #83: djpeg-shared-3x2-float-prog-cmp ...................***Failed    0.00 sec
testout_3x2_float.ppm: FAILED.  Checksum is 0e917a34193ef976b679a6b069b1be26
```

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
* Obtain a 64-bit PowerPC computer and install a 32-bit chroot on it.
* Build libjpeg-turbo 2.0.2.
* Run ``ctest``.

**Image(s) needed in order to reproduce the bug (if applicable):**
n/a

**Expected behavior:**
Test suite passing (which it does on 64-bit native).

**Observed behavior:**
Test suite failing.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
Linux gwyn 4.14.88-mc13-easy-power8 #1 SMP Fri Feb 22 21:12:46 UTC 2019 ppc
gcc version 8.3.0 (Adelie 8.3.0) 
GNU ld (GNU Binutils) 2.32

**libjpeg-turbo version(s) in which the bug was observed:**
2.0.2

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**
This is a fun one.

```
6abd39160c5a3762e9ebe024e75407665093e715 is the first bad commit
commit 6abd39160c5a3762e9ebe024e75407665093e715
Author: DRC <information@libjpeg-turbo.org>
Date:   Tue Nov 15 08:47:43 2016 -0600

    Unified CMake-based build system
    
    See #56 for discussion.
    
    Fixes #21, Fixes #29, Fixes #37, Closes #56, Fixes #58, Closes #73
    Obviates #82
    
    See also:
    https://sourceforge.net/p/libjpeg-turbo/feature-requests/5/
    https://sourceforge.net/p/libjpeg-turbo/patches/5/
```

This is because, in the autoconf build system, `make test` output contained:

```
./djpeg -dct float -outfile testout_3x2_float.ppm testout_3x2_float_prog.jpg
if [ "" = "sse" ]; then \
        md5/md5cmp 1a75f36e5904d6fc3a85a43da9ad89bb testout_3x2_float.ppm; \
elif [ "" = "32bit" ]; then \
        md5/md5cmp f6bfab038438ed8f5522fbd33595dcdc testout_3x2_float.ppm; \
elif [ "" = "64bit" ]; then \
        md5/md5cmp 0e917a34193ef976b679a6b069b1be26 testout_3x2_float.ppm; \
elif [ "" = "387" ]; then \
        md5/md5cmp cb0a1f027f3d2917c902b5640214e025 testout_3x2_float.ppm; \
fi
rm -f testout_3x2_float.ppm testout_3x2_float_prog.jpg
```

**Additional information:**

**Comment by dcommander** [comment]
Ugh.  Yes, the old build system didn't automatically run the floating point tests (you had to run `make FLOATTEST={type} test` in order to enable them), because their expected output depends on the compiler.  The only PowerPC test bed I have is the Oregon State University Open Source Lab, and a 32-bit build of libjpeg-turbo tests successfully on those machines.  Thus, I can't really change the default behavior, because it would break the regression tests on the only platform I have available for testing.  I think you just need to change the `FLOATTEST` CMake variable to `64bit`.  I guess that's an idiosyncrasy of the chroot environment.
