### ISSUE TITLE
Question: How do I modify CMakeLists.txt  for performance analysis by use gprof

### ISSUE THREAD

**Issue by fermay** [libjpeg-turbo/libjpeg-turbo#345]
I want to see how long each function takes， so i add " set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -pg")  " in the CMakeLists.txt , but it seemingly not work, how can i modify in CMakeLists.txt ?

Thannks.

**Comment by dcommander** [comment]
Don't edit CMakeLists.txt.  Just run `ccmake {source-directory}` (where `{source-directory}` is the path to the libjpeg-turbo source), toggle advanced mode, and edit `CMAKE_C_FLAGS` there.  Or, you can just pass `-DCMAKE_C_FLAGS=-pg` on the cmake command line when you configure the build.

**Comment by fermay** [comment]
Thank you for your reply！
i am in Linux ,which architecture is x86_64, i use command :
1、cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS=-pg ./      ，which ./ is {source-directory}
2、make
3、./tjexample xxxx.jpg xxx.yuv 
4、gprof ./tjexample gmon.out   
but output Each sample counts as 0.01 seconds  no time accumulated

**Comment by dcommander** [comment]
That is not a libjpeg-turbo problem.  That's a gprof problem.  I haven't used gprof in a while, so I don't remember how to make it work.  All I could do is either google it or spend my free time trying to figure out how to make it work.  But you can also do those things.
