### ISSUE TITLE
 Signed Integer Overflow in jdhuff.c

### ISSUE THREAD

**Issue by skal65535** [libjpeg-turbo/libjpeg-turbo#347]
**Clear and concise description of the bug:**
The attached fabricated bitstreams will trigger an integer overflow and underflow
during the "s += state.last_dc_val[ci];" decoding operation.
The dc_diff coded is large enough to trigger a 32bit overflow in DC-luma value, after a enough blocks are decoded. Similar bitstream could be fabricated for 10bit or 12bit sample depth, as well as DC-chroma possibly.
The spec doesn't say anything about the acceptable range of PRED and DIFF (paragraph F.2.1.3.1).

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
djpeg overflow1.jpg
djpeg overflow2.jpg

ASAN will report "UndefinedBehaviorSanitizer: signed-integer-overflow"

**libjpeg-turbo version(s) in which the bug was observed:**
1.5.2

images to reproduce:

![overflow1](https://user-images.githubusercontent.com/6326167/55861254-3d0c5e00-5b76-11e9-8097-c7db376916ff.jpg)
![overflow2](https://user-images.githubusercontent.com/6326167/55861255-3da4f480-5b76-11e9-8794-56a4ad78557f.jpg)

**Comment by dcommander** [comment]
A couple of things:
1. Please re-test with the latest release (2.0.2.)  This project's public support policy is:
    - Any release of libjpeg-turbo ceases to be supported when a new bug-fix version with the same major version number is released (because how else can you "support" a particular version other than by releasing a new version with bug fixes?)  1.5.2 ceased being supported in 2017, with the release of 1.5.3.
    - No new releases of an old major version (1.5.x, in this case) will occur after a new major version (2.0.x, in this case) is out of the beta-test phase.  Thus, there are bug fixes in 2.0.2 that don't exist in 1.5.3, much less 1.5.2.
    - I try, as best as I can, to back-port relevant bug fixes to the last major version branch (the 1.5.x branch, in this case), but that code base certainly does not receive the same amount of attention as the current major version branch (the master branch.)
    - I can make variations to this policy in order to support a particular release for enterprise customers, but that costs $.
2. Please indicate which file this bug is in.

**Comment by dcommander** [comment]
Never mind.  I noticed that the file name was in the title.

**Comment by skal65535** [comment]
Hi,

my bad, in an effort to minimize the repro files, i cut them a bit too much.
Please find the full -much larger- files here:
   https://drive.google.com/open?id=1zARJujdkSbHuQSR3b5MvXYvR0kbAexe5
(too large to be attached here).
There's also a small patch against 5857929f (HEAD) that will print the overflow when it happens.

hope it helps,
skal/

**Comment by dcommander** [comment]
Refer to commit log for details.

**Comment by dcommander** [comment]
Another note: I just realized that this is actually the same issue as the one that  9ab569e6163a906fe8d4443a8a4c0d466a112394 fixed in the progressive Huffman decoder.  That issue was fixed by introducing an if() statement, but since the Huffman codec's performance depends heavily on the compiler, the introduction of new if() statements can change that performance.  Thus, every time a new if() statement is introduced, it is necessary to thoroughly test for performance regression.  In this case, the chances of performance regression are greater, since jdhuff.c is more optimized than jdphuff.c.  Thus, I'd rather not use an if() statement unless absolutely necessary (such as, for instance, if this issue could be shown to have any security ramifications-- but I don't think it could.)

**Comment by skal65535** [comment]
Fair enough.

Thanks for the fix! 
Note that there's also a similar line at jdhuff.c:691 with potential overflow.

skal/

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/jdhuff.c#L691

**Comment by dcommander** [comment]
Yes, and I'll fix that one as soon as someone can come up with a real JPEG image that triggers it.  I've fixed more than a handful of UBSan errors over the past five years, and none of them has ever amounted to a real security issue (the only one that even came close was an out-of-bounds array reference.)  In general, I find UBSan to be overly pedantic, and with rare exceptions, fixing the issues it flagged hasn't improved our code in any meaningful way.  On more than one occasion, I've fixed an error with one version of UBSan, only to have a newer version of UBSan trigger on the fixed code.  Thus, I'm really not interested in preemptively guessing what UBSan might trigger on.  I'll fix the actual errors it reports when it reports them.

**Comment by skal65535** [comment]
I've uploaded overflow5.jpg and overflow6.jpg at the same location, that exercise the wrap-around at jdhuff.c:691 too.

files: https://drive.google.com/open?id=1Kpdp4NTkYZKLJWO9XJLuPio7XqiDkzJ3

skal/

(that being said, I concur to the general feeling about UBSan fixes).
