### ISSUE TITLE
Integrating libjpeg-turbo into external CMake build system

### ISSUE THREAD

**Issue by Crisspl** [libjpeg-turbo/libjpeg-turbo#353]
Hi, we're trying to integrate libjpeg-turbo into our project, but struggling with weird error given by cmake:
```
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_ASM_COMPILE_OBJECT
```
(this multiple times)

Here's the CMakeLists.txt file with `add_subdirectory(libjpeg-turbo)`: https://github.com/Crisspl/IrrlichtBAW/blob/jpeg-turbo/3rdparty/CMakeLists.txt#L37
which is ran from here https://github.com/Crisspl/IrrlichtBAW/blob/jpeg-turbo/CMakeLists.txt#L140

However it all configures and then builds fine when treated separately, not by `add_subdirectory` from our scripts (I mean just how it's usually done with CMake).
Could you take a look and hopefully you'll find some possible cause?

**Comment by dcommander** [comment]
Please use `ExternalProject_Add()`.  Integrating our build system with `add_subdirectory()` isn't supported or supportable.

**Comment by konsnos** [comment]
Hey @dcommander ,

May I ask what are the issues with add_subdirectory?

In a similar note I am trying to include the project in CMake with FetchContent

```
include(FetchContent)
FetchContent_Declare(
  libjpeg-turbo
  GIT_REPOSITORY https://github.com/libjpeg-turbo/libjpeg-turbo.git
  GIT_TAG        2.0.4
)

FetchContent_MakeAvailable(libjpeg-turbo)
```

The given error in this case is 
```
CMake Error at build/_deps/libjpeg-turbo-src/CMakeLists.txt:1386 (install):
  install FILES given no DESTINATION!
```

and it seems that `${CMAKE_INSTALL_DOCDIR}` is empty.

**Comment by dcommander** [comment]
Search for add_subdirectory in the issues. I’ve had to explain it multiple times already.
