### ISSUE TITLE
Question about jpeg_read_scanlines functionality

### ISSUE THREAD

**Issue by noah-curran** [libjpeg-turbo/libjpeg-turbo#359]
Hi,

I am wondering how jpeg_read_scanlines actually reads the data for something I am working on. I tried reading the source code, but the functionality for reading seems to be within a function pointer (in cinfo->main->process_data). I couldn't find where this function pointer is declared, so would I be able to get a finger in the right direction? If it helps, I am reading in the data via file, so I used jpeg_stdio_src.

I appreciate any help!

**Comment by dcommander** [comment]
Looking at the djpeg source is your best bet. If the libjpeg API is too complex, you can also use the TurboJPEG API, which is more straightforward and better documented.

**Comment by noah-curran** [comment]
Unfortunately, for my needs, the TurboJPEG API is too limiting. After taking a look at djpeg, I'm unsure how this makes anything more clear about how jpeg_read_scanlines works when that file just seems to indicate how to use it. I am particularly interested in how this method decodes the image. Does it have a "pixel pointer" where it moves through the huffman encoded jpeg file until it has obtained enough pixels to cover the designated number of rows? I'm also interested to see if jpeg_skip_scanlines works in a different or similar way as jpeg_read_scanlines.

**Comment by noah-curran** [comment]
Actually, I think I figured it out. Thanks for the help.
