### ISSUE TITLE
Can't open a JPEG image saved with libjpeg-turbo (possibly size-related)

### ISSUE THREAD

**Issue by FlorentTomi** [libjpeg-turbo/libjpeg-turbo#361]
Hello,

Problem:
I saved an image with libjpeg-turbo, and tried to open it back with it.
The program crash during tjDecompress2 (seems like an access violation).
Informations given by tjDecompressHeader3 are valid.

Image information:
Size: 47617 x 29422
Format: RGB

I have no issue opening other images with the same code. This image is bigger than any other image I usually open, so I think it may be size-related, even though it's not really close the '65535x65535' JPEG size limit.

Thank you!

**Comment by dcommander** [comment]
Should now be fixed.  Please re-test.

**Comment by liamwhite** [comment]
Confirming that this issue is fixed by 2a9e3bd7430cfda1bc812d139e0609c6aca0b884.

Hoping to see this in a release soon.

**Comment by dcommander** [comment]
Fixing this problem exhausted the libjpeg-turbo General Fund through September, unfortunately.  I have applied for compensation through the Google Security Patch Rewards program, which seems particularly fair given that Google requested that I fix this bug.  Barring that, the 2.0.3 release will have to be delayed until I catch up with the General Fund.
