### ISSUE TITLE
Unsupported marker type 0x0b

### ISSUE THREAD

**Issue by zhengrenzhe** [libjpeg-turbo/libjpeg-turbo#364]
hello, i want to decode an jpeg image, tjDecompressHeader3 is successfully, but tjDecompress2 report error `Unsupported marker type 0x0b`, here is my example code:

```c
  char *buff = calloc(1, 8);
  size_t filesize = 0;

  read_file(TEST_FILE_PATH, buff, &filesize); // custom function, read file is successfully

  int width = 0;
  int height = 0;
  int subsmap = 0;
  int colorspace = 0;

  // decompress header is also successfully
  int result = tjDecompressHeader3(
      decoder,
      (unsigned char *) buff,
      filesize,
      &width,
      &height,
      &subsmap,
      &colorspace
  );

  printf("[%s] width: %dpx, height: %dpx, subsmap: %d, colorspace: %d\n",
         tjGetErrorStr2(decoder),
         width,
         height,
         subsmap,
         colorspace);
  // [No error] width: 913px, height: 693px, subsmap: 2, colorspace: 1

  unsigned char buffer[width * height * 3];

  int flag = 0;
  flag |= TJFLAG_FASTDCT;
  // but this step report error
  int res = tjDecompress2(decoder, (unsigned char *) buff, filesize, buffer, width, 0, height, TJCS_RGB, flag);

  printf("[%s]", tjGetErrorStr2(decoder));
  // [Unsupported marker type 0x0b]
```
attached file is my test image, so what is the right way to decode this image? i tried any Pixel formats and flags, but received same error msg every time. how can i confirm the right tjDecompress2's params(pixelFormat and flags)? thank you very much!

![test](https://user-images.githubusercontent.com/5652241/61931107-57960600-afb2-11e9-9d65-2d4f492b65d9.jpg)

**Comment by dcommander** [comment]
I don't see anything wrong with how you are decoding the image, but I suspect the problem is with how you are reading the image into memory.  You appear to be allocating only 8 bytes for it, so `read_file()` is probably blowing out of your buffer.  If not, then double check how you are reading the file in `read_file()`.  If you are using `fopen()` on a Windows machine, make sure you specify "rb" as the mode rather than "r", or else `fread()` will try to convert any line feed characters it encounters into carriage return + line feed, which will have the effect of corrupting the JPEG file structure.

**Comment by dcommander** [comment]
I see another problem.  You should be passing `TJPF_RGB` as the pixel format in `tjDecompress2()`, not `TJCS_RGB`.  Refer to the API documentation: https://cdn.rawgit.com/libjpeg-turbo/libjpeg-turbo/master/java/doc/index.html

As far as which flags and pixel formats are "correct", that depends on your specific application.  The pixel format controls the format of the output buffer.  It has nothing to do with the JPEG image itself.  Also, unless you fully understand the differences between the fast and accurate integer DCT, it's probably best to leave that setting alone.  There isn't a lot of performance difference between the "fast" and "accurate" DCTs in libjpeg-turbo.  Those settings are historical-- a relic of the early 90s, when some CPUs were so slow that it took minutes to decode a multi-megapixel JPEG file.

**Comment by zhengrenzhe** [comment]
thanks
