### ISSUE TITLE
jpegtran: autocrop

### ISSUE THREAD

**Issue by jidanni** [libjpeg-turbo/libjpeg-turbo#372]
jpegtran could add an autocrop feature: eating the borders of images.
E.g., Billy places small picture on big scanner bed, and later wants to losslessly trim all that extra white from the edges without needing to calculate coordinates.

**Comment by jidanni** [comment]
Sure, one might say what if there was a speck of dust on the scanner bed, making it not all white...

**Comment by dcommander** [comment]
Sorry, but that would require pattern recognition.  jpegtran performs lossless cropping in frequency space by discarding whole MCU blocks.  I doubt that what you propose would even be possible in frequency space, and even if it was, it would be out of scope for a JPEG codec library.  Please do not expect this free library to be everything to everyone.  It began as nothing more than a high-speed drop-in replacement for libjpeg.  I have added features, such as the TurboJPEG API and the libjpeg-turbo colorspace extensions, that make it easier for developers to manipulate JPEG images, but at the end of the day, we're still just a codec library, not a comprehensive image processing program.

**Comment by jidanni** [comment]
(OK. I was probably over-interpreting this part of the man page:)
>       For practical use, you may prefer to discard any untransformable edge pixels rather than having a strange-looking strip along the right and/or bottom edges of a transformed image.  To do this, add the -trim switch:
