### ISSUE TITLE
Can it be used with VB6.0

### ISSUE THREAD

**Issue by amoltarte** [libjpeg-turbo/libjpeg-turbo#376]
Do you have any wrapper with which I can use latest libjpeg-turbo in my widely used app which is developed in VB6 (Visual Basic 6.0)
We have used ijl15 in our vb software but want to switch to libjpeg-turbo.
Any help is appreciated.

**Comment by dcommander** [comment]
No such wrapper exists to my knowledge.  VB 6 was declared a legacy technology two years before libjpeg-turbo even existed.  It might be possible to call TurboJPEG API functions in **turbojpeg.dll** from VB using `Private Declare Function`, but I don't really know much about VB.  I just know, from googling, that others have done that in the past:  http://www.vbforums.com/showthread.php?845771-Calling-Jpeglib-turbo-from-vb6-make-app-crash

**Comment by dcommander** [comment]
Also note: I do provide consulting and funded development work on libjpeg-turbo for reasonable hourly rates, so if your organization wishes to pay me to write a VB wrapper, I can certainly do that.  Otherwise, it's not likely to happen, given that VB is an obsolete technology.
