### ISSUE TITLE
Trouble getting started with libjpeg-turbo

### ISSUE THREAD

**Issue by MikeCowlishaw** [libjpeg-turbo/libjpeg-turbo#380]
Hi; I have for some years been using libjpeg (and currently build it and use it for building 32-bit and 64-bit applications on Windows, such as PanGazer).  I therefore have two trees (Win-builds and Win-builds-64, both mingw-based).

As far as I can tell, I should be able to use libjpeg-turbo .a files as drop-in replacements for the two libjpeg.a files (one in each tree)?   However, I cannot determine which downloadable binary/binaries I should use to get these two files.  Ideally a file with only the two files (32-bit and 64-bit .a).

Any guidance would be much appreciated, and apologies if I've missed something obvious.

Mike Cowlishaw  (speleotrove.com)

**Comment by dcommander** [comment]
Install **libjpeg-turbo-2.0.3-gcc.exe** and **libjpeg-turbo-2.0.3-gcc64.exe** from https://sourceforge.net/projects/libjpeg-turbo/files/2.0.3.  The .a files will be under, respectively, **c:\libjpeg-turbo-gcc\lib** and **c:\libjpeg-turbo-gcc64\lib**.

**Comment by MikeCowlishaw** [comment]
Many thanks!   Don't know how I missed the gcc64.exe.
