### ISSUE TITLE
AVX2 Fast-int forward DCT returns different results than the other forward DCTs.

### ISSUE THREAD

**Issue by tigermonkey** [libjpeg-turbo/libjpeg-turbo#386]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

Yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

No

**Clear and concise description of the bug:**

Fast-int forward DCT returns different results than the other forward DCTs.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

Originally experienced with mozjpeg https://github.com/mozilla/mozjpeg/issues/328

But I can write a C example that exhibits the problem. 

**Image(s) needed in order to reproduce the bug (if applicable):**

Referenced in the above issue.

**Expected behavior:**

All forward DCTs should return similar results.

**Observed behavior:**

The AVX2 DCT returns different values.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

Linux, GCC 7.4.0, Intel i7-7600U

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the master branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

Latest. 

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

N/A

**Additional information:**

**Comment by dcommander** [comment]
Also, your post does not make clear exactly what you expect.  The fast integer forward DCT is of course supposed to produce different results than "the other forward DCTs."  However, the AVX2 and SSE2 and C implementations of the fast integer forward DCT should all produce identical results (as well as produce identical results to the same algorithm in libjpeg v6b.)  `make test` assures that.

**Comment by tigermonkey** [comment]
Here is an example that reproduces the problem:

```c
#include<stdio.h>

#define JPEG_INTERNALS
#include "jinclude.h"
#include "jpeglib.h"
#include "jdct.h"

extern void jsimd_fdct_islow_avx2(DCTELEM *data);
extern void jsimd_fdct_islow_sse2(DCTELEM *data);
extern void jpeg_fdct_islow(DCTELEM *data);

void print_block(DCTELEM *data) {
    for (size_t i = 0; i < DCTSIZE2; i++) {
        printf("%6d ", data[i]);
        if (i % 8 == 7)
            printf("\n");
    }
}

DCTELEM test[] = {
    -128, -128, -128, -118, 157, 157, 157, 157,
    -128, -128, -128, -120, 157, 157, 157, 157,
    -128, -128, -128, -122, 157, 157, 157, 157,
    -128, -128, -128, -128, 157, 157, 157, 157,
    -128, -128, -128, -128, 120, 157, 157, 157,
    -128, -128, -128, -127, 116, 157, 157, 157,
    -128, -128, -128, -128, 123, 157, 157, 157,
    -128, -128, -128, -124, 157, 157, 157, 157
};

typedef void (*dct_f)(DCTELEM *data);

void test_dct(dct_f f, const char *name) {
    printf(">>>> %s\n", name);
    DCTELEM test_copy[DCTSIZE2];
    memcpy(test_copy, test, sizeof(test));
    printf(">>>> Before DCT\n");
    print_block(test_copy);
    (*f)(test_copy);
    printf(">>>> After DCT\n");
    print_block(test_copy);
    printf("\n");
}

int main(int argc, char *argv[]) {
    test_dct(jsimd_fdct_islow_avx2, "jsimd_fdct_islow_avx2");
    test_dct(jsimd_fdct_islow_sse2, "jsimd_fdct_islow_sse2");
    test_dct(jpeg_fdct_islow, "jpeg_fdct_islow");
    return 0;
}
```

Save it as t.c and compile with
```sh
 gcc -ggdb -o t t.c build/simd/CMakeFiles/simd.dir/x86_64/jfdctint-avx2.asm.o build/simd/CMakeFiles/simd.dir/x86_64/jfdctint-sse2.asm.o build/simd/CMakeFiles/simd.dir/x86_64/jfdctflt-sse.asm.o build/simd/CMakeFiles/simd.dir/x86_64/jfdctfst-sse2.asm.o ./build/CMakeFiles/turbojpeg-static.dir/jfdctint.c.o ./build/CMakeFiles/turbojpeg-static.dir/jfdctfst.c.o ./build/CMakeFiles/turbojpeg-static.dir/jfdctflt.c.o
```

Running it produces:
```
>>>> jsimd_fdct_islow_avx2                                                                                        
>>>> Before DCT
  -128   -128   -128   -118    157    157    157    157 
  -128   -128   -128   -120    157    157    157    157 
  -128   -128   -128   -122    157    157    157    157 
  -128   -128   -128   -128    157    157    157    157 
  -128   -128   -128   -128    120    157    157    157 
  -128   -128   -128   -127    116    157    157    157 
  -128   -128   -128   -128    123    157    157    157 
  -128   -128   -128   -124    157    157    157    157 
>>>> After DCT
   845   8159    109   2791    -83  -1774     45   1448 
   104    -16   -136     47    104    -72    -56     84 
    71     -9    -93     26     71    -39    -39     46 
   -97     26    127    -73    -97    110     53   -130 
    37    -11    -48     31     37    -46    -20     54 
     3     -4     -3     10      3    -15     -1     17 
    17     -1    -22      4     17     -5     -9      7 
   -29      9     37    -25    -29     36     15    -43 

>>>> jsimd_fdct_islow_sse2
>>>> Before DCT
  -128   -128   -128   -118    157    157    157    157 
  -128   -128   -128   -120    157    157    157    157 
  -128   -128   -128   -122    157    157    157    157 
  -128   -128   -128   -128    157    157    157    157 
  -128   -128   -128   -128    120    157    157    157 
  -128   -128   -128   -127    116    157    157    157 
  -128   -128   -128   -128    123    157    157    157 
  -128   -128   -128   -124    157    157    157    157 
>>>> After DCT
   845   8159    109   2791    -83  -1774     45   1448 
   104    -16   -136     47    104    -72    -56     84 
    71     -9    -93     26     71    -39    -39     46 
   -97     26    127    -73    -97    110     53   -130 
    37    -11    -48     31     37    -46    -20     54 
     3     -4     -3     10      3    -15     -1     17 
    17     -1    -22      4     17     -5     -9      7 
   -29      9     37    -25    -29     36     15    -43 

>>>> jpeg_fdct_islow
>>>> Before DCT
  -128   -128   -128   -118    157    157    157    157 
  -128   -128   -128   -120    157    157    157    157 
  -128   -128   -128   -122    157    157    157    157 
  -128   -128   -128   -128    157    157    157    157 
  -128   -128   -128   -128    120    157    157    157 
  -128   -128   -128   -127    116    157    157    157 
  -128   -128   -128   -128    123    157    157    157 
  -128   -128   -128   -124    157    157    157    157 
>>>> After DCT
   845  -8225    109   2791    -83  -1774     45   1448 
   104    -16   -136     47    104    -72    -56     84 
    71     -9    -93     26     71    -39    -39     46 
   -97     26    127    -73    -97    110     53   -130 
    37    -11    -48     31     37    -46    -20     54 
     3     -4     -3     10      3    -15     -1     17 
    17     -1    -22      4     17     -5     -9      7 
   -29      9     37    -25    -29     36     15    -43                        
```

The second value for each of the DCTs is: 8159, 8159 and -8225. I think the -8225 is the correct one.

**Comment by dcommander** [comment]
Please explain the disparity in your claims.

Your initial post claims that the fast integer forward DCT returns different results than "the other forward DCTs."  However, your comment above deals with the slow integer forward DCT, not the fast integer forward DCT, and it clearly shows that the AVX2 and SSE2 results are identical (which is inconsistent with your claim that the AVX2 algorithm is producing different results than all others.)

So let me explain a few things:
1. It is expected that the SIMD and C algorithms won't return identical values across every single possible input value.  However, they should return identical values across every single possible input value that would be encountered when compressing a real JPEG image.  So in order for me to treat this as a libjpeg-turbo bug, I need you to:
    1. Demonstrate the problem using a real input image, not an artificially constructed set of inputs.
    2. Demonstrate the problem using libjpeg-turbo, not mozjpeg.  I don't support mozjpeg unless someone is specifically paying me to do so, and due to the nature of mozjpeg, it would not surprise me if this problem is only reproducible in that downstream project and not in upstream libjpeg-turbo.
2. The SSE2 algorithms are quite stable and very thoroughly tested, so as long as the AVX2 algorithms are producing identical results to the SSE2 algorithms, it's likely that what you're observing isn't a real bug.

**Comment by tigermonkey** [comment]
What I meant by "AVX2 fast-int forward DCT" was the `jsimd_fdct_islow_avx2`. Sorry for the confusion. After reporting I experimented with that C snippet and I found SSE2 was also affected.

> It is expected that the SIMD and C algorithms won't return identical values across every single possible input value. However, they should return identical values across every single possible input value that would be encountered when compressing a real JPEG image.

Are those possible input values documented somewhere? I could not find what the SIMD algorithms expect. I suspect the SIMD functions always receive values in the range 0 to 255 in libjpeg-turbo, and does not expect negative values. However the SIMD instructions seem to work on 16-bit integers.

**Comment by dcommander** [comment]
`jsimd_fdct_islow_avx2()` is the AVX2 slow integer forward DCT.  `jsimd_fdct_ifast_avx2()` is the AVX2 fast integer forward DCT.  That's an important distinction.

The algorithm expects input values in the range of -128 to 127.  The 157 value in your test matrix is the source of the issue.
