### ISSUE TITLE
tjDecompressToYUV2  double free

### ISSUE THREAD

**Issue by OOSYOO** [libjpeg-turbo/libjpeg-turbo#387]
Hi:
When I decode a [picture](https://drive.google.com/open?id=1EdqmsMExmzA151Op-ptoDLSg7u_2Nr-h) with “tjDecompressToYUV2”, it will cause doublefree；

![double_free_info](https://user-images.githubusercontent.com/39845909/68634178-85866280-052f-11ea-8594-69755de72e01.jpg)

**Comment by dcommander** [comment]
Is this reproducible using the latest (2.0.3) release?

**Comment by OOSYOO** [comment]
yes------------------ 原始邮件 ------------------
发件人: "DRC"<notifications@github.com>
发送时间: 2019年11月12日(星期二) 中午12:59
收件人: "libjpeg-turbo/libjpeg-turbo"<libjpeg-turbo@noreply.github.com>;
抄送: "ShenYue"<381940186@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [libjpeg-turbo/libjpeg-turbo] tjDecompressToYUV2  double free(#387)



Is this reproducible using the latest (2.0.3) release?
 
&mdash;

**Comment by OOSYOO** [comment]
> Is this reproducible using the latest (2.0.3) release?

yes
