### ISSUE TITLE
srcPlanes parameter of tjCompressFromYUVPlanes should be const

### ISSUE THREAD

**Issue by zhykzhykzhyk** [libjpeg-turbo/libjpeg-turbo#395]
The current type of `srcPlanes` paramter of `tjCompressFromYUVPlanes` is `const unsigned char **`, which implies the function could change the pointer to a plane, `const unsigned char *const *` would be better.

**Comment by dcommander** [comment]
I will bear that in mind if the API function needs to be changed for other reasons. The TurboJPEG API evolved over the years, rather than being designed, so it has some imperfections.

**Comment by dcommander** [comment]
Subsumed by #517

**Comment by dcommander** [comment]
Implemented in the TurboJPEG 3 API
