### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [libjpeg-turbo/libjpeg-turbo#398]
[Extra null pointer checks are not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [decomp](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/c30b1e72dac76343ef9029833d1561de07d29bad/tjbench.c#L307 "decomp function")
- [Java_org_libjpegturbo_turbojpeg_TJTransformer_transform](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/6399d0a699b1756337cd0589bf3de0b4fad48b20/turbojpeg-jni.c#L1235 "Java_org_libjpegturbo_turbojpeg_TJTransformer_transform function")

**Comment by dcommander** [comment]
This is a common programming practice that is not specific to this project.  I'm old enough that, back when I learned how to program in C, not all compilers properly handled `free(NULL)`.  I do agree that these NULL checks are unnecessary with modern compilers.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/libjpeg-turbo/libjpeg-turbo/commit/fdf890335455d9470f21863b01f1ecb9bf085c86 "Eliminate unnecessary NULL checks before free()").
