### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [libjpeg-turbo/libjpeg-turbo#399]
I would like to point out that identifiers like “[`__TURBOJPEG_H__`](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/6d8caa9f88184ad1698e91c94b37acb9506dacf0/turbojpeg.h#L29 "Update candidate")” and “[`__4X`](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/6d8caa9f88184ad1698e91c94b37acb9506dacf0/simd/powerpc/jsimd_altivec.h#L33 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by dcommander** [comment]
I already answered this in https://github.com/VirtualGL/virtualgl/issues/110.  Same answer here.  Not interested.

**Comment by elfring** [comment]
:crystal_ball: I became curious if the change interest will grow from other users of this software according to the [avoidance of undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?").

**Comment by dcommander** [comment]
Other users of the software probably don’t care as long as the software works. I’ve told you before that I would be more likely to fix these issues if there were an automated tool or compiler flag that would detect them. But you haven’t provided one.

**Comment by elfring** [comment]
Various tools are available to detect also the potential for undefined software behaviour.
Would you like to try a program like “grep” out for a corresponding source code search?

**Comment by dcommander** [comment]
Provide exact instructions for using such tools to detect these issues.  I am not going to spend any of my valuable time crafting such a tool.

**Comment by dcommander** [comment]
Also, `grep` is not an acceptable solution.  The tool must be something pre-existing, such as Clang Static Analyzer or a compiler option that can be used along with `-Werror`.

**Comment by elfring** [comment]
>If such a tool doesn't exist, then that means that the community at large doesn't care much about these issues, so why should I?

Will the software development attention grow also for [secure coding guidelines](https://wiki.sei.cmu.edu/confluence/display/c/SEI+CERT+C+Coding+Standard "SEI CERT C Coding Standard")?

**Comment by dcommander** [comment]
I am through answering your questions. Please answer mine.

**Comment by elfring** [comment]
It seems that your change resistance hinders you from taking more helpful information better into account.

**Comment by dcommander** [comment]
I’ve told you what I need from you in order to proceed. Provide it or go away. Trolling me is not one of your options.

**Comment by dcommander** [comment]
In fact, I am not resistant to change at all.  I've already explained that this project has limited resources, and your nit picking has taken hours of my time away from developing new, meaningful features for the open source community.  I am not resistant to change, but I also believe that change should justify itself.  I simply can't dedicate hours to code style issues, and you haven't convinced me that these issues are any more than that.  It is your responsibility to convince me, not my responsibility to be convinced.
