### ISSUE TITLE
add version information resource to Windows DLL

### ISSUE THREAD

**Issue by dummzeuch** [libjpeg-turbo/libjpeg-turbo#407]
The Windows DLLs don't seem to have the version information resource that Windows executables usually have. Since all DLLs have the same name and there seems to be no way (API call?) to get the version this makes it very difficult to troubleshoot any problems.

Adding a version info resource would help a lot here.

**Comment by dcommander** [comment]
You can currently use the Strings application in Windows Sysinternals (https://docs.microsoft.com/en-us/sysinternals/downloads/strings) to fetch libjpeg-turbo version information from the DLL's string table:

```
strings64 c:\libjpeg-turbo\bin\*.dll | findstr /i build
```
Is that an acceptable solution?

**Comment by dcommander** [comment]
@dummzeuch Is the solution I presented above workable?

**Comment by dcommander** [comment]
Closing due to lack of response.  I'm certainly unwilling to implement a new feature for someone who can't be bothered to respond to my questions.

**Comment by dummzeuch** [comment]
Oops, missed your reply again. Sorry.

In Windows, you can check the version information resource by right clicking on an executable and selecting "Properties" and then the "Details" tab. That's convenient when you want to check the version manually, e.g. to see whether some oddity is related to a specific version of a DLL of if a DLL needs updates. In my line of work (road condition survey with measurement vehicles whose software is running on Windows) it is costly to send an updated executable to an installation, so knowing beforehand which version is currently in use saves time and effort. So far we try to track this information in external documentation, but that's not as reliable as I would like it to be.

Depending on where the version info is available in the sources it wouldn't be difficult to read that info and append the version info resource to the executable after it has been created.
Unfortunately I am not familiar with the build system used in this project and don't know what options those tools have. So I cannot suggest a working solution.

**Comment by dcommander** [comment]
This has been implemented.  See #576.
