### ISSUE TITLE
Android YUV to Jpeg compression error from Java API

### ISSUE THREAD

**Issue by bach1bouzouk** [libjpeg-turbo/libjpeg-turbo#413]
Hello,

We tried to compress a YUV 420 to JPEG using the Java/JNI API from Turbojpeg on android:
                        
```
//  toTransmit -> YUV 420 byte array
yuvImage = new YUVImage(toTransmit, width, 4, height, SAMP_420);                           

TJCompressor tjc = new TJCompressor();
tjc.setSourceImage(yuvImage);
tjc.setSubsamp(SAMP_420);
tjc.setJPEGQuality(70);

byte[] output_jpeg = tjc.compress(TJ.FLAG_BOTTOMUP);
tjc.close();
```

We expected a filled `output_jpeg` and get a this error instead : 
**java.lang.IllegalStateException: No source image is associated with this instance**

Logs

` java.lang.IllegalStateException: No source image is associated with this instance
at org.libjpegturbo.turbojpeg.TJCompressor.checkSourceImage(TJCompressor.java:653)
at org.libjpegturbo.turbojpeg.TJCompressor.compress(TJCompressor.java:380)`

Informations:
- Platform: Android
- Target: arm64-v8a
- libjpeg-turbo-2.0.4 (release)

Are we using the Java/JNI wrapper correctly or is this a libjpeg-turbo issue ?

Could we use the C API from a custom JNI in the meantime to get the compress JPEG file ? I see in [this post](https://github.com/libjpeg-turbo/libjpeg-turbo/issues/161#issuecomment-319248983) that you discourage JNI calls outside your API for perfomances reasons ?

**Comment by dcommander** [comment]
Should now be fixed in master
