### ISSUE TITLE
Support for JPEG compression for BayerRG8?

### ISSUE THREAD

**Issue by mwiegant** [libjpeg-turbo/libjpeg-turbo#416]
Hello,

Does libjpeg-turbo have any support for JPEG compression for BayerRG8 formats?

I'm not explicitly using libjpeg-turbo, but I have a C# project that is using [libjpeg-turbo-net](https://github.com/Sergey-Terekhin/libjpeg-turbo-net) which I believe is just a C# wrapper for libjpeg-turbo.

-- 

We have a feed of data from a camera, and while we can get straight BGR formatted data from the camera, it takes a lot longer to get the data when it's formatted that way. I'm separately looking into what options Windows / C# might have for converting from BayerRG8 to BGR.

**Comment by dcommander** [comment]
It might be possible to use the libjpeg API to create a JPEG image that uses the RGB colorspace (as opposed to the YCbCr colorspace normally used in JPEG images) with two green samples for every red and blue sample.  It might also be possible to feed that data directly into the compressor as planar R/G/B data using `jpeg_write_raw_data()`.  If that doesn't work, however, then I have no other ideas.  Also, unfortunately, the existing libjpeg-turbo C# wrappers are built around the TurboJPEG API, not the libjpeg API, so they do not expose the underlying functions necessary to accomplish what I propose.  Also, RGB JPEG images unfortunately do not compress as well as YCbCr JPEG images.  If you're OK with "throwing away" the additional green resolution (which you seem to be, given that BGR is acceptable apart from the slow performance), then I'd recommend just writing your own BayerRG8-to-planar-YCbCr converter and feeding the YCbCr planes into the TurboJPEG API, which supports compressing a JPEG image directly from YCbCr planar data.
