### ISSUE TITLE
Upgrade version of jquery.js

### ISSUE THREAD

**Issue by Kingshuk1991** [libjpeg-turbo/libjpeg-turbo#421]
Is it possible to upgrade the version of jquery.js ? The used version is v1.7.1 where the latest version is 3.5.0

**Comment by dcommander** [comment]
Our project does not provide that file.

**Comment by Kingshuk1991** [comment]
It is present inside doc/html
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/doc/html/jquery.js

**Comment by dcommander** [comment]
The documentation is auto-generated by Doxygen, so I was not even aware that there was a copy of jquery.js in that folder until now.  If there is a specific problem with that version of jquery.js, then describe the problem rather than asking me to blindly upgrade it with no justification.

**Comment by Kingshuk1991** [comment]
Apologies, I did not provide the context and justification before. We are using libpeg-turbo in our product and while doing CVE analysis, it was found that jQuery versions older than 3.0.0 has some vulnerabilities. That is why, I was asking about it.

**Comment by dcommander** [comment]
Context is everything.  I doubt that the vulnerabilities apply to Doxygen's stripped-down version of jquery.js, which is used only for a statically-generated web page.  If you can determine that they do, then let me know.
