### ISSUE TITLE
500: Internal Server Error

### ISSUE THREAD

**Issue by Jonatanjrss** [libjpeg-turbo/libjpeg-turbo#424]
Did you remove the zip package accidentally or on purpose?

**Comment by dcommander** [comment]
What zip package?  And what does that have to do with 500: Internal Server Error?

**Comment by Jonatanjrss** [comment]
In the clone or download option of your project, when I clicked the button to download your project I was being redirected to a page that presented this error 500. But it's back up and running, I think there must be a problem with the github servers. You can close this.
