### ISSUE TITLE
Question: How to create a jvirt_barray_ptr?

### ISSUE THREAD

**Issue by supercmmetry** [libjpeg-turbo/libjpeg-turbo#426]
I have been browsing the internet for two days in search of documentation related to creating virtual array descriptors.

I want to be able to write DCT coefficients to a jvirt_barray_ptr and then write those coefficients using jpeg_write_coefficients(). But unfortunately, I cant think of any way to do that.

I have been successfuly in fetching a jvirt_barray_ptr from jpeg_read_coefficients and writing it directly using jpeg_write_coefficients, but creating the virtual array seems tough.

Can anyone provide me with a snippet to create a jvirt_barray_ptr and store dct coefficients in it?

**Comment by dcommander** [comment]
You want to use the `request_virt_barray` and `access_virt_barray` methods in the memory manager.  Execute `git grep request_virt_barray` and `git grep access_virt_barray` to see several examples of usage in the libjpeg-turbo source code.
