### ISSUE TITLE
Tests 83 - djpeg-shared-3x2-float-prog-cmp and 234 - djpeg-static-3x2-float-prog-cmp fail on ppc32 (Big Endian)

### ISSUE THREAD

**Issue by ernsteiswuerfel** [libjpeg-turbo/libjpeg-turbo#428]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes.
At first it looked like bug #344 but I guess it can't be the same issue as the build here was not done on a ppc64 host in a 32bit chroot, but natively on a ppc32 host.

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No

**Clear and concise description of the bug:**
```
83/302 Testing: djpeg-shared-3x2-float-prog-cmp
83/302 Test: djpeg-shared-3x2-float-prog-cmp
Command: "/root/build/libjpeg-turbo/build/md5/md5cmp" "f6bfab038438ed8f5522fbd33595dcdc" "testout_3x2_fl
oat.ppm"
Directory: /root/build/libjpeg-turbo/build
"djpeg-shared-3x2-float-prog-cmp" start time: May 05 20:03 CEST
Output:
----------------------------------------------------------
testout_3x2_float.ppm: FAILED.  Checksum is 0e917a34193ef976b679a6b069b1be26
<end of output>
Test time =   0.01 sec
----------------------------------------------------------
Test Failed.
"djpeg-shared-3x2-float-prog-cmp" end time: May 05 20:03 CEST
"djpeg-shared-3x2-float-prog-cmp" time elapsed: 00:00:00
----------------------------------------------------------


234/302 Testing: djpeg-static-3x2-float-prog-cmp
234/302 Test: djpeg-static-3x2-float-prog-cmp
Command: "/root/build/libjpeg-turbo/build/md5/md5cmp" "f6bfab038438ed8f5522fbd33595dcdc" "testout_3x2_fl
oat.ppm"
Directory: /root/build/libjpeg-turbo/build
"djpeg-static-3x2-float-prog-cmp" start time: May 05 20:06 CEST
Output:
----------------------------------------------------------
testout_3x2_float.ppm: FAILED.  Checksum is 0e917a34193ef976b679a6b069b1be26
<end of output>
Test time =   0.01 sec
----------------------------------------------------------
Test Failed.
"djpeg-static-3x2-float-prog-cmp" end time: May 05 20:06 CEST
"djpeg-static-3x2-float-prog-cmp" time elapsed: 00:00:00
----------------------------------------------------------
```

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
```
git clone https://github.com/libjpeg-turbo/libjpeg-turbo
cd libjpeg-turbo
mkdir build && cd build && cmake ../
make -j3 && make test
```

**Image(s) needed in order to reproduce the bug (if applicable):**

**Expected behavior:**
Test suite passing.

**Observed behavior:**
Test suite failing.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
Portage 2.3.99 (python 3.6.10-final-0, default/linux/powerpc/ppc32/17.0/desktop/gnome/systemd, gcc-9.3.0, glibc-2.30-r8, 5.6.8-gentoo-PowerMacG4 ppc)
System uname: Linux-5.6.8-gentoo-PowerMacG4-ppc-7455,_altivec_supported-with-gentoo-2.6
KiB Mem:     2053900 total,   1627012 free
KiB Swap:   16777212 total,  16777212 free

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the master branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
2.0.3, 2.0.4, git master

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**
Dunno.

**Additional information:**

**Comment by ernsteiswuerfel** [comment]
[CMakeCache.txt](https://github.com/libjpeg-turbo/libjpeg-turbo/files/4583093/CMakeCache.txt)

**Comment by dcommander** [comment]
On platforms that don't have SIMD support for the floating point DCT/IDCT algorithms, the mathematical output of those algorithms depends on the compiler and FPU.  The build system sets reasonable defaults for most 64-bit compilers and most 32-bit compilers, but those defaults aren't universal.  In your case, it appears as if the build system is setting the `FLOATTEST` CMake variable to `32bit` when you really need it to be set to `64bit`.  That is consistent with my experience on PPC platforms.  They seem to always require `FLOATTEST=64bit`, even when using 32-bit code.

**Comment by ernsteiswuerfel** [comment]
@dcommander You were right! Setting` FLOATTEST=64bit` makes all the tests pass on my G4, Gentoo Linux.
