### ISSUE TITLE
Question: Which building technique should be used for Raspbian (NIX-ARM)?

### ISSUE THREAD

**Issue by mrjetas** [libjpeg-turbo/libjpeg-turbo#430]
Sorry for posting this question here but to be more precise the building guide does not explicitly show how it is done for the nix-arm platforms other than Android.
---
Platform and Hardware info:
Raspberry Pi 3 Model B Rev 1.2,
ARMv7 Processor rev 4 (v7l) x 4 cores,
Raspbian GNU/Linux 10 (buster).
---
Auxiliary question: Does the libjpg-turbo use any special ARM instructions to speed up en(/de)coding?

**Comment by dcommander** [comment]
Other Linux/ARM platforms use the generic Un*x instructions.
