### ISSUE TITLE
tjCompress2 perform slower than libjpeg api

### ISSUE THREAD

**Issue by xvjinkun** [libjpeg-turbo/libjpeg-turbo#434]
I use turbojpeg api to encode  rgba to jpeg data ,here is my compress code:
   `
   tjhandle compressor = tjInitCompress();

    unsigned char * jpegData = NULL;
    unsigned long jpegSize = 0;
     tjCompress2(compressor,rgba,width,0,height,TJPF_RGBX,&jpegData,&jpegSize,TJSAMP_444,98,TJFLAG_FASTDCT);
` 

I debug turbojpeg source ,then found than when I call 
`tjCompress2`, it call `setCompDefaults` init the comp_infos by `jpeg_set_colorspace(cinfo, JCS_YCbCr)`,inside it init the `comp_info->h_samp_factor` and `comp_info->v_samp_factor` and set `cinfo->num_componentsj=3` as same as I call by libjpeg api,however,then at last of `setCompDefaults `,comp_info are modify:

`cinfo->comp_info[0].h_samp_factor = tjMCUWidth[subsamp] / 8;`

 `cinfo->comp_info[1].h_samp_factor = 1` 

  `cinfo->comp_info[2].h_samp_factor = 1;`

 ` if (cinfo->num_components > 3)`

  `  cinfo->comp_info[3].h_samp_factor = tjMCUWidth[subsamp] / 8;`

  `cinfo->comp_info[0].v_samp_factor = tjMCUHeight[subsamp] / 8;`
  `cinfo->comp_info[1].v_samp_factor = 1;`
 ` cinfo->comp_info[2].v_samp_factor = 1;`
  `if (cinfo->num_components > 3)`
 `   cinfo->comp_info[3].v_samp_factor = tjMCUHeight[subsamp] / 8;`

then go on:
`tjCompress2` step into  `jpeg_start_compress`  step into `jinit_compress_master` step into `jinit_downsampler`  here it is:

this function init the downsampler method by compare comp_info's v_samp_factor and h_samp_factor but here it go different with libjpeg, the downsample method of turbojpeg api is 
`ownsample->methods[ci] = fullsize_downsample;`   no simd support and libjpeg api will enable simd acc of `downsample->methods[ci] = jsimd_h2v2_downsample;`

then I `#if 0 `  the last of `setCompDefaults ` where modify the comp_info to 1,then I perform as well as libjpeg does,I don't know  what this code do ,if I `#if 0` it ,is there anything unexpected happened?
``

**Comment by dcommander** [comment]
Yes, that's because you specified 4:4:4 subsampling by passing `TJSAMP_444` to `tjCompress2()`.  If you want to use 4:2:0 subsampling, which is the default in the libjpeg API, then you need to specify `TJSAMP_420`.
