### ISSUE TITLE
jcopy_sample_rows() causes SIGSEGV

### ISSUE THREAD

**Issue by zodf0055980** [libjpeg-turbo/libjpeg-turbo#441]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No

**Clear and concise description of the bug:**
jcopy_sample_rows try to read  *0x8 causes SIGSEGV

0x00007ffff7b7d48a in jcopy_sample_rows (input_array=0x555555764728, source_row=0x0, output_array=0x8, dest_row=0x0, num_rows=0x1, num_cols=0x60) at /home/yuan/libjpeg-turbo/jutils.c:112
112	    outptr = *output_array++;

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
in read_and_discard_scanlines() , it calls jpeg_read_scanlines(cinfo, NULL, 1);
However NULL will be output array address in jcopy_sample_rows().

**Image(s) needed in order to reproduce the bug (if applicable):**
![sample](https://user-images.githubusercontent.com/25863161/86568115-f7b82580-bf9e-11ea-95bf-a36bfd43e649.jpg)

**Expected behavior:**

**Observed behavior:**

```
./djpeg -fast -skip 1,20 -outfile ./outt ./sample.jpg

gdb-peda$ bt
#0  0x00007ffff7b7d48a in jcopy_sample_rows (input_array=0x555555764728, source_row=0x0, output_array=0x8, dest_row=0x0, num_rows=0x1, num_cols=0x60) at /home/yuan/libjpeg-turbo/jutils.c:112
#1  0x00007ffff7b61454 in merged_2v_upsample (cinfo=0x7fffffffd970, input_buf=0x555555766610, in_row_group_ctr=0x555555766664, in_row_groups_avail=0x8, output_buf=0x0, out_row_ctr=0x7fffffffd764, 
    out_rows_avail=0x1) at /home/yuan/libjpeg-turbo/jdmerge.c:266
#2  0x00007ffff7b5b5a1 in process_data_simple_main (cinfo=0x7fffffffd970, output_buf=0x0, out_row_ctr=0x7fffffffd764, out_rows_avail=0x1) at /home/yuan/libjpeg-turbo/jdmainct.c:313
#3  0x00007ffff7b4dcc1 in jpeg_read_scanlines (cinfo=0x7fffffffd970, scanlines=0x0, max_lines=0x1) at /home/yuan/libjpeg-turbo/jdapistd.c:285
#4  0x00007ffff7b4ddfb in read_and_discard_scanlines (cinfo=0x7fffffffd970, num_lines=0x1) at /home/yuan/libjpeg-turbo/jdapistd.c:336
#5  0x00007ffff7b4dec9 in increment_simple_rowgroup_ctr (cinfo=0x7fffffffd970, rows=0x5) at /home/yuan/libjpeg-turbo/jdapistd.c:366
#6  0x00007ffff7b4e46d in jpeg_skip_scanlines (cinfo=0x7fffffffd970, num_lines=0x14) at /home/yuan/libjpeg-turbo/jdapistd.c:530
#7  0x0000555555557638 in main (argc=0x7, argv=0x7fffffffdcd8) at /home/yuan/libjpeg-turbo/djpeg.c:711
#8  0x00007ffff7754b97 in __libc_start_main (main=0x555555556f8c <main>, argc=0x7, argv=0x7fffffffdcd8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdcc8)
    at ../csu/libc-start.c:310
#9  0x0000555555555c6a in _start ()
```

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 , Linux version 5.3.0-61-generic 

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the master branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
commit ae87a958613b69628b92088b313ded0d4f59a716 in master

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

**Comment by dcommander** [comment]
Should be fixed now.  Please test.

**Comment by zodf0055980** [comment]
It's okay now, thanks!

**Comment by dcommander** [comment]
There were still some

**Comment by mathias-clerc** [comment]
I have a similar issue using v2.1.2.

```
__memmove_evex_unaligned_erms 0x00007f46229c9383
jcopy_sample_rows 0x0000562324e61427
merged_2v_upsample 0x0000562324e5af50
process_data_simple_main 0x0000562324e6fee9
jpeg_read_scanlines 0x0000562324e5410b
```

Should I open a separate issue or reopen this one ?

**Comment by dcommander** [comment]
@mathias-clerc This issue was closed and fixed, so open a new issue.
