### ISSUE TITLE
clang LTO compilation fails

### ISSUE THREAD

**Issue by vanhauser-thc** [libjpeg-turbo/libjpeg-turbo#447]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
surly did

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
no

**Clear and concise description of the bug:**
This bug was not present in libjpegturbo 1.x, so likely a 2.x issue.
When trying to compiling libjpegturbo with the lto optimization of clang it fails:
```
[ 51%] Linking C executable tjbench-static
/bin/ld: /tmp/lto-llvm-24033d.o: in function main':
ld-temp.o:(.text.main+0x35): undefined reference to tjGetScalingFactors'
...(and many other references not found)
```

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
```
rm -rf libjpeg-turbo
git clone --depth 1 https://github.com/libjpeg-turbo/libjpeg-turbo
cd libjpeg-turbo
export CC=clang
export CFLAGS="-flto=full -fPIC"
cmake . -DENABLE_STATIC=on -DENABLE_SHARED=off
make
```

Note: the -fPIC is required as without this the functions (like tjGetScalingFactors) are defined as `dso local` and that surely cannot work.
With -fPIC it looks good:
```
llvm-ar x libturbojpeg.a turbojpeg.c.o
llvm-link -S -o turbojpeg.ll turbojpeg.c.o 
grep tjGetScalingFactors turbojpeg.ll
define %struct.tjscalingfactor* @tjGetScalingFactors(i32* %0) local_unnamed_addr #3 {
```
So the function is there, global and well defined

**Image(s) needed in order to reproduce the bug (if applicable):**
none

**Expected behavior:**
it should compile and create working binaries

**Observed behavior:**
compilation breaks

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
amd64
This happens with clang-8, clang-9, clang-10, clang-11 and clang-12 (the last two are in development)

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the master branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

this happens with the current master.
it is not present in 1.5.2 or 1.3.1

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**
?

**Comment by dcommander** [comment]
I see exactly the same issue with the 1.5.x code base.  The fix with the 2.0.x code base is to manually specify `CMAKE_AR` and `CMAKE_RANLIB`, e.g.:

```
cmake . -DENABLE_STATIC=on -DENABLE_SHARED=off -DCMAKE_AR=/usr/lib/llvm-8/bin/llvm-ar -DCMAKE_RANLIB=/usr/lib/llvm-8/bin/llvm-ranlib
```

**Comment by vanhauser-thc** [comment]
ah thank you.
I set RANLIB=... and AR=... but the environment variables were not picked up as it seems...

**Comment by dcommander** [comment]
CMake picks up some of the same environment variables as autotools, such as `CC` and `CFLAGS`, but not all of them.
