### ISSUE TITLE
linking issues with lld

### ISSUE THREAD

**Issue by enh-google** [libjpeg-turbo/libjpeg-turbo#448]
if i try to link libjpeg-turbo with the LLVM lld linker, i see:
```
  ld.lld: error: relocation R_386_GOTOFF cannot be used against symbol 
  jpeg_nbits_table; recompile with -fPIC
  >>> defined in jpeg_nbits_table.o
  >>> referenced by simd/i386/jchuff-sse2.asm
  >>> simd/i386/jchuff-sse2.o:(.text+0x85)
```

i talked to our linker expert, and he said:
```
    movzx edx, byte [GOTOFF(ebp, jpeg_nbits_table + ecx)]

  Code generation only produces @GOTOFF references for local symbols
  (lib/Target/X86/X86Subtarget.cpp). Assembly code may misuse @GOTOFF for
  global symbols.

  Normally if the target symbol is local, both movl $1, foo@GOTOFF(%ecx)
  and leal foo@GOTOFF(%eax), %eax will produce a R_386_GOTOFF relocation
  referencing a STT_SECTION local symbol. There is no issue for GNU ld or
  LLD.

  If the target symbol is global and not non-preemptible (due to hidden
  visibility, dynamic-list, -Bsymbolic, etc), LLD will reproduce such an
  error while GNU ld permissively allows it.

  The fix is to make jpeg_nbits_table hidden. If it cannot be hidden
  (referenced by other shared objects), this will be more difficult to
  fix.
```
and, indeed, the error goes away if i do any of these things. for now i'm going with a version script that hides the jpeg_nbits_table symbol. see https://android-review.googlesource.com/c/platform/external/libjpeg-turbo/+/1388929 for the AOSP change.

i thought i'd file this bug because eventually someone else will hit this (right now lld isn't even on my Debian box, so short of "download the Android source and ...", i'm struggling to give you plausible repro instructions).

i did also test just adding `__attribute__((visibility("hidden")))` to the jpeg_nbits_table definition and that worked too. i'm happy to send a patch along those lines if you'd like --- presumably with some #ifdef'ing to only do this on a supported compiler.

**Comment by enh-google** [comment]
oops. it turns out this bug is actually only in the chromium copy of libjpeg-turbo --- your code looks like:
```
jpeg_nbits_table.h:static const unsigned char jpeg_nbits_table[65536] = {

```
which is fine.

sorry for the noise. i'll go hassle the chromium folks instead!

**Comment by dcommander** [comment]
Yes, we would like to eventually adopt some version of that patch (allowing `jpeg_nbits_table` to be shared between assembly and C.)  #114 tracks that effort.  Currently, the problem is that the SSE2 Huffman encoder changed in the 2.1 evolving (dev) branch of libjpeg-turbo, and the changes affected how `jpeg_nbits_table` is accessed from the assembly code.  Thus, Chrome's and Mozilla's patches no longer work, and I'm not sure how to make them work (see also: https://bugzilla.mozilla.org/show_bug.cgi?id=1501523).

**Comment by enh-google** [comment]
yeah, your https://bugzilla.mozilla.org/show_bug.cgi?id=1501523#c20 looks like the exact same problem (`__attribute__((visibility("hidden")))` would be the most direct workaround, modulo anything that might be needed to make that wor for MSVC too).

i'll pass your comment on to the chromium folks. (i'm just an Android patch monkey trying to get ARM's PAC/BTI/MTE fixes for armv9 :-) )

**Comment by dcommander** [comment]
The original goal was to share the data between C and assembly so as to avoid unnecessary memory usage, so the visibility isn’t really the crux of the issue.

**Comment by enh-google** [comment]
it is though --- it's the visibility that's causing the issues with the bad relocations (or more expensive instruction sequences, depending). if you make the shared array visibility hidden, you can continue to have the cheap access to it that you used to get with multiple copies, without introducing invalid relocations.

**Comment by enh-google** [comment]
this error from your comment 20 on the other bug is the exact same error i hit, for the exact same reason:
```
/usr/bin/ld: ../simd/CMakeFiles/simd.dir/x86_64/jchuff-sse2.asm.o: relocation R_X86_64_PC32 against symbol `jpeg_nbits_table' can not be used when making a shared object; recompile with -fPIC
```

**Comment by dcommander** [comment]
OK, so that may have been why the error only occurred with 32-bit macOS in my case— those may have been the only 32-bit builds I was doing that used lld. Regardless, I’m happy to revisit this in more detail if someone can figure out how to upstream the shared jpeg_nbits_table patch with the current dev branch.
