### ISSUE TITLE
macOS arm64 official binary

### ISSUE THREAD

**Issue by LxLasso** [libjpeg-turbo/libjpeg-turbo#452]
It would be lovely if the official macOS binary that included arm64 for the Mac platform!

**Comment by dcommander** [comment]
I intend to look into that for the 2.1 release. My understanding is that building a macOS arm64 fork may require a newer Xcode than my build platform can currently support, so that may prevent it from happening.

**Comment by LxLasso** [comment]
Yes, XCode 12 is required - which is still in beta. :-/

**Comment by dcommander** [comment]
Yeah, and Xcode 12 requires Catalina, which is two revisions ahead of where my official build infrastructure is right now.  That's the main issue.

**Comment by dcommander** [comment]
Realistically, this isn't going to happen for libjpeg-turbo 2.1.  Dependencies:
- Upgrade my primary build machine to Mojave
    - This is proving to be a PITA, not to mention an unwelcome expense, due to the need to find replacements for 32-bit apps, but I will need to get it done within the next few months.
- Upgrade my macOS VM to Catalina.
- Configure the VM to perform official builds.
- Add official build scripts for macOS/armv8.
- Configure the Travis build to use the xcode12.2 image
    - This will enable macOS/armv8 in the pre-release builds.
    - This will require testing to ensure no performance or compatibility regression in the existing slices, since all of them will be built with Xcode 12.2.

Here's wishing it were possible to run macOS in a Docker container.  That would make all of this so much simpler.

I'll keep posting status updates here.  At the moment, our project is out of funding until probably next summer, so that means no unfunded features until the funding catches up.

**Comment by dcommander** [comment]
The pre-release build should now contain a macOS arm64 architecture:
https://s3.amazonaws.com/libjpeg-turbo-pr/dev/osx/index.html
Please test that while I finish up benchmarking, compatibility testing, and integration with the official build system.

**Comment by LxLasso** [comment]
I have tested it - links fine, opens and saves fine! All good as far as I can tell.

**Comment by dcommander** [comment]
OK, great!  So far, I can't find any performance or compatibility differences between Xcode 8.3 and 12.2, so I will probably migrate all of the slices (as opposed to just the macOS/arm64 slice) to Xcode 12.2.  If that's the case, then the official builds will be essentially identical to the PR builds, and no further testing will be necessary.  I'll keep you posted.

**Comment by lmcd** [comment]
Thanks for your work on this so far 👍

**Comment by dcommander** [comment]
This has been fully implemented in the official and pre-release build systems.  My testing revealed that Xcode 12.2 works fine for both (no compatibility or performance regression vs. Xcode 8.3), so I'm using Xcode 12.2 for everything.  That means that the official build of 2.1 beta, once released, will work identically to the current pre-release.
