### ISSUE TITLE
JPG rotation with -perfect not lossless

### ISSUE THREAD

**Issue by krishty** [libjpeg-turbo/libjpeg-turbo#453]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

Yes. I found a similar bug in mozjpegtran’s bugtracker (https://github.com/mozilla/mozjpeg/issues/224), but it involved a malformed file. jpegtran does not report any file errors with my current problem.

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

No.

**Clear and concise description of the bug:**

Rotating a specific JPG successfully with jpegtran, the pixel values change – even when `-perfect` is used.

1. I noticed this problem with mozjpegtran 3.3.1 on Windows. I then reproduced it with a 2015 version of mozjpegtran and its current master branch. Eventually, I downloaded the current version (2.0.5) of libjpeg-turbo and reproduced the problem there as well.
2. Source and result are different both when opened with GIMP as well as with MS Paint, so I assume it’s no decoder issue either.
3. I reported it to mozjpegtran and they sent me here because it reproduces with libjpeg-turbo.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
1. Download attached test.jpg
2. `jpegtran.exe -rotate 270 -perfect test.jpg > test_rotated.jpg`

**Image(s) needed in order to reproduce the bug (if applicable):**

![test](https://user-images.githubusercontent.com/51880096/91896972-ef782000-ec99-11ea-8003-bad741084f0a.jpg)

**Expected behavior:**
The pixels in input and output should be identical (except for the rotation, of course). If the pixels are different, `-perfect` should cause an error.

**Observed behavior:**
Difference of up 2/256 in all three color channels. Green has the least error. Here’s the result; below a diff I created in Gimp.
![test_rotated](https://user-images.githubusercontent.com/51880096/91896978-f1da7a00-ec99-11ea-81b8-2fa9e86671fa.jpg)
![diff](https://user-images.githubusercontent.com/51880096/91896987-f43cd400-ec99-11ea-89b3-7a94010be1fc.png)

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
libjpeg-turbo-2.0.5-vc64.exe from the SourceForge download page; two derived projects (mozjpegtran in various versions and Efficient Compression Tool); Windows 10 & AMD Ryzen 5.

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the master branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
libjpeg-turbo-2.0.5-vc64.exe from the SourceForge download page

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**
unknown

**Additional information:**
I tested a few other files of very different sizes and motives but had no problems with them. I have been using jpegtran for almost a decade now and never encountered something like this.

**Comment by dcommander** [comment]
Lossless transformation guarantees that the DCT coefficients will be unaltered, but the various decompression algorithms are directional, so if they produce output {y} for input {x}, they will not necessarily produce output rotateN{y} for input rotateN{x}.  That is particularly true if the JPEG image uses subsampling, which this one does.  It's a 4:4:0 image, so rotating it 270 degrees converts it to a 4:2:2 image.

Test 1:
```
# ./djpeg test.jpg >test.ppm
# ./jpegtran -rotate 270 -perfect test.jpg >test_rotated.jpg
# ./jpegtran -rotate 90 -perfect test_rotated.jpg >test_unrotated.jpg
# ./djpeg test_unrotated.jpg >test_unrotated.ppm
# md5sum test.ppm test_unrotated.ppm
b5e795e98b2ccd7a7840aa6c88bcabac  test.ppm
b5e795e98b2ccd7a7840aa6c88bcabac  test_unrotated.ppm
```
Conclusion: The act of rotating, in and of itself, is indeed reversible (lossless) in the frequency domain.

Test 2:
```
# ./djpeg test.jpg >test.ppm
# convert -rotate 270 test.ppm test_rotated_im.ppm
# ./jpegtran -rotate 270 -perfect test.jpg >test_rotated.jpg
# ./djpeg test_rotated.jpg >test_rotated_ljt.ppm
# imdiff test_rotated_im.ppm test_rotated_ljt.ppm 
B: max err.= 4 avg err.= 0.393676 rms= 0.855484 PSNR= 49.5204
G: max err.= 3 avg err.= 0.214881 rms= 0.473203 PSNR= 54.6637
R: max err.= 3 avg err.= 0.261924 rms= 0.637469 PSNR= 52.0755
T: max err.= 4 avg err.= 0.290161 rms= 0.673832 PSNR= 51.5937
```
Conclusion: The image decompressed and then rotated in the spatial domain is different than the image rotated in the frequency domain and then decompressed. (NOTE: imdiff is available [here](https://gist.github.com/dcommander/01a5f598d0bf3871548b2654584fd738).)

I can improve the correlation by disabling fancy upsampling ...
```
# ./djpeg -nosmooth test.jpg >test.ppm
# convert -rotate 270 test.ppm test_rotated_im.ppm
# ./jpegtran -rotate 270 -perfect test.jpg >test_rotated.jpg
# ./djpeg -nosmooth test_rotated.jpg >test_rotated_ljt.ppm
# imdiff test_rotated_im.ppm test_rotated_ljt.ppm 
B: max err.= 3 avg err.= 0.044878 rms= 0.264491 PSNR= 59.7164
G: max err.= 2 avg err.= 0.032485 rms= 0.181466 PSNR= 62.9888
R: max err.= 3 avg err.= 0.035595 rms= 0.216087 PSNR= 61.4721
T: max err.= 3 avg err.= 0.037653 rms= 0.223293 PSNR= 61.1872
```
but this also makes the subsampling artifacts more visible.  The correlation is further improved when using a 4:4:4 input image (PSNR > 64, generally) but is still not 100% because of directional round-off error.

**Comment by krishty** [comment]
Thanks a lot for the detailed explanation!
