### ISSUE TITLE
Support for building for Windows ARM64 with MSVC compiler

### ISSUE THREAD

**Issue by jeevcat** [libjpeg-turbo/libjpeg-turbo#461]
Is this already supported? How can I do this?

I'm currently getting linker errors, but this might just be a cross compilation issue?

```
simd\CMakeFiles\simd.dir\x86_64\jsimdcpu.asm.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'ARM64'
```

I did the following:
```
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvarsall.bat" x86_arm64
mkdir build
cd build
cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
nmake
```

**Comment by dcommander** [comment]
Create a file called **win64-arm-toolchain.cmake** with the following contents:
```
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
```
and then pass `-DCMAKE_TOOLCHAIN_FILE=win64-arm-toolchain.cmake` to CMake.

Note, however, that the ARM SIMD extensions for libjpeg-turbo don't currently support Visual Studio, so you'll need to either build with MinGW or disable the SIMD extensions (`-DWITH_SIMD=0`).  Hopefully #455 will enable ARM SIMD support for Visual Studio, but that will not land until libjpeg-turbo 2.1.

**Comment by jeevcat** [comment]
Thanks a lot! How significant is the performance hit without SIMD?

**Comment by dcommander** [comment]
Very.  2-4x, generally, is the speedup that the ARM SIMD extensions give vs. the C code.

**Comment by dcommander** [comment]
Reopening, since Arm is working on getting the new intrinsics implementation of the Neon SIMD extensions in the dev branch (libjpeg-turbo 2.1 evolving) to build under MSVC.

**Comment by jonathanwright-ARM** [comment]
Should be enabled by: https://github.com/libjpeg-turbo/libjpeg-turbo/pull/475
