### ISSUE TITLE
PGP key used for release signing is 1024bit DSA

### ISSUE THREAD

**Issue by dvzrv** [libjpeg-turbo/libjpeg-turbo#462]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No

**Clear and concise description of the bug:**
The PGP key in use (`7D6293CC6378786E1B5C496885C7044E033FDE16`) for doing detached signatures for the releases (e.g. [2.0.5](https://sourceforge.net/projects/libjpeg-turbo/files/2.0.5/)) is 1024bit DSA.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

```
gpg --keyserver keyserver.ubuntu.com --search-keys 7D6293CC6378786E1B5C496885C7044E033FDE16
```

**Image(s) needed in order to reproduce the bug (if applicable):**
n/a

**Expected behavior:**
Release tarball signing is done using a not broken/ strong key type (e.g. RSA > 4096 or ed25519).

**Observed behavior:**
Releases are signed using a key type that is [broken since 2010](https://en.wikipedia.org/wiki/Digital_Signature_Algorithm#Sensitivity).

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
All

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the master branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
All

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**
To ensure a chain of trust please try to sign the new key with the old key (if that is even possible).
Announce a new key here and/or on the website and use it for the next release.
The current key in use is basically purely cosmetic at this point.

**Comment by dcommander** [comment]
I'll look into it for the upcoming releases, but please avoid hyperbole when describing security issues. The purpose of the signing key is to validate the integrity of the official packages. It still takes an exceptional amount of computing power to crack a 1024-bit key in human-scale time, and there is little impetus for an organization to invest in that compute power for the sole purpose of releasing a fake copy of official packages for an open source JPEG library, particularly when only a subset of users use those official packages. Plus, users can always validate the packages using the MD5 sums instead. If a 1024-bit key is not considered the best practice anymore, then so be it, but calling it "purely cosmetic" is overstating your case. These keys are not meant to guard a missile silo.

**Comment by dvzrv** [comment]
> I'll look into it for the upcoming releases

Thanks a lot! Much appreciated! :) 

> but please avoid hyperbole when describing security issues.

I apologize for the perceivably rather snarky ticket (now that I re-read it). It was certainly not meant to discredit you or your work, but can rather be attributed to me filing out a templated ticket on auto-pilot after a long day of packaging!

I would like to add, that although brute-forcing a 1024bit DSA key might be nothing one might want to do on a laptop, in today's world it is easy to click a short-lived server farm to do the heavy lifting.
Man-in-the-middle and supply chain attacks (as unlikely as they might be in the scope of this project) do happen and if there's something we can do to decrease the likelihood of it happen, then that's a great thing.
Therefore I am very grateful that you want to look into the topic!

**Comment by dcommander** [comment]
Here's a strawman tarball that is signed with a new 4096-bit RSA key (https://libjpeg-turbo.org/downloads/LJT-GPG-KEY), which itself is signed with the old 1024-bit DSA key:

https://libjpeg-turbo.org/downloads/libjpeg-turbo-2.0.6.tar.gz
https://libjpeg-turbo.org/downloads/libjpeg-turbo-2.0.6.tar.gz.sig

Please verify that this looks good to you before I make it public.  I intend to use the new key only for new releases, because it's a royal PITA to re-publish packages for old releases.  Thus, the old key will remain valid, and I'll put links for both old and new keys at https://libjpeg-turbo.org/Downloads/DigitalSignatures once this process is complete.  I intend to also generate a new 4096-bit key for pre-releases and revoke the old 1024-bit pre-release key, since pre-releases are ephemeral and are, by definition, obsoleted as soon as a new pre-release build is available.  Let me know if any of that seems problematic.

**Comment by dcommander** [comment]
@dvzrv A timely response is appreciated.  2.0.6 and 2.1 beta releases are expected to go live next week, barring any unforeseen issues.

**Comment by dvzrv** [comment]
@dcommander many thanks! :)

This looks good:

```
$ gpg --list-signatures 0338C8D8D9FDA62CF9C421BD7EC2DBB6F4DBF434
pub   rsa4096 2020-11-12 [SC]
      0338C8D8D9FDA62CF9C421BD7EC2DBB6F4DBF434
uid           [ unknown] The libjpeg-turbo Project (Signing key for official binaries) <information@libjpeg-turbo.org>
sig 3        7EC2DBB6F4DBF434 2020-11-12  The libjpeg-turbo Project (Signing key for official binaries) <information@libjpeg-turbo.org>
sig 3        85C7044E033FDE16 2020-11-12  The libjpeg-turbo Project (Signing key for official binaries) <information@libjpeg-turbo.org>
```

```
$ gpg --keyid-format long --list-keys 85C7044E033FDE16
pub   dsa1024/85C7044E033FDE16 2015-07-21 [SC]
      7D6293CC6378786E1B5C496885C7044E033FDE16
uid                 [ unknown] The libjpeg-turbo Project (Signing key for official binaries) <information@libjpeg-turbo.org>
sub   elg2048/FB2994D40721B919 2015-07-21 [E]
```

```
$ gpg --keyid-format long --list-keys 0338C8D8D9FDA62CF9C421BD7EC2DBB6F4DBF434
pub   rsa4096/7EC2DBB6F4DBF434 2020-11-12 [SC]
      0338C8D8D9FDA62CF9C421BD7EC2DBB6F4DBF434
uid                 [ unknown] The libjpeg-turbo Project (Signing key for official binaries) <information@libjpeg-turbo.org>
```

To add a note that anything below version x.y.z uses one key and anything above version x.y.z uses another is totally fine.
