### ISSUE TITLE
Feature wish: lossless join of images

### ISSUE THREAD

**Issue by Cigaes** [libjpeg-turbo/libjpeg-turbo#464]
There is a patch here for an old version of libjpeg: https://puhuri.iki.fi/src/libjpeg/ that allows to join losslessly two images: side-by-side if they have the same height, one on top of the other if they have the same width. Would you consider adopting this feature into the official source code? It would make it available to everybody and avoid bitrot.
Thanks.

**Comment by dcommander** [comment]
Would the `jpegtran -drop` feature in jpeg-9d do the trick?  If so, I would consider integrating that feature.

**Comment by Cigaes** [comment]
Yes, it is even better. Thank you very much.

**Comment by dcommander** [comment]
OK, well, that also means you can use jpeg-9d in a pinch, since that is a supported code base (albeit not supported by us.)  I'll determine whether it makes sense to integrate the feature into libjpeg-turbo v2.1.

**Comment by Cigaes** [comment]
Indeed. And that's true for #465 too. I hope it gets here and then into Debian, but your help has already been very useful. Thank you.

**Comment by dcommander** [comment]
Unfortunately it appears that the `-drop` option in jpeg-9d doesn't do what you need.  It just allows for "dropping" another image into an existing image at a given set of coordinates.  It can't be used to join images side-by-side.  Can you confirm?  If `-drop` isn't suitable, then unfortunately I'm going to have to punt and say that this is best addressed in a downstream program, not in libjpeg-turbo.

**Comment by Cigaes** [comment]
It works in two steps: first use `-crop` to enlarge the image, then `-drop` the extra image on a blank part. It is more universal than just side-by-side.

**Comment by dcommander** [comment]
Integrated into dev.  Once you see a build with today's date (October 27) here:
https://s3.amazonaws.com/libjpeg-turbo-pr/dev/linux/index.html
give it a try.
