### ISSUE TITLE
Feature wish: lossless redaction of parts of an image

### ISSUE THREAD

**Issue by Cigaes** [libjpeg-turbo/libjpeg-turbo#465]
Would you consider implementing a feature to replace parts of an image with an uniform color or a random pattern (or even possibly contents from a compatible image) while preserving the rest of the image lossllessly?
The use case I have in mind is to obscure the faces of pedestrians before submitting photos of a building to Wikipedia, but I am sure many other uses are possible.
(Not being familiar with the structure of the JPEG bitstream, I am considering doing it from the outside: replace parts of the file with random data, decode it and see which pixels changed, then refine the changed parts.)

**Comment by dcommander** [comment]
Would the `jpegtran -wipe` feature in jpeg-9d do the trick?  If so, I would consider integrating that feature.

**Comment by Cigaes** [comment]
Yes, it works perfectly. Thank you very much.

**Comment by dcommander** [comment]
Integrated into dev.  Once you see a build with today's date (October 27) here:
https://s3.amazonaws.com/libjpeg-turbo-pr/dev/linux/index.html
give it a try.
