### ISSUE TITLE
x86_64: fatal: more than one input file specified:

### ISSUE THREAD

**Issue by zxpgo** [libjpeg-turbo/libjpeg-turbo#473]
[  0%] Building ASM_NASM object simd/CMakeFiles/simd.dir/x86_64/jsimdcpu.asm.o
x86_64: fatal: more than one input file specified: /Users/a406/work/linphone-sdk/external/libjpeg-turbo/simd/x86_64/jsimdcpu.asm

make[8]: *** [simd/CMakeFiles/simd.dir/x86_64/jsimdcpu.asm.o] Error 1
make[7]: *** [simd/CMakeFiles/simd.dir/all] Error 2
make[6]: *** [all] Error 2
make[5]: *** [/Users/a406/work/linphone-sdk/build/WORK/ios-x86_64/Stamp/EP_turbojpeg/EP_turbojpeg-build] Error 2
make[4]: *** [CMakeFiles/EP_turbojpeg.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [ios-x86_64-prefix/src/ios-x86_64-stamp/ios-x86_64-build] Error 2
make[1]: *** [CMakeFiles/ios-x86_64.dir/all] Error 2
make: *** [all] Error 2

**Comment by zxpgo** [comment]
How to solve?

**Comment by dcommander** [comment]
I am not a mind reader. Demonstrate how to reproduce the problem.

**Comment by leleliu008** [comment]
@zxpgo @dcommander 

this problem is caused by [cmake 3.19.1](https://github.com/Kitware/CMake/releases/tag/v3.19.1). I use [cmake 3.18.4](https://github.com/Kitware/CMake/releases/tag/v3.18.4) resolved this problem. remove `-DCMAKE_OSX_ARCHITECTURES=x86_64` also can resolve this problem.

the reason is [cmake 3.19.1](https://github.com/Kitware/CMake/releases/tag/v3.19.1) auto add `-arch x86_64` flags to `nasm` command when cross-comping, but `nasm` don't recognized this flag. so it reported `more than one input file specified.`

error log (formatted for easy reading) :
```
[  2%] Building ASM_NASM object simd/CMakeFiles/simd.dir/x86_64/jsimdcpu.asm.o
cd /var/folders/jw/7vmz4m1970932zln9tb1whxr0000gn/T/tmp.v97brFDG/1606588708/iPhoneSimulator/x86_64/simd && \
/usr/local/bin/nasm \
-I/var/folders/jw/7vmz4m1970932zln9tb1whxr0000gn/T/tmp.v97brFDG/1606588708/iPhoneSimulator/x86_64 \
-I/var/folders/jw/7vmz4m1970932zln9tb1whxr0000gn/T/tmp.v97brFDG \
-DMACHO -D__x86_64__ -DPIC \
-I"/var/folders/jw/7vmz4m1970932zln9tb1whxr0000gn/T/tmp.v97brFDG/simd/nasm/" \
-I"/var/folders/jw/7vmz4m1970932zln9tb1whxr0000gn/T/tmp.v97brFDG/simd/x86_64/" \
-arch x86_64 \
-f macho64 \
-o CMakeFiles/simd.dir/x86_64/jsimdcpu.asm.o \
/var/folders/jw/7vmz4m1970932zln9tb1whxr0000gn/T/tmp.v97brFDG/simd/x86_64/jsimdcpu.asm
x86_64: fatal: more than one input file specified: /var/folders/jw/7vmz4m1970932zln9tb1whxr0000gn/T/tmp.v97brFDG/simd/x86_64/jsimdcpu.asm
```

**reproduce:**
build machine:
```
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H15
```
[cmake 3.19.1](https://github.com/Kitware/CMake/releases/tag/v3.19.1) in `PATH`
run command:
```
cmake \
-DCMAKE_VERBOSE_MAKEFILE=ON \
-DCMAKE_COLOR_MAKEFILE=ON \
-DCMAKE_TOOLCHAIN_FILE=toolchain.cmake \
-DCMAKE_OSX_ARCHITECTURES=x86_64 \
-DCMAKE_INSTALL_PREFIX=`pwd`/out \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD_SHARED_LIBS=OFF \
-DBUILD_TESTING=OFF \
-G 'Unix Makefiles' \
-Wno-dev \
-S . \
-B build.d \
-DENABLE_STATIC=ON \
-DENABLE_SHARED=ON \
-DWITH_JAVA=OFF \
-DWITH_SIMD=ON \
-DFORCE_INLINE=ON &&
make -C build.d
```
toolchain.cmake:
```
set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang")
set(CMAKE_C_FLAGS "-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -Qunused-arguments -arch x86_64 -Os -pipe -miphonesimulator-version-min=8.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -Qunused-arguments -D__x86_64__")

set(CMAKE_CXX_COMPILER "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++")
set(CMAKE_CXX_FLAGS "-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -Qunused-arguments -arch x86_64 -Os -pipe -miphonesimulator-version-min=8.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -Qunused-arguments -D__x86_64__")

set(CMAKE_AR "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar")
set(CMAKE_RANLIB "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib")

set(CMAKE_NM "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm")
set(CMAKE_STRIP "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip")

set(CMAKE_OSX_SYSROOT "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk")
```

**Comment by dcommander** [comment]
OK, I’ll see if I can work around it somehow. In general, though, I advise against using `CMAKE_OSX_ARCHITECTURES` with libjpeg-turbo. There is no need to, since we can’t accommodate multiple architectures in a single build (due to the use of assembly code.) Our build system has facilities to combine multiple architectures into the same set of binaries before packaging them, but the multiple architectures have to be built separately.

**Comment by zxpgo** [comment]
> cmake \
> -DCMAKE_VERBOSE_MAKEFILE=ON \
> -DCMAKE_COLOR_MAKEFILE=ON \
> -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake \
> -DCMAKE_OSX_ARCHITECTURES=x86_64 \
> -DCMAKE_INSTALL_PREFIX=`pwd`/out \
> -DCMAKE_BUILD_TYPE=Release \
> -DBUILD_SHARED_LIBS=OFF \
> -DBUILD_TESTING=OFF \
> -G 'Unix Makefiles' \
> -Wno-dev \
> -S . \
> -B build.d \
> -DENABLE_STATIC=ON \
> -DENABLE_SHARED=ON \
> -DWITH_JAVA=OFF \
> -DWITH_SIMD=ON \
> -DFORCE_INLINE=ON &&
> make -C build.d

89-=

**Comment by dcommander** [comment]
I was able to reproduce this issue, but there is nothing I can do about it.  CMake is incorrectly injecting the `-arch` flag into the NASM flags after those flags are set by our build system.  CMake understands NASM and maintains separate flags for it (`CMAKE_ASM_NASM_FLAGS`), so this is a CMake bug.  As you discovered, setting `CMAKE_OSX_ARCHITECTURES` to a single value works properly with prior versions of CMake.  libjpeg-turbo does not and cannot support setting `CMAKE_OSX_ARCHITECTURES` to multiple values.

**Comment by leleliu008** [comment]
@dcommander yes, this problem is caused by the latest version of cmake([cmake3.19.1](https://github.com/Kitware/CMake/releases/tag/v3.19.1)). I will report this issue to them.

**Comment by mweinelt** [comment]
@leleliu008 Can you reference the upstream issue?

**Comment by leleliu008** [comment]
@mweinelt this problem is nothing to do with `libjpeg-turbo`. It is caused by the latest version of cmake([cmake3.19.1](https://github.com/Kitware/CMake/releases/tag/v3.19.1)). I want to report this problem to `CMake Team`, but have not yet been reported.

**Comment by bradking** [comment]
See [CMake Issue 21553](https://gitlab.kitware.com/cmake/cmake/-/issues/21553).
