### ISSUE TITLE
Change in behaviour when decoding particular progressive JPEG

### ISSUE THREAD

**Issue by jonathanwright-ARM** [libjpeg-turbo/libjpeg-turbo#477]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No

**Clear and concise description of the bug:**
Progressive JPEG decodes to different image (different MD5 hash) in 2.0.90 and later compared to 2.0.6.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
`./djpeg -dct int -ppm -outfile non-interleaved_progressive.ppm non-interleaved_progressive.jpg`

**Image(s) needed in order to reproduce the bug (if applicable):**
![non-interleaved_progressive](https://user-images.githubusercontent.com/31624044/100885429-8aa3b000-34aa-11eb-8fb6-d304c41797f3.jpg)

**Expected behavior:**
MD5 hash: 327ec50874672b84e0cbf9b0aa719ef0

**Observed behavior:**
MD5 hash: e7df16ee94384e2a0c9f6b49d71539bc

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
GCC 9.3.0, Ubuntu 20.04.1, Intel Xeon E5-2660 v4
The difference also exists when compiling with Clang (same OS and CPU.)
New MD5 hash also observed when compiling libjpeg-turbo 2.0.90 and later using MSVC for Windows 10 on Arm.

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the master branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
Verified that the image decodes to the new MD5 hash for the tip of the master branch and tag 2.0.90. The old behaviour is observed for tags 2.0.6 and 2.0.5.

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**
Working on it.

**Additional information:**
This issue was caught when trying to integrate libjpeg-turbo 2.0.90 (and bug fixes on tip of master branch) into Chromium - you can see the failed tests at the first link:

- https://chromium-review.googlesource.com/c/chromium/src/+/2564483
- https://chromium-review.googlesource.com/c/chromium/deps/libjpeg_turbo/+/2565390

This issue does exist on Arm platforms, despite only x86(_64) bot failures.

**Comment by jonathanwright-ARM** [comment]
Ok, after bisecting, the change in behaviour was introduced in this commit: 42825b68d570fb07fe820ac62ad91017e61e9a25

Given that this seems intentional - changing behaviour in the block-smoothing algorithm in the libjpeg API library - presumably Chromium just needs to update our expected results in the web_tests.

@ProgramMax and @LeonScroggins please confirm this looks ok to you?

**Comment by LeonScroggins** [comment]
What does the difference look like? But yes, I believe this is intentional, and Chromium needs to update its expected results.

**Comment by dcommander** [comment]
Yes, this is intended behavior, because the test image is incomplete.  It contains three separate DC component scans but ends halfway through the third component scan.  Since all component scan headers have been encountered, the quantization table has been decoded.  That means that there is enough data for the new (Google-introduced) 5x5 + 9AC smoothing algorithm to take effect on the DC scans.  Since the image ends before another scan can be decoded, the smoothed DC scans contribute entirely to the output image.

**Comment by jonathanwright-ARM** [comment]
@LeonScroggins here's the two .ppm images. As for the difference between them, the colour boundary looks "smoothed" (which is the new intentional behaviour.) Ok, given that this is all fine we can close this issue as "it's a feature" and update our test expectations in Chromium. Thanks all :)
![master-tip-non-interleaved_progressive](https://user-images.githubusercontent.com/31624044/100904141-a022d500-34be-11eb-9210-4e9022b4a307.png)
![2-0-6-non-interleaved_progressive](https://user-images.githubusercontent.com/31624044/100904165-a749e300-34be-11eb-9c03-ee31240f69fc.png)
