### ISSUE TITLE
Resurrection of "undefined shift" fuzzing issue

### ISSUE THREAD

**Issue by jonathanwright-ARM** [libjpeg-turbo/libjpeg-turbo#478]
After updating Chromium to use libjpeg-turbo 2.1 beta1 with cherry-picked bug-fixes[1], Clusterfuzz seems to have resurrected the `shift exponent 825387374 is too large for 32-bit type 'int'` issue that was originally reported here[2].

```
  ../../third_party/libjpeg_turbo/jdcoefct.c:619:38: runtime error: shift exponent 825387374 is too large for 32-bit type 'int'
  #0 0x5573d1be58de in decompress_smooth_data third_party/libjpeg_turbo/jdcoefct.c:619:38
  #1 0x5573d1be779b in process_data_simple_main third_party/libjpeg_turbo/jdmainct.c:300:10
  #2 0x5573d1bd2436 in jpeg_read_scanlines third_party/libjpeg_turbo/jdapistd.c:287:3
```

Chromium bug discussion (containing link to reproducer test case): https://bugs.chromium.org/p/chromium/issues/detail?id=1156073
Clusterfuzz output: https://clusterfuzz.com/testcase-detail/5763431711178752

Adding @lovell @mo271 

[1] https://chromium-review.googlesource.com/c/chromium/deps/libjpeg_turbo/+/2565390
[2] https://github.com/libjpeg-turbo/libjpeg-turbo/issues/459#issuecomment-733720010

**Comment by dcommander** [comment]
I still cannot reproduce the issue.  I've tried various implementations of UBSan with no luck.  Find a compiler, O/S, and set of compiler options and djpeg options that reliably reproduce the issue.  I cannot debug an issue if it is only reproducible using OSS-Fuzz.

**Comment by dcommander** [comment]
NOTE: Despite being listed as the project owner, I cannot access that link for the Clusterfuzz output, nor can I access the Clusterfuzz test case link in the aforementioned Chromium bug report (I got the test case link from https://github.com/libjpeg-turbo/libjpeg-turbo/issues/459#issuecomment-733720010).

**Comment by lovell** [comment]
One of the libvips fuzz tests started reporting a new and similar "shift exponent" issue at the same line a few days ago but I cannot reproduce outside of OSS-Fuzz so have been reluctant to report it here.

The test cases from #459 do *not* trigger it but here's [a new test case](https://github.com/libjpeg-turbo/libjpeg-turbo/files/5653722/clusterfuzz-testcase-minimized-pngsave_buffer_fuzzer-5269054595792896.txt) that does should that be of any use. Running valgrind within OSS-Fuzz does not report anything for this new test case either.

I too am unsure how to debug this further. Perhaps there are some clever people at Google who can help ;)

**Comment by mo271** [comment]
As before, one can get some potentially useful output using valgrind. Compiling with
```
 cmake -D CMAKE_C_COMPILER=clang-10  -DCMAKE_C_FLAGS="-O0 -g" ../
```
and then running
```
wget https://user-images.githubusercontent.com/3491627/101376530-fde56180-38b0-11eb-938d-734119a5b5ba.jpg
valgrind --leak-check=yes --track-origins=yes djpeg -outfile out.ppm 101376530-fde56180-38b0-11eb-938d-734119a5b5ba.jpg
```
where `djpeg` is the build of the current head https://github.com/libjpeg-turbo/libjpeg-turbo/commit/7b68764905173ecb149b518943c32a27fd345d68. The relevant valgrind output is:
```
==844843== Conditional jump or move depends on uninitialised value(s)
==844843==    at 0x4876928: decompress_smooth_data (jdcoefct.c:521)
==844843==    by 0x48837C4: process_data_simple_main (jdmainct.c:300)
==844843==    by 0x4873CC5: jpeg_read_scanlines (jdapistd.c:287)
==844843==    by 0x402710: main (djpeg.c:810)
==844843==  Uninitialised value was created by a heap allocation
==844843==    at 0x483877F: malloc (vg_replace_malloc.c:307)
==844843==    by 0x489742E: alloc_small (jmemmgr.c:318)
==844843==    by 0x4886076: get_sof (jdmarker.c:278)
==844843==    by 0x4883E33: read_markers (jdmarker.c:0)
==844843==    by 0x48824B2: consume_markers (jdinput.c:323)
==844843==    by 0x4873517: jpeg_consume_input (jdapimin.c:313)
==844843==    by 0x4873476: jpeg_read_header (jdapimin.c:261)
==844843==    by 0x40260D: main (djpeg.c:671)
==844843== 
==844843== Conditional jump or move depends on uninitialised value(s)
==844843==    at 0x48770A1: decompress_smooth_data (jdcoefct.c:610)
==844843==    by 0x48837C4: process_data_simple_main (jdmainct.c:300)
==844843==    by 0x4873CC5: jpeg_read_scanlines (jdapistd.c:287)
==844843==    by 0x402710: main (djpeg.c:810)
==844843==  Uninitialised value was created by a heap allocation
==844843==    at 0x483877F: malloc (vg_replace_malloc.c:307)
==844843==    by 0x489742E: alloc_small (jmemmgr.c:318)
==844843==    by 0x4886076: get_sof (jdmarker.c:278)
==844843==    by 0x4883E33: read_markers (jdmarker.c:0)
==844843==    by 0x48824B2: consume_markers (jdinput.c:323)
==844843==    by 0x4873517: jpeg_consume_input (jdapimin.c:313)
==844843==    by 0x4873476: jpeg_read_header (jdapimin.c:261)
==844843==    by 0x40260D: main (djpeg.c:671)
==844843== 
==844843== Conditional jump or move depends on uninitialised value(s)
==844843==    at 0x48770B7: decompress_smooth_data (jdcoefct.c:630)
==844843==    by 0x48837C4: process_data_simple_main (jdmainct.c:300)
==844843==    by 0x4873CC5: jpeg_read_scanlines (jdapistd.c:287)
==844843==    by 0x402710: main (djpeg.c:810)
==844843==  Uninitialised value was created by a heap allocation
==844843==    at 0x483877F: malloc (vg_replace_malloc.c:307)
==844843==    by 0x489742E: alloc_small (jmemmgr.c:318)
==844843==    by 0x4886076: get_sof (jdmarker.c:278)
==844843==    by 0x4883E33: read_markers (jdmarker.c:0)
==844843==    by 0x48824B2: consume_markers (jdinput.c:323)
==844843==    by 0x4873517: jpeg_consume_input (jdapimin.c:313)
==844843==    by 0x4873476: jpeg_read_header (jdapimin.c:261)
==844843==    by 0x40260D: main (djpeg.c:671)
==844843== 
==844843== Conditional jump or move depends on uninitialised value(s)
==844843==    at 0x4877357: decompress_smooth_data (jdcoefct.c:650)
==844843==    by 0x48837C4: process_data_simple_main (jdmainct.c:300)
==844843==    by 0x4873CC5: jpeg_read_scanlines (jdapistd.c:287)
==844843==    by 0x402710: main (djpeg.c:810)
==844843==  Uninitialised value was created by a heap allocation
==844843==    at 0x483877F: malloc (vg_replace_malloc.c:307)
==844843==    by 0x489742E: alloc_small (jmemmgr.c:318)
==844843==    by 0x4886076: get_sof (jdmarker.c:278)
==844843==    by 0x4883E33: read_markers (jdmarker.c:0)
==844843==    by 0x48824B2: consume_markers (jdinput.c:323)
==844843==    by 0x4873517: jpeg_consume_input (jdapimin.c:313)
==844843==    by 0x4873476: jpeg_read_header (jdapimin.c:261)
==844843==    by 0x40260D: main (djpeg.c:671)
==844843== 
==844843== Conditional jump or move depends on uninitialised value(s)
==844843==    at 0x4877369: decompress_smooth_data (jdcoefct.c:668)
==844843==    by 0x48837C4: process_data_simple_main (jdmainct.c:300)
==844843==    by 0x4873CC5: jpeg_read_scanlines (jdapistd.c:287)
==844843==    by 0x402710: main (djpeg.c:810)
==844843==  Uninitialised value was created by a heap allocation
==844843==    at 0x483877F: malloc (vg_replace_malloc.c:307)
==844843==    by 0x489742E: alloc_small (jmemmgr.c:318)
==844843==    by 0x4886076: get_sof (jdmarker.c:278)
==844843==    by 0x4883E33: read_markers (jdmarker.c:0)
==844843==    by 0x48824B2: consume_markers (jdinput.c:323)
==844843==    by 0x4873517: jpeg_consume_input (jdapimin.c:313)
==844843==    by 0x4873476: jpeg_read_header (jdapimin.c:261)
==844843==    by 0x40260D: main (djpeg.c:671)
==844843== 
==844843== Conditional jump or move depends on uninitialised value(s)
==844843==    at 0x4877567: decompress_smooth_data (jdcoefct.c:687)
==844843==    by 0x48837C4: process_data_simple_main (jdmainct.c:300)
==844843==    by 0x4873CC5: jpeg_read_scanlines (jdapistd.c:287)
==844843==    by 0x402710: main (djpeg.c:810)
==844843==  Uninitialised value was created by a heap allocation
==844843==    at 0x483877F: malloc (vg_replace_malloc.c:307)
==844843==    by 0x489742E: alloc_small (jmemmgr.c:318)
==844843==    by 0x4886076: get_sof (jdmarker.c:278)
==844843==    by 0x4883E33: read_markers (jdmarker.c:0)
==844843==    by 0x48824B2: consume_markers (jdinput.c:323)
==844843==    by 0x4873517: jpeg_consume_input (jdapimin.c:313)
==844843==    by 0x4873476: jpeg_read_header (jdapimin.c:261)
==844843==    by 0x40260D: main (djpeg.c:671)
```
So it still seems to me that there are cases when some value coef_bits is not properly initialized. Perhaps this is due to jumping out early in https://github.com/libjpeg-turbo/libjpeg-turbo/blob/7b68764905173ecb149b518943c32a27fd345d68/jdcoefct.c#L403?
Will investigate further.
![testcase](https://user-images.githubusercontent.com/3491627/101376530-fde56180-38b0-11eb-938d-734119a5b5ba.jpg)

**Comment by dcommander** [comment]
Still can't reproduce any UBSan errors, but I was able to reproduce the valgrind errors.  Those should be fixed now.

NOTE: Using a default value of 0 is definitely correct here:

**Comment by dcommander** [comment]
Still can't reproduce any UBSan errors, but I was able to reproduce the valgrind errors.  Those should be fixed now.

Notes:

- https://github.com/libjpeg-turbo/libjpeg-turbo/files/5653722/clusterfuzz-testcase-minimized-pngsave_buffer_fuzzer-5269054595792896.txt was not useful at all.  It just caused `djpeg` to error out with `PPM output must be grayscale or RGB` before `decompress_smooth_data()` was ever invoked.  If there are particular `djpeg` arguments necessary to reproduce a failure, then **please specify those arguments**.  This goes back to my general rant regarding OSS-Fuzz, which is that it is too difficult to reproduce those test failures outside of OSS-Fuzz.  If I could glean the desired information from the OSS-Fuzz logs, then so be it, but right now, I can't even see those logs.  https://clusterfuzz.com/testcase-detail/5763431711178752 gives me "Access denied", even though I am logged into the [Google account that is set as the primary contact for libjpeg-turbo](https://github.com/google/oss-fuzz/blob/master/projects/libjpeg-turbo/project.yaml#L3).)

- 110d8d6dcafaed517e8f77a6253169535ee3a20e is necessary to avoid "Conditional jump or move depends on uninitialised value(s)" errors in valgrind at all points in `decompress_smooth_data()` that access `coef_bits[1]` through `coef_bits[5]` when decompressing https://user-images.githubusercontent.com/3491627/101376530-fde56180-38b0-11eb-938d-734119a5b5ba.jpg.  Using a default value of 0 is definitely correct here:
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/jdphuff.c#L134.  Any other value produces unexpected results with partial decompression of scans from the test image in https://github.com/libjpeg-turbo/libjpeg-turbo/issues/343.

- c7ca521bc85b57d41d3ad4963c13fc0100481084 is necessary to avoid "Conditional jump or move depends on uninitialised value(s)" errors in valgrind at all points in `decompress_smooth_data()` that access `coef_bits[1]` through `coef_bits[5]` when decompressing https://github.com/libjpeg-turbo/libjpeg-turbo/files/5597075/clusterfuzz-testcase-minimized-pngsave_buffer_fuzzer-5728375846731776.txt.  I'm not sure whether -1 is the correct value here:
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/jdcoefct.c#L410.  In my testing, it doesn't seem to matter.

**Comment by dcommander** [comment]
Please see note at the top of this page: https://libjpeg-turbo.org/DeveloperInfo/PreReleases

regarding the fact that pre-release builds are currently out of sync with the Git repository.  Unfortunately, Travis CI hasn't yet responded to my support requests regarding that issue, and it's been more than a week, so I'm losing hope that they will respond at all.

**Comment by jonathanwright-ARM** [comment]
The fuzzers for MSan[1] and UBSan[2] are happy after applying the above fix[3] here[4]. Thanks all.

[1] https://bugs.chromium.org/p/chromium/issues/detail?id=1156513
[2] https://bugs.chromium.org/p/chromium/issues/detail?id=1156073
[3] https://github.com/libjpeg-turbo/libjpeg-turbo/commit/110d8d6dcafaed517e8f77a6253169535ee3a20e
[4] https://chromium-review.googlesource.com/c/chromium/deps/libjpeg_turbo/+/2575667

**Comment by mo271** [comment]
Thanks to @jonathanwright-ARM for bringing up the issue and to @dcommander for the quick fix!
