### ISSUE TITLE
resource leak in empty_mem_output_buffer()

### ISSUE THREAD

**Issue by invd** [libjpeg-turbo/libjpeg-turbo#479]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes.

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No.

**Clear and concise description of the bug:**
When performing transformations on certain invalid image inputs, there is some memory handling through the `empty_mem_output_buffer()` buffer resizing function that leaves `malloc()`'ed memory assigned after exiting (correctly) with errors. 

This is detected with LeakSanitizer: 
```
ERROR in line 292 while transforming input image:
Invalid SOS parameters for sequential JPEG
==24113==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 131072 byte(s) in 1 object(s) allocated from:
    #0 0x49a48d in malloc (/libjpeg-turbo/build/tjexample+0x49a48d)
    #1 0x7f7d94f825e1 in empty_mem_output_buffer /libjpeg-turbo/build/../jdatadst-tj.c:99:26
    #2 0x7f7d94e43647 in emit_byte /libjpeg-turbo/build/../jcmarker.c:120:10
    #3 0x7f7d94e43647 in emit_dqt /libjpeg-turbo/build/../jcmarker.c:178:7
    #4 0x7f7d94e3c08c in write_frame_header /libjpeg-turbo/build/../jcmarker.c:510:13
    #5 0x7f7d94e4cfdc in prepare_for_pass /libjpeg-turbo/build/../jcmaster.c:508:7
    #6 0x7f7d94dc63cf in jpeg_finish_compress /libjpeg-turbo/build/../jcapimin.c:176:5
    #7 0x7f7d94f4625b in tjTransform /libjpeg-turbo/build/../turbojpeg.c:1975:44
    #8 0x4cbe67 in main /libjpeg-turbo/build/../tjexample.c:290:11
    #9 0x7f7d94a0abba in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6)
```

The memory leak issue was found through a custom fuzzing harness but can be reproduced with the upstream example code as described in the next section. 

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
`tjexample poc_1.jpg foo.jpg -hflip` when compiled with AddressSanitizer via `CFLAGS="-fsanitize=address"`
Use the provided image file as input.

Note: the issue is not specific to `-hflip` and can be triggered by any transform operation.

**Image(s) needed in order to reproduce the bug (if applicable):**
![poc_1](https://user-images.githubusercontent.com/33624438/101953262-5a6eb680-3bfa-11eb-82f0-7e6593b6800f.jpg)

**Expected behavior:**
Error handling without leak.

**Observed behavior:**
Resource leak.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
x86_64 GNU/Linux, Debian 10, observed with both clang-12 and GCC 9.3.0

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the master branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
Fresh git master 1388ad67574d3488870c8b45c22069b6c268abe2 .

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**
Not a known regression.

**Additional information:**

**Comment by dcommander** [comment]
Fixed.  This was just an oversight in the example code (which is project-private), not a more general issue with the library or any of the public-facing applications.
