### ISSUE TITLE
jpeg_mem_dest windows memory free

### ISSUE THREAD

**Issue by XanaduAPI** [libjpeg-turbo/libjpeg-turbo#483]
On Windows 10, when I use jpeg_stdio_dest, I am always prompted that there is not enough disk space, but my disk space is sure to be enough, and I use the admin permission to start the application.

I couldn't solve the problem, so I chose to use jpeg_mem_dest to bypass the disk problem, but now I can't use free to jpeg_mem_dest I think the memory requested by should be available on Linux / MacOS, but my libjpeg-8.dll is compiled with mingw32, so I wonder if there is an API that allows me to release jpeg_mem_dest Memory requested by?

**Comment by dcommander** [comment]
That's odd.  If you're using the default libjpeg-turbo build options, then **libjpeg-8.dll** should be linking against the DLL version of the C run-time library.  That means that the memory allocated using `malloc()` in `jpeg_mem_dest()` should be freeable using a `free()` call made from your application, as long as your application is also linked against the DLL version of the C run-time library.  If either your application or **libjpeg-8.dll** is linked against the static C run-time library, however, then then `malloc()` and `free()` cannot be called across a DLL boundary.

**Comment by XanaduAPI** [comment]
So I may need to use the compiled version instead of the version installed by MinGW, right?
Maybe I need to add a release function in the DLL

**Comment by dcommander** [comment]
I don't know anything about the version installed by MinGW.  I do know that we distribute an official libjpeg-turbo package that includes MinGW-compatible binaries, and the libjpeg API DLL included in that package should properly allow applications to free memory allocated by the library.

Apart from that, the memory source/destination managers are inherited from libjpeg.  If you can demonstrate a clear API deficiency, then I'll consider addressing it, but you haven't yet given me sufficient information to even understand the problem (example code is always appreciated.)
