### ISSUE TITLE
Is it possible to exclude libjpeg.a from built libraries?

### ISSUE THREAD

**Issue by m-peko** [libjpeg-turbo/libjpeg-turbo#484]
Hi there,
I would like to know if it is possible to exclude `libjpeg.a` from built libraries somehow? The reason why I am asking this is because I use libjpeg-turbo along with OpenCV which uses libjpeg and then `libjpeg.a` from libjpeg-turbo and `libjpeg.a` from OpenCV clash and cause OpenCV functions to not work properly.
Thanks and best regards

**Comment by dcommander** [comment]
Yes, just pass `-DENABLE_STATIC=0` to CMake.
