### ISSUE TITLE
Inconsistent JPEG decompression results generated by libjpeg-turbo1.5.90 and 2.0.0 and the speed gap

### ISSUE THREAD

**Issue by BaoXiaoyi1999** [libjpeg-turbo/libjpeg-turbo#489]
Hi,

I found that the JPEG decoding results generated by libjpeg-turbo 2.0.0 was different from those generated by libjpeg-turbo 1.5.90, and there was also a speed gap in between. I am wondering why. 

When I used the [test dataset](http://lear.inrialpes.fr/people/jegou/data.php) for decompression, libjpeg-turbo 2.0.0 and libjpeg-turbo 1.5.90 didn't have the same output. On photo 213600 for example, about 20% pixels do not align, and most of the value difference was within +-2. 

Besides, when decoding with recompiled OpenCV 3.2.0, version 2.0.0 was about 2x compared to 1.5.90 on my test dataset. However, the results of 2.0.0 did not accord with the default libjpeg option while those of 1.5.90 did.

I read the commit history and the change log, yet having nothing in mind. Thanks ahead!

**Comment by dcommander** [comment]
I have no idea why OpenCV compiled with 2.0.0 is slower than with 1.5.90.  That slow-down is certainly not reproducible with the plain libjpeg-turbo code, nor is the decoding difference you report:
```
$ git clone https://github.com/libjpeg-turbo/libjpeg-turbo.git -b 1.5.90
$ cd libjpeg-turbo
$ mkdir build
$ cd build
$ cmake ..
$ make
$ wget ftp://ftp.inrialpes.fr/pub/lear/douze/data/jpg1.tar.gz
$ wget ftp://ftp.inrialpes.fr/pub/lear/douze/data/jpg2.tar.gz
$ tar xf jpg*.tar.gz
$ for i in jpg/*.jpg; do djpeg $i >jpg/`basename $i .jpg`.ppm; done
$ md5sum jpg/*.ppm >md5sum.txt
$ cd ..
$ git checkout 2.0.0
$ cd build
$ make
$ for i in jpg/*.jpg; do djpeg $i >jpg/`basename $i .jpg`.ppm; done
$ md5sum -c md5sum.txt | grep -v OK
```
But of course you didn't specify *anything* about the platform on which you observed the phenomenon.  I guess I'm expected to read your mind?  Which O/S?  Which CPU?  Which compiler (or did you use one of our official packages)?  Which compiler options?

Also, in the future, it would be *really* helpful if you would provide *one* image that demonstrates a problem, not a multi-gigabyte test suite.  It would also be really helpful if you would use `git bisect` to determine the exact commit that introduced the error.

**Comment by BaoXiaoyi1999** [comment]
Sorry for my late reply and really thank you for your detailed explanation!

I tried your code and got the same result as you. libjpeg-turbo 1.5.90 generated the same image as libjpeg-turbo 2.0.0, and their speed was almost the same when tested with tjbench.

It is not a problem within libjpeg-turbo. The inconsistency may have something to do with my use of OpenCV. In my experiment, turbo 1.5.90 = turbo 2.0.0, but opencv + turbo 1.5.90 != opencv + turbo 2.0.0. However, opencv + turbo 1.5.90 = opencv + libjpeg. 
```
cd libjpeg-turbo
mkdir build && cd build && mkdir local
# make sure nasm has been installed
# sudo apt install nasm
cmake .. -DCMAKE_INSTALL_PREFIX=`realpath ./local` -DCMAKE_BUILD_TYPE=Release
make 
make install

# download and compile opencv
cd opencv-3.2.0
mkdir build && cd build && mkdir local
cmake .. -DWITH_IPP=OFF \
    -DWITH_LAPACK=OFF \
    -DBUILD_JPEG=OFF \
    -DWITH_JPEG=ON \
    -DJPEG_LIBRARY=/path to libjpeg turbo/build/local/lib/libturbojpeg.so \
    -DJPEG_INCLUDE_DIR=/path to libjpeg turbo/build/local/include/ \
    -DCMAKE_INSTALL_PREFIX=`realpath ./local` \
    -DCMAKE_BUILD_TYPE=Release
make 
make install

# test
LD_LIBRARY_PATH=/path to opencv3.2.0/build/local/lib:/path to libjpeg turbo/build/local/lib /path/to/path to imgdecode cpp
```

I decided to move on with next task. Thank you again for your help!

**Comment by dcommander** [comment]
I don't know much about OpenCV, but as far as I can tell, it does not use the TurboJPEG API library.  Thus, you are passing the wrong library in the `JPEG_LIBRARY` CMake variable.  README.md in the libjpeg-turbo source tree explains the difference between the TurboJPEG and libjpeg API libraries.  Most downstream projects use the libjpeg API library.

**Comment by vrbincs** [comment]
I have seen a similar thing as @BaoXiaoyi1999 when using Qt to generate a histogram. The Qt on my system uses libjpeg-turbo (Arch Linux - https://github.com/archlinux/svntogit-packages/blob/packages/qt5-base/trunk/PKGBUILD) and the pixels decoded by the Qt API seems to be different that in GIMP.

The histogram values produced by the histogram tool in Qt do not match with GIMP histogram. There are small differences just like @BaoXiaoyi1999 noted in his original comment.

Also, I converted the same image to PNG and constructed a histogram with the same tool. Now, the histogram does match with the histogram generated in GIMP (assuming GIMP is okay :D).

That said, I can only conclude that there seems to be a genuine problem with the recent version(s) of jpeg-turbo (I am not sure for older releases as I am not sure when Arch linux switched to jpeg-turbo). A decoded picture with jpeg-turbo seems to produce slightly different results than the reference library (GIMP).

My system info:
Arch Linux (up-to-date)
jpeg-turbo 2.0.6
Qt 5.15.2

Here is an example of the image: https://github.com/NearmapTechnology/nearmap-Cpp-coding-test/blob/master/data/DSC_0278.JPG

**Comment by BaoXiaoyi1999** [comment]
> I don't know much about OpenCV, but as far as I can tell, it does not use the TurboJPEG API library. Thus, you are passing the wrong library in the `JPEG_LIBRARY` CMake variable. README.md in the libjpeg-turbo source tree explains the difference between the TurboJPEG and libjpeg API libraries. Most downstream projects use the libjpeg API library.

Before version 3.4.0， OpenCV used libjpeg as its default for JPEG decoding. After that, libjpeg-turbo became the default. As my project was using opencv 3.2.0, I had to manually assign libjpeg-turbo for decoding by passing its path as a parameter.  Personally I think the code could successfully do what I want.

**Comment by dcommander** [comment]
@BaoXiaoyi1999 You're misunderstanding me.  libjpeg-turbo provides two librarie: the libjpeg API library that is backward-compatible with libjpeg (but provides 2-6x better performance) and the TurboJPEG API library that provides an API that is unique to libjpeg-turbo.  Just because a project uses libjpeg-turbo does not mean that is using the TurboJPEG API.  As far as I can tell, OpenCV is not using the TurboJPEG API, but you are attempting to pass the TurboJPEG API library to the OpenCV build system.  That may be causing the OpenCV build system to ignore the value of `JPEG_LIBRARY` that you passed.  That might also be causing the OpenCV build system to use the libjpeg API library provided by the operating system, which might not be libjpeg-turbo (or it could be a version of libjpeg-turbo that doesn't perform as well as the one you built.)

**Comment by BaoXiaoyi1999** [comment]
Ohh so maybe I could try to find out how to choose Turbo API within opencv explicitly, and that could possibly remove the inconsistency

**Comment by dcommander** [comment]
As far as I can tell, OpenCV does not support the TurboJPEG API.  You have to use the libjpeg API, which means that you need to link against libjpeg.so/libjpeg.a rather than libturbojpeg.so/libturbojpeg.a.

**Comment by dcommander** [comment]
@vrbincs No idea why that would occur, but in order for me to debug any such issue, you'll need to isolate it using only libjpeg-turbo. I suspect that, in the process of isolating it, you will also discover what changed in the downstream code or build system that caused the mathematical output of the codec to change.

**Comment by dcommander** [comment]
Also, regarding mathematical compatibility, please refer to this section of README.md, which describes the situations in which the mathematical (bitwise) output of libjpeg-turbo is expected to be different than that of libjpeg:
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/README.md#mathematical-compatibility
