### ISSUE TITLE
jpegexiforient: add exif tags if there are none

### ISSUE THREAD

**Issue by dingens** [libjpeg-turbo/libjpeg-turbo#494]
jpegexiforient silently does nothing on files that don't contain exif tags. I'd be great if it could create them when called in *set* mode. (But if it is a deliberate decision not to do so, at least it should inform about the failure, and maybe give hints.)

**Comment by dcommander** [comment]
jpegexiforient is not part of libjpeg-turbo (or libjpeg, for that matter.)  It appears to be provided by JPEGClub.org, which is a domain owned by the Independent JPEG Group (the maintainer of libjpeg.)  However, [the source code itself](https://github.com/CiderMan/jpegexiforient) has no copyright header, so it's unclear which license applies.

**Comment by dingens** [comment]
Ah hm okay. I reported here because in Debian, it's part of the `libjpeg-turbo-progs` package. Sorry for the disruption then, I'll try elsewhere :)
