### ISSUE TITLE
In which part the quantization table calculation takes place

### ISSUE THREAD

**Issue by OssNass** [libjpeg-turbo/libjpeg-turbo#496]
This is more of a question than an issue:

I am trying to modify libjpeg turbo, specifically to change how the quantization are calculated on per block basis.

I just want to know in which part of the code is the calculation of quantization table based on quality happens.

**Comment by dcommander** [comment]
Look in jcparam.c, but also note that the libjpeg API allows you to compute the tables yourself and inject them into the compressor, so it isn’t strictly necessary to modify libjpeg-turbo.

**Comment by OssNass** [comment]
The standard behaviour is to add custom quantization table that used on the entire image, my modification is to use a different quantization per 8*8 block.

Thanks anyway

**Comment by dcommander** [comment]
Out of curiosity, how do you intend to encode the quant tables into the JPEG file?

**Comment by dcommander** [comment]
Out of curiosity, how do you intend to encode the quantization tables into the JPEG file?

**Comment by OssNass** [comment]
I don't, instead I'm going to store the quality of each block and then use that to calculate its quantization table based on the jpeg standard, however the quality values will be of two values a minimum value and a maximum value to maximize compression
