### ISSUE TITLE
x86/x86_64 stack alignment in assembly sources

### ISSUE THREAD

**Issue by ilyakurdyukov** [libjpeg-turbo/libjpeg-turbo#498]
It may be harmless, or may matter in very rare cases. 

x86_64/jidctint-avx2.asm:

```
EXTN(jsimd_idct_islow_avx2):
    push        rbp
    mov         rax, rsp                     ; rax = original rbp
    mov         rbp, rsp                     ; rbp = aligned rbp
    push_xmm    4
    collect_args 4
```

"push_xmm" macro for WIN64 uses movaps, but the stack is not aligned on a 16-byte boundary. But the stack will probably be aligned from the caller.

x86_64/jidctflt-sse2.asm:

```
EXTN(jsimd_idct_float_sse2):
    push        rbp
    mov         rax, rsp                     ; rax = original rbp
    sub         rsp, byte 4
    and         rsp, byte (-SIZEOF_XMMWORD)  ; align to 128 bits
```

For `x86_64` it should be 8, not 4. I wonder what will happen on interrupt exactly after "sub" and before "and".

Didn't check all assembly sources.

**Comment by dcommander** [comment]
The code in question is very thoroughly tested, so if it hasn't caused a problem yet, I doubt it will.
