### ISSUE TITLE
Build failing using Xcode7 (I would like to build using bitcode enabled)

### ISSUE THREAD

**Issue by szigetics** [libjpeg-turbo/libjpeg-turbo#5]
I used the following script to build the library for iOS : 
```
#!/bin/bash

autoreconf -fiv


mkdir libs
mkdir libs/ios
mkdir libs/ios/device
mkdir libs/ios/simulator

cd src

COMPILER_TOOL="xcodebuild"
IOS_SIMULATOR_VERSION_OF_THE_CURRENT_ENVIRONMENT=`"$COMPILER_TOOL" -showsdks | grep -E "^\s+iOS\s+\d+" | awk '{print $2}'`
echo "IOS_SIMULATOR_VERSION_OF_THE_CURRENT_ENVIRONMENT determined by create_iOS_SimulatorBuild : $IOS_SIMULATOR_VERSION_OF_THE_CURRENT_ENVIRONMENT"

IOS_PLATFORMDIR=/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform
IOS_SYSROOT=$IOS_PLATFORMDIR/Developer/SDKs/iPhoneOS$IOS_SIMULATOR_VERSION_OF_THE_CURRENT_ENVIRONMENT.sdk
IOS_SIMULATOR_PLATFORMDIR=/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform
IOS_SIMULATOR_SYSROOT=$IOS_SIMULATOR_PLATFORMDIR/Developer/SDKs/iPhoneSimulator$IOS_SIMULATOR_VERSION_OF_THE_CURRENT_ENVIRONMENT.sdk
IOS_GCC=/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang

 echo $IOS_SIMULATOR_SYSROOT;

# armv7
echo "--- Building for armv7 ---"
make clean
IOS_CFLAGS="-arch armv7 -miphoneos-version-min=8.0"
./configure --host arm-apple-darwin10 \
    CC="$IOS_GCC" LD="$IOS_GCC" \
    CFLAGS="-mfloat-abi=softfp -isysroot $IOS_SYSROOT -O3 $IOS_CFLAGS" \
    LDFLAGS="-mfloat-abi=softfp -isysroot $IOS_SYSROOT $IOS_CFLAGS" \
    CCASFLAGS="-no-integrated-as $IOS_CFLAGS"
make
mv -v .libs/libturbojpeg.a ../libs/libturbojpeg_armv7_a

# armv7s
echo "--- Building for armv7s ---"
make clean
IOS_CFLAGS="-arch armv7s -miphoneos-version-min=8.0"
./configure --host arm-apple-darwin10 \
    CC="$IOS_GCC" LD="$IOS_GCC" \
    CFLAGS="-mfloat-abi=softfp -isysroot $IOS_SYSROOT -O3 $IOS_CFLAGS" \
    LDFLAGS="-mfloat-abi=softfp -isysroot $IOS_SYSROOT $IOS_CFLAGS" \
    CCASFLAGS="-no-integrated-as $IOS_CFLAGS"
make
mv -v .libs/libturbojpeg.a ../libs/libturbojpeg_armv7s_a

# arm64
echo "--- Building for arm64 ---"
make clean
IOS_CFLAGS="-arch arm64 -miphoneos-version-min=8.0"
./configure --host aarch64-apple-darwin \
    CC="$IOS_GCC" LD="$IOS_GCC" \
    CFLAGS="-isysroot $IOS_SYSROOT -O3 $IOS_CFLAGS" \
    LDFLAGS="-isysroot $IOS_SYSROOT $IOS_CFLAGS"
make
mv -v .libs/libturbojpeg.a ../libs/libturbojpeg_arm64_a


# i386 (32-bit Build on 64-bit OS X ==> i686)
echo "--- Building for i386 (32-bit Build on 64-bit OS X ==> i686) ---"
make clean
./configure --host i686-apple-darwin CFLAGS='-O3 -m32' LDFLAGS=-m32
make
 mv -v .libs/libturbojpeg.a ../libs/libturbojpeg_x86_a


 # x86_64
 echo "--- Building for x86_64 ---"
 make clean
 ./configure --host x86_64-apple-darwin NASM=/opt/local/bin/nasm
 make
  mv -v .libs/libturbojpeg.a ../libs/libturbojpeg_x86_64_a

# # lipo
cd ..
xcrun -sdk iphoneos lipo -arch armv7 libs/libturbojpeg_armv7_a -arch armv7s libs/libturbojpeg_armv7s_a -arch arm64 libs/libturbojpeg_arm64_a -create -output libs/ios/device/libturbojpeg.a
xcrun -sdk iphoneos lipo -arch i386 libs/libturbojpeg_x86_a -arch x86_64 libs/libturbojpeg_x86_64_a -create -output libs/ios/simulator/libturbojpeg.a

rm -f libs/*_a
```

Unfortunately this does not work any more. :disappointed: 

The errors I can see are similar : 
"file was built for armv7 which is not the architecture being linked (x86_64)"

Do you have any idea abot how could I fix this?

Thanks!

**Comment by dcommander** [comment]
Follow the iOS build instructions in BUILDING.txt.

**Comment by szigetics** [comment]
Thanks for your fast answer!

Hm... I thought that I am executing just the same in my script as what is described in BUILDING.txt... I've slightly modified it and now it created the library. I will post the final build script soon once I am sure that it is ready. (Once I checked that the built lib works as expected.)

Thanks again!

**Comment by szigetics** [comment]
Hm... I could build the lib, but I receive this error when I try to link it when targeting simulator : 

"ld: in .../libjpeg-turbo-1.4.1-ios-bitcode/package/libs/ios/simulator/libturbojpeg.a(libturbojpeg_la-jcapimin.o), building for iOS simulator, but linking in object file built for OSX, for architecture x86_64"

Do you know how can this be fixed?

Thanks!

**Comment by dcommander** [comment]
I think the simulator has to use the i386 architecture, not x86_64.

**Comment by szigetics** [comment]
Since Apple released their 64bit processor (arm64), there are 2 simulator architectures : i386 and x86_64 .

**Comment by dcommander** [comment]
I have no idea, but this is not a libjpeg-turbo bug.

**Comment by szigetics** [comment]
I could finally build it. Xcode has a bug which is described here :  https://discuss.newrelic.com/t/build-failure-in-ios-9/25963 .

To fix the build, I had to change the parameters slightly : 
## i386 (32-bit Build on 64-bit OS X ==> i686)
echo "--- Building for i386 (32-bit Build on 64-bit OS X ==> i686) ---"
make clean
./configure --host i686-apple-darwin CFLAGS='-O3 -m32 -arch i386 -fembed-bitcode -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -mios-simulator-version-min=8.0' LDFLAGS=-m32
make
 mv -v .libs/libturbojpeg.a ../libs/libturbojpeg_x86_a


##  x86_64
 echo "--- Building for x86_64 ---"
 make clean
 ./configure --host x86_64-apple-darwin CFLAGS='-arch x86_64 -fembed-bitcode -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -mios-simulator-version-min=8.0' NASM=/opt/local/bin/nasm
 make
  mv -v .libs/libturbojpeg.a ../libs/libturbojpeg_x86_64_a

My full build script for iOS with Xcode7, with BitCode flag enabled is : 
```
#!/bin/bash

if [ ! -d "../libs" ]; then
    echo "../libs does not exists or not a directory!!!"
    exit 1;
fi

autoreconf -fiv

IOS_PLATFORMDIR=/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform
IOS_SYSROOT=$IOS_PLATFORMDIR/Developer/SDKs/iPhoneOS9.0.sdk
IOS_SIMULATOR_PLATFORMDIR=/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform
IOS_SIMULATOR_SYSROOT=$IOS_SIMULATOR_PLATFORMDIR/Developer/SDKs/iPhoneSimulator9.0.sdk
IOS_GCC=/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang

## armv7
echo "--- Building for armv7 ---"
make clean
IOS_CFLAGS="-arch armv7 -miphoneos-version-min=8.0"
./configure --host arm-apple-darwin10 \
    CC="$IOS_GCC" LD="$IOS_GCC" \
    CFLAGS="-mfloat-abi=softfp -isysroot $IOS_SYSROOT -O3 $IOS_CFLAGS -fembed-bitcode" \
    LDFLAGS="-mfloat-abi=softfp -isysroot $IOS_SYSROOT $IOS_CFLAGS" \
    CCASFLAGS="-no-integrated-as $IOS_CFLAGS"
make
mv -v .libs/libturbojpeg.a ../libs/libturbojpeg_armv7_a

## armv7s
echo "--- Building for armv7s ---"
make clean
IOS_CFLAGS="-arch armv7s -miphoneos-version-min=8.0"
./configure --host arm-apple-darwin10 \
    CC="$IOS_GCC" LD="$IOS_GCC" \
    CFLAGS="-mfloat-abi=softfp -isysroot $IOS_SYSROOT -O3 $IOS_CFLAGS -fembed-bitcode" \
    LDFLAGS="-mfloat-abi=softfp -isysroot $IOS_SYSROOT $IOS_CFLAGS" \
    CCASFLAGS="-no-integrated-as $IOS_CFLAGS"
make
mv -v .libs/libturbojpeg.a ../libs/libturbojpeg_armv7s_a

## arm64
echo "--- Building for arm64 ---"
make clean
IOS_CFLAGS="-arch arm64 -miphoneos-version-min=8.0"
./configure --host aarch64-apple-darwin \
    CC="$IOS_GCC" LD="$IOS_GCC" \
    CFLAGS="-isysroot $IOS_SYSROOT -O3 $IOS_CFLAGS -fembed-bitcode" \
    LDFLAGS="-isysroot $IOS_SYSROOT $IOS_CFLAGS"
make
mv -v .libs/libturbojpeg.a ../libs/libturbojpeg_arm64_a


## i386 (32-bit Build on 64-bit OS X ==> i686)
echo "--- Building for i386 (32-bit Build on 64-bit OS X ==> i686) ---"
make clean
./configure --host i686-apple-darwin CFLAGS='-O3 -m32 -arch i386 -fembed-bitcode -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -mios-simulator-version-min=8.0' LDFLAGS=-m32
make
 mv -v .libs/libturbojpeg.a ../libs/libturbojpeg_x86_a


##  x86_64
 echo "--- Building for x86_64 ---"
 make clean
 ./configure --host x86_64-apple-darwin CFLAGS='-arch x86_64 -fembed-bitcode -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -mios-simulator-version-min=8.0' NASM=/opt/local/bin/nasm
 make
  mv -v .libs/libturbojpeg.a ../libs/libturbojpeg_x86_64_a

## lipo
mkdir -p ../libs/ios/device
mkdir -p ../libs/ios/simulator

xcrun -sdk iphoneos lipo -arch armv7 ../libs/libturbojpeg_armv7_a -arch armv7s ../libs/libturbojpeg_armv7s_a -arch arm64 ../libs/libturbojpeg_arm64_a -create -output ../libs/ios/device/libturbojpeg.a
xcrun -sdk iphoneos lipo -arch i386 ../libs/libturbojpeg_x86_a -arch x86_64 ../libs/libturbojpeg_x86_64_a -create -output ../libs/ios/simulator/libturbojpeg.a

rm -f ../libs/*_a

```

Thanks again!

**Comment by dcommander** [comment]
My understanding is that fully supporting bitcode is a more complicated issue than just adding `-fembed-bitcode` to the compile flags.  Bitcode is an intermediate representation and is somewhat architecture-independent, so my understanding is that it isn't compatible with assembly.  That's why I haven't made any big moves toward supporting it.  @dhoerl, does that ring true?

See also https://github.com/dhoerl/libjpeg-turbo-builder/issues/8.

**Comment by macteo** [comment]
I've been able to build, archive and export rebuilding from bitcode an iOS app including `libturbo-jpeg.a` produced with the above script.

Is there a way to find out if the included bitcode doesn't cover the whole library?
I would expect the export to fail if there isn't full coverage.

**Comment by dhoerl** [comment]
I tried to build the library with bitcode several months ago, and it failed. No way to convert NEON to bitcode. I believe I searched and found others saying the same. Maybe that has changed - I just don't know. If the build with bitcode worked, well someone could upload a bitcode app with the library to Test Flight, not release it, but have someone test the app with Test Flight. If the app can encode and decode JSON, well, that would more or less indicate it was working, no?

**Comment by macteo** [comment]
I uploaded an app that includes (and uses the library). 
Checked include bitcode in Organizer. 

![screen shot 2016-08-09 at 17 07 32](https://cloud.githubusercontent.com/assets/587988/17521572/2003f0ec-5e54-11e6-8286-95ef594da24e.png)

The build has been uploaded and processed by iTunes Connect.
It became available on TestFlight.
Downloaded installed and it's working on my device.

Do you suggest any other test?

**Comment by dhoerl** [comment]
When I originally got back to DRC on this issue, I had tried to build a universal binary with all the relevant ARM binaries and bitcode. It didn't work. So I went back to my project and well now it does compile with the -fembed-bitcode" flag. I don't have any more info to add -I can only imagine that clang was updated since I previously did my build, which I believe was last January.

**Comment by dcommander** [comment]
But I don't understand how that's even possible with assembly code.  Even if it were possible, the assembly would have to be converted into bitcode and back again, which defeats the whole purpose of having hand-tuned assembly.

**Comment by dhoerl** [comment]
The flag is added to each architecture build. Perhaps in the end the binary has two components - a single bitcode and a "special" section for NEON binary. I'll ask on the developer forum and see if anyone can explain it.

**Comment by dhoerl** [comment]
There is a Q&A on the dev forums on NEON and bitcode. Apple engineers state "it will just work" more or less. Even with bitcode you need to build for the various known architectures (which for sure seems odd!). Anyway, if you have a developer login you can see the thread (its long) here: https://forums.developer.apple.com/thread/3971

**Comment by dcommander** [comment]
Yeah, if you can get a straight answer on that, that would be great.  I am certainly willing to support bitcode in my official builds, although it would require some work, so I need to understand exactly what I'm getting myself into and what pitfalls (if any) there are.  Part of that work would involve regression testing the performance to ensure that the addition of bitcode hasn't affected it, as well as to sort out the compatibility situation.  Bitcode requires iOS 9, and I'm hoping that including it won't affect backward compatibility with iOS 7 and 8 (I can test that pretty easily with a jailbroken iPhone 4S that I keep around for exactly that purpose.)  I would need to update my official builds, which are currently using XCode 4.6.x and 5.1.x to build those architectures.  It would also be nice if I could make the simplifying assumption that this only needs to be included with ARMv7, v7s, and v8.  Including it with x86 doesn't seem useful, unless that's required for the simulator.

Furthermore, I think it's probably safe to drop ARMv6 support.  The most recent device that required that was the iPhone 3G, and iOS 4.2.1 was the latest O/S to support that phone.  libjpeg-turbo has never supported iOS < 4.3, so it seems that our inclusion of ARMv6 wasn't ever useful to begin with.

**Comment by mayeut** [comment]
The bitcode isn't interpreted at all by devices. It's just embedded within your obj files / binaries for Apple backend to rebuild them on their servers so there won't be any performance penalty when you do your tests given that assembly now seems supported somehow.
The LLVM bitcode that gets embedded is the Optimized LLVM IR code which is fed to the compiler backend to generate the final binary. You can see this by adding `-v` to CFLAGS. The short version for `clang -c -fembed-bitcode -O3 -v -o file.o file.c` being:
```
clang -cc1 ...some_options.... -emit-llvm-bc -O3 -o temp.bc -x c file.c
clang -cc1 ...some_other_options... -emit-obj -fembed-bitcode -disable-llvm-optzns -O3 -o file.o -x ir temp.bc
``` 

The fact the LLVM IR is not re-optimized (`-disable-llvm-optzns`) in the second pass makes sense here (optimizer has not changed between the 2 commands) but there's no telling if Apple will do the same on their end (that is just run the backend or first run the LLVM IR optimizer with their up to date optimizer version)

So in short, for the C portion of code, we don't know what will be generated by Apple's backend (are they using the same version, do they use specific tuning for different processors, specific flags, ...)
What in my opinion should be a showstopper for anyone (not for Apple apparently) is that what you ship (to end-users) is not what you test. Performances are one thing and, one would argue that bitcode allows Apple to target specific micro-architectures leading to better performances "on average" (deliver binaries tuned for Apple A7 on iPhone 5S devices, binaries tuned for A8 on iPhone 6, ...). The other thing is that the backend used could be buggy and the binaries delivered to end-users would crash, corrupt data, ... pick your poison. There's no way for a developer to foresee this. He will just have to wait for support requests/ bug reports from end-users.

Regarding bitcode requiring iOS 9, I did not find this piece of information in [Apple documentation](https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html). Slicing requires iOS 9 but not Bitcode according to this (& I don't see why it would given how it works but maybe I'm wrong).

Finally, although it's now quite old (almost one year), [this article](https://medium.com/@FredericJacobs/why-i-m-not-enabling-bitcode-f35cd8fbfcc5) might be of interest.

**Comment by mayeut** [comment]
Well, I forgot to mention that when not using `-fembed-bitcode`, clang would still follow the same workflow the difference being that it would not embed the optimized LLVM IR in the final object. This proves no performance penalty (well, when doing local tests... who knows what happens once it reaches Apple's servers)
c.f. the last article in my previous comment which describes the workflow.

**Comment by dcommander** [comment]
That's good to know that, at least in theory, adding bitcode won't change performance, but I still have to test it, because I have to change compilers in order to embed bitcode.  Hopefully any performance differences between the older compiler I'm using now (LLVM-GCC) and the newer clang will be positive or negligible, and hopefully the newer iOS 9 SDK is still backward compatible.

**Comment by dcommander** [comment]
I've done some testing with this on a jailbroken iPhone 5S, using libjpeg-turbo built with XCode 7.2.1 and armv7, armv7s, and arm64 architectures.  Performance-wise, the only reason why embedding bitcode is feasible at all is because of the NEON Huffman encoder.  Otherwise, because Clang does such a crap job of optimizing our C Huffman encoder, switching to Xcode 7.2.1 would have caused compression performance to drop by 10-15%.  As it stands, the switch to Xcode 7.2.1 is a mixed bag in terms of performance:

**ARMv8:**
- compression speedup:  -1.4 - 4.0% (avg. 1.1%)
- decompression speedup:  -5.1 - 0.93% (avg. -1.7%)

**ARMv7s:**
- compression speedup:  -2.4 - 4.2% (avg. 1.6%)
- decompression speedup:  -3.8 - 6.1% (avg. 2.7%)

**ARMv7:**
- compression speedup:  -2.4 - 7.6% (avg. 1.4%)
- decompression speedup:  -3.6 - 4.6% (avg. 0.61%)

I'm not a fan of the decompression slow-downs under ARMv8.  These are almost all with 4:2:0 and 4:2:2 images (there is no ARMv8 NEON acceleration for 4:2:0 and 4:2:2 upsampling, and this is apparently another C algorithm that Clang does a crap job of optimizing.)  4:2:2 performs the worst (generally in the -4 to -5% range relative to libjpeg-turbo 1.5.0), and 4:2:0 is generally in the -2 to -4% range relative to libjpeg-turbo 1.5.0.  100% of the decompression slow-downs under ARMv7[s] are due to 4:2:0 upsampling, which is similarly not NEON-accelerated (but 4:2:2 is NEON-accelerated on that architecture.)

The other downside is that embedding bitcode into the ARMv7 binaries means that they can no longer be used on iOS < 6.0, but I don't consider that a big deal.  I think you'd be hard pressed to find any currently-maintained applications that are supporting anything older than iOS 7, much less anything older than iOS 6.

I think the benefits in this case outweigh the downsides, so I will proceed with including bitcode in the libjpeg-turbo 1.5.1 binaries.

**Comment by dcommander** [comment]
If someone could test http://www.libjpeg-turbo.org/libjpeg-turbo-1.5.1.dmg and verify that bitcode is properly enabled, I would greatly appreciate it.

**Comment by dcommander** [comment]
Never mind.  I figured out how to test it myself.  1.5.1 has landed.

**Comment by kasamsun111** [comment]
> I used the following script to build the library for iOS :
> 
> ```
> #!/bin/bash
> 
> autoreconf -fiv
> 
> 
> mkdir libs
> mkdir libs/ios
> mkdir libs/ios/device
> mkdir libs/ios/simulator
> 
> cd src
> 
> COMPILER_TOOL="xcodebuild"
> IOS_SIMULATOR_VERSION_OF_THE_CURRENT_ENVIRONMENT=`"$COMPILER_TOOL" -showsdks | grep -E "^\s+iOS\s+\d+" | awk '{print $2}'`
> echo "IOS_SIMULATOR_VERSION_OF_THE_CURRENT_ENVIRONMENT determined by create_iOS_SimulatorBuild : $IOS_SIMULATOR_VERSION_OF_THE_CURRENT_ENVIRONMENT"
> 
> IOS_PLATFORMDIR=/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform
> IOS_SYSROOT=$IOS_PLATFORMDIR/Developer/SDKs/iPhoneOS$IOS_SIMULATOR_VERSION_OF_THE_CURRENT_ENVIRONMENT.sdk
> IOS_SIMULATOR_PLATFORMDIR=/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform
> IOS_SIMULATOR_SYSROOT=$IOS_SIMULATOR_PLATFORMDIR/Developer/SDKs/iPhoneSimulator$IOS_SIMULATOR_VERSION_OF_THE_CURRENT_ENVIRONMENT.sdk
> IOS_GCC=/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
> 
>  echo $IOS_SIMULATOR_SYSROOT;
> 
> # armv7
> echo "--- Building for armv7 ---"
> make clean
> IOS_CFLAGS="-arch armv7 -miphoneos-version-min=8.0"
> ./configure --host arm-apple-darwin10 \
>     CC="$IOS_GCC" LD="$IOS_GCC" \
>     CFLAGS="-mfloat-abi=softfp -isysroot $IOS_SYSROOT -O3 $IOS_CFLAGS" \
>     LDFLAGS="-mfloat-abi=softfp -isysroot $IOS_SYSROOT $IOS_CFLAGS" \
>     CCASFLAGS="-no-integrated-as $IOS_CFLAGS"
> make
> mv -v .libs/libturbojpeg.a ../libs/libturbojpeg_armv7_a
> 
> # armv7s
> echo "--- Building for armv7s ---"
> make clean
> IOS_CFLAGS="-arch armv7s -miphoneos-version-min=8.0"
> ./configure --host arm-apple-darwin10 \
>     CC="$IOS_GCC" LD="$IOS_GCC" \
>     CFLAGS="-mfloat-abi=softfp -isysroot $IOS_SYSROOT -O3 $IOS_CFLAGS" \
>     LDFLAGS="-mfloat-abi=softfp -isysroot $IOS_SYSROOT $IOS_CFLAGS" \
>     CCASFLAGS="-no-integrated-as $IOS_CFLAGS"
> make
> mv -v .libs/libturbojpeg.a ../libs/libturbojpeg_armv7s_a
> 
> # arm64
> echo "--- Building for arm64 ---"
> make clean
> IOS_CFLAGS="-arch arm64 -miphoneos-version-min=8.0"
> ./configure --host aarch64-apple-darwin \
>     CC="$IOS_GCC" LD="$IOS_GCC" \
>     CFLAGS="-isysroot $IOS_SYSROOT -O3 $IOS_CFLAGS" \
>     LDFLAGS="-isysroot $IOS_SYSROOT $IOS_CFLAGS"
> make
> mv -v .libs/libturbojpeg.a ../libs/libturbojpeg_arm64_a
> 
> 
> # i386 (32-bit Build on 64-bit OS X ==> i686)
> echo "--- Building for i386 (32-bit Build on 64-bit OS X ==> i686) ---"
> make clean
> ./configure --host i686-apple-darwin CFLAGS='-O3 -m32' LDFLAGS=-m32
> make
>  mv -v .libs/libturbojpeg.a ../libs/libturbojpeg_x86_a
> 
> 
>  # x86_64
>  echo "--- Building for x86_64 ---"
>  make clean
>  ./configure --host x86_64-apple-darwin NASM=/opt/local/bin/nasm
>  make
>   mv -v .libs/libturbojpeg.a ../libs/libturbojpeg_x86_64_a
> 
> # # lipo
> cd ..
> xcrun -sdk iphoneos lipo -arch armv7 libs/libturbojpeg_armv7_a -arch armv7s libs/libturbojpeg_armv7s_a -arch arm64 libs/libturbojpeg_arm64_a -create -output libs/ios/device/libturbojpeg.a
> xcrun -sdk iphoneos lipo -arch i386 libs/libturbojpeg_x86_a -arch x86_64 libs/libturbojpeg_x86_64_a -create -output libs/ios/simulator/libturbojpeg.a
> 
> rm -f libs/*_a
> ```
> 
> Unfortunately this does not work any more. 
> 
> The errors I can see are similar :
> "file was built for armv7 which is not the architecture being linked (x86_64)"
> 
> Do you have any idea abot how could I fix this?
> 
> Thanks!
