### ISSUE TITLE
Need just repack data. Or just add JFIF without decopress/compress steps.

### ISSUE THREAD

**Issue by KonstantinBYvitebsk** [libjpeg-turbo/libjpeg-turbo#501]
Hi. I have a file. It is just raw jpg data. Without JFIF.
Is it posiible to add JFIF information with this library without decompressing->compressing?

Please look at the file:
![test](https://user-images.githubusercontent.com/8515668/108247868-4304fa00-7164-11eb-9ad6-e4518c60645a.jpg)
I want just to add basic JFIF information.

**Comment by dcommander** [comment]
Running it through jpegtran seems to do the trick.

**Comment by KonstantinBYvitebsk** [comment]
It is really makes what I need. Thank you..
