### ISSUE TITLE
For safety reasons, how to disable Rpath/Runpath when compiling libjpeg.so and libturbojpeg.so

### ISSUE THREAD

**Issue by wangsc0355** [libjpeg-turbo/libjpeg-turbo#502]
Linux 64 bit，Android Platform，arm64

**Comment by dcommander** [comment]
What do you mean "for safety reasons"?

**Comment by wangsc0355** [comment]
Enabling the Rpath / RunPath link option will cause the binary feature to display the rpath / runpath path, and it will be easier for attackers to construct rpath attacks. Therefore, I need to disable the rpath / runpath link option

**Comment by dcommander** [comment]
This is the first link that comes up from googling “disable RPATH CMake”:

https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling

Seems like you could have found it just as easily as I did. I am happy to provide support for issues specific to libjpeg-turbo, to have a discussion about the tradeoffs associated with including an RPATH in our shared libraries, or to fix any issues in our build system that would prevent you from disabling RPATH, but imparting general Linux software development knowledge is not my job.
