### ISSUE TITLE
add_custom_target cannot create target "dist" because another target with   the same name already exists.

### ISSUE THREAD

**Issue by CharStiles** [libjpeg-turbo/libjpeg-turbo#504]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
no

**Clear and concise description of the bug:**
When also compiling as a git submodule in a project that also has the popular library [nng](https://github.com/nanomsg/nng) I get the error 
`
-- Building static libs
CMake Error at external/HoloPlayCore/libs/nng/CMakeLists.txt:478 (add_custom_tar
get):
  add_custom_target cannot create target "dist" because another target with
  the same name already exists.  The existing target is a custom target
  created in source directory
  "C:/Users/me/Desktop/my_project/my_project_api/external/libjpeg-turbo".

  See documentation for policy CMP0002 for more details.

-- Configuring incomplete, errors occurred!
`
**Steps to reproduce the bug (using *only* libjpeg-turbo):**
You can make a quick project where it has nng and libjpeg-turbo as a submodule and make a CMakeLists.txt where you 
`
include_directories(libjpeg-turbo)
add_subdirectory(libjpeg-turbo)
target_link_libraries(my_project libjpeg-turbo)

include_directories(nng)
add_subdirectory(nng)
target_link_libraries(my_project nng)
`

**Expected behavior:**
It compiles with no namespace errors, that libjpeg-turbo would have unique target names. 

**Observed behavior:**
it throws an error.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.28.29337.0
-- The CXX compiler identification is MSVC 19.28.29337.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/
2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the master branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
master

**Additional information:**
This is the policy in cmake referenced: https://cmake.org/cmake/help/v3.0/policy/CMP0002.html
If this isnt considered a bug  & wont be fixed- is there a workaround I can do? Thank you! Also sorry if there is something wrong on my end, I am new to cmake systems.

**Comment by dcommander** [comment]
It is impossible for a ubiquitous library such as libjpeg-turbo to handle all potential conflicts with downstream build systems.  I could change the name of our `dist` target, but what if the new name conflicts with a target in some other project?  You can find [numerous examples](https://github.com/libjpeg-turbo/libjpeg-turbo/issues?q=externalproject_add) of people asking me to support adding libjpeg-turbo into downstream projects with `add_subdirectory()` and just as many examples of me explaining why that is unsupportable.  Your choices are:

1. Use `ExternalProject_Add()` to include an unmodified libjpeg-turbo source tree.
2. Use `add_subdirectory()` and maintain whatever downstream libjpeg-turbo build system modifications that are necessary to make it work.  Please [do not expect any of those modifications to be accepted upstream](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/.github/CONTRIBUTING.md).

**Comment by dcommander** [comment]
Sorry if that came across as gruff.  Ever since migrating the build system from autotools to CMake, I've had numerous requests for this, and I don't understand why.  Irrespective of the build system, supporting the needs of downstream build systems in an upstream library (particularly one as popular as libjpeg-turbo) has never been feasible.

**Comment by CharStiles** [comment]
Gruff or not, thanks for answering my question! I appreciate it- now i know that this is considered a downstream support request :) I tried to find where libjepeg-turbo creates a dist target to change it in my code to just get it to work, but i couldnt find it anywhere! when i search dist in the repository nothing comes up.
