### ISSUE TITLE
jpeg_write_scanlines JERR_FILE_WRITE

### ISSUE THREAD

**Issue by XanaduAPI** [libjpeg-turbo/libjpeg-turbo#508]
I often run into JERR_FILE_WRITE errors when saving JPEG files.
I found that in empty_output_buffer, when saving the buffer to the file, it only determines whether fwrite is equal or not.
It also throws JERR_FILE_WRITE.
So, do you need to add a circular write to ensure that an exception is thrown only when something goes wrong? When the write is insufficient, let's continue trying to write.
Here is some of the code I saved.

---------- CXX ----------
	XANADU_CHECK_RETURN(_Picture, false);

	auto		vSync = false;
	auto		vLength = static_cast<unsigned long>(_Picture->_Width * _Picture->_Height * 4);
	auto		vMemory = XANADU_NEW unsigned char[vLength];

	XANADU_CHECK_RETURN(vMemory, false);
	Xanadu::memset(vMemory, 0, vLength);

	auto		vHandle = jpeg_compress_struct();
	auto		vError = jpeg_error_mgr();
	vHandle.err = jpeg_std_error(&vError);
	jpeg_create_compress(&vHandle);
	jpeg_mem_dest(&vHandle, &vMemory, &vLength);
	//jpeg_stdio_dest(&cinfo, vFile);
	vHandle.err->error_exit = HandlePictureJpegError;
	vHandle.image_width = _Picture->_Width;
	vHandle.image_height = _Picture->_Height;
	vHandle.input_components = 3;
	vHandle.in_color_space = JCS_RGB;

	jpeg_set_defaults(&vHandle);
	jpeg_set_quality(&vHandle, 100, TRUE);
	jpeg_start_compress(&vHandle, TRUE);

	//保存Exif
	if(_Picture->_Exif.size() > 4)
	{
		jpeg_write_marker(&vHandle, JPEG_APP0 + 1, (const JOCTET*)((_Picture->_Exif.data()) + 4), static_cast<unsigned int>(_Picture->_Exif.size() - 4));
	}

	//保存ICC
	if(_Picture->_ICC.size() > 0)
	{
#ifdef XANADU_SYSTEM_WINDOWS
		jpeg_write_icc_profile(&vHandle, (const JOCTET*)_Picture->_ICC.data(), (unsigned int)_Picture->_ICC.size());
#endif // XANADU_SYSTEM_WINDOWS
	}

	//申请图像内存
	auto		vRGB = XPicture::RGBA_RGB(_Picture->_RGBA);
	auto		vRow = XANADU_NEW JSAMPROW[sizeof(JSAMPROW) * _Picture->_Height];
	for(auto vIndex = 0U; vIndex < _Picture->_Height && vRow; vIndex++)
	{
		vRow[vIndex] = XANADU_NEW JSAMPLE[_Picture->_Width * 3];
		if(vRow[vIndex])
		{
			Xanadu::memcpy(vRow[vIndex], vRGB.data() + (vIndex * _Picture->_Width * 3), _Picture->_Width * 3);
		}
	}
	vSync = true;
	while(vHandle.next_scanline < vHandle.image_height)
	{
		vHandle.err->msg_code = 0;
		jpeg_write_scanlines(&vHandle, &vRow[vHandle.next_scanline], 1);
		if(vHandle.err->msg_code != 0)
		{
			vSync = false;
			break;
		}
	};
	jpeg_finish_compress(&vHandle);
	jpeg_destroy_compress(&vHandle);

	auto		vFile = XFileSystem::FileOpen(_File, L"wb");
	if(vFile)
	{
		XFileSystem::FileWrite(vFile, vMemory, vLength);
		XFileSystem::FileClose(vFile);
	}
	XANADU_DELETE_ARR(vMemory);
	//释放图像内存
	for(auto vIndex = 0U; vIndex < _Picture->_Height && vRow; vIndex++)
	{
		XANADU_DELETE_ARR(vRow[vIndex]);
	}
	XANADU_DELETE_ARR(vRow);
	return vSync;

---------- CXX ----------

When I replace jpeg_mem_dest with jpeg_stdio_dest, and other memory operations with file operations, I'm always told I'm out of space. But my SSD has a terabyte of space left.

**Comment by dcommander** [comment]
The stdio destination manager has been mostly unchanged for 25 years, and no major issues have been discovered with it in that timeframe.  Thus, my best guess is that your code is not using the feature correctly.  However, I have no way to diagnose that issue using an isolated code snippet that contains no other context, nor is it my responsibility to do so.  cjpeg contains a working example of using the stdio destination manager.  I would suggest comparing your usage to that of cjpeg and figuring out what is different.  Since cjpeg is quite stable, the issue will most likely be related to those differences.
