### ISSUE TITLE
Missing Huffman code table entry error with certain scan configurations

### ISSUE THREAD

**Issue by MegaByte** [libjpeg-turbo/libjpeg-turbo#509]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes, however, it is similar to #335 

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No

**Clear and concise description of the bug:**
Certain scan configurations do not work on certain images, instead returning the error: Missing Huffman code table entry

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
Run jpegtran with this scan file and the following image:
```
0 1 2: 0 0 0 9;
0: 10 41 0 2;
0: 10 41 2 1;
```

**Image(s) needed in order to reproduce the bug (if applicable):**
https://cloud.githubusercontent.com/assets/11577741/24460119/4f5f0160-146b-11e7-98e7-20c111d0ffac.jpg

**Expected behavior:**
JPEG is processed and output with desired scans.

**Observed behavior:**
Error returned: Missing Huffman code table entry

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
Windows 10 x64 (official VC builds)

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the master branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
Releases 1.5.90 - current (2.0.3 as of this writing)

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**
5b177b3cab5cfb661256c1e74df160158ec6c34e

**Additional information:**
Discovered in MegaByte/jpegultrascan#2

**Comment by dcommander** [comment]
@mayeut Any ideas?  The issue was actually introduced in 16bd984557fa2c490be0b9665e2ea0d4274528a8, and I have no clue how to fix it.  It appears to exist in the SSE2 implementation but not the C implementation (setting `JSIMD_FORCENONE=1` in the environment makes it go away.)  I haven't tested the Neon implementation yet.

**Comment by MegaByte** [comment]
A little bit more exploration found that this also occurs when a scan is included with:
10 <= Ss <= 18
Se = Ss + 31
Ah = 2
Al = 1

The 31 requirement might be a hint...

**Comment by dcommander** [comment]
Integrated into master and 2.0.x branches.  I also confirmed that the issue did not exist with the Neon implementation.
