### ISSUE TITLE
Uninstall issue

### ISSUE THREAD

**Issue by weihohoho** [libjpeg-turbo/libjpeg-turbo#511]
I delete the whole file without using the uninstall.exe

Now the installer keeps warning  
"An existing version of the libjpeg-turbo SDK.... is already installed. Please uninstall it first."

How could I solve such problem please?

**Comment by weihohoho** [comment]
Problem resolved. Just get an uninstall.exe from another PC shall solve the problem.

**Comment by dcommander** [comment]
For future reference, the best way to resolve that issue is to delete **c:\windows\system32\turbojpeg.dll**.

**Comment by dcommander** [comment]
Also, in the future, please do not assign the "bug" label unless you are sure it is a libjpeg-turbo bug.  Deleting the software manually and then being surprised that the uninstaller no longer works is not a bug.

**Comment by weihohoho** [comment]
Thank you very much for the help and sorry for getting a mess in the labels.
