### ISSUE TITLE
Build fails with WITH_SIMD=OFF and ENABLE_SHARED=ON

### ISSUE THREAD

**Issue by clbr** [libjpeg-turbo/libjpeg-turbo#520]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes. Nothing in open or closed ones.

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No.

**Clear and concise description of the bug:**
The build fails if you configure it as a shared library, but disable simd.

```
[ 11%] Linking C shared library ../libjpeg.so
/usr/bin/ld: ../CMakeFiles/simd.dir/jsimd_none.c.o: relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
../CMakeFiles/simd.dir/jsimd_none.c.o: error adding symbols: Bad value
collect2: ld returned 1 exit status
```

And indeed, there is no -fPIC passed to jsimd_none.c.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
Configure as a shared library but disable simd.

**Image(s) needed in order to reproduce the bug (if applicable):**

**Expected behavior:**
Build succeeds.

**Observed behavior:**
Build fails.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
Linux, gcc 10.2, x86_64

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
a219fd13b086d9af or today's git

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

**Comment by dcommander** [comment]
Can't reproduce on Ubuntu 20.04:

```
git clone https://github.com/libjpeg-turbo/libjpeg-turbo.git
cd libjpeg-turbo
mkdir build
cd build
cmake -DENABLE_SHARED=ON -DWITH_SIMD=OFF -DCMAKE_C_COMPILER=gcc-10 ..
make
```

**Comment by clbr** [comment]
I configured cmake using the curses gui, ccmake. It's possible some other option interferes (or it's a cmake bug, my cmake version is 3.20.2). How do I share my config result with you?

**Comment by dcommander** [comment]
As long as you performed both the configuration and generation steps using ccmake, the build should still work properly.  ccmake is just invoking cmake behind the scenes.

Please attach CMakeCache.txt from your build directory.

**Comment by clbr** [comment]
https://termbin.com/z9xv

**Comment by dcommander** [comment]
This might be the issue:

```
//A wrapper around 'ar' adding the appropriate '--plugin' option
// for the GCC compiler
CMAKE_C_COMPILER_AR:FILEPATH=CMAKE_C_COMPILER_AR-NOTFOUND

//A wrapper around 'ranlib' adding the appropriate '--plugin' option
// for the GCC compiler
CMAKE_C_COMPILER_RANLIB:FILEPATH=CMAKE_C_COMPILER_RANLIB-NOTFOUND
```

The `ar` and `ranlib` programs weren't found on your system.  Other than that, I've exactly reproduced your build-- same GCC and CMake versions, same **CMakeCache.txt** (except pointing to my home directory rather than yours), and it works fine for me.

**Comment by clbr** [comment]
I believe that's because Ubuntu changes the gcc defaults. They enable fPIC by default. Please build with VERBOSE=1 and see if your cmake makefile is passing -fPIC to jsimd_none.c. It is not for me, and my gcc is with upstream defaults.

https://cmake.org/pipermail/cmake/2012-June/050951.html
Old link to cmake ml with the same issue, saying you must not use OBJECT libraries in a SHARED library unless you set POSITION_INDEPENDENT_CODE on them. That was the 2.8 cmake era, not sure if it's changed.

**Comment by dcommander** [comment]
`-fPIC` is not being passed to the compiler when building **jsimd_none.c**.

```
[  5%] Building C object CMakeFiles/simd.dir/jsimd_none.c.o
/usr/bin/gcc-10  -I/home/drc/src/libjpeg-turbo/build -I/home/drc/src/libjpeg-turbo -O3 -march=nocona -mtune=k8 -pipe -fomit-frame-pointer -O3 -DNDEBUG -MD -MT CMakeFiles/simd.dir/jsimd_none.c.o -MF CMakeFiles/simd.dir/jsimd_none.c.o.d -o CMakeFiles/simd.dir/jsimd_none.c.o -c /home/drc/src/libjpeg-turbo/jsimd_none.c
```

It is, however, being passed to the linker when linking the libjpeg API shared library:
```
[ 67%] Linking C shared library ../libjpeg.so
cd /home/drc/src/libjpeg-turbo/build/sharedlib && /opt/cmake3/bin/cmake -E cmake_link_script CMakeFiles/jpeg.dir/link.txt --verbose=1
/usr/bin/gcc-10 -fPIC -O3 -march=nocona -mtune=k8 -pipe -fomit-frame-pointer -O3 -DNDEBUG -Wl,--version-script,/home/drc/src/libjpeg-turbo/build/sharedlib/../libjpeg.map -Wl,-O1 -shared -Wl,-soname,libjpeg.so.62 -o ../libjpeg.so.62.3.0 CMakeFiles/jpeg.dir/__/jcapimin.c.o CMakeFiles/jpeg.dir/__/jcapistd.c.o CMakeFiles/jpeg.dir/__/jccoefct.c.o CMakeFiles/jpeg.dir/__/jccolor.c.o CMakeFiles/jpeg.dir/__/jcdctmgr.c.o CMakeFiles/jpeg.dir/__/jchuff.c.o CMakeFiles/jpeg.dir/__/jcicc.c.o CMakeFiles/jpeg.dir/__/jcinit.c.o CMakeFiles/jpeg.dir/__/jcmainct.c.o CMakeFiles/jpeg.dir/__/jcmarker.c.o CMakeFiles/jpeg.dir/__/jcmaster.c.o CMakeFiles/jpeg.dir/__/jcomapi.c.o CMakeFiles/jpeg.dir/__/jcparam.c.o CMakeFiles/jpeg.dir/__/jcphuff.c.o CMakeFiles/jpeg.dir/__/jcprepct.c.o CMakeFiles/jpeg.dir/__/jcsample.c.o CMakeFiles/jpeg.dir/__/jctrans.c.o CMakeFiles/jpeg.dir/__/jdapimin.c.o CMakeFiles/jpeg.dir/__/jdapistd.c.o CMakeFiles/jpeg.dir/__/jdatadst.c.o CMakeFiles/jpeg.dir/__/jdatasrc.c.o CMakeFiles/jpeg.dir/__/jdcoefct.c.o CMakeFiles/jpeg.dir/__/jdcolor.c.o CMakeFiles/jpeg.dir/__/jddctmgr.c.o CMakeFiles/jpeg.dir/__/jdhuff.c.o CMakeFiles/jpeg.dir/__/jdicc.c.o CMakeFiles/jpeg.dir/__/jdinput.c.o CMakeFiles/jpeg.dir/__/jdmainct.c.o CMakeFiles/jpeg.dir/__/jdmarker.c.o CMakeFiles/jpeg.dir/__/jdmaster.c.o CMakeFiles/jpeg.dir/__/jdmerge.c.o CMakeFiles/jpeg.dir/__/jdphuff.c.o CMakeFiles/jpeg.dir/__/jdpostct.c.o CMakeFiles/jpeg.dir/__/jdsample.c.o CMakeFiles/jpeg.dir/__/jdtrans.c.o CMakeFiles/jpeg.dir/__/jerror.c.o CMakeFiles/jpeg.dir/__/jfdctflt.c.o CMakeFiles/jpeg.dir/__/jfdctfst.c.o CMakeFiles/jpeg.dir/__/jfdctint.c.o CMakeFiles/jpeg.dir/__/jidctflt.c.o CMakeFiles/jpeg.dir/__/jidctfst.c.o CMakeFiles/jpeg.dir/__/jidctint.c.o CMakeFiles/jpeg.dir/__/jidctred.c.o CMakeFiles/jpeg.dir/__/jquant1.c.o CMakeFiles/jpeg.dir/__/jquant2.c.o CMakeFiles/jpeg.dir/__/jutils.c.o CMakeFiles/jpeg.dir/__/jmemmgr.c.o CMakeFiles/jpeg.dir/__/jmemnobs.c.o CMakeFiles/jpeg.dir/__/jaricom.c.o CMakeFiles/jpeg.dir/__/jcarith.c.o CMakeFiles/jpeg.dir/__/jdarith.c.o ../CMakeFiles/simd.dir/jsimd_none.c.o  -Wl,-rpath,:::::::::::::::::::::: 
```
I understand your point.  When **libsimd.a** is generated from the SIMD sources, the libjpeg-turbo build system enables PIC if shared libraries are enabled:

```
if(CMAKE_POSITION_INDEPENDENT_CODE OR ENABLE_SHARED)
  set_target_properties(simd PROPERTIES POSITION_INDEPENDENT_CODE 1)
endif()
```

It would make sense that the build system should do that when **libsimd.a** is generated from **jsimd_none.c** as well, but in practice, I still can't reproduce any issues stemming from the current behavior.

**Comment by clbr** [comment]
You can't reproduce because you're using Ubuntu's changed gcc. The missing fPIC to that file will cause issues on any "standard" gcc.

**Comment by clbr** [comment]
IOW, it's not enough to pass -fPIC to the linker, if any of the source files was compiled without. It results in the linker relocation error I quoted above. Ubuntu happens to have changed defaults so their file is position-independent even without the option.

**Comment by clbr** [comment]
Here's how you can confirm for yourself the change in defaults.

touch empty.c
gcc -S -fverbose-asm empty.c
grep -ie -fp empty.s

**Comment by dcommander** [comment]
My testing does not support your conclusions.  I tried:
- GCC 9.3.0 and 10.2.0 on Ubuntu 20.04
- GCC 4.8.5 and 8.3.1 on CentOS 7
- GCC 10.2.1 on Fedora 33

You are correct that both versions of GCC on Ubuntu 20.04 automatically add `-fPIC` and `-fPIE`, but none of the GCC versions on CentOS or Fedora do that.  And yet building with `-DWITH_SIMD=0 -DENABLE_STATIC=0` (`ENABLE_SHARED=1` is the default) works fine in all cases, even though `-fPIC` is not being passed to the compiler when building **jsimd_none.c**.

I am not opposed to modifying the build system, but I first want to solve this mystery.

**Comment by clbr** [comment]
Can you reopen the ticket while the investigation lasts?

When exactly gcc generates that relocation is not something I know about. That's gcc internals.

**Comment by dcommander** [comment]
I don't know anything about it either.  But so far, you're the only person who has reported this issue.  I minimally need to understand the reproduction mechanism so I can document the scope of the issue and its fix.  The fact that the issue doesn't reproduce on Ubuntu and non-Ubuntu flavors of GCC 10.2 suggests that there is something special about your flavor of GCC, so please help me understand what that something is.

**Comment by clbr** [comment]
I've verified clang 2.9 reproduces, but clang 3.1 does not.

I believe the main thing is clear - shared library objects should be compiled with -fPIC. The file here is getting away with not doing so for some reason, could be because it's so small, and whether such a small file triggers things depends on which relocation type happens to be chosen for the symbols in there. Just my guess so far.

**Comment by clbr** [comment]
https://termbin.com/w4ad

Yes, this theory has some support. When I add some code to the file with the above patch, it then fails with clang 3.1 too.
