### ISSUE TITLE
Improving Huffman Decoder, by using lookup tables for small AC coefficients

### ISSUE THREAD

**Issue by etemesi254** [libjpeg-turbo/libjpeg-turbo#525]
Hey there..

The Huffman Decoder is fast and props to that, 
but i found out other libraries like [stb_image.h](https://github.com/nothings/stb/blob/master/stb_image.h) and a Rust [jpeg-decoder](https://github.com/image-rs/jpeg-decoder)  build a table for small ac coefficients that decodes the value and  does an equivalent of receive_extend

For the Rust library, the code is [here](https://github.com/image-rs/jpeg-decoder/blob/ab6d326a7b194568725731a19603fb580814452d/src/huffman.rs#L217)

For the C library its [here](https://github.com/nothings/stb/blob/ea2f937a01ce39795ab02b6c6e30173b4f1ed46c/stb_image.h#L1986)

I thought it might offer a speed up since using the lookup table would be faster( for small AC coefficients) than the method currently in use

So I tried implementing it(by adding some code in `make_d_derived_tbl`) and I came up with...
```c
if (!is_dc){
   int i,s;
    int fast_ac[1<<HUFF_LOOKAHEAD];
   // Zero all the values, during decoding , value 0 will indicate not found
   memset(fast_ac,0,(1<<(HUFF_LOOKAHEAD)*sizeof(fast_ac[0]));
   for (i =0;i<(1<<HUFF_LOOKAHEAD);++i){
           s = dtbl->lookup[i];
           /* l-> current code length */
           int l =  s >> HUFF_LOOKAHEAD;
          /* If code length is smaller than HUFF_LOOKAHEAD, build a table which decodes both magnitue and value of small AC's in one go*/
           if (l<HUFF_LOOKAHEAD){
                /*s->code values*/
               s =s &((1<<HUFF_LOOKAHEAD)-1);
               int run_length = s >>4;
               int  magnitude = s & 15;
               // end of my thoughts
           }
     }
}
```
The above code is the same as the initial steps the function decode_mcu_fast does
when [decoding ac coefficients](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/5135c2e25d923b3737a92a686b124759883dd209/jdhuff.c#L692) up until line 695 (when the AC coefficient is small enough to be stored in the lookup table) 

During AC decoding, i thought of the following change
1. Implement `HUFF_DECODE_AC` macro
2. In the macro
```c
// copying from HUFF_DECODE macro
s = PEEK_BITS(HUFF_LOOKAHEAD); \
s = htbl->lookup[s]; \
nb = s >> HUFF_LOOKAHEAD; \ 
 s = s & ((1 << HUFF_LOOKAHEAD) - 1); \
/* If the bits are less than HUFF_LOOKAHEAD 
* we can check our fast_ac table
*/
if (nb < HUFF_LOOKAHEAD){ \
    int r = htbl->ac_lookup[s];\ 
  
   if (r !=0){\
   /* some cool bit shifts to extract value and number of bits to drop*/
   DROP_BITS(number_of_bits_needed_for_ac)\
   (*block)[jpeg_natural_order[k]]=(JCOEF)s;\
   } 
}
/* The value is too large to store in the fast_ac table
*lets do the normal way 
*/
else{ \
/* Continue with the normal way of decoding AC values */
s = (get_buffer >> bits_left) & ((1 << (nb)) - 1); \ 
}\ 
```

But then I could not wrap my head on how to implement the `receive_extend` to make the `fast_ac` table   and I thought that I might reach out for help because you wrote the initial implementation and understand it way better than me and also before I choose to go the dark path (mixing this code with another implementation to "make it work").

So I'm reaching out, hoping to see if maybe this can be implemented,(or maybe if it can cause regressions, why it should not be implemented)

# TL_DR/ TL_DU

Can there be an implementation of an ac lookup table that contains values for small AC coefficients which can be read instead of going the long step currently in use?

**Comment by dcommander** [comment]
Tom Lane wrote the initial implementation in the 1990s.  I mostly just optimized it.  Because the Huffman decoder is usually the first code that gets executed when decompressing an arbitrary JPEG image (which can be malformed), that decoder has historically been the source of most of the security issues that have been found in libjpeg-turbo.  Now that libjpeg-turbo is fully integrated with OSS-Fuzz, such issues are a lot easier to detect before they are released into the wild, but I am still loathe to modify the Huffman decoder unless doing so would produce a compelling overall speedup (it would need to be at least 15% across a broad range of test images in order to justify the inevitable disruption to the stability of the libjpeg-turbo code base.)

If you or someone else can figure out the necessary algorithmic changes and submit a PR that provides a compelling overall speedup, then I will consider it for a future major release of libjpeg-turbo, but I don't personally have the resources to work on such a feature unless an organization is specifically paying for my labor to do so.

**Comment by etemesi-ke** [comment]
Update: Figured out how to integrate it but not sure of where to store the array, basically now I have it inside the `Derived_tbl` struct which I am thinking it's wasteful for structs holding dc tables since it allocates memory regions we don't use.

Probably thinking the tables can be moved to cinfo struct and read from there. 

I will file a pr only affecting baseline decoding and (progressive decoding will follow when I understand what's happening) 
in a few hours

**Comment by dcommander** [comment]
Adding to the cinfo struct is definitely not allowed, since that struct is exposed and thus part of the ABI.  I would suggest storing the table in the `huff_entropy_decoder` struct.

**Comment by dcommander** [comment]
Do not close issues until they are resolved.

**Comment by etemesi-ke** [comment]
Sorry closed it because I figured it would take some time before the issues on my side are resolved

**Comment by C-A-E** [comment]
Quick update, it works for un-sampled baseline images, the rest crash(weird memory errore) so i'll file a PR once i fix it

**Comment by etemesi254** [comment]
Quick question, is it fine if i put it in the `d_derived_tbl` struct and use a null pointer for DC tables? Because extending `huff_entropy_decoder` is crazily hard, and matching an AC table to the lookup table is something i come to view as an impossibility(eg the Y AC lookup may be used by the CB AC leading to images as below)
![A very cool but not effective image](https://user-images.githubusercontent.com/24320659/127977790-0ec4d0bf-2a62-4d2c-9e66-aa6bea1630a3.jpg)
for this image ![Mr Lee](https://github.com/elementary/wallpapers/raw/master/backgrounds/Mr.%20Lee.jpg)

**Comment by dcommander** [comment]
I don't understand why you say that extending `huff_entropy_decoder` is "crazily hard".  Please explain.

**Comment by etemesi254** [comment]
Okay from this gist of the now modified [jduff.c](https://gist.github.com/etemesi254/d6db68e2032372331c71464ce3608d90), the PR I'm working on starts at line 256 , the new AC decoding routine looks like [this](https://gist.github.com/etemesi254/3afc8d1066596c2bd515d1d04cf1222b),
If a coefficient exist( for small AC tables, which should be many as is the point of huffman coding), we eliminate the code from line 22-55, which when macro expansion occurs becomes a lot.. 

## But on to issues 
My problems start at line 271

-  We `tblno` is not a consistent way to know which AC table we s are in, typically I found out (the hard way) it returns values as (0,1,1) for a YCbCr image, which I really don't understand why this is bad because then the tables will point to the wrong values, the `Cr` table will overwrite the `Cb` table
     - This can be solved easily, lets use `ci` (line 101) and pass that to `jpeg_make_d_derived_tbl` since its unique for every table and it works(it goes 0,1,2),

The other problem is now what really makes me question my existence
- Heading to `decode_mcu_fast`, `cinfo->blocks_in_MCU` says there are four blocks for a sub-sampled image [Y(2,1),Cb(1,1),Cr(1,1)], how can I work around that? I have no idea, but i try, and that doesn't look pretty, the Y AC  will be iterated twice, but how can I reflect that? I have no idea, assuming the iteration proceeds as `0`,`1`,`2`,`3` ; `0` and `1` iterations  represent Y AC table, stored at `entropy->ac_tbls[0]` but the code on the second iteration will fetch the table for `Cb`, and probably end up with a wrong value, but that isn't even the worst case
    - There is no `entropy->ac_tables[3]`, we never initialized it, we are now entering uninitialized memory, values we get start to be erratic, unpredictable, crazy,
        
     -   I look into the Image, I am testing, I'm getting errors, the previous image with no sub-sampling, perfect, this one, what magic is this?, I try images in random, some work some I'm getting green pixelated matrix images, I conclude I must have done something painfully wrong, do a fresh fetch and restart, the same thing, start putting `printf` statements everywhere and questioning my existence,plug in `Valgrind`, it tells me uninitialized memory, a few days of debugging and a lot of cussing, it hits me, down-sampled images have a different number of blocks per MCU,`blocks_in_MCU` is a bad index to the fast AC table, and my faith is restored in myself, 
          
   
 And I realize that probably i should just have extended a `d_derived_tbl` to save me from all of this, because I know I will get the right table for the right component no matter what sub-sampling ratio an image is in.

**Comment by dcommander** [comment]
In practice, most JPEG images are encoded using the "sample" Huffman tables from the spec, in which the same table is reused for Cb and Cr.  Refer to **jstdhuff.c**.

That block layout is correct for 4:2:2 subsampling.  Bearing in mind that the JPEG codec operates on 8x8 blocks at the low level, an MCU ("minimum coded unit") represents the smallest possible set of 8x8 blocks that can produce a full set of upsampled pixels.  Since the chrominance components are subsampled 2x horizontally, you need two luminance blocks for every chrominance block.

Unfortunately I don't really understand most of your other comments, as they are buried in the weeds of an issue that I have yet to dig into.  I'm sorry that I can't be of more help.  I have no funding at the moment to look into this, and no funding for an independent open source developer means no time.

**Comment by etemesi254** [comment]
Sorry if my comments sounded a bit insane.

Okay i'll use 4:2:2 subsampling. the MCU's are in the order

`Y Y Cb Cr` 

The loop [at `decode_mcu_fast`](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/4c313544e2a030e95567246047652f9aabf7b394/jdhuff.c#L675)  will iterate 4 times. and `blkn` will go from 0 to 3

But the fast AC tables have been stored in the following order

0->Y
1->Cb
2->Cr

When using `blkn` to refer to my fast AC table, when `blkn` is zero
We use the `Y` table. 

When it increments to 1, it uses the `Cb` table even though we are still decoding data for the `Y` table.

Now the painful thing about bitstream decoding is that if you get one thing wrong everything goes wrong because bit positions become messed and you essentially start decoding the wrong values

If the `Cb` lookup table may say we consume 5 bits but the `Y`  table would have said 7 bits, so we are at the wrong offset.

When we get to the third iteration and do `entropy->ac_tables[3]`, we essentially never initialized a table here(our tables are in 0..2) and so we are playing with uninitialized memory (`Valgrind` catches this). Therefore the computer gives us whatever data it feels like

I had suggested modifying `d_derived_tbl`  struct because I know that your loop will always (magically) return the correct table no matter the sub-sampling/number of iterations `blkn` will go through. and therefore it would just be a matter of accessing the fast ac table but due to ABI incompatibilities and honestly I can't see a way forward


And I hope your funding issue will one day be sorted, honestly if I could I would donate, because you are doing an amazing job, but I'm a university kid in a third world country who thought that a cool way to keep himself busy is to write fast image decoders(currently stuck on [jpeg](https://github.com/etemesi254/zune-jpeg) decoding, the interesting part is the [benchmarks page](https://github.com/etemesi254/zune-jpeg/blob/master/Benches.md).

And after borrowing parts and concepts from those open source decoders(like the `refill_bit_buffer`, strategy and `stb_image.h` accelerated Huffman decoding), I thought I might suggest an enhancement here. 

Which we know it's not going well

**Comment by dcommander** [comment]
You have to use `cinfo->MCU_membership[blkn]` to determine the appropriate component index for a given MCU block index.
