### ISSUE TITLE
How to build static library libjpeg for ARM32bit (armv_7a)

### ISSUE THREAD

**Issue by qaziullah** [libjpeg-turbo/libjpeg-turbo#530]
I need to build libjpeg static library libjpeg.a for ARM 32bit (architecture ARM V7A). I am using Ubuntu on virtual box (oracle) and my machine is 64bit. I have cloned the github directory name libjpeg-turbo for this purpose but don't know how to build libjpeg.a from this.

Any help would be appreciated.

Note: I want to build libjpeg.a for the target device ARM cortex-A9 (ARMV-7A 32bit architecture) present on Intel SOC FPGA board. I am running linux on arm.
Also I am new to LIBJPEG so kinldy guide me.

**Comment by dcommander** [comment]
**libjpeg.a** is built by default.  Please refer to https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/BUILDING.md#build-procedure.
