### ISSUE TITLE
Auto create symlink file .so to /lib64

### ISSUE THREAD

**Issue by jazz1611** [libjpeg-turbo/libjpeg-turbo#532]
hello,

i have build libturbo-jpeg to rpm and it install success to other machine CentOS 7 but need create symlink file `/opt/libjpeg-turbo/lib64/libturbojpeg.so` manually to `/lib64/libturbojpeg.so`. did you know how it make auto create symlink that file in RPM?

Link RPM: https://xfl.jp/j2tyZb

regards,

**Comment by jazz1611** [comment]
hello,

i have other build with this command `cmake -G"Unix Makefiles" -DCMAKE_INSTALL_LIBDIR=/lib64/ && make rpm`. but it failed install in other machine CentOS 7

Link other RPM: https://xfl.jp/j5yiKs

```
[root@dev-aapanel ~]# rpm -ivh libjpeg-turbo-2.1.0.x86_64_lib64.rpm
Preparing...                          ################################# [100%]
        file /lib64 from install of libjpeg-turbo-2.1.0-20210707.x86_64 conflicts with file from package filesystem-3.2-25.el7.x86_64
[root@dev-aapanel ~]#
```
Regards,

**Comment by dcommander** [comment]
I just pushed a commit that will allow you to set `CMAKE_INSTALL_LIBDIR=/usr/lib64` and generate an RPM that does not conflict with the Red Hat `filesystem` RPM.

**Comment by jazz1611** [comment]
@dcommander 
hello,
i builded with your recommand command and it install fine in other machine CentOS 7 without create symlink there library. thank you.
regards,
