### ISSUE TITLE
Size passed to jpeg_free_large is not same as was passed to jpeg_get_large

### ISSUE THREAD

**Issue by zavadovsky** [libjpeg-turbo/libjpeg-turbo#542]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No

**Clear and concise description of the bug:**
Size passed to jpeg_free_large is different from size passed to jpeg_get_large for same address

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
Override jpeg_get_large and jpeg_free_large with such code:
```
void FAR * jpeg_get_large (j_common_ptr cinfo, size_t size)
{
	void FAR* ret = malloc(size);
	printf("jpeg_get_large(%u): %p", size, ret);
	return ret;
}

void __wrap_jpeg_free_large (j_common_ptr cinfo, void FAR *object, size_t size)
{
	printf("jpeg_get_large(%p, %d)", object, size);
	free(object);
}
```
Decode any image and see logs.
Typical output will be:
```
jpeg_get_large(299): 0x50fa85d8
jpeg_get_large(299): 0x50f894f0
jpeg_get_large(1323): 0x50fc58d8
jpeg_get_large(2603): 0x50f6f940
jpeg_get_large(683): 0x50faea00
jpeg_get_large(683): 0x50fa4a98
jpeg_get_large(363): 0x50fce8c0
jpeg_free_large(0x50fce8c0, 332)
jpeg_free_large(0x50fa4a98, 652)
jpeg_free_large(0x50faea00, 652)
jpeg_free_large(0x50f6f940, 2572)
jpeg_free_large(0x50fc58d8, 1292)
jpeg_free_large(0x50f894f0, 268)
jpeg_free_large(0x50fa85d8, 268)
```

**Image(s) needed in order to reproduce the bug (if applicable):**
All images I got.

**Expected behavior:**
jpeg_free_large is called using same size as was passed to jpeg_get_large

**Observed behavior:**
Size passed to jpeg_free_large is 31 byte lesser than size passed to jpeg_get_large

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
GCC-6.3, Linux 3.10.x-4.4.x, MIPS, ARM

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
v2.0.2
I saw history for jmemmgr.c - it wasn't changed since 2.0.2

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**
Unknown

**Additional information:**
I did some research in code and found this in alloc_large:
```
  hdr_ptr = (large_pool_ptr)jpeg_get_large(cinfo, sizeofobject +
                                           sizeof(large_pool_hdr) +
                                           ALIGN_SIZE - 1); // +31 on my systems
  ...
  hdr_ptr->bytes_used = sizeofobject;
  hdr_ptr->bytes_left = 0;
```

and opposite code in free_pool:
```
    space_freed = lhdr_ptr->bytes_used +
                  lhdr_ptr->bytes_left +
                  sizeof(large_pool_hdr);
    jpeg_free_large(cinfo, (void *)lhdr_ptr, space_freed); // (ALIGN_SIZE - 1) wasn't added here
  }
```

Don't know whole logic but currently I suppose that here is some error.
May be I'm wrong.

**Comment by dcommander** [comment]
This seems to be an oversight from 5557fd221, code that has existed in libjpeg-turbo since the very beginning (the code in question ensures proper alignment for our SIMD-accelerated implementations of libjpeg algorithms.)  The issue is innocuous, since the default memory manager ignores the size argument.  Do you actually need to use that size argument in your implementation?

**Comment by zavadovsky** [comment]
> Do you actually need to use that size argument in your implementation?

The main LOL was that we really had small memory manager for JPEG decoding and this manager had relyed on size argument of  jpeg_free_large to limit total memory amount used by libjpeg-turbo.
And this "manager" was our "legacy" - was written many years ago and its author has used size argument - for unknown reason for me.

Currently I rewrote this our stuff and we don't use size argument anymore.
So this bug doesn't affect us now.

But maybe someone else still continue to use it?

**Comment by dcommander** [comment]
This is the first complaint I've received about it in the 11-year history of this project.  Even the legacy memory managers in libjpeg ignored the size argument to `jpeg_free_*()`.  That being said, the fix was trivial, so I went ahead and fixed it.

**Comment by zavadovsky** [comment]
> That being said, the fix was trivial, so I went ahead and fixed it.

Thanks!
