### ISSUE TITLE
jpeg decode misalignment between libturboJpeg and libjpeg-9c

### ISSUE THREAD

**Issue by tilaba** [libjpeg-turbo/libjpeg-turbo#544]
the decoded pixels are not totally same when jpg pictures are decoded by libturboJpeg( libjpeg-8c.) and libjpeg-9c.? how to solve it

![image](https://user-images.githubusercontent.com/31062802/130357774-a23e5f3e-fa1d-450a-b6c5-11e927945a7c.png)

**Comment by dcommander** [comment]
Please see https://github.com/libjpeg-turbo/libjpeg-turbo#mathematical-compatibility. There are only limited circumstances under which libjpeg-turbo can be expected to generate bitwise-compatible output relative to libjpeg v7 and later. libjpeg-turbo generates bitwise-compatible output relative to libjpeg v6b in most cases. The suite of regression tests that runs every time a commit is pushed confirms that the various algorithms in libjpeg-turbo are generating the expected output.
