### ISSUE TITLE
tjDecompressToYUVPlanes returns -1 even if just a warning occurs

### ISSUE THREAD

**Issue by Ziriax** [libjpeg-turbo/libjpeg-turbo#548]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

Yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

No

**Clear and concise description of the bug:**

`tjDecompressToYUVPlanes` seems to return -1 when a warning occurs, even when the `TJFLAG_STOPONWARNING` flag is not passed.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

Call `tjDecompressToYUVPlanes` on any JPEG that emits a warning. 

**Image(s) needed in order to reproduce the bug (if applicable):**

Any JPEG that emits a warning

**Expected behavior:**

`tjDecompressToYUVPlanes` should return 0 when a warning occurs, unless `TJFLAG_STOPONWARNING` is passed. Another flag could be added to make this more explicit.

**Observed behavior:**

`tjDecompressToYUVPlanes` returns `-1` when a warning occurs.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

Any

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

2.1.1

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

**Comment by dcommander** [comment]
Referring to the [TurboJPEG API documentation](https://cdn.rawgit.com/libjpeg-turbo/libjpeg-turbo/main/doc/html/group___turbo_j_p_e_g.html), a warning is a type of error, so both errors and warnings cause the API functions to return -1 or NULL.  `TJFLAG_STOPONWARNING` just causes the underlying codec to stop processing the image as soon as a warning is encountered.  In other words, it causes non-fatal errors to be treated as fatal errors.
