### ISSUE TITLE
Crop failure with 4:4:4 image

### ISSUE THREAD

**Issue by arc6011** [libjpeg-turbo/libjpeg-turbo#549]
I have encountered an error in cropping a set of 4:4:4 images using the latest version (2.1.1).

My utility performs the following steps related to cropping :
1. reads the source image from file into memory
2. gets the image attributes by calling tjDecompressHeader3()
3. constrains the cropping x, y, width, and height by the MCU alignment
4. crops the image by calling tjTransform()

tjDecompressHeader3() on these images writes 0 (zero) to the address of the _jpegSubsamp_ argument. However, even though the dimensions are coerced into 8-pixel alignment, tjTransform() fails with the error "To crop this JPEG image, x must be a multiple of 8 and y must be a multiple of 16."

The jpegtran utility performs the cropping using the same dimensions on these same images without error.

I've attached one of the images. It is intentionally blank, but it is a valid example of an image being processed. The cropped dimensions being used:
x = 248
y = 216
w = 472
h = 424

![0000000001](https://user-images.githubusercontent.com/13943503/131875216-b6de871c-a563-42cd-bc60-64d5d169a76c.jpg)

**Comment by dcommander** [comment]
Reproduced with
```
tjexample 131875216-b6de871c-a563-42cd-bc60-64d5d169a76c.jpg out.jpg -crop 472x424+248+216
```
Investigating.

**Comment by dcommander** [comment]
Fixed and pushed
