### ISSUE TITLE
Test 83 - djpeg-shared-3x2-float-prog-cmp  Failed in aarch64

### ISSUE THREAD

**Issue by yangcheng1203** [libjpeg-turbo/libjpeg-turbo#551]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
yes，I found that there was a PR #468  submission to solve the failure of ARM64 test-83 and test-234, but I merged the relevant PR, and the local build still failed.

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
no
**Clear and concise description of the bug:**
After building libjpeg-turbo 2.0.5 on aarch64, one tests fail:

     83 - djpeg-shared-3x2-float-prog-cmp (Failed)

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
cmake  . &&  make  -O -j4 V=1 VERBOSE=1 V=1  && make test

**Image(s) needed in order to reproduce the bug (if applicable):**
n/a

**Expected behavior:**
Test suite passing

**Observed behavior:**
Test suite failing.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
linux/aarch64
gcc version :7.3.0
cmake version: 3.16.5

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
libjpeg-turbo releases:2.0.5

**Comment by dcommander** [comment]
Already fixed in 2.0.6 via https://github.com/libjpeg-turbo/libjpeg-turbo/commit/88bf1d16786c74f76f2e4f6ec2873d092f577c75.  2.0.5 became obsolete as soon as 2.0.6 was released. Please do not file bug reports against obsoleted releases until you have verified that the issue exists in the latest release in the same series.
