### ISSUE TITLE
Not able to build on VS2008

### ISSUE THREAD

**Issue by Praveer1981** [libjpeg-turbo/libjpeg-turbo#555]
Hi,
 Is  it possible to build libjgpeg on visual studio 2008 ?

**Comment by dcommander** [comment]
Visual Studio 2008 ceased being supported by Microsoft three years ago, and it hasn't been tested in libjpeg-turbo in quite some time.  What issue specifically are you encountering?  Just saying that it won't build is not helpful.

**Comment by Praveer1981** [comment]
@dcommander dcommander Is there any test app which I can refer to in order to use libjpag ?  I want to use it on windows platform

**Comment by Praveer1981** [comment]
@dcommander Thanks for your response, let me push my code in git and share the link with you

**Comment by Praveer1981** [comment]
@dcommander 
here is the github link https://github.com/Praveer1981/libJpeg_test
Background:
We are upgrading our libjpeg library from version 0.8 to 2.1.1
I have created a sample app which uses libjpeg. it is exactly similar as our project
When I try to build libJpeg , i get a lot of error.

Do let me know if you need more info. it looks lite there are many flags need to be added in the config file
but I am not sure what are those
