### ISSUE TITLE
i got wrong result when i  try compressing framebuffer(1920x1080)

### ISSUE THREAD

**Issue by fastalks** [libjpeg-turbo/libjpeg-turbo#556]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

no

**Clear and concise description of the bug:**

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

i got wrong result when i  try compressing framebuffer(1920x1080).
and i am sure the source image is ABGR .

my code is :

    tjCompress2(handle, framebuffer_memory,
			vinfo.xres, finfo.line_length,
			vinfo.yres, TJPF_ABGR,
			&jpeg_data, &jpegSize,
			TJSAMP_444, 50,
			TJFLAG_NOREALLOC);

**Image(s) needed in order to reproduce the bug (if applicable):**

**Expected behavior:**
  get right screenshot

**Observed behavior:**
 got  wrong screenshot

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
android studio , mac os 

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

**Comment by wangfaguo** [comment]
jni code:

JNIEXPORT jint JNICALL Java_com_wfg_jni_XJni_screenCap(JNIEnv *env, jobject clazz, jbyteArray ba) {

    int fd, ret, byte_per_frame;
    unsigned long	jpegSize = 0;
    unsigned char	*framebuffer_memory;

    unsigned char* jpeg_data = NULL;

    static struct fb_var_screeninfo vinfo;
    struct fb_fix_screeninfo finfo;
    // turbo-jpeg 
    tjhandle	 handle;

    fd = open("/dev/graphics/fb0", O_RDONLY);

    if(fd < 0)
    {
        LOGD("======Cannot open /dev/graphics/fb0!");
        return -1;
    }

    // variable info 
    ret = ioctl(fd, FBIOGET_VSCREENINFO, &vinfo);
    if(ret < 0 )
    {
        LOGD("======Cannot get variable screen information.");
        close(fd);
        return -1;
    }

    // 
    LOGD("====== xres : %d",  vinfo.xres);
    LOGD("====== yres : %d",  vinfo.yres);

    LOGD("====== xres_virtual : %d",  vinfo.xres_virtual);
    LOGD("====== yres_virtual : %d",  vinfo.yres_virtual);

    /* offset from virtual to visible */
    LOGD("====== xoffset : %d",  vinfo.xoffset);
    LOGD("====== yoffset : %d",  vinfo.yoffset);

    LOGD("====== bits_per_pixel : %d",  vinfo.bits_per_pixel);

    // 
    LOGD("====== fb_bitfield red.offset : %d",  vinfo.red.offset);
    LOGD("====== fb_bitfield red.length : %d",  vinfo.red.length);
    // msb_right == 0 Big endian
    LOGD("====== fb_bitfield red.msb_right : %d",  vinfo.red.msb_right);
    LOGD("====== fb_bitfield green.offset : %d",  vinfo.green.offset);
    LOGD("====== fb_bitfield green.length : %d",  vinfo.green.length);
    LOGD("====== fb_bitfield green.msb_right : %d",  vinfo.green.msb_right);
    LOGD("====== fb_bitfield blue.offset : %d",  vinfo.blue.offset);
    LOGD("====== fb_bitfield blue.length : %d",  vinfo.blue.length);
    LOGD("====== fb_bitfield blue.msb_right : %d",  vinfo.blue.msb_right);
    LOGD("====== fb_bitfield transp.offset : %d",  vinfo.transp.offset);
    LOGD("====== fb_bitfield transp.length : %d",  vinfo.transp.length);
    LOGD("====== fb_bitfield transp.msb_right : %d",  vinfo.transp.msb_right);

    LOGD("====== height : %d",  vinfo.height);
    // width of picture in mm 
    LOGD("====== width : %d",  vinfo.width);
    // UP 0
    // CW 1
    // UD 2
    // CCW 3
    /* angle we rotate counter clockwise */
    LOGD("====== rotate : %d",  vinfo.rotate);

    // fixed info 
    ret = ioctl(fd, FBIOGET_FSCREENINFO, &finfo);
    if(ret < 0 )
    {
        LOGD("Cannot get fixed screen information.");
        close(fd);
        return -1;
    }

    LOGD("====== smem_start : %lu",  finfo.smem_start);

    LOGD("====== smem_len : %d",  finfo.smem_len);

    LOGD("====== line_length : %d",  finfo.line_length);

    //FB_TYPE_PACKED_PIXELS                0       /* Packed Pixels        */
    //FB_TYPE_PLANES                            1       /* Non interleaved planes */
    //FB_TYPE_INTERLEAVED_PLANES      2       /* Interleaved planes   */
    //FB_TYPE_TEXT                                3       /* Text/attributes      */
    //FB_TYPE_VGA_PLANES                    4       /* EGA/VGA planes       */
    //FB_TYPE_FOURCC                          5       /* Type identified by a V4L2 FOURCC */
    LOGD("====== type : %d",  finfo.type);
    byte_per_frame = finfo.line_length * vinfo.yres;

    framebuffer_memory = (unsigned char*)mmap(
            NULL,
            byte_per_frame,
            PROT_READ,
            MAP_SHARED,
            fd,
            0);

    if(framebuffer_memory == MAP_FAILED) {
        close(fd);
        LOGE("mmap for fb0 failed!");
        return -1;
    }

    handle = tjInitCompress();

    jpeg_data = (unsigned char *) malloc(byte_per_frame);

    tjCompress2(handle, framebuffer_memory,
                vinfo.xres, finfo.line_length,
                vinfo.yres, TJPF_ABGR,
                &jpeg_data, &jpegSize,
                TJSAMP_444, 10,
                TJFLAG_NOREALLOC);

    LOGD("Turbo-jpeg compress fb0 done!");
    munmap(framebuffer_memory, byte_per_frame);

    (*env)->SetByteArrayRegion(env,
                               ba,
                               0,
                               jpegSize,
                               (jbyte*)jpeg_data);

    free(jpeg_data);
    close(fd);
    tjDestroy(handle);
    return jpegSize;
}


java code :

    private void initView() {

        findViewById(R.id.accessibility_find_and_click).setOnClickListener(this);
        mImageView = (ImageView) findViewById(R.id.Reset);
        mImageView.postDelayed(new Runnable() {
            @Override
            public void run() {
                XJni jni = new XJni();
                byte[] imageBytes = new byte[1920 * 1080 * 4];
                long start = System.currentTimeMillis();
                int jpegSize = jni.screenCap(imageBytes);

                if (jpegSize == -1) {
                    Log.d(TAG, "Error happened in jni!");
                    return;
                }
                Log.d(TAG, "Time = " + (System.currentTimeMillis() - start));
                Log.d(TAG, "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF jpeg size = " + jpegSize);
                Bitmap bm = BitmapFactory.decodeByteArray(imageBytes, 0, jpegSize);
                if (bm != null) {
                    mImageView.setImageBitmap(bm);
                } else {
                    Log.d(TAG, "bitmap == null");
                }
            }
        }, 2000);

    }
