### ISSUE TITLE
android arm64-v8a build error via cmake

### ISSUE THREAD

**Issue by yanwei07** [libjpeg-turbo/libjpeg-turbo#563]
my cmake calling :
cmake -G"Unix Makefiles" \
  -DANDROID_ABI=arm64-v8a \
  -DANDROID_ARM_MODE=arm \
  -DANDROID_PLATFORM=android-${ANDROID_VERSION} \
  -DANDROID_TOOLCHAIN=${TOOLCHAIN} \
  -DCMAKE_ASM_FLAGS="--target=aarch64-linux-android${ANDROID_VERSION}" \
  -DCMAKE_TOOLCHAIN_FILE=${NDK_PATH}/build/cmake/android.toolchain.cmake \
  -DCMAKE_INSTALL_PREFIX=`pwd`/../output/arm64-v8a

error message :-- CMAKE_BUILD_TYPE = Release
-- VERSION = 2.1.2, BUILD = 20211115
-- 64-bit build (arm64)
-- CMAKE_INSTALL_PREFIX = /home/yw/mydev/libjpeg/libjpeg-turbo2.1/output/arm64-v8a
-- CMAKE_INSTALL_BINDIR = bin (/home/yw/mydev/libjpeg/libjpeg-turbo2.1/output/arm64-v8a/bin)
-- CMAKE_INSTALL_DATAROOTDIR = share (/home/yw/mydev/libjpeg/libjpeg-turbo2.1/output/arm64-v8a/share)
-- CMAKE_INSTALL_DOCDIR = share/doc/libjpeg-turbo (/home/yw/mydev/libjpeg/libjpeg-turbo2.1/output/arm64-v8a/share/doc/libjpeg-turbo)
-- CMAKE_INSTALL_INCLUDEDIR = include (/home/yw/mydev/libjpeg/libjpeg-turbo2.1/output/arm64-v8a/include)
-- CMAKE_INSTALL_LIBDIR = lib (/home/yw/mydev/libjpeg/libjpeg-turbo2.1/output/arm64-v8a/lib)
-- CMAKE_INSTALL_MANDIR = share/man (/home/yw/mydev/libjpeg/libjpeg-turbo2.1/output/arm64-v8a/share/man)
-- Shared libraries enabled (ENABLE_SHARED = 1)
-- Static libraries enabled (ENABLE_STATIC = 1)
-- 12-bit JPEG support disabled (WITH_12BIT = 0)
-- Arithmetic decoding support enabled (WITH_ARITH_DEC = 1)
-- Arithmetic encoding support enabled (WITH_ARITH_ENC = 1)
-- TurboJPEG API library enabled (WITH_TURBOJPEG = 1)
-- TurboJPEG Java wrapper disabled (WITH_JAVA = 0)
-- In-memory source/destination managers enabled (WITH_MEM_SRCDST = 1)
-- Emulating libjpeg API/ABI v6.2 (WITH_JPEG7 = 0, WITH_JPEG8 = 0)
-- libjpeg API shared library version = 62.3.0
-- Compiler flags = -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -O3 -DNDEBUG 
-- Linker flags = -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,--gc-sections  
-- Compiler supports pointers to undefined structures.
-- INLINE = __inline__ __attribute__((always_inline)) (FORCE_INLINE = 1)
-- THREAD_LOCAL = __thread
-- Linker supports GNU-style version scripts
-- CMAKE_EXECUTABLE_SUFFIX = 
-- Use full Neon SIMD intrinsics implementation (NEON_INTRINSICS = ON)
-- SIMD extensions: arm64 (WITH_SIMD = 1)
-- FLOATTEST = no-fp-contract
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yw/mydev/libjpeg/libjpeg-turbo2.1/libjpeg-turbo
[  0%] Building C object simd/CMakeFiles/simd.dir/arm/jcgray-neon.c.o
[  0%] Building C object simd/CMakeFiles/simd.dir/arm/jcphuff-neon.c.o
[  1%] Building C object simd/CMakeFiles/simd.dir/arm/jcsample-neon.c.o
[  1%] Building C object simd/CMakeFiles/simd.dir/arm/jdmerge-neon.c.o
[  1%] Building C object simd/CMakeFiles/simd.dir/arm/jdsample-neon.c.o
[  2%] Building C object simd/CMakeFiles/simd.dir/arm/jfdctfst-neon.c.o
[  2%] Building C object simd/CMakeFiles/simd.dir/arm/jidctred-neon.c.o
[  2%] Building C object simd/CMakeFiles/simd.dir/arm/jquanti-neon.c.o
[  3%] Building C object simd/CMakeFiles/simd.dir/arm/jccolor-neon.c.o
[  3%] Building C object simd/CMakeFiles/simd.dir/arm/jidctint-neon.c.o
[  3%] Building C object simd/CMakeFiles/simd.dir/arm/jidctfst-neon.c.o
[  4%] Building C object simd/CMakeFiles/simd.dir/arm/aarch64/jchuff-neon.c.o
[  4%] Building C object simd/CMakeFiles/simd.dir/arm/jdcolor-neon.c.o
[  4%] Building C object simd/CMakeFiles/simd.dir/arm/jfdctint-neon.c.o
[  4%] Building C object simd/CMakeFiles/simd.dir/arm/aarch64/jsimd.c.o
[  4%] Built target simd
[  5%] Building C object CMakeFiles/turbojpeg.dir/jcapimin.c.o
[  5%] Building C object CMakeFiles/turbojpeg.dir/jcapistd.c.o
[  5%] Building C object CMakeFiles/turbojpeg.dir/jccoefct.c.o
[  6%] Building C object CMakeFiles/turbojpeg.dir/jccolor.c.o
[  6%] Building C object CMakeFiles/turbojpeg.dir/jcdctmgr.c.o
[  6%] Building C object CMakeFiles/turbojpeg.dir/jchuff.c.o
[  7%] Building C object CMakeFiles/turbojpeg.dir/jcicc.c.o
[  7%] Building C object CMakeFiles/turbojpeg.dir/jcinit.c.o
[  7%] Building C object CMakeFiles/turbojpeg.dir/jcmainct.c.o
[  7%] Building C object CMakeFiles/turbojpeg.dir/jcmarker.c.o
[  8%] Building C object CMakeFiles/turbojpeg.dir/jcmaster.c.o
[  8%] Building C object CMakeFiles/turbojpeg.dir/jcomapi.c.o
[  8%] Building C object CMakeFiles/turbojpeg.dir/jcparam.c.o
[  9%] Building C object CMakeFiles/turbojpeg.dir/jcphuff.c.o
[  9%] Building C object CMakeFiles/turbojpeg.dir/jcprepct.c.o
[  9%] Building C object CMakeFiles/turbojpeg.dir/jcsample.c.o
[ 10%] Building C object CMakeFiles/turbojpeg.dir/jctrans.c.o
[ 10%] Building C object CMakeFiles/turbojpeg.dir/jdapimin.c.o
[ 10%] Building C object CMakeFiles/turbojpeg.dir/jdapistd.c.o
[ 11%] Building C object CMakeFiles/turbojpeg.dir/jdatadst.c.o
[ 11%] Building C object CMakeFiles/turbojpeg.dir/jdatasrc.c.o
[ 11%] Building C object CMakeFiles/turbojpeg.dir/jdcoefct.c.o
[ 12%] Building C object CMakeFiles/turbojpeg.dir/jdcolor.c.o
[ 12%] Building C object CMakeFiles/turbojpeg.dir/jddctmgr.c.o
[ 12%] Building C object CMakeFiles/turbojpeg.dir/jdhuff.c.o
[ 13%] Building C object CMakeFiles/turbojpeg.dir/jdicc.c.o
[ 13%] Building C object CMakeFiles/turbojpeg.dir/jdinput.c.o
[ 13%] Building C object CMakeFiles/turbojpeg.dir/jdmainct.c.o
[ 14%] Building C object CMakeFiles/turbojpeg.dir/jdmarker.c.o
[ 14%] Building C object CMakeFiles/turbojpeg.dir/jdmaster.c.o
[ 14%] Building C object CMakeFiles/turbojpeg.dir/jdmerge.c.o
[ 15%] Building C object CMakeFiles/turbojpeg.dir/jdphuff.c.o
[ 15%] Building C object CMakeFiles/turbojpeg.dir/jdpostct.c.o
[ 15%] Building C object CMakeFiles/turbojpeg.dir/jdsample.c.o
[ 16%] Building C object CMakeFiles/turbojpeg.dir/jdtrans.c.o
[ 16%] Building C object CMakeFiles/turbojpeg.dir/jerror.c.o
[ 16%] Building C object CMakeFiles/turbojpeg.dir/jfdctflt.c.o
[ 16%] Building C object CMakeFiles/turbojpeg.dir/jfdctfst.c.o
[ 17%] Building C object CMakeFiles/turbojpeg.dir/jfdctint.c.o
[ 17%] Building C object CMakeFiles/turbojpeg.dir/jidctflt.c.o
[ 17%] Building C object CMakeFiles/turbojpeg.dir/jidctfst.c.o
[ 18%] Building C object CMakeFiles/turbojpeg.dir/jidctint.c.o
[ 18%] Building C object CMakeFiles/turbojpeg.dir/jidctred.c.o
[ 18%] Building C object CMakeFiles/turbojpeg.dir/jquant1.c.o
[ 19%] Building C object CMakeFiles/turbojpeg.dir/jquant2.c.o
[ 19%] Building C object CMakeFiles/turbojpeg.dir/jutils.c.o
[ 19%] Building C object CMakeFiles/turbojpeg.dir/jmemmgr.c.o
[ 20%] Building C object CMakeFiles/turbojpeg.dir/jmemnobs.c.o
[ 20%] Building C object CMakeFiles/turbojpeg.dir/jaricom.c.o
[ 20%] Building C object CMakeFiles/turbojpeg.dir/jcarith.c.o
[ 21%] Building C object CMakeFiles/turbojpeg.dir/jdarith.c.o
[ 21%] Building C object CMakeFiles/turbojpeg.dir/turbojpeg.c.o
[ 21%] Building C object CMakeFiles/turbojpeg.dir/transupp.c.o
[ 22%] Building C object CMakeFiles/turbojpeg.dir/jdatadst-tj.c.o
[ 22%] Building C object CMakeFiles/turbojpeg.dir/jdatasrc-tj.c.o
[ 22%] Building C object CMakeFiles/turbojpeg.dir/rdbmp.c.o
[ 23%] Building C object CMakeFiles/turbojpeg.dir/rdppm.c.o
[ 23%] Building C object CMakeFiles/turbojpeg.dir/wrbmp.c.o
[ 23%] Building C object CMakeFiles/turbojpeg.dir/wrppm.c.o
[ 24%] Linking C shared library libturbojpeg.so
[ 24%] Built target turbojpeg
[ 24%] Building C object CMakeFiles/tjunittest.dir/tjunittest.c.o
[ 25%] Building C object CMakeFiles/tjunittest.dir/tjutil.c.o
[ 25%] Building C object CMakeFiles/tjunittest.dir/md5/md5.c.o
[ 25%] Building C object CMakeFiles/tjunittest.dir/md5/md5hl.c.o
[ 26%] Linking C executable tjunittest
[ 26%] Built target tjunittest
[ 27%] Building C object CMakeFiles/tjexample.dir/tjexample.c.o
[ 27%] Linking C executable tjexample
[ 27%] Built target tjexample
[ 28%] Building C object CMakeFiles/tjbench.dir/tjbench.c.o
[ 28%] Building C object CMakeFiles/tjbench.dir/tjutil.c.o
[ 28%] Linking C executable tjbench
[ 28%] Built target tjbench
[ 28%] Building C object CMakeFiles/turbojpeg-static.dir/jcapimin.c.o
[ 28%] Building C object CMakeFiles/turbojpeg-static.dir/jcapistd.c.o
[ 29%] Building C object CMakeFiles/turbojpeg-static.dir/jccoefct.c.o
[ 29%] Building C object CMakeFiles/turbojpeg-static.dir/jccolor.c.o
[ 29%] Building C object CMakeFiles/turbojpeg-static.dir/jcdctmgr.c.o
[ 29%] Building C object CMakeFiles/turbojpeg-static.dir/jchuff.c.o
[ 30%] Building C object CMakeFiles/turbojpeg-static.dir/jcicc.c.o
[ 30%] Building C object CMakeFiles/turbojpeg-static.dir/jcinit.c.o
[ 30%] Building C object CMakeFiles/turbojpeg-static.dir/jcmainct.c.o
[ 31%] Building C object CMakeFiles/turbojpeg-static.dir/jcmarker.c.o
[ 31%] Building C object CMakeFiles/turbojpeg-static.dir/jcmaster.c.o
[ 31%] Building C object CMakeFiles/turbojpeg-static.dir/jcomapi.c.o
[ 32%] Building C object CMakeFiles/turbojpeg-static.dir/jcparam.c.o
[ 32%] Building C object CMakeFiles/turbojpeg-static.dir/jcphuff.c.o
[ 32%] Building C object CMakeFiles/turbojpeg-static.dir/jcprepct.c.o
[ 33%] Building C object CMakeFiles/turbojpeg-static.dir/jcsample.c.o
[ 33%] Building C object CMakeFiles/turbojpeg-static.dir/jctrans.c.o
[ 33%] Building C object CMakeFiles/turbojpeg-static.dir/jdapimin.c.o
[ 34%] Building C object CMakeFiles/turbojpeg-static.dir/jdapistd.c.o
[ 34%] Building C object CMakeFiles/turbojpeg-static.dir/jdatadst.c.o
[ 34%] Building C object CMakeFiles/turbojpeg-static.dir/jdatasrc.c.o
[ 35%] Building C object CMakeFiles/turbojpeg-static.dir/jdcoefct.c.o
[ 35%] Building C object CMakeFiles/turbojpeg-static.dir/jdcolor.c.o
[ 35%] Building C object CMakeFiles/turbojpeg-static.dir/jddctmgr.c.o
[ 36%] Building C object CMakeFiles/turbojpeg-static.dir/jdhuff.c.o
[ 36%] Building C object CMakeFiles/turbojpeg-static.dir/jdicc.c.o
[ 36%] Building C object CMakeFiles/turbojpeg-static.dir/jdinput.c.o
[ 37%] Building C object CMakeFiles/turbojpeg-static.dir/jdmainct.c.o
[ 37%] Building C object CMakeFiles/turbojpeg-static.dir/jdmarker.c.o
[ 37%] Building C object CMakeFiles/turbojpeg-static.dir/jdmaster.c.o
[ 38%] Building C object CMakeFiles/turbojpeg-static.dir/jdmerge.c.o
[ 38%] Building C object CMakeFiles/turbojpeg-static.dir/jdphuff.c.o
[ 38%] Building C object CMakeFiles/turbojpeg-static.dir/jdpostct.c.o
[ 38%] Building C object CMakeFiles/turbojpeg-static.dir/jdsample.c.o
[ 39%] Building C object CMakeFiles/turbojpeg-static.dir/jdtrans.c.o
[ 39%] Building C object CMakeFiles/turbojpeg-static.dir/jerror.c.o
[ 39%] Building C object CMakeFiles/turbojpeg-static.dir/jfdctflt.c.o
[ 40%] Building C object CMakeFiles/turbojpeg-static.dir/jfdctfst.c.o
[ 40%] Building C object CMakeFiles/turbojpeg-static.dir/jfdctint.c.o
[ 40%] Building C object CMakeFiles/turbojpeg-static.dir/jidctflt.c.o
[ 41%] Building C object CMakeFiles/turbojpeg-static.dir/jidctfst.c.o
[ 41%] Building C object CMakeFiles/turbojpeg-static.dir/jidctint.c.o
[ 41%] Building C object CMakeFiles/turbojpeg-static.dir/jidctred.c.o
[ 42%] Building C object CMakeFiles/turbojpeg-static.dir/jquant1.c.o
[ 42%] Building C object CMakeFiles/turbojpeg-static.dir/jquant2.c.o
[ 42%] Building C object CMakeFiles/turbojpeg-static.dir/jutils.c.o
[ 43%] Building C object CMakeFiles/turbojpeg-static.dir/jmemmgr.c.o
[ 43%] Building C object CMakeFiles/turbojpeg-static.dir/jmemnobs.c.o
[ 43%] Building C object CMakeFiles/turbojpeg-static.dir/jaricom.c.o
[ 44%] Building C object CMakeFiles/turbojpeg-static.dir/jcarith.c.o
[ 44%] Building C object CMakeFiles/turbojpeg-static.dir/jdarith.c.o
[ 44%] Building C object CMakeFiles/turbojpeg-static.dir/turbojpeg.c.o
[ 45%] Building C object CMakeFiles/turbojpeg-static.dir/transupp.c.o
[ 45%] Building C object CMakeFiles/turbojpeg-static.dir/jdatadst-tj.c.o
[ 45%] Building C object CMakeFiles/turbojpeg-static.dir/jdatasrc-tj.c.o
[ 46%] Building C object CMakeFiles/turbojpeg-static.dir/rdbmp.c.o
[ 46%] Building C object CMakeFiles/turbojpeg-static.dir/rdppm.c.o
[ 46%] Building C object CMakeFiles/turbojpeg-static.dir/wrbmp.c.o
[ 47%] Building C object CMakeFiles/turbojpeg-static.dir/wrppm.c.o
[ 47%] Linking C static library libturbojpeg.a
[ 47%] Built target turbojpeg-static
[ 48%] Building C object CMakeFiles/tjbench-static.dir/tjbench.c.o
[ 48%] Building C object CMakeFiles/tjbench-static.dir/tjutil.c.o
[ 48%] Linking C executable tjbench-static
libturbojpeg.a: error adding symbols: Archive has no index; run ranlib to add one
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/tjbench-static.dir/build.make:100: tjbench-static] Error 1
make[1]: *** [CMakeFiles/Makefile2:419: CMakeFiles/tjbench-static.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
[  4%] Built target simd
[ 24%] Built target turbojpeg
[ 26%] Built target tjunittest
[ 27%] Built target tjexample
[ 28%] Built target tjbench
[ 47%] Built target turbojpeg-static
[ 47%] Linking C executable tjbench-static
libturbojpeg.a: error adding symbols: Archive has no index; run ranlib to add one
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/tjbench-static.dir/build.make:100: tjbench-static] Error 1
make[1]: *** [CMakeFiles/Makefile2:419: CMakeFiles/tjbench-static.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by dcommander** [comment]
As **BUILDING.md** states, you should set the `NDK_PATH`, `TOOLCHAIN`, and `ANDROID_VERSION` environment variables to suit your needs.  If you have not done that, then that is the source of the error.  If you have done that, then please post the values of those variables from your build.

**Comment by yanwei07** [comment]
hi, thank your reply, I have defined NDK_PATH, TOOLCHAIN, and ANDROID_VERSION:
export NDK_PATH=/home/yw/Android/Sdk/ndk/21.1.6352462
export TOOLCHAIN=clang
export ANDROID_VERSION=21

**Comment by dcommander** [comment]
I can't reproduce the failure, unfortunately.  I tried NDK r22b on macOS, which is approximately the same NDK version that you are using.
