### ISSUE TITLE
Checks on Se field

### ISSUE THREAD

**Issue by I-mpossible** [libjpeg-turbo/libjpeg-turbo#564]
Hi,

I found that given the following jpeg, libjpeg-turbo-2.1.1 could convert it to a BMP but libjepg-9d complains: Invalid progressive parameters Ss=0 Se=78 Ah=0 Al=0.

[testcase.zip](https://github.com/libjpeg-turbo/libjpeg-turbo/files/7575432/testcase.zip)

```
djpeg -bmp testcase.jpg
```

The corresponding check in libjpeg-9d is at jdinput.c:249
```
switch (cinfo->Se) {
case (1*1-1):
  cinfo->block_size = 1;
  cinfo->natural_order = jpeg_natural_order; /* not needed */
  cinfo->lim_Se = cinfo->Se;
  break;
case (2*2-1):
  ...
```

I'm wondering if there are missing checks on Se field in libjpeg-turbo? Would it cause bugs or interoperability issues?

Thanks in advance.

**Comment by dcommander** [comment]
I will examine the test case in more detail, but the code you posted from jpeg-9d is related to the SmartScale feature, which implements a variable DCT block size. That feature is an unofficial extension of the JPEG format that was never accepted by ISO/ITU-T. Unless the test case produces a crash or an error with ASan, LSan, UBSan, or MSan, then it’s probably nothing of concern.

**Comment by I-mpossible** [comment]
Thanks for your reply! 

I looked up related information on SmartScale. It seeems Se is required by ISO/ITU-T to be 63 only, while SmartScale allows it to be other values (Please correct me if I was wrong). 

I saw that libjpeg-9d complains Se field being 78 in the testcase. Se I presume libjpeg-turbo accepts 78 as a valid value (or perhaps just ignored it?) Would it be good to add Se==63 check in libjpeg-turbo? Or does libjpeg-turbo has other methods to deduce the value so as to provide better robustness?

Thanks!
