### ISSUE TITLE
Compression of pgm (grayscale) with cjpeg results in 3 components JPEG file

### ISSUE THREAD

**Issue by malaterre** [libjpeg-turbo/libjpeg-turbo#566]
**Expected behavior:**

$ convert -size 512x512 -depth 8 xc:black black.pgm
$ cjpeg -outfile black.jpg black.pgm
$ file black.jpg
black.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 512x512, components 1

**Observed behavior:**

$ convert -size 512x512 -depth 8 xc:black black.pgm
$ cjpeg -outfile black.jpg black.pgm
$ file black.jpg
black.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 512x512, components 3

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

Linux Debian/bullseye

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

aa74590

**Additional information:**

**Comment by dcommander** [comment]
Fixed.  cjpeg now automatically compresses BMP and GIF files containing only shades of gray into grayscale JPEG images as well.  This can be verified with [this test script](https://gist.github.com/dcommander/e25102c3285633dd5b559385fb20d0bb).
