### ISSUE TITLE
cross compile for Windows ARM32 dll fails (ARM64 dll without problem)

### ISSUE THREAD

**Issue by Dav151** [libjpeg-turbo/libjpeg-turbo#572]
I use Windows 10 PC to cross compile for Window **ARM32** dll, and it fails. It built successfully for **ARM64** dll .

**For ARM64:**
>vcvarsamd64_arm64.bat
>cmake -G"NMake Makefiles" -DCMAKE_TOOLCHAIN_FILE=win64-arm-toolchain.cmake -DCMAKE_BUILD_TYPE=Release ../libjpeg-turbo-2.1.1
>nmake
Built success.

**For ARM32:**
>vcvarsamd64_arm.bat
>cmake -G"NMake Makefiles" -DCMAKE_TOOLCHAIN_FILE=win32-arm-toolchain.cmake -DCMAKE_BUILD_TYPE=Release ../libjpeg-turbo-2.1.1
>nmake

**Detect "neon intrinsics  fail"**

-- Performing Test NEED_SOFTFP_FOR_INTRINSICS
-- Performing Test NEED_SOFTFP_FOR_INTRINSICS - Failed
-- Looking for vld1_s16_x3
-- Looking for vld1_s16_x3 - not found
-- Looking for vld1_u16_x2
-- Looking for vld1_u16_x2 - not found
-- Looking for vld1q_u8_x4
-- Looking for vld1q_u8_x4 - not found
-- Use partial Neon SIMD intrinsics implementation (NEON_INTRINSICS = OFF)
-- The ASM compiler identification is MSVC
-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.26.28801/bin/Hostx64/arm/cl.exe
-- CMAKE_ASM_FLAGS = /DWIN32 /D_WINDOWS /W3 /W3 /wd4996
-- SIMD extensions: arm (WITH_SIMD = 1)
-- FLOATTEST = no-fp-contract

>namke

l : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
cl : Command line warning D9024 : unrecognized source file type 'D:\libjpeg-turbo\libjpeg-turbo-2.1.1\simd\arm\aarch32\jsimd_neon.S', object file assumed
cl : Command line warning D9027 : source file 'D:\libjpeg-turbo\libjpeg-turbo-2.1.1\simd\arm\aarch32\jsimd_neon.S' ignored
cl : Command line warning D9021 : no action performed

build fail..

Any help would be appreciated!

**Comment by dcommander** [comment]
For the time being, you can work around it by passing `-DNEON_INTRINSICS=1` to CMake.  That variable is supposed to be set automatically for Windows builds, so I'll investigate why it isn't.

**Comment by Dav151** [comment]
updated:

I found a temp solution.

**1. mask the code in "libjpeg-turbo-2.1.1\simd\arm\jidctfst-neon.c" to fix the compile error**
/* Store DCT block to memory. */
  /*vst1q_lane_u64((uint64_t *)outptr0, vreinterpretq_u64_u8(rows_04), 0);
  vst1q_lane_u64((uint64_t *)outptr1, vreinterpretq_u64_u8(rows_15), 0);
  vst1q_lane_u64((uint64_t *)outptr2, vreinterpretq_u64_u8(rows_26), 0);
  vst1q_lane_u64((uint64_t *)outptr3, vreinterpretq_u64_u8(rows_37), 0);
  vst1q_lane_u64((uint64_t *)outptr4, vreinterpretq_u64_u8(rows_04), 1);
  vst1q_lane_u64((uint64_t *)outptr5, vreinterpretq_u64_u8(rows_15), 1);
  vst1q_lane_u64((uint64_t *)outptr6, vreinterpretq_u64_u8(rows_26), 1);
  vst1q_lane_u64((uint64_t *)outptr7, vreinterpretq_u64_u8(rows_37), 1);*/

**2. add "add_definitions(-D__ARM_NEON__)" in CMakeLists.txt, as I see "__ARM_NEON__" not define in "MSVC ARM" Env**

**3. add "TJFlags.AccurateDct" option when call jpeg compress function to force use "JDCT_ISLOW" instead of "JDCT_FASTEST" , as I mask the code in jidctfst-neon.c**

The performance is 2.5-3x faster than original  Unity API call.

**Comment by dcommander** [comment]
Unfortunately the Neon intrinsics seem quite broken in the AArch32 Visual C++ compiler, and hacking the libjpeg-turbo code to work around that isn't a viable solution.  Why do you need to build an AArch32 libjpeg-turbo DLL?  As far as I'm aware, all Windows on Arm releases require AArch64 CPUs, so I don't see the point of releasing a 32-bit application for that platform.

@jwright-arm Any thoughts?

**Comment by jwright-arm** [comment]
Many moons ago, Windows RT was built for Armv7-A (32-bit only) and there were devices like the Surface RT[1] that had 32-bit only SoCs e.g. the Tegra 3 (based on Cortex-A9.) There's also the Windows Phone ecosystem which was built for Armv7-A and ran on some SoCs that were 32-bit only.

Both of these platforms are deprecated so I don't think we should make an effort to support them. There is no reason whatsoever to build or release an AArch32 version of an application intended for Windows 10 or Windows 11 - as has been said, it's a requirement to have an 64-bit capable Armv8-A SoC.

[1] https://support.microsoft.com/en-us/surface/surface-rt-specifications-dcc757dc-b4ab-c33f-d3b3-352cf5d2e637

**Comment by dcommander** [comment]
Closing as SEP.  Building a Windows/AArch32 version of libjpeg-turbo is still possible without SIMD acceleration, and you can probably build a SIMD-accelerated version using MinGW.  That's the best we can do for a deprecated platform that MS itself doesn't even support.
