### ISSUE TITLE
corrupted size vs. prev_size without fancy upsampler

### ISSUE THREAD

**Issue by typingtanuki** [libjpeg-turbo/libjpeg-turbo#574]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

Yes.

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

No.

**Clear and concise description of the bug:**

Using `jpeg_crop_scanline` and `do_fancy_upsampling = false` together will crash with `corrupted size vs. prev_size` on some pictures.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

* Running the following code with the attached image will fail
    * Enabling the fancy upsampler will succeed
    * Not cropping scanlines will also succeed

```
    jpeg_decompress_struct cinfo{};
    jpeg_error_mgr jerr{};

    cinfo.err = jpeg_std_error(&jerr);
    jpeg_create_decompress(&cinfo);

    jpeg_stdio_src(&cinfo, infile);

    jpeg_read_header(&cinfo, true);

    // Changing this will succeed
    cinfo.do_fancy_upsampling = false;

    jpeg_start_decompress(&cinfo);

    // Changing this will succeed
    jpeg_crop_scanline(&cinfo, &cropLeft, &cropWidth);

    unsigned int stride = cropWidth * cinfo.output_components;
    unsigned int imageSize = stride * height;

    auto *image = new unsigned char[imageSize];

    JSAMPROW csr = image;
    while (cinfo.output_scanline < cinfo.image_height) {
        jpeg_read_scanlines(&cinfo, &csr, 1);
        csr += stride;
    }

    jpeg_finish_decompress(&cinfo);
    jpeg_destroy_decompress(&cinfo);

    fclose(infile);
```

**Image(s) needed in order to reproduce the bug (if applicable):**

Image metadata:

`JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, comment: "Lavc58.54.100", baseline, precision 8, 2048x1080, components 3`

![2](https://user-images.githubusercontent.com/10096364/151085981-d6a31c81-2182-443c-a32e-d739c5807c47.jpg)

**Expected behavior:**

Image is decompressed.

**Observed behavior:**

`corrupted size vs. prev_size` while `jpeg_finish_decompress` or `jpeg_read_scanlines`.

Stack when failing in `jpeg_finish_decompress`:

```
__pthread_kill_implementation 0x00007f220db14808
__pthread_kill_internal 0x00007f220db14808
__GI___pthread_kill 0x00007f220db14808
__GI_raise 0x00007f220dac0476
__GI_abort 0x00007f220daa67b7
__libc_message 0x00007f220db075e6
malloc_printerr 0x00007f220db1eadc
unlink_chunk 0x00007f220db1fbdb
_int_free 0x00007f220db2070b
__GI___libc_free 0x00007f220db22ce5
free_pool 0x000055826a87630d
jpeg_abort 0x000055826a878d8c
jpeg_finish_decompress 0x000055826a8684b1
```

Stack when failing in `jpeg_read_scanlines`:

```
__memmove_evex_unaligned_erms 0x00007f3902256383
jcopy_sample_rows 0x000055bb6a3cf497
merged_2v_upsample 0x000055bb6a3c8fc0
process_data_simple_main 0x000055bb6a3ddf59
jpeg_read_scanlines 0x000055bb6a3c217b
```

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

Confirmed on 2 separate configurations:

* Configuration 1 (bare metal)
    * Ubuntu 21.10
    * Kernel 5.13
    * GCC 11.2
    * CMake 3.18.4
    * Intel i7-1185G7
* Configuration 2 (aws)
    * Ubuntu 20.04
    * Kernel 5.11
    * GCC 9.3
    * CMake 3.16.3
    * Intel Xeon 8259CL

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

libjpeg-turbo 2.1.2

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

**Comment by dcommander** [comment]
I can't reproduce the issue using `djpeg -nosmooth -crop`, so you're going to have to provide me with a standalone test case.  Without the surrounding context and concrete values for the various variables, your code snippet isn't useful.

**Comment by typingtanuki** [comment]
Thank you for looking into the issue.

I can confirm that using `djpeg` the issue does not occur.

It can be reproduced by running the following code:
```
#include <iostream>
#include <jpeglib.h>

unsigned char *read(const std::string &path,
                    JDIMENSION cropLeft,
                    JDIMENSION cropWidth) {
    auto infile = fopen(path.c_str(), "rb");

    jpeg_decompress_struct cinfo{};
    jpeg_error_mgr jerr{};

    cinfo.err = jpeg_std_error(&jerr);
    jpeg_create_decompress(&cinfo);

    jpeg_stdio_src(&cinfo, infile);

    jpeg_read_header(&cinfo, true);

    // Changing this will succeed
    cinfo.do_fancy_upsampling = false;

    jpeg_start_decompress(&cinfo);

    // Changing this will succeed
    jpeg_crop_scanline(&cinfo, &cropLeft, &cropWidth);

    unsigned int stride = cropWidth * cinfo.output_components;
    unsigned int imageSize = stride * cinfo.image_height;

    auto *image = new unsigned char[imageSize];

    JSAMPROW csr = image;
    while (cinfo.output_scanline < cinfo.image_height) {
        jpeg_read_scanlines(&cinfo, &csr, 1);
        csr += stride;
    }

    jpeg_finish_decompress(&cinfo);
    jpeg_destroy_decompress(&cinfo);

    fclose(infile);
}

int main() {
    read("sample.jpg", 10, 20);
    return 0;
}
```

**Comment by dcommander** [comment]
Reproduced.  I more or less understand the cause but am still trying to nail down why it doesn't occur with djpeg.

**Comment by typingtanuki** [comment]
I can confirm the fix works.
Thank you.
