### ISSUE TITLE
Reusing buffers for multiple compression runs

### ISSUE THREAD

**Issue by trbtm** [libjpeg-turbo/libjpeg-turbo#579]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

Yes.

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

No.

**Clear and concise description of the bug:**

I basically created a wrapper around one of the basic examples to use libjpeg-turbo to convert an RGBA framebuffer to JPEG in memory, so far so uninteresting. I created this piece of code to be able to reuse all of the structs / buffers etc. since I am streaming MJPEG with this and want to avoid allocating memory in the realtime part of the server.

```c
// jpeg_converter.c
struct jpeg_converter_struct
{
    struct jpeg_compress_struct cinfo;
    struct jpeg_error_mgr jerr;

    unsigned long jpeg_buffer_len;
    unsigned char *jpeg_buffer;
    int row_stride;

    unsigned char *framebuffer;
};

jpeg_converter jpeg_converter_init(int frame_width, int frame_height, int num_per_pixel)
{
    jpeg_converter converter = malloc(sizeof(*converter) * 1);

    converter->cinfo.err = jpeg_std_error(&converter->jerr);
    jpeg_create_compress(&converter->cinfo);

    converter->cinfo.image_width = frame_width;
    converter->cinfo.image_height = frame_height;
    converter->cinfo.input_components = num_per_pixel;
    converter->cinfo.in_color_space = JCS_EXT_RGBA;
    converter->row_stride = frame_width * num_per_pixel;

    converter->jpeg_buffer_len = 0ul;
    converter->jpeg_buffer = NULL;
    jpeg_mem_dest(&converter->cinfo, &converter->jpeg_buffer, &converter->jpeg_buffer_len);

    jpeg_set_defaults(&converter->cinfo);
    // limit to baseline-JPEG values
    jpeg_set_quality(&converter->cinfo, 100, TRUE);

    // Helper fields
    size_t num_framebuffer = frame_width * frame_height * num_per_pixel;
    converter->framebuffer = malloc(sizeof(*converter->framebuffer) * num_framebuffer);

    return converter;
}

unsigned char *jpeg_converter_convert(jpeg_converter converter, unsigned long *jpeg_buffer_len)
{
    jpeg_start_compress(&converter->cinfo, TRUE);

    JSAMPROW row_pointer[1];
    while (converter->cinfo.next_scanline < converter->cinfo.image_height) {
        row_pointer[0] = &converter->framebuffer[converter->cinfo.next_scanline * converter->row_stride];
        jpeg_write_scanlines(&converter->cinfo, row_pointer, 1);
    }

    jpeg_finish_compress(&converter->cinfo);

    *jpeg_buffer_len = converter->jpeg_buffer_len;

    return converter->jpeg_buffer;
}
```
```c
// jpeg_converter.h for the sake of completeness
struct jpeg_converter_struct;
typedef struct jpeg_converter_struct *jpeg_converter;
```

If I use this code as it is, it exactly converts one framebuffer as it supposed to do (one function call of `jpeg_converter_convert`) and after that `converter->framebuffer` doesn't get updated anymore. I looked into the source code and figured that memory gets released, etc. when calling `jpeg_finish_compress`.

I fixed the issue by moving `jpeg_mem_dest` into the convert function:

```c
unsigned char *jpeg_converter_convert(jpeg_converter converter, unsigned long *jpeg_buffer_len)
{
    jpeg_mem_dest(&converter->cinfo, &converter->jpeg_buffer, &converter->jpeg_buffer_len);
	
    jpeg_start_compress(&converter->cinfo, TRUE);

    JSAMPROW row_pointer[1];
    while (converter->cinfo.next_scanline < converter->cinfo.image_height) {
        row_pointer[0] = &converter->framebuffer[converter->cinfo.next_scanline * converter->row_stride];
        jpeg_write_scanlines(&converter->cinfo, row_pointer, 1);
    }

    jpeg_finish_compress(&converter->cinfo);

    *jpeg_buffer_len = converter->jpeg_buffer_len;

    return converter->jpeg_buffer;
}
```

This mostly fixes the issue but I am wondering whether this is the expected behaviour.

Maybe there is a lib function that I don't know the achieve the same without calling `jpeg_mem_dest` for every frame.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

Raspberry Pi 4B
project compiler: clang version 9.0.1-6+rpi1~bpo10+1
build of libjpegturbo: cc (Raspbian 8.3.0-6+rpi1) 8.3.0 (as selected by cmake)

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

tags/2.1.2

**Comment by dcommander** [comment]
Calling `jpeg_mem_dest()` with every frame is the right thing to do.  `tjCompress*()` in the TurboJPEG API (which wraps the libjpeg API) implements the same type of reusable buffer approach, and it calls `jpeg_mem_dest_tj()` with every frame.  (`jpeg_mem_dest_tj()` is an internal version of `jpeg_mem_dest()` that optionally allows dynamically buffer reallocation to be disabled.)  Note that you could probably use the TurboJPEG API to accomplish what you want with a lot less headache.   Since Debian doesn't package the TurboJPEG API, you could use [our official arm64 .deb package](https://sourceforge.net/projects/libjpeg-turbo/files/).
