### ISSUE TITLE
libjpeg-turbo cross-compile to Android fails

### ISSUE THREAD

**Issue by mattgruenke** [libjpeg-turbo/libjpeg-turbo#58]
I have encountered two issues that I think can't be sidestepped using any of the current CMake options.

The first is that -DUSE_SETMODE is hard-coded, for some executables that are always built.  Many platforms do not have setmode(), and I've even found that some platforms have a setmode() with an incompatible prototype.

The second issue is that the installation stage assumes executable filenames have a .exe extension.

Attached is a patch which resolves these problems.  I have not tested on other platforms.  But, the nature of the patch is such that you'll know if it worked simply by whether the build succeeds.

[libjpeg-turbo-1.4.2.patch.zip](https://github.com/libjpeg-turbo/libjpeg-turbo/files/139457/libjpeg-turbo-1.4.2.patch.zip)

**Comment by mattgruenke** [comment]
BTW, for anyone else who's trying the same thing, I also had to
`export CFLAGS="-DSIZEOF_SIZE_T=4"`

But that's simply an artifact of cross-compiling, and I'm not aware of a way to automate that via CMake.

**Comment by dcommander** [comment]
CMake is not supported as a build system for Android.  libjpeg-turbo 1.4.2 did not have complete Android build instructions for ARMv8, so it's probably best to refer to the latest instructions in Git master: 
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/BUILDING.md

If #56 ever becomes a reality, then we will fully support building libjpeg-turbo for all Un\*x platforms using CMake, but otherwise, our official support policy is:  autotools for Un\*x builds and CMake for Windows builds, QED.  I've explained in other tickets (linked from #56) why supporting only one build system per platform is the only sane way of managing this project.

**Comment by mattgruenke** [comment]
I'm sympathetic to the idea of having one buildsystem, but as long as there's any support for CMake, why not consider patches which fix things & move the project in the direction of #56?

If you look at the patch, it includes fixes in cdjpeg.c, rdjpgcom.c, and wrjpgcom.c that would also benefit other buildsystems.

**Comment by mattgruenke** [comment]
Please understand that I did not come here with an agenda to push CMake.  I made a good faith effort to build the package.  When I encountered problems, I spent a little extra time to prepare and submit a nice patch, in an attempt to help others and give back to the project.

As I said, I think the patch has value beyond the CMake toolchain.

**Comment by dcommander** [comment]
Please read the discussions linked to from #56.  I explain in those threads why doing things piecemeal isn't a good option.  Either CMake is fully supported on Un\*x (and autotools is removed), or it isn't supported on Un\*x at all.  I've heard all of the arguments, and my decision is to support only one build system per platform, QED.

**Comment by mattgruenke** [comment]
Thanks for the response & thanks for your efforts.  I appreciate a high-quality, speedy alternative to IJG's library.

I'm happy to contribute to the OSS projects I use, but the reality of my situation is that I can only do so in a piecemeal fashion.  I respect your judgement in managing this project, but the all-or-nothing approach does shut out a pool of potential contributors & contributions.
