### ISSUE TITLE
start to install

### ISSUE THREAD

**Issue by alicera** [libjpeg-turbo/libjpeg-turbo#580]
Q1: If building on Windows, nasm.exe/yasm.exe should be in your PATH.
     Does the project have use the var `-DCMAKE_ASM_NASM_COMPILER` ?
Q2: If using `-DCMAKE_ASM_NASM_COMPILER`, it need to the `-WITH_SIMD` for cmake?

**Comment by dcommander** [comment]
> Q1: If building on Windows, nasm.exe/yasm.exe should be in your PATH. Does the project have use the var `-DCMAKE_ASM_NASM_COMPILER` ?

Yes, you can use either the `CMAKE_ASM_NASM_COMPILER` CMake variable or the `ASM_NASM` environment variable to specify the path of NASM.  I have updated **BUILDING.md** to reflect that.

> Q2: If using `-DCMAKE_ASM_NASM_COMPILER`, it need to the `-WITH_SIMD` for cmake?

`WITH_SIMD` is enabled by default, but that variable will be automatically disabled if the build system encounters a problem with the assembler (or, in the case of non-x86 platforms, the SIMD intrinsics.)  Normally the build system will fall back to a non-SIMD build, but you can specify `-DREQUIRE_SIMD=1` to disable this fallback.
