### ISSUE TITLE
For clarity is 12bit useable now or work is starting/in progress?

### ISSUE THREAD

**Issue by Fredrum** [libjpeg-turbo/libjpeg-turbo#590]
Hello!
I'm just now looking for something to do 12bit single channel (grey scale) image stream/video compression and came across libjpeg-turbo. Iv'e read through some of the issues and see there's talk about this type of feature but I'm not getting a clear picture of if this is working right now or if it's something that's in progress or just starting?

Cheers!

**Comment by dcommander** [comment]
Referring to https://github.com/libjpeg-turbo/libjpeg-turbo/issues/199#issuecomment-1303932860, the 12-bit implementation has been completely refactored, so both 8-bit and 12-bit data precisions now share the same libjpeg API structures and all but a handful of libjpeg API functions.  Apologies if you had already started integrating the previous implementation.  I decided to go ahead and make a much cleaner implementation of it before it got released into the wild.
