### ISSUE TITLE
Add new function like tjLoadImageFromMemory 

### ISSUE THREAD

**Issue by nxdong** [libjpeg-turbo/libjpeg-turbo#596]
# For user can load image form memory directly.

for example:

DLLEXPORT unsigned char *tjLoadImageFromMemory(const unsigned char *fileBuf, unsigned long fileSize, int *width,
                                     int align, int *height, int *pixelFormat,
                                     int flags);

DLLEXPORT int tjSaveImageToMemory(const unsigned char *fileBuf, unsigned long fileSize, int *width, unsigned char *buffer,
                          int width, int pitch, int height, int pixelFormat,
                          int flags);

* user can use those functions without filesystem.

**Comment by dcommander** [comment]
That is what `tjCompress*()` and `tjDecompress*()` already do.
