### ISSUE TITLE
different floating point DCT accuracy characteristics causes test failures on exotic platforms

### ISSUE THREAD

**Issue by xen0n** [libjpeg-turbo/libjpeg-turbo#597]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

This is similar to #302 as LoongArch is not making use of SIMD currently, but it's preventing the test suite to cleanly pass on that platform, so probably worth a separate issue.

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

No.

**Clear and concise description of the bug:**

Fused floating-point multiply-add operations on LoongArch give higher accuracy than individual multiplications and additions, causing the tests generating `testout_3x2_float.ppm` to fail.

Hex diff shows very minimal changes to decoded pixels, as is confirmed by manual inspection of resulting images, but tests fail nevertheless and annoying.

Disabling optimizations makes the problem go away, but we probably don't want to do that, given SIMD is currently unavailable for the platform, and we certainly don't want it to get even slower.

This problem most likely also exists on Loongson's MIPS cores, and probably other architectures with similar behavior regarding FMA accuracy *and* without SIMD support. As we don't know exactly how these platforms behave, and that the floating-point DCT is considered "legacy", it may be okay to accept failures on this particular test for exotic platforms.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

- Find a LoongArch machine or set up a chroot
- `mkdir build && cd build && cmake .. -G Ninja && ninja && ctest -jNN` replacing NN with your preferred concurrency
- Observe failures

**Image(s) needed in order to reproduce the bug (if applicable):**

n/a

**Expected behavior:**

Tests pass

**Observed behavior:**

```
183/310 Test  #87: djpeg-shared-3x2-float-prog-cmp ...................***Failed    0.00 sec
...
275/310 Test #242: djpeg-static-3x2-float-prog-cmp ...................***Failed    0.00 sec
```

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

`loongarch64-unknown-linux-gnu`; CPU model is Loongson 3A5000.

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

Reproducible with tip of main branch.

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

n/a

**Additional information:**

This is found during testing of Gentoo on the LoongArch architecture; you could find more information on [the Gentoo project page](https://wiki.gentoo.org/wiki/Project:LoongArch), which also contains some instructions on setting up a chroot so people without real LoongArch hardware can also test.

**Comment by xen0n** [comment]
This is the expected/actual output from the testsuite: [issue597.zip](https://github.com/libjpeg-turbo/libjpeg-turbo/files/8648802/issue597.zip)

**Comment by dcommander** [comment]
This isn’t a bug. You just need to set the appropriate value of the `FLOATTEST` CMake variable for your platform. It is impossible to guess the appropriate value of that variable for all platforms.

**Comment by xen0n** [comment]
> This isn’t a bug. You just need to set the appropriate value of the `FLOATTEST` CMake variable for your platform. It is impossible to guess the appropriate value of that variable for all platforms.

Good to know; thanks for the quick reply!
