### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by introspection3** [libjpeg-turbo/libjpeg-turbo#599]
MSB8066	“simd\x86_64\jccolor-avx2.asm;simd\x86_64\jccolor-sse2.asm;simd\x86_64\jcgray-avx2.asm;simd\x86_64\jcgray-sse2.asm;simd\x86_64\jchuff-sse2.asm;simd\x86_64\jcphuff-sse2.asm;simd\x86_64\jcsample-avx2.asm;simd\x86_64\jcsample-sse2.asm;simd\x86_64\jdcolor-avx2.asm;simd\x86_64\jdcolor-sse2.asm;simd\x86_64\jdmerge-avx2.asm;simd\x86_64\jdmerge-sse2.asm;simd\x86_64\jdsample-avx2.asm;simd\x86_64\jdsample-sse2.asm;simd\x86_64\jfdctflt-sse.asm;simd\x86_64\jfdctfst-sse2.asm;simd\x86_64\jfdctint-avx2.asm;simd\x86_64\jfdctint-sse2.asm;simd\x86_64\jidctflt-sse2.asm;simd\x86_64\jidctfst-sse2.asm;simd\x86_64\jidctint-avx2.asm;simd\x86_64\jidctint-sse2.asm;simd\x86_64\jidctred-sse2.asm;simd\x86_64\jquantf-sse2.asm;simd\x86_64\jquanti-avx2.asm;simd\x86_64\jquanti-sse2.asm;simd\x86_64\jsimdcpu.asm”的自定义生成已退出，代码为 9009。	libjpeg-turbo-win	D:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	245

**Comment by dcommander** [comment]
I only speak English. Please translate the text of the error message.

**Comment by introspection3** [comment]
The custom build for has exited with code 9009 @dcommander

**Comment by dcommander** [comment]
Sorry, I do not understand. I need to know the text of the error message, not the error code.

**Comment by dcommander** [comment]
That error code generally means that a file was not found.  It is impossible for me to know why Visual Studio is generating that error, since you have not posted any context nor described how you are attempting to build libjpeg-turbo.
