### ISSUE TITLE
master no longer compiles with -DWITH_JPEG8=ON

### ISSUE THREAD

**Issue by ismail** [libjpeg-turbo/libjpeg-turbo#60]
Exact cmake command line:

`
cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=/home/ismail/github/hacks/mingw/toolchain-x86_64-w64-mingw32.cmake -DCMAKE_INSTALL_PREFIX=/opt/mingw64-static -DBUILD_SHARED_LIBS=OFF -DWITH_JPEG8=ON -DWITH_TURBOJPEG=OFF ..
`

ends up with:
`
FAILED: /usr/bin/x86_64-w64-mingw32-gcc  -DWITH_SIMD -Djpeg_EXPORTS -I. -I../ -O3 -DNDEBUG -MMD -MT sharedlib/CMakeFiles/jpeg.dir/__/jdapistd.c.obj -MF sharedlib/CMakeFiles/jpeg.dir/__/jdapistd.c.obj.d -o sharedlib/CMakeFiles/jpeg.dir/__/jdapistd.c.obj   -c ../jdapistd.c
../jdapistd.c: In function 'jpeg_crop_scanline':
../jdapistd.c:193:16: error: 'struct jpeg_decompress_struct' has no member named 'min_DCT_scaled_size'
   align = cinfo->min_DCT_scaled_size * cinfo->max_h_samp_factor;
`

**Comment by asavah** [comment]
Same with autotools:
./configure --with-jpeg8 leads to:
```
jdapistd.c: In function ‘jpeg_crop_scanline’:
jdapistd.c:193:16: error: ‘struct jpeg_decompress_struct’ has no member named ‘min_DCT_scaled_size’
   align = cinfo->min_DCT_scaled_size * cinfo->max_h_samp_factor;
```

**Comment by dcommander** [comment]
Sorry about that.  The tiled decoding feature broke the build.  Should be working now.

**Comment by ismail** [comment]
Thanks!
