### ISSUE TITLE
Add NO_GETENV cmake option 

### ISSUE THREAD

**Issue by fabiosky** [libjpeg-turbo/libjpeg-turbo#600]
Hello,

It seems that for very small image sizes, retrieving environment variables will dominate the total jpeg encode time.
The following gist is the minimal code representing my use case. I use the library to encode several small images, each one of a given size (e.g. 32x32), serially:

https://gist.github.com/fabiosky/2c992fc88f98f6a96b3bd413d45e74bf

I'm using main branch (but really makes no difference).

If I execute the application:
```
encode_test 32 32 1048576
Elapsed time: 29546892, Dummy counter: 0
```
So, almost 30 seconds (Intel Core i7-6600U 2.60 Ghz, Windows 10)

When recompiling the library with `NO_GETENV` defined I get:
```
encode_test 32 32 1048576
Elapsed time: 18733246, Dummy counter: 0
```

So it is almost half the time of the previous run.

I also profiled what is going on with the Visual Studio profiler:

Before:
```
   Function Name                    Exclusive Samples %
01 common_getenv_nolock<char>                    35.80%
02 jpeg_make_c_derived_tbl                       15.65%
03 emit_byte                                      9.20%
04 compute_reciprocal                             4.64%
05 jsimd_extbgr_ycc_convert_avx2                  4.32%
06 jsimd_huff_encode_one_block_sse2               3.07%
07 jsimd_fdct_ifast_sse2                          2.79%
08 jpeg_add_quant_table                           2.65%
09 emit_dht                                       2.16%
10 flss                                           2.03%
```

With  `NO_GETENV` defined, instead:

```
   Function Name                    Exclusive Samples %
01 jpeg_make_c_derived_tbl                       20.75%
02 emit_byte                                     14.48%
03 compute_reciprocal                             7.41%
04 jsimd_extbgr_ycc_convert_avx2                  6.09%
05 jpeg_add_quant_table                           5.58%
06 jsimd_huff_encode_one_block_sse2               5.32%
07 jsimd_fdct_ifast_sse2                          4.26%
08 flss                                           3.83%
09 emit_dht                                       3.26%
10 RtlpLowFragHeapAllocFromContext                1.91%
```

My question is. Since I really do not need environment variable dynamic override, is there a way to add a cmake parameter to build with 
`NO_GETENV` defined?

Thanks,
Fabio

**Comment by nacho** [comment]
Thanks for the info!

**Comment by fabiosky** [comment]
Thanks!
