### ISSUE TITLE
Allow libjpeg-turbo to load JPEG coefficient tables from TIFF

### ISSUE THREAD

**Issue by amyspark** [libjpeg-turbo/libjpeg-turbo#604]
Hi,

I've been working towards implementing TIFF + JPEG + YCbCr support in Krita, with the help of libjpeg-turbo. The branch is available [here](https://invent.kde.org/lsegovia/krita/-/tree/work/amyspark/tiff-2).

To achieve it, a key step is to prime the decoder with the Huffman/arithmetic coding coefficient tables. This is done in raw libjpeg with the help of [jpeg_read_header](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/1f55ae7b0fa3acc348a630171617d0e56d922b68/jdapimin.c#L254), which is what libtiff uses.

Since this codepath is not available in libjpeg-turbo, and the planar decoding API is very much useful to me, I've written a patch which is available [in the amyspark/libjpeg-turbo](https://github.com/amyspark/libjpeg-turbo/tree/amyspark/libtiff) branch of my fork.

Would such an enhancement be acceptable for you?

**Comment by amyspark** [comment]
> Would it make sense to incorporate this functionality into the existing tjDecompressHeader3() function? 

Sure, let me work on it. Once I have it working @dcommander, should I send the PR or ping you first?

**Comment by dcommander** [comment]
You can go ahead and submit it as a PR.  Please modify the copyright header of **turbojpeg.c** and **turbojpeg.h** to attribute the new code to either yourself (if you are developing the new code as an individual) or your employer (if you are developing the new code as a work for hire.)

**Comment by dcommander** [comment]
Implemented and pushed.  Please test.
