### ISSUE TITLE
jpeg_mem_dest buffer keeps growing while compressing YUV420 data on RasPi3 ARM

### ISSUE THREAD

**Issue by alanszlosek** [libjpeg-turbo/libjpeg-turbo#610]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

Yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

No

**Clear and concise description of the bug:**

On a RasPi 3B+, I'm encoding YUV420 data to JPEG using `jpeg_write_raw_data()`. The jpeg_mem_dest buffer keeps growing. Eventually it OOMs my long-running process.

I was testing with 1920x1080 YUV420 data acquired from libcamera-still (`libcamera-still -n --width 1920 --height 1080 -e yuv420 -o test.yuv`). I can provide sample data if you'd like.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

* Acquire YUV420p data, where planes are in order in a single file. Y data, then U data, then V data. Save to file.
* Update yuv path in C++ code line 95 (see code below)
* Compile yuv.cpp sample code (see Makefile below)
* Run `./yuv`
* Notice the buffer length keeps growing, as do the generated JPEG file sizes

**Image(s) needed in order to reproduce the bug (if applicable):**

**Expected behavior:**

jpeg_mem_dest buffer doesn't keep growing.

**Observed behavior:**

Buffer keeps growing and OOMs my process. Each jpeg gets larger and larger, even from the same input data.

Program output:

```Length of jpeg_mem_dest buffer: 419344
Length of jpeg_mem_dest buffer: 838688
Length of jpeg_mem_dest buffer: 1258032
Length of jpeg_mem_dest buffer: 1677376
Length of jpeg_mem_dest buffer: 2096720
Length of jpeg_mem_dest buffer: 2516064
Length of jpeg_mem_dest buffer: 2935408
Length of jpeg_mem_dest buffer: 3354752
Length of jpeg_mem_dest buffer: 3774096
```

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

* RasPi 3B+ running the Debian 11 version of the RasPi OS
* libjpeg62-turbo-dev/stable 1:2.0.6-4 arm64 package.
* Debian clang version 11.0.1-2. Target: aarch64-unknown-linux-gnu. Thread model: posix

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

2.0.6-4 arm64 debian package

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

```
#include <iomanip>
#include <iostream>
#include <memory>

typedef struct PiMeraSettings {
    unsigned int width;
    unsigned int height;
    unsigned int stride;
} PiMeraSettings;


#include <jpeglib.h>
#if JPEG_LIB_VERSION_MAJOR > 9 || (JPEG_LIB_VERSION_MAJOR == 9 && JPEG_LIB_VERSION_MINOR >= 4)
typedef size_t jpeg_mem_len_t;
#else
typedef unsigned long jpeg_mem_len_t;
#endif


int frame_counter = 0;
void processingThread(const PiMeraSettings *settings) {
    //other settings
    int jpeg_quality = 90;

    // testing stuff
    int buf_len = settings->width * settings->height * 1.5;
    uint8_t* buf;
    FILE* in;

    // BEGIN JPEG STUFF
    // much of this guided by libcamera-apps repo
    // set up jpeg stuff once
    char filename[40];
    uint8_t* jpeg_buffer;
    uint8_t *Y;
    uint8_t *U;
    uint8_t *V;
    size_t Y_size;
    size_t U_size;
    size_t V_size;
    uint8_t* Y_max;
    uint8_t* U_max;
    uint8_t* V_max;
    jpeg_mem_len_t jpeg_len;
    struct jpeg_compress_struct cinfo;
    struct jpeg_error_mgr jerr;
    int stride2 = settings->stride / 2;

    // libjpeg allocates its own buffer. so this needs to be NULL
    jpeg_len = 0;
    jpeg_buffer = NULL;

    cinfo.err = jpeg_std_error(&jerr);
    jpeg_create_compress(&cinfo);

    cinfo.image_width = settings->width;
    cinfo.image_height = settings->height;
    cinfo.input_components = 3;
    cinfo.in_color_space = JCS_YCbCr;
    cinfo.jpeg_color_space = cinfo.in_color_space;
    cinfo.restart_interval = 0;

    //jpeg_set_colorspace(&cinfo, cinfo.in_color_space);
    jpeg_set_defaults(&cinfo);
    cinfo.raw_data_in = TRUE;
    jpeg_set_quality(&cinfo, jpeg_quality, TRUE);
    jpeg_mem_dest(&cinfo, &jpeg_buffer, &jpeg_len);
    
    JSAMPROW y_rows[16];
    JSAMPROW u_rows[8];
    JSAMPROW v_rows[8];
    JSAMPARRAY rows[] = { y_rows, u_rows, v_rows };
    
    // END JPEG STUFF

    // testing stuff
    buf = (uint8_t*)malloc(buf_len);
    Y_size = settings->width * settings->height;
    U_size = V_size = (settings->width/2) * (settings->height/2);
    Y = buf;
    U = buf + Y_size;
    V = buf + Y_size + U_size;
   
    Y_max = (Y + Y_size) - settings->stride;
    U_max = (U + U_size) - stride2;
    V_max = (V + V_size) - stride2;


    int i = 1;
    while (i < 10) {
        i++;
        frame_counter++;

        in = fopen("/home/pi/temp/test.yuv", "rb");
        fread(buf, buf_len, 1, in);
        fclose(in);

        jpeg_start_compress(&cinfo, TRUE);

        for (uint8_t *Y_row = Y, *U_row = U, *V_row = V; cinfo.next_scanline < settings->height;)
        {
            for (int i = 0; i < 16; i++, Y_row += settings->stride) {
                y_rows[i] = std::min(Y_row, Y_max);
            }
            for (int i = 0; i < 8; i++, U_row += stride2, V_row += stride2) {
                u_rows[i] = std::min(U_row, U_max);
                v_rows[i] = std::min(V_row, V_max);
            }
            jpeg_write_raw_data(&cinfo, rows, 16);
        }
        jpeg_finish_compress(&cinfo);
        printf("Length of jpeg_mem_dest buffer: %lu\n", jpeg_len);

        snprintf(filename, 40, "%d.jpeg", frame_counter);
        FILE* fp = fopen(filename, "wb");
        fwrite(jpeg_buffer, jpeg_len, 1, fp);
        fclose(fp);
    }
    jpeg_destroy_compress(&cinfo);
    
    return;
}

int main()
{
    PiMeraSettings settings;
    settings.width = 1920;
    settings.height = 1080;
    settings.stride = settings.width;

    processingThread(&settings);


    return 0;
}
```

Makefile

```
yuv: yuv.cpp
	clang++ -g -std=c++17 -o yuv \
		-L /usr/lib/aarch64-linux-gnu \
		-l jpeg \
		yuv.cpp
```

**Comment by dcommander** [comment]
Please provide a **test.yuv** file.

**Comment by alanszlosek** [comment]
No problem, I've attached one to this message. Had to wrap it in a zip.

[test.zip](https://github.com/libjpeg-turbo/libjpeg-turbo/files/9103909/test.zip)

**Comment by dcommander** [comment]
More details:

The destination manager's `init_destination()` method is called within the body of `jpeg_start_compress()`, and the destination manager's `term_destination()` method is called within the body of `jpeg_finish_compress()`.  (In the case of the memory destination manager, the `init_destination()` method is a no-op.)  The crux of the issue is that the destination manager's `next_output_byte` and `free_in_buffer` fields do not get reset between iterations of the loop, so the destination manager thinks that the buffer is exhausted and continues trying to grow it.  You could manually reset the `next_output_byte` and `free_in_buffer` fields at the end of each iteration, but that wouldn't reset the memory destination manager's hidden `newbuffer` field, so the buffer may still grow unnecessarily (but only to about twice of its needed size, not out of control as you observed.)  The most reliable solution is, per above, to call `jpeg_mem_dest()` once for each pair of `jpeg_start_compress()`/`jpeg_finish_compress()` calls.  That is what the TurboJPEG API does.  (Incidentally, you can probably use the much simpler `tjCompressFromYUVPlanes()` function rather than futzing with the libjpeg API.)

**Comment by alanszlosek** [comment]
Thank you for that detailed response, I should be able to try those suggestions tomorrow.

`tjCompressFromYUVPlanes()` sounds better, but ultimately I want to use whatever's the most performant (SIMD, etc). Are the TurboJPEG and libjpeg APIs similar performance-wise?

**Comment by dcommander** [comment]
In libjpeg-turbo, the TurboJPEG API is basically just a wrapper for the libjpeg API, so the performance for identical operations should be identical.  The SIMD routines are at the lowest level of the libjpeg-turbo architecture and are used by all of the external APIs.  Unless I miss my guess, the `tjCompressFromYUVPlanes()` function is doing essentially the same thing that your code is doing, so it should perform similarly.
