### ISSUE TITLE
Use-of-uninitialized-value with MSAN (jpeg-v9c)

### ISSUE THREAD

**Issue by Tricker-z** [libjpeg-turbo/libjpeg-turbo#612]
Hi, developers of libjpeg:

Recently, I test the binary `djpeg` instrumented with MSAN (in jpeg-v9c). Unfortunately, it incurred a crash with the following error information.  Any help would be greatly appreciated from you :D

```
Corrupt JPEG data: 10 extraneous bytes before marker 0xdb
P6
6 15
255
==15969==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x562e829cc1c6 in h2v2_merged_upsample jdmerge.c
    #1 0x562e829ca817 in merged_2v_upsample jdmerge.c
    #2 0x562e82a50065 in process_data_simple_main jdmainct.c
    #3 0x562e82985468 in jpeg_read_scanlines (/workspace/jpeg-9c/djpeg+0xca468) (BuildId: 0d96ba5610ec5b738719575ca310980e916cfc3e)
    #4 0x562e82961640 in main (/workspace/jpeg-9c/djpeg+0xa6640) (BuildId: 0d96ba5610ec5b738719575ca310980e916cfc3e)
    #5 0x7f7e3205ad8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 89c3cb85f9e55046776471fed05ec441581d1969)
    #6 0x7f7e3205ae3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: 89c3cb85f9e55046776471fed05ec441581d1969)
    #7 0x562e828da304 in _start (/workspace/jpeg-9c/djpeg+0x1f304) (BuildId: 0d96ba5610ec5b738719575ca310980e916cfc3e)

SUMMARY: MemorySanitizer: use-of-uninitialized-value jdmerge.c in h2v2_merged_upsample
Exiting
```

---

**Crash input**

Here is the file that triggers the error - [djpeg.tar.gz](https://github.com/libjpeg-turbo/libjpeg-turbo/files/9226553/djpeg.tar.gz)

Thanks & Best regards !

**Comment by dcommander** [comment]
jpeg-9c is maintained by the IJG (Guido Vollbeding), not us. Is the error reproducible with libjpeg-turbo?

**Comment by Tricker-z** [comment]
Oh I see, it was my fault, and the error is not reproducible with libjpeg-turbo. I'll close the issue and turn to IJG.

**Comment by dcommander** [comment]
You filed an identical bug report under https://github.com/libjpeg-turbo/ijg, which is still controlled by our organization. Note that the IJG is not on GitHub. You will need to contact them through email, using the contact info provided in the jpeg-9c README file.
