### ISSUE TITLE
Uncaught RuntimeError: unreachable in wasm 

### ISSUE THREAD

**Issue by cucibala** [libjpeg-turbo/libjpeg-turbo#614]
` 
#define RGB_COUNT 3
#define JPEG_QUALITY 10
  //定义一个压缩对象，这个对象用于处理主要的功能
struct jpeg_compress_struct jpeg;
//用于错误信息
struct jpeg_error_mgr jerr;
int rgb2jpgAction(struct jpeg_compress_struct pCinfo, const char *pRgbData, const int width, const int height)
{
    int depth = RGB_COUNT;
    JSAMPROW row_pointer[1];
 
    pCinfo.image_width      = width;
    pCinfo.image_height     = height;
    pCinfo.input_components = depth;
    pCinfo.in_color_space   = JCS_EXT_BGR;
    jpeg_set_defaults(&pCinfo); 
    jpeg_set_quality(&pCinfo, JPEG_QUALITY, TRUE);
    jpeg_start_compress(&pCinfo, TRUE);
    int row_stride = width * depth;
    while (pCinfo.next_scanline < pCinfo.image_height)
    {
        int x = pCinfo.next_scanline * row_stride;
        row_pointer[0] = (JSAMPROW)(pRgbData + x);
        jpeg_write_scanlines(&pCinfo, row_pointer, 1);
        LOG_DEBUG("%d, %d", x, pCinfo.next_scanline);
    }

    jpeg_finish_compress(&pCinfo);
    jpeg_destroy_compress(&pCinfo);

    return 0;
}

size_t ImageUtils::rgb2jpg(const char *pRgbData, const int width, const int height, unsigned char** pDest)
{
    long unsigned int pSize = width * height * RGB_COUNT;
    struct jpeg_compress_struct cinfo;
    struct jpeg_error_mgr jerr;
    cinfo.err = jpeg_std_error(&jerr);
    jpeg_create_compress(&cinfo);
    jpeg_mem_dest(&cinfo, pDest, &pSize);
    rgb2jpgAction(cinfo, pRgbData, width, height);
    LOG_DEBUG("pSIze:%d ", pSize);
    return pSize;
} 
`  
It can run the loop correctly a few times, but at a certain number of times there will be an exception, and the place where the exception occurs is jpeg_write_scanlines, whether it is a problem with the wasm environment or a problem with my code, I don't know if anyone else has encountered this error

**Comment by cucibala** [comment]
![image](https://user-images.githubusercontent.com/48320342/184835931-88ad738b-dad7-4ccd-8f29-cd3f5e57c29d.png)

**Comment by dcommander** [comment]
That error message is from WASM, not from libjpeg-turbo.  I don't see any obvious issues in your code, but you are using the default error manager (`jpeg_std_error()`), which exits the program if a libjpeg API error occurs.  It may be that a legitimate libjpeg API error occurs, which causes the program to exit, and that may trigger the `unreachable` error in WASM.  I would suggest implementing your own error manager to catch the error, as demonstrated in [example.txt](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/example.txt), or using the TurboJPEG API, which does all of that for you.  Once I know which libjpeg API error is being thrown, then I can give you better advice as to how to fix it.

**Comment by cucibala** [comment]
如果我直接用自己的数据，同样会导致，相同的错误 “Uncaught RuntimeError: unreachable”, 如果我构造一段数据 入r g b 所有的位都设置为234，这样子不会报上面的异常，但是压缩后的图片是不正确的。下面是我的图片
![image](https://user-images.githubusercontent.com/48320342/185017196-e6fb99b6-0cee-4114-b5c5-645bbde19971.png)

**Comment by cucibala** [comment]
To add to this, I also tried the jpeglib api method to generate this incorrect image

**Comment by cucibala** [comment]
I compiled with g c c and wrote the test method, the same code generated the picture is normal, will not generate the wrong picture

**Comment by cucibala** [comment]
I found the reason, probably related to my jconfig.h configuration, I re-edited it, and then replaced the latest jconfig.h and then the problem is solved, thank you for the answer
