### ISSUE TITLE
Segfault in jsimd_rgb_ycc_convert_avx2 upon misuse

### ISSUE THREAD

**Issue by petab1te** [libjpeg-turbo/libjpeg-turbo#615]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No

**Clear and concise description of the bug:**
Misuse of the library with a malformed image can cause a SIGSEGV on linux. I have not been able to track what exact misuse causes the bug other than the function which is segfaulting: jsimd_rgb_ycc_convert_avx2

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
Clone this broken testing app: git clone https://github.com/petab1te/bggp3harness
Compile with: gcc jpeg_sample.c
Run the test app with the safe image to prove it works under perfect conditions: ./a.out test.jpg
Run the test app with the provided altered image: ./a.out crash.jpeg

**Image(s) needed in order to reproduce the bug (if applicable):**
[https://github.com/petab1te/bggp3harness/blob/master/crash.jpeg](url)

**Expected behavior:**
The expected behavior is to exit safely or throw an error.

**Observed behavior:**
The observer behavior is a SIGSEGV crash.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
Linux, gcc 12.2.0, 5.19.2-artix1-2, AMD Ryzen 9 5900HS with Radeon Graphics

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
2.1.4 and 2.1.3

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

**Comment by dcommander** [comment]
You admit that the issue is caused by misuse of the library, so why are you filing this as a bug against libjpeg-turbo?

**Comment by dcommander** [comment]
Very likely, your application is overrunning the buffer it creates.  There is no way for any library to safely handle that.  I would suggest using valgrind to figure out where the buffer overrun is occurring.  That is exactly what I would do to diagnose the failure, but it isn't my job to diagnose other people's code, nor do I have the budget for that.

The libjpeg API is admittedly not very user-friendly or user-proof.  It's a 30-year-old API that was designed around the needs of MS-DOS systems.  If you're looking for something more friendly, use the TurboJPEG API instead.
