### ISSUE TITLE
Potentially uninitialized memory in output with fuzz testcase

### ISSUE THREAD

**Issue by agoodm88** [libjpeg-turbo/libjpeg-turbo#619]
**Clear and concise description of the bug:**
While fuzzing libjpeg-turbo with a custom collected cminned and tminned corpus I've located a potential bug which (according to the msan/valgrind causes uninitialized memory to be outputted.  I've triaged this with valgrind using --malloc-fill and it seems the uninitialized memory does not alter the output data however I still thought this was interesting enough to report anyway as I am not terribly experienced in this.

alan@fuzz:~$ /home/alan/libjpeg-turbo_msan/djpeg id7_mod.jpg >/dev/null
Premature end of JPEG file
Uninitialized bytes in __interceptor_fwrite at offset 0 inside [0x7280000001a0, 12285)
==2440436==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x4a13d3 in main /home/alan/libjpeg-turbo_msan/djpeg.c:797:7
    #1 0x7f6e47899d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #2 0x7f6e47899e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #3 0x421434 in _start (/home/alan/libjpeg-turbo_msan/djpeg+0x421434)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/alan/libjpeg-turbo_msan/djpeg.c:797:7 in main

alan@littlebrat:~/scratch/jpg$ valgrind --track-origins=yes djpeg id7_mod.jpg >/dev/null
==144454== Memcheck, a memory error detector
==144454== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==144454== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==144454== Command: djpeg id7_mod.jpg
==144454== 
Premature end of JPEG file
==144454== Syscall param write(buf) points to uninitialised byte(s)
==144454==    at 0x4A09A37: write (write.c:26)
==144454==    by 0x497FF6C: _IO_file_write@@GLIBC_2.2.5 (fileops.c:1180)
==144454==    by 0x4981A60: new_do_write (fileops.c:448)
==144454==    by 0x4981A60: _IO_new_do_write (fileops.c:425)
==144454==    by 0x4981A60: _IO_do_write@@GLIBC_2.2.5 (fileops.c:422)
==144454==    by 0x4980754: _IO_new_file_xsputn (fileops.c:1243)
==144454==    by 0x4980754: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==144454==    by 0x4975056: fwrite (iofwrite.c:39)
==144454==    by 0x10ACE1: ??? (in /usr/bin/djpeg)
==144454==    by 0x491ED8F: (below main) (libc_start_call_main.h:58)
==144454==  Address 0x4b7f8b9 is 9 bytes inside a block of size 4,096 alloc'd
==144454==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==144454==    by 0x4973C23: _IO_file_doallocate (filedoalloc.c:101)
==144454==    by 0x4982D5F: _IO_doallocbuf (genops.c:347)
==144454==    by 0x4981FDF: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==144454==    by 0x4980754: _IO_new_file_xsputn (fileops.c:1243)
==144454==    by 0x4980754: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==144454==    by 0x496A1CC: outstring_func (vfprintf-internal.c:239)
==144454==    by 0x496A1CC: __vfprintf_internal (vfprintf-internal.c:1263)
==144454==    by 0x4A29EC2: __fprintf_chk (fprintf_chk.c:33)
==144454==    by 0x10ACB0: ??? (in /usr/bin/djpeg)
==144454==    by 0x491ED8F: (below main) (libc_start_call_main.h:58)
==144454== 
==144454== Syscall param write(buf) points to uninitialised byte(s)
==144454==    at 0x4A09A37: write (write.c:26)
==144454==    by 0x497FF6C: _IO_file_write@@GLIBC_2.2.5 (fileops.c:1180)
==144454==    by 0x498084F: new_do_write (fileops.c:448)
==144454==    by 0x498084F: _IO_new_file_xsputn (fileops.c:1254)
==144454==    by 0x498084F: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==144454==    by 0x4975056: fwrite (iofwrite.c:39)
==144454==    by 0x10ACE1: ??? (in /usr/bin/djpeg)
==144454==    by 0x491ED8F: (below main) (libc_start_call_main.h:58)
==144454==  Address 0x4b24d98 is 12,712 bytes inside a block of size 16,343 alloc'd
==144454==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==144454==    by 0x48ACBA5: ??? (in /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2)
==144454==    by 0x48972CD: ??? (in /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2)
==144454==    by 0x489F36B: ??? (in /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2)
==144454==    by 0x489E23E: ??? (in /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2)
==144454==    by 0x4891CCE: jpeg_consume_input (in /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2)
==144454==    by 0x4891F21: jpeg_read_header (in /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2)
==144454==    by 0x10A6D1: ??? (in /usr/bin/djpeg)
==144454==    by 0x491ED8F: (below main) (libc_start_call_main.h:58)
==144454== 
==144454== Syscall param write(buf) points to uninitialised byte(s)
==144454==    at 0x4A09A37: write (write.c:26)
==144454==    by 0x497FF6C: _IO_file_write@@GLIBC_2.2.5 (fileops.c:1180)
==144454==    by 0x4981A60: new_do_write (fileops.c:448)
==144454==    by 0x4981A60: _IO_new_do_write (fileops.c:425)
==144454==    by 0x4981A60: _IO_do_write@@GLIBC_2.2.5 (fileops.c:422)
==144454==    by 0x497F557: _IO_file_sync@@GLIBC_2.2.5 (fileops.c:798)
==144454==    by 0x4974229: fflush (iofflush.c:40)
==144454==    by 0x10C008: ??? (in /usr/bin/djpeg)
==144454==    by 0x10AA7F: ??? (in /usr/bin/djpeg)
==144454==    by 0x491ED8F: (below main) (libc_start_call_main.h:58)
==144454==  Address 0x4b7f8bf is 15 bytes inside a block of size 4,096 alloc'd
==144454==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==144454==    by 0x4973C23: _IO_file_doallocate (filedoalloc.c:101)
==144454==    by 0x4982D5F: _IO_doallocbuf (genops.c:347)
==144454==    by 0x4981FDF: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==144454==    by 0x4980754: _IO_new_file_xsputn (fileops.c:1243)
==144454==    by 0x4980754: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==144454==    by 0x496A1CC: outstring_func (vfprintf-internal.c:239)
==144454==    by 0x496A1CC: __vfprintf_internal (vfprintf-internal.c:1263)
==144454==    by 0x4A29EC2: __fprintf_chk (fprintf_chk.c:33)
==144454==    by 0x10ACB0: ??? (in /usr/bin/djpeg)
==144454==    by 0x491ED8F: (below main) (libc_start_call_main.h:58)
==144454==  Uninitialised value was created by a heap allocation
==144454==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==144454==    by 0x48ACDE4: ??? (in /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2)
==144454==    by 0x48ACF4D: ??? (in /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2)
==144454==    by 0x48ADB1C: jinit_upsampler (in /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2)
==144454==    by 0x48A0808: jinit_master_decompress (in /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2)
==144454==    by 0x4895284: jpeg_start_decompress (in /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2)
==144454==    by 0x10A8F2: ??? (in /usr/bin/djpeg)
==144454==    by 0x491ED8F: (below main) (libc_start_call_main.h:58)
==144454== 
==144454== 
==144454== HEAP SUMMARY:
==144454==     in use at exit: 0 bytes in 0 blocks
==144454==   total heap usage: 14 allocs, 14 frees, 398,542 bytes allocated
==144454== 
==144454== All heap blocks were freed -- no leaks are possible
==144454== 
==144454== For lists of detected and suppressed errors, rerun with: -s
==144454== ERROR SUMMARY: 4095 errors from 3 contexts (suppressed: 0 from 0)

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
Decompress attached image.

**Image(s) needed in order to reproduce the bug (if applicable):**
Attached

**Expected behavior:**
I believe the image is invalid in construction, so an error should be thrown.  Other jpeg decompression library refuse to process the file.

**Observed behavior:**
Outputted image with pretty, but deterministic patterns.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
Various, libjpeg-turbo version used by Google and others produces the same output as the version used on Ubuntu 22.04.

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
I am sorry; I dont know.

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**
I am sorry; I dont know.

**Additional information:**
![id7_mod](https://user-images.githubusercontent.com/74600896/191872322-9000d61a-d444-4579-80be-2793bde7a6c5.jpg)

**Comment by dcommander** [comment]
I’ll look at it when I get back to the lab next week, but it looks like a false positive I have seen before. Valgrind and MSan don’t do a very good job of detecting memory initialization by assembly code, so we disable the SIMD code when running libjpeg-turbo through MSan.

**Comment by agoodm88** [comment]
This explanation feels quite plausible because my malloc-fill testing does not find any variation in the output.  

I've not triaged the results of my fuzzing a great deal because I ran into this behaviour while triaging test cases defined by AFL as 'variable behaviour' as part of troubleshooting the fuzzing harness due to slightly reduced stability score.  Does the aforementioned memory initialization detection stuff also impact AFL? (I am fuzzing a binary instrumented with just AFL or Honnggfuzz and then triaging separately with some custom ideas and normal MSAN/ASAN/UBSAN builds)

**Comment by dcommander** [comment]
Very likely it does affect those fuzzers. We disable SIMD code with MSan in OSS-Fuzz. Try re-building with `WITH_SIMD` disabled. If the problem goes away, then it’s the same known issue that has existed since the beginning of libjpeg-turbo.

**Comment by agoodm88** [comment]
Yes no errors seen with MSAN build completed with WITH_SIMD disabled.  I am running the entire corpus through the msan build but dont expect to find anything interesting at this point.

Are you interested in UBSAN finds at all?

**Comment by dcommander** [comment]
Yes, if I can reproduce them.

**Comment by dcommander** [comment]
Closing as SEP, since this bug report describes a known issue with libjpeg-turbo's SIMD extensions and valgrind or MSan.  Please file a separate bug report for UBSan issues.

**Comment by obfuscated** [comment]
I've hit a similar issue while running my application which uses libjpeg-turbo under valgrind.
Using `example decompress source.jpg dest.ppm` on the affected image reproduces the same way. Turning off SIMD "solves" the problem.
Have you tried to report this problem to valgrind people? It seems the latest version (3.21) still exhibits the problem.

Also saving the image using gimp to another jpg file fixes the problem, too.

**Comment by dcommander** [comment]
@obfuscated It's been an issue for all of the 13 years that libjpeg-turbo has been a project, and other projects with assembly code have the same issue.  I gather that it's a fundamental limitation of the memory checker tools in general.  The Chromium developers even went to the trouble of [documenting the limitation](https://www.chromium.org/developers/testing/memorysanitizer/), which also affects libvpx, libyuv, and ffmpeg.  I don't know if a wholesale rewrite of the x86-64 assembly code using intrinsics (as proposed in #732) would work around the limitation.  (Someone could test that now by building libjpeg-turbo, with the Neon SIMD extensions enabled, for Linux/AArch64 using Clang.  If valgrind and MSan work properly with that build, then there's a good chance that those tools would work properly with an intrinsics implementation of the x86-64 SIMD extensions.)

MSan uses compile-time instrumentation, so I doubt it could ever be made to work properly with raw assembly code (except maybe intrinsics, per above, but I'm not sure about that.)  valgrind, however, dynamically disassembles and reassembles the executable code in real time and runs it on a virtual CPU.  Thus, it may be possible to make valgrind work properly with our SIMD extensions by modifying one or the other or both, or it may simply be too difficult or slow for valgrind to track and emulate SIMD instructions on its virtual CPU.  Note that I haven't retested this issue since we modified the x86-64 assembly functions to use a standard stack frame (which landed in the recent libjpeg-turbo 3.0.1 release.)

**Comment by obfuscated** [comment]
I've tried both `main` build and the latest release. Both fail the same way. I'm interested in valgrind only.
MSan looked like something impossible to setup on a user machine. And for it to work a llvm-asm compiler would be required (one that turns the asm in llvm ir, which is then compiled to machine code).

@dcommander Do you remember what is the instruction pattern that fails to work correctly with valgrind?

**Comment by dcommander** [comment]
> I've tried both `main` build and the latest release. Both fail the same way. I'm interested in valgrind only.
> 
> MSan looked like something impossible to setup on a user machine. And for it to work a llvm-asm compiler would be required (one that turns the asm in llvm ir, which is then compiled to machine code).

MSan is no more difficult to use than valgrind. You simply install the package and pass specific compiler and linker flags when building the code. All of the major Linux distros include a package for it. But yes, I think it does require Clang. 

> @dcommander Do you remember what is the instruction pattern that fails to work correctly with valgrind?

I don't know that it was ever one specific pattern. I seem to recall that it had something to do with the SIMD instructions, but I may be misremembering that. The conversations regarding this issue took place in the 2010-2011 timeframe on SourceForge, so I'll try to dig them up on Monday.

**Comment by dcommander** [comment]
Here's an old thread in which I was able to reproduce a similar issue with valgrind, but only with specific versions of valgrind:
https://sourceforge.net/p/libjpeg-turbo/bugs/48
and another thread in which the issue was narrowed down to the SSE2 YCbCr-to-RGB color converter:
https://sourceforge.net/p/libjpeg-turbo/bugs/82
More specifically, the Chromium developers narrowed it down to the `maskmovdqu` instruction and worked around it:
https://bugs.chromium.org/p/chromium/issues/detail?id=72399
but their workaround caused problems, because they failed to account for unaligned image rows (Chromium's image buffers are apparently always 16-byte-aligned):
https://sourceforge.net/p/libjpeg-turbo/mailman/libjpeg-turbo-devel/thread/20120608141547.4c8c4236%40ossman.lkpg.cendio.se/#msg29379367

As far as I know, the original issue was due to the `maskmovdqu` instruction, which the SIMD code no longer uses.  (We eventually adopted the workaround from Chromium, once the bugs with it were fixed.)
