### ISSUE TITLE
Parallel build with Java enabled fails using autotools build

### ISSUE THREAD

**Issue by mayeut** [libjpeg-turbo/libjpeg-turbo#62]
Parallel build with Java enabled fails using autotools build.
Tested on:
`Mac OS X 10.11.3`
`automake 1.15`
`autoconf 2.69`

Configured with: `../libjpeg-turbo/configure --host i686-apple-darwin --with-java --with-pic --with-simd  CFLAGS="-m32 -O3 -mmacosx-version-min=10.5" LDFLAGS="-m32" CC=/usr/local/opt/gcc/bin/gcc-5`

Here's the log output:
```
Matt$ make -j8
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in java
 cd ../../libjpeg-turbo && /bin/sh /Users/Matt/Dev/libjpeg-turbo/libjpeg-turbo/missing automake-1.15 --foreign java/Makefile
 cd .. && /bin/sh ./config.status java/Makefile 
config.status: creating java/Makefile
make[2]: *** No rule to make target `TJExample.class', needed by `turbojpeg.jar'.  Stop.
make[2]: *** Waiting for unfinished jobs....
CLASSPATH=.:../../libjpeg-turbo/java/.${CLASSPATH:+":$CLASSPATH"} javac -d .  -target 1.5 -source 1.5  ../../libjpeg-turbo/java/org/libjpegturbo/turbojpeg/TJ.java ../../libjpeg-turbo/java/org/libjpegturbo/turbojpeg/TJCompressor.java ../../libjpeg-turbo/java/org/libjpegturbo/turbojpeg/TJCustomFilter.java ../../libjpeg-turbo/java/org/libjpegturbo/turbojpeg/TJDecompressor.java ../../libjpeg-turbo/java/org/libjpegturbo/turbojpeg/TJException.java ../../libjpeg-turbo/java/org/libjpegturbo/turbojpeg/TJScalingFactor.java ../../libjpeg-turbo/java/org/libjpegturbo/turbojpeg/TJTransform.java ../../libjpeg-turbo/java/org/libjpegturbo/turbojpeg/TJTransformer.java ../../libjpeg-turbo/java/org/libjpegturbo/turbojpeg/YUVImage.java ../../libjpeg-turbo/java/TJExample.java ../../libjpeg-turbo/java/TJUnitTest.java ../../libjpeg-turbo/java/TJBench.java org/libjpegturbo/turbojpeg/TJLoader.java
warning: [options] bootstrap class path not set in conjunction with -source 1.5
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
4 warnings
echo timestamp > classnoinst.stamp
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Replacing the rule `turbojpeg.jar: $(JAVA_CLASSES) ${srcdir}/MANIFEST.MF` with `turbojpeg.jar: classnoinst.stamp ${srcdir}/MANIFEST.MF` in `java/Makefile.am` does the trick but I doubt this is the right way to do it & my knowledge of autotools does not allow me to propose a patch.

**Comment by dcommander** [comment]
This is a long-standing problem.  I usually just work around it by running `make -j{jobs}` multiple times until it succeeds.  I'll see if I can figure out a better approach.  I think parallel make also fails on the SIMD extensions.

**Comment by mayeut** [comment]
I never had any problems with parallel builds before adding the `--with-java` switch. Maybe that's just luck. Anyway, really minor but just thought it should be reported.

**Comment by dcommander** [comment]
I don't really see a better solution than the one you came up with.  This is one argument in favor of dropping autotools in favor of CMake (refer to #56), since CMake generally does a much better job of dependency resolution.
