### ISSUE TITLE
[Help document bug] For tjbench, the help document misses some options

### ISSUE THREAD

**Issue by ccccmd** [libjpeg-turbo/libjpeg-turbo#621]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes, I have.

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No, it doesn't.

**Clear and concise description of the bug:**
The "-h" option of tjbench misses the option "qq", "custom", "nooutput"  for version 2.1.4.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
Compare the help document with the source code.

**Image(s) needed in order to reproduce the bug (if applicable):**

**Expected behavior:**
"qq", "custom", "nooutput" need appear in the help document.

**Observed behavior:**

+ For the option "qq", the following code appears during option parsing and modifies the quiet in ./tjbench.c:890 for version 2.1.4.

```
        quiet = 2;
```
+ For the option "custom", the following code appears during option parsing and modifies the customFilter in ./tjbench.c:922 for version 2.1.4.

```
        customFilter = dummyDCTFilter;
```

+ For the option "nooutput", the following code appears during option parsing and modifies the xformOpt in ./tjbench.c:924 for version 2.1.4.

```
        xformOpt |= TJXOPT_NOOUTPUT;
```

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
ubuntu 20.04

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
2.1.4

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**
But they do not appear in the document provided by "-h".

It may prevent users from using the relevant function.

**Comment by dcommander** [comment]
Those options are intentionally undocumented, because they are generally only useful for internal testing.  `-qq` prints the results in a single column with no headers, so it is only useful with a [specific spreadsheet format](https://libjpeg-turbo.org/pmwiki/uploads/About/libjpegturbo-1.5.ods).  `-custom` and `-nooutput` are used to regression-test specific TurboJPEG API features and to demonstrate their use to programmers, but those options are not generally useful to end users of TJBench, as they do not produce usable output images.

**Comment by ccccmd** [comment]
Thanks
