### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by radarhere** [libjpeg-turbo/libjpeg-turbo#623]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No

**Clear and concise description of the bug:**
During `jpeg_read_scanlines` for a fuzzed file, an error occurs. On macOS, it is a segmentation fault. On Windows, it is exit code -1073741819, an access violation.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
While this segfault was originally found in a more complex context, I now believe that it can be triggered by just trying to read the file. The following is just a slightly simplified [StackOverflow example of how to read a jpeg file.](https://stackoverflow.com/a/22463461/4093019)
```c
unsigned long x, y;
unsigned long data_size;
unsigned char * rowptr[1];
unsigned char * jdata;
struct jpeg_decompress_struct info;
struct jpeg_error_mgr err;

FILE* file = fopen("file", "rb");

info.err = jpeg_std_error(&err);
jpeg_create_decompress(& info);

jpeg_stdio_src(&info, file);
jpeg_read_header(&info, TRUE);

jpeg_start_decompress(&info);

x = info.output_width;
y = info.output_height;

data_size = x * y * 3;

jdata = (unsigned char *)malloc(data_size);
while (info.output_scanline < info.output_height) {
  rowptr[0] = (unsigned char *)jdata + 3 * info.output_width * info.output_scanline;

  jpeg_read_scanlines(&info, rowptr, 1);
}
```

**Image(s) needed in order to reproduce the bug (if applicable):**
![file](https://user-images.githubusercontent.com/3112309/195834949-d997ec55-a933-4edd-b71f-4600174b3cab.jpg)

**Expected behavior:**
The code would be able to continue executing.

**Observed behavior:**
Code exited during `jpeg_read_scanlines`.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
macOS 11.7, Apple clang version 13.0.0 (clang-1300.0.29.30), x86_64
Microsoft Windows Server 2022, MSVC 19.33.31630.0, x86_64

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
stable 2.1.4. On Windows, also tested prerelease 2.1.80.

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**
I haven't tested this with earlier libjpeg-turbo versions.

**Additional information:**
If you are not able to replicate in any way, please let me know how I can improve this reproduction. If I have introduced a coding error in the process of trying to create a minimal example, I can try again.

**Comment by dcommander** [comment]
The first thing you should try is using `info.output_components` rather than hard-coding the number of components to 3.  Some JPEG images (such as images that use the YCCK colorspace) can only decompress to 4-component output images, so assuming 3 output components is incorrect.

If you still observe a failure, then try the same image with djpeg.  If the image also fails with djpeg, then attach the image, and I will investigate.

**Comment by radarhere** [comment]
I have actually already attached the image in the first comment, it just looks like a line.

**Comment by radarhere** [comment]
Indeed, using `info.output_components` instead of `3` in both code lines allows it run without error. And trying again, I've found a solution for my original context.

So, if it is not a problem in your evaluation that the code I posted above triggers a segmentation fault, this can be closed. Thanks for your time.

**Comment by dcommander** [comment]
I verified that the test image uses a JPEG colorspace of CMYK, so libjpeg-turbo will default to an output colorspace of CMYK (4 components) when attempting to decompress the image.  That's why your code failed.  The image does not trigger a segfault with djpeg or any other tools included with libjpeg-turbo.
