### ISSUE TITLE
Simple program not compiling

### ISSUE THREAD

**Issue by jeroentaverne** [libjpeg-turbo/libjpeg-turbo#634]
I made a small program that just uses a few basic functions, but all of them can't be found. Do I need to link in a different library perhaps?

gcc -lturbojpeg test3.c
/usr/bin/ld: /tmp/ccXtVVsN.o: in function `main':
/usr/bin/ld: test3.c:(.text+0xd9): undefined reference to `tjInitDecompress'
/usr/bin/ld: test3.c:(.text+0x109): undefined reference to `tjDecompressHeader2'
/usr/bin/ld: test3.c:(.text+0x140): undefined reference to `tjDecompress2'
/usr/bin/ld: test3.c:(.text+0x150): undefined reference to `tjDestroy'
collect2: error: ld returned 1 exit status

**Comment by dcommander** [comment]
Those functions should all be in libturbojpeg, so I'm not sure why it isn't working. Are you building libjpeg-turbo from source? If so, then please specify how you are building and installing it.

**Comment by jeroentaverne** [comment]
Thanks for your reply!
I am running Ubuntu 22.
test3.c:
[test3.txt](https://github.com/libjpeg-turbo/libjpeg-turbo/files/10132732/test3.txt)

I have installed it by:
sudo apt install libturbojpeg-dev

**Comment by dcommander** [comment]
Try
```
gcc test3.c -lturbojpeg
```
instead.

**Comment by jeroentaverne** [comment]
Thanks! That did it.
