### ISSUE TITLE
12 and 16 bit support compilation struggles

### ISSUE THREAD

**Issue by teub** [libjpeg-turbo/libjpeg-turbo#647]
Hello,

I'm trying to build the latest version as a single library and I can't find a way to do it.
Looking at the headers, it looks like it's assumed all versions of the functions are supposed to exist ?

It would be nice to either have a cmake option to disable 12 and 16 bit support, or to be able to compile the project as a single library if we're not supposed to disable those modes.

Example of how to do it :

jcapistd.c could look something like that :

#define BITS_IN_JSAMPLE 8
#include jcapistd.inl
#define BITS_IN_JSAMPLE 12
#include jcapistd.inl
#define BITS_IN_JSAMPLE 16
#include jcapistd.inl

This would avoid having to create multiple libraries if they're not supposed to be usable by themselves. What do you think ?

**Comment by teub** [comment]
nvm I probably should look more into it, sorry

**Comment by dcommander** [comment]
3.0.x already addresses this.  Download the 3.0 beta1 version that just dropped today.

**Comment by teub** [comment]
I looked more into it :) Indeed I don't think there's a way to use the library without 12 or 16 bpp. For example jinit_compress_master assumes j12* and j16* functions exist.

Thanks a lot for your answer, I will check the 3.0 version !

**Comment by teub** [comment]
Well... I was actually using the 3.0 version :-) (which is 2.1.90, hence the confusion).

The problem I'm describing is actually with this latest version, but maybe I haven't explained it well.

**Comment by dcommander** [comment]
Sorry I misunderstood your question.

The answer is unfortunately no.  It's very difficult to maintain a library that has all manner of `#ifdef`s for various features.  I maintain the `#ifdef`s that existed in 1999, such as `C_PROGRESSIVE_SUPPORTED`, etc., but I am not in a position to introduce new ones.  You can partly get what you want by editing **jmorecfg.h** and disabling `C_LOSSLESS_SUPPORTED` and `D_LOSSLESS_SUPPORTED`, which will eliminate 16-bit data precision, but 12-bit data precision will still be there.  The ability to access multiple data precisions in the same library is a feature, not a bug.  Any application that is so memory-constrained as to not want multiple data precisions is probably better served by sticking to the 2.1.x release series.

Unfortunately, I racked up a 75-hour funding deficit in the process of putting out 3.0 beta1, so I have no ability to look into this further.

**Comment by teub** [comment]
Ok, thank you for your time !
Actually I don't mind having the 12 and 16 bit versions as well, I was just struggling to compile it as a single library. I can probably live with the older versions !
Thanks again.

**Comment by dcommander** [comment]
So I guess I'm back to my initial confusion, then, because the build system automatically compiles it all into a single library.  What exactly are you trying to do, and how exactly is it not working?

**Comment by dcommander** [comment]
No, the build system takes advantage of CMake's "object library" feature.  Object libraries are basically virtual libraries, so when the build system generates the static libraries (**libjpeg.a** and **libturbojpeg.a**), then contain all of the objects for all data precisions.  You can verify this by running `nm -g` on **libjpeg.a** and grepping for `j12` or `j16`.

**Comment by teub** [comment]
Oh, I see ! Thanks for the clarification.

With Visual Studio, CMake seems to generate a .vcxproj static lib per virtual library, which are then linked together in one library (either as static or dynamic).

Anyway this makes it a bit difficult to build the library without CMake (I'm using it just for the custom build steps, but I generate my project files differently as it's part of a bigger thing), and even then it's probably confusing to have the same .c files listed multiple times in the IDE.

**Comment by dcommander** [comment]
I'm not enough of a Visual C++ expert these days to be of much help, and supporting downstream build systems is out of scope for my support anyhow.

**Comment by teub** [comment]
I get it, no worries :-)
Thank you !

**Comment by fghoussen** [comment]
Just reporting that on debian, the official package doesn't allow using 12/16 data precision:

```
>> dpkg -l libjpeg62-turbo-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                      Version      Architecture Description
+++-=========================-============-============-====================================================
ii  libjpeg62-turbo-dev:amd64 1:2.1.5-2    amd64        Development files for the libjpeg-turbo JPEG library


>> grep -n JSAMPLE /usr/include/jpeglib.h
69:typedef JSAMPLE *JSAMPROW;      /* ptr to one image row of pixel samples. */
658:  JSAMPLE *sample_range_limit;  /* table for fast range-limiting */

>> grep J16SAMPLE /usr/include/jpeglib.h


```

12/16 data precision structs seems to have been stripped although they appear in the original version https://github.com/libjpeg-turbo/libjpeg-turbo/blob/abeca1f0cc638a6492d81f4c3b956c2dec817c3e/jpeglib.h#L90

Is this intended? If yes, how to use 12/16 data precision using official debian packages?

**Comment by dcommander** [comment]
@fghoussen The feature was introduced in libjpeg-turbo 3.0, so of course it won't be present in a distribution-supplied package that is still based on libjpeg-turbo 2.1.5. Refer to the libjpeg-turbo change log. Distribution-supplied packages are not "official" from the point of view of libjpeg-turbo. They are maintained downstream by the O/S developers, they may or may not be based on the latest libjpeg-turbo release, and they may or may not contain unsanctioned downstream changes. Thus, I cannot and do not support those downstream packages except insofar as the issues also exist upstream.

I go out of my way to provide official Debian-compatible libjpeg-turbo packages with every libjpeg-turbo release. Those are called "libjpeg-turbo-official" and install under **/opt/libjpeg-turbo** so as not to conflict with the distribution-supplied package. The official packages are available for download under the assets section of each release of libjpeg-turbo on GitHub. You can also use our [APT repository:
](https://libjpeg-turbo.org/Downloads/YUM).

**Comment by dcommander** [comment]
@fghoussen Also note: It is bad etiquette to use a closed issue on GitHub to report something that may or may not be related. Before you comment on a closed issue, please carefully read all prior comments in that issue to ensure that your issue is the same. If it isn't, then file a new issue.
