### ISSUE TITLE
SIGILL due to use of AVX2 instructions since f579cc1 / 2.1.5

### ISSUE THREAD

**Issue by kleisauke** [libjpeg-turbo/libjpeg-turbo#649]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes.

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No.

**Clear and concise description of the bug:**
Since commit f579cc11b33e5bfeb9931e37cc74b4a33c95d2e6 libjpeg-turbo produces a SIGILL on non-AVX2 capable CPUs when running via libvips with a concurrency of 2 or higher.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
I'm working on a standalone reproducer. But I think the `simd_support` variable will be `~0` since libvips may run `jpeg_read_scanlines()` on arbitrary threads (i.e. not the one that called `init_simd()`).

**Image(s) needed in order to reproduce the bug (if applicable):**
https://wsrv.nl/zebra.jpg, but other JPEG images would reproduce this as well.

**Expected behavior:**
```console
$ vips copy zebra.jpg x.png --vips-concurrency=1
$ JSIMD_FORCENONE=1 vips copy zebra.jpg x.png --vips-concurrency=2
$ vips copy zebra.jpg x.png --vips-concurrency=2
$ echo $?
0
```

**Observed behavior:**
```console
$ vips copy zebra.jpg x.png --vips-concurrency=1
$ JSIMD_FORCENONE=1 vips copy zebra.jpg x.png --vips-concurrency=2
$ vips copy zebra.jpg x.png --vips-concurrency=2
Illegal instruction (core dumped)
$ echo $?
132
```

<details>
  <summary>GDB backtrace</summary>

```console
$ coredumpctl debug
           PID: 1596210 (vips)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 4 (ILL)
     Timestamp: Wed 2023-02-01 16:56:11 CET (4s ago)
  Command Line: vips copy zebra.jpg x.png --vips-concurrency=2
    Executable: /usr/bin/vips
 Control Group: /
         Slice: -.slice
       Boot ID: <REDACTED>
    Machine ID: <REDACTED>
      Hostname: <REDACTED>
       Storage: /var/lib/systemd/coredump/core.vips.0.011ed54e0daa4a6a9484e5affe8dc00a.1596210.1675266971000000.lz4
       Message: Process 1596210 (vips) of user 0 dumped core.
                
                Stack trace of thread 1596213:
                #0  0x00007f2ee0feaae3 jsimd_h2v2_fancy_upsample_avx2.rowloop (libjpeg.so.62)
                #1  0x0000000000000002 n/a (n/a)
                #2  0x00007f2ee0fc9484 sep_upsample (libjpeg.so.62)
                #3  0x00007f2ee0fc131a process_data_context_main (libjpeg.so.62)
                #4  0x00007f2ee0fb35e2 jpeg_read_scanlines (libjpeg.so.62)
                #5  0x00007f2ee3bc6e7a read_jpeg_generate (libvips.so.42)
                #6  0x00007f2ee3d4cea5 vips_region_generate (libvips.so.42)
                #7  0x00007f2ee3d4e437 vips_region_prepare_to_generate (libvips.so.42)
                #8  0x00007f2ee3d579ba vips_region_prepare_to (libvips.so.42)
                #9  0x00007f2ee3cc643e vips_tile_cache_gen (libvips.so.42)
                #10 0x00007f2ee3d4cea5 vips_region_generate (libvips.so.42)
                #11 0x00007f2ee3d4dd8d vips_region_fill (libvips.so.42)
                #12 0x00007f2ee3d57727 vips_region_prepare (libvips.so.42)
                #13 0x00007f2ee3cc778e vips_sequential_generate (libvips.so.42)
                #14 0x00007f2ee3d4cea5 vips_region_generate (libvips.so.42)
                #15 0x00007f2ee3d4dd8d vips_region_fill (libvips.so.42)
                #16 0x00007f2ee3d57727 vips_region_prepare (libvips.so.42)
                #17 0x00007f2ee3cd5721 vips_extract_area_gen (libvips.so.42)
                #18 0x00007f2ee3d4cea5 vips_region_generate (libvips.so.42)
                #19 0x00007f2ee3d4dd8d vips_region_fill (libvips.so.42)
                #20 0x00007f2ee3d57727 vips_region_prepare (libvips.so.42)
                #21 0x00007f2ee3d3cddd vips_image_write_gen (libvips.so.42)
                #22 0x00007f2ee3d4cea5 vips_region_generate (libvips.so.42)
                #23 0x00007f2ee3d4dd8d vips_region_fill (libvips.so.42)
                #24 0x00007f2ee3d57727 vips_region_prepare (libvips.so.42)
                #25 0x00007f2ee3bc209d vips_foreign_load_generate (libvips.so.42)
                #26 0x00007f2ee3d4cea5 vips_region_generate (libvips.so.42)
                #27 0x00007f2ee3d4dd8d vips_region_fill (libvips.so.42)
                #28 0x00007f2ee3d57727 vips_region_prepare (libvips.so.42)
                #29 0x00007f2ee3cd01ed vips_copy_gen (libvips.so.42)
                #30 0x00007f2ee3d4cea5 vips_region_generate (libvips.so.42)
                #31 0x00007f2ee3d4dd8d vips_region_fill (libvips.so.42)
                #32 0x00007f2ee3d57727 vips_region_prepare (libvips.so.42)
                #33 0x00007f2ee3d3cddd vips_image_write_gen (libvips.so.42)
                #34 0x00007f2ee3d4cea5 vips_region_generate (libvips.so.42)
                #35 0x00007f2ee3d4dd8d vips_region_fill (libvips.so.42)
                #36 0x00007f2ee3d57727 vips_region_prepare (libvips.so.42)
                #37 0x00007f2ee3d3cddd vips_image_write_gen (libvips.so.42)
                #38 0x00007f2ee3d4cea5 vips_region_generate (libvips.so.42)
                #39 0x00007f2ee3d4e437 vips_region_prepare_to_generate (libvips.so.42)
                #40 0x00007f2ee3d579ba vips_region_prepare_to (libvips.so.42)
                #41 0x00007f2ee3d45b0c wbuffer_work_fn (libvips.so.42)
                #42 0x00007f2ee3d2d594 vips_worker_work_unit (libvips.so.42)
                #43 0x00007f2ee3d2cc32 vips_threadset_work (libvips.so.42)
                #44 0x00007f2ee3d2c673 vips_thread_run (libvips.so.42)
                #45 0x00007f2ee38b9fca g_thread_proxy (libglib-2.0.so.0)
                #46 0x00007f2ee24e01cf start_thread (libpthread.so.0)
                #47 0x00007f2ee3264e73 __clone (libc.so.6)
                
                Stack trace of thread 1596211:
                #0  0x00007f2ee32649bd syscall (libc.so.6)
                #1  0x00007f2ee38d8d23 g_cond_wait (libglib-2.0.so.0)
                #2  0x00007f2ee3d580bd vips__semaphore_downn_until (libvips.so.42)
                #3  0x00007f2ee3d45b80 wbuffer_write_thread (libvips.so.42)
                #4  0x00007f2ee3d2cc32 vips_threadset_work (libvips.so.42)
                #5  0x00007f2ee3d2c673 vips_thread_run (libvips.so.42)
                #6  0x00007f2ee38b9fca g_thread_proxy (libglib-2.0.so.0)
                #7  0x00007f2ee24e01cf start_thread (libpthread.so.0)
                #8  0x00007f2ee3264e73 __clone (libc.so.6)
                
                Stack trace of thread 1596210:
                #0  0x00007f2ee32649bd syscall (libc.so.6)
                #1  0x00007f2ee38d8d23 g_cond_wait (libglib-2.0.so.0)
                #2  0x00007f2ee3d580bd vips__semaphore_downn_until (libvips.so.42)
                #3  0x00007f2ee3d2d889 vips_threadpool_run (libvips.so.42)
                #4  0x00007f2ee3d461af vips_sink_disc (libvips.so.42)
                #5  0x00007f2ee3bd83d2 vips_foreign_save_spng_write (libvips.so.42)
                #6  0x00007f2ee3bd863b vips_foreign_save_spng_build (libvips.so.42)
                #7  0x00007f2ee3bd7928 vips_foreign_save_spng_target_build (libvips.so.42)
                #8  0x00007f2ee3d3735d vips_object_build (libvips.so.42)
                #9  0x00007f2ee3d44a98 vips_cache_operation_buildp (libvips.so.42)
                #10 0x00007f2ee3d4ba4d vips_call_required_optional (libvips.so.42)
                #11 0x00007f2ee3d4c156 vips_call_by_name (libvips.so.42)
                #12 0x00007f2ee3d4c6d9 vips_call_split_option_string (libvips.so.42)
                #13 0x00007f2ee3d3ef22 vips_image_write_to_file (libvips.so.42)
                #14 0x00007f2ee3d38db4 vips_object_get_argument_to_string (libvips.so.42)
                #15 0x00007f2ee3d4b181 vips_call_argv_output (libvips.so.42)
                #16 0x00007f2ee3d370e7 vips_argument_map (libvips.so.42)
                #17 0x00007f2ee3d4c815 vips_call_argv (libvips.so.42)
                #18 0x0000563193c05951 main (vips)
                #19 0x00007f2ee3265d85 __libc_start_main (libc.so.6)
                #20 0x0000563193c05e7e _start (vips)
                
                Stack trace of thread 1596212:
                #0  0x00007f2ee32649bd syscall (libc.so.6)
                #1  0x00007f2ee38d8d23 g_cond_wait (libglib-2.0.so.0)
                #2  0x00007f2ee3d580bd vips__semaphore_downn_until (libvips.so.42)
                #3  0x00007f2ee3d45b80 wbuffer_write_thread (libvips.so.42)
                #4  0x00007f2ee3d2cc32 vips_threadset_work (libvips.so.42)
                #5  0x00007f2ee3d2c673 vips_thread_run (libvips.so.42)
                #6  0x00007f2ee38b9fca g_thread_proxy (libglib-2.0.so.0)
                #7  0x00007f2ee24e01cf start_thread (libpthread.so.0)
                #8  0x00007f2ee3264e73 __clone (libc.so.6)
                
                Stack trace of thread 1596214:
                #0  0x00007f2ee32649bd syscall (libc.so.6)
                #1  0x00007f2ee38d834c g_mutex_lock_slowpath (libglib-2.0.so.0)
                #2  0x00007f2ee3d2d371 vips__worker_lock (libvips.so.42)
                #3  0x00007f2ee3cc7718 vips_sequential_generate (libvips.so.42)
                #4  0x00007f2ee3d4cea5 vips_region_generate (libvips.so.42)
                #5  0x00007f2ee3d4dd8d vips_region_fill (libvips.so.42)
                #6  0x00007f2ee3d57727 vips_region_prepare (libvips.so.42)
                #7  0x00007f2ee3cd5721 vips_extract_area_gen (libvips.so.42)
                #8  0x00007f2ee3d4cea5 vips_region_generate (libvips.so.42)
                #9  0x00007f2ee3d4dd8d vips_region_fill (libvips.so.42)
                #10 0x00007f2ee3d57727 vips_region_prepare (libvips.so.42)
                #11 0x00007f2ee3d3cddd vips_image_write_gen (libvips.so.42)
                #12 0x00007f2ee3d4cea5 vips_region_generate (libvips.so.42)
                #13 0x00007f2ee3d4dd8d vips_region_fill (libvips.so.42)
                #14 0x00007f2ee3d57727 vips_region_prepare (libvips.so.42)
                #15 0x00007f2ee3bc209d vips_foreign_load_generate (libvips.so.42)
                #16 0x00007f2ee3d4cea5 vips_region_generate (libvips.so.42)
                #17 0x00007f2ee3d4dd8d vips_region_fill (libvips.so.42)
                #18 0x00007f2ee3d57727 vips_region_prepare (libvips.so.42)
                #19 0x00007f2ee3cd01ed vips_copy_gen (libvips.so.42)
                #20 0x00007f2ee3d4cea5 vips_region_generate (libvips.so.42)
                #21 0x00007f2ee3d4dd8d vips_region_fill (libvips.so.42)
                #22 0x00007f2ee3d57727 vips_region_prepare (libvips.so.42)
                #23 0x00007f2ee3d3cddd vips_image_write_gen (libvips.so.42)
                #24 0x00007f2ee3d4cea5 vips_region_generate (libvips.so.42)
                #25 0x00007f2ee3d4dd8d vips_region_fill (libvips.so.42)
                #26 0x00007f2ee3d57727 vips_region_prepare (libvips.so.42)
                #27 0x00007f2ee3d3cddd vips_image_write_gen (libvips.so.42)
                #28 0x00007f2ee3d4cea5 vips_region_generate (libvips.so.42)
                #29 0x00007f2ee3d4e437 vips_region_prepare_to_generate (libvips.so.42)
                #30 0x00007f2ee3d579ba vips_region_prepare_to (libvips.so.42)
                #31 0x00007f2ee3d45b0c wbuffer_work_fn (libvips.so.42)
                #32 0x00007f2ee3d2d594 vips_worker_work_unit (libvips.so.42)
                #33 0x00007f2ee3d2cc32 vips_threadset_work (libvips.so.42)
                #34 0x00007f2ee3d2c673 vips_thread_run (libvips.so.42)
                #35 0x00007f2ee38b9fca g_thread_proxy (libglib-2.0.so.0)
                #36 0x00007f2ee24e01cf start_thread (libpthread.so.0)
                #37 0x00007f2ee3264e73 __clone (libc.so.6)
```
</details>

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
```console
$ vips --version
vips-8.14.1
$ gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-16)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ cat /etc/redhat-release
Rocky Linux release 8.7 (Green Obsidian)
$ grep avx2 /proc/cpuinfo
$ echo $?
1
$ lscpu | grep "^Model name"
Model name:          Intel(R) Core(TM) i5-3570S CPU @ 3.10GHz
```

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
2.1.5

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**
f579cc11b33e5bfeb9931e37cc74b4a33c95d2e6 is the first bad commit.

**Additional information:**
I confirm that building with `-DWITH_TURBOJPEG=0` (causing `THREAD_LOCAL` to be no-op) resolves this.
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/fd93d98a959ac3700e2da07310a44867c9c46f03/CMakeLists.txt#L477
```console
$ mkdir libjpeg-turbo
$ curl -sL https://downloads.sourceforge.net/project/libjpeg-turbo/2.1.5/libjpeg-turbo-2.1.5.tar.gz | tar xzC libjpeg-turbo --strip-components=1
$ cd libjpeg-turbo
$ cmake -G"Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/opt/libjpeg-turbo -DCMAKE_BUILD_TYPE=RELEASE -DWITH_TURBOJPEG=0
$ make install
```

Setting the ` JSIMD_FORCENONE=1 ` env also fixes this issue (as seen in the commands above), but this would affect performance.

The `libjpeg-turbo-official` RPMs are also affected by this issue.

**Comment by dcommander** [comment]
Obviously there is no issue when running libjpeg-turbo standalone, so the actual bug is that libvips doesn't correctly handle thread-local variables, not that libjpeg-turbo dares to use them.

This is an example of "no good deed goes unpunished", because people have complained bitterly for years about an innocuous race condition in `simd_support` that might, in the worst case, cause `jpeg_simd_cpu_support()` to get called more than once (but that doesn't really matter, because `jpeg_simd_cpu_support()` is idempotent.)  So I made `simd_support` thread-local, and now someone else is complaining bitterly.  So who am I supposed to please, and who am I supposed to displease?  Because apparently it's impossible to please everyone.

The workaround you found isn't really a workaround, because now that `THREAD_LOCAL` is being used outside of the TurboJPEG API library, the build system needs to define it regardless of whether `WITH_TURBOJPEG` is true.  So you're going to need to get with the libvips developers and figure out why they can't handle our thread-local variable properly.

**Comment by dcommander** [comment]
BTW, the scenario you describe, whereby `init_simd()` is called in one thread but not the others, should never happen unless libvips is doing some custom hackery that might have worked accidentally but never should've been expected to work.  The SIMD functions aren't even externally exposed by our libraries.  They are called internally, and libjpeg-turbo always calls the corresponding `jsimd_can*()` function first, which calls `init_simd()`.  Note that every thread must have its own libjpeg instance.  If libvips is trying to share an instance across multiple threads, then that explains why it's failing.  Don't do that.

**Comment by kleisauke** [comment]
> Note that every thread must have its own libjpeg instance. If libvips is trying to share an instance across multiple threads, then that explains why it's failing. Don't do that.

This indeed seems to be the culprit. For reference, here's a standalone reproduction:
<details>
  <summary>Standalone reproduction</summary>

```c
/* compile with:
 *   gcc -g -Wall test.c `pkg-config libjpeg --cflags --libs` -lpthread
 * run with
 *   ./a.out zebra.jpg
 */

#include <stdio.h>
#include <jpeglib.h>
#include <pthread.h>

void *threaded_read(void *arg) {
  struct jpeg_decompress_struct *cinfo = (struct jpeg_decompress_struct *)arg;
  JSAMPARRAY buffer;
  int row_stride;

  row_stride = cinfo->output_width * cinfo->output_components;
  buffer = (*cinfo->mem->alloc_sarray)((j_common_ptr)cinfo, JPOOL_IMAGE,
                                       row_stride, 1);

  while (cinfo->output_scanline < cinfo->output_height)
    (void)jpeg_read_scanlines(cinfo, buffer, 1);

  return NULL;
}

int main(int argc, char **argv) {
  struct jpeg_decompress_struct cinfo;
  struct jpeg_error_mgr std_err;
  pthread_t thread;
  FILE *infile;

  if (argc < 2 || !(infile = fopen(argv[1], "rb"))) {
    printf("Usage: %s filename\n", argv[0]);
    return 1;
  }

  cinfo.err = jpeg_std_error(&std_err);
  jpeg_create_decompress(&cinfo);
  jpeg_stdio_src(&cinfo, infile);
  (void)jpeg_read_header(&cinfo, TRUE);
  (void)jpeg_start_decompress(&cinfo);

  (void)pthread_create(&thread, NULL, threaded_read, &cinfo);
  (void)pthread_join(thread, NULL);

  (void)jpeg_finish_decompress(&cinfo);
  jpeg_destroy_decompress(&cinfo);
  (void)fclose(infile);

  return 0;
}
```
</details>

/cc @jcupitt

**Comment by dcommander** [comment]
Does libvips literally do what the example code above does, i.e. share an instance created in the main thread with only one child thread?  Or does it share the same instance with multiple child threads?  The latter is clearly incorrect and shouldn't be expected to work, and **libjpeg.txt** says as much.  However, I tend to agree that the former should at least not crash.  Let me see if it's possible to store the SIMD state in the master struct, so it will always be attached to the libjpeg instance.

**Comment by dcommander** [comment]
No such luck.  I am reminding myself why `simd_support` was a global variable to begin with.  It's because some of the SIMD functions can't accept a libjpeg API instance as an argument, because they are designed to plug into existing libjpeg API modules that have specific function signatures.  Changing those function signatures would require deep modifications throughout the libjpeg API library, and I don't have the funding for that right now.  So our only real choices are:

1. Revert f579cc11b33e5bfeb9931e37cc74b4a33c95d2e6 and deal with the inevitable whining about the innocuous race condition returning (but since f579cc11b33e5bfeb9931e37cc74b4a33c95d2e6 was never documented, I don't feel particularly compelled to apologize for its removal.)
2. Take a "do no harm" approach and don't assume that a SIMD capability flag is set if `simd_support == ~0U`.  However, in the example above, this would result in the child thread using SSE2 instructions even if the machine is capable of AVX2.  I don't like that, because it introduces a non-intuitive and hard-to-diagnose slow-down.
3. Call `init_simd()` within the body of every SIMD extension function.  For performance reasons, `init_simd()` should only run once within each thread, because some implementations of it have to parse a file under **/proc**.  That's why there are `jsimd_can_*()` functions for every SIMD extension.  However, the fact that we are now using a thread-local variable for `simd_support` guarantees that `init_simd()` will only run once within each thread, so calling it within the body of every SIMD extension function would just introduce an additional branch.  An additional branch is enough to require a complete benchmark run, though, so this option is at least a couple of hours of work.
4. Do nothing except:
    - Improve the documentation to reflect that *any* usage of a libjpeg API instance, other than creation and destruction, must be contained within a single thread.
    - Introduce an undocumented CMake variable that allows specific implementations to disable thread-local storage.

1 and 4 are the easiest options.  4 is my preference, given our project's current funding deficit.

**Comment by jcupitt** [comment]
Hi @dcommander,

First, thank you for this great project.

A `struct jpeg_decompress_struct` pointer can be used by more than one libvips worker thread, though never at the same time. Use of thread-private will break our assumptions around threading and would not be easy for us to work around :( We use this same model (no concurrent calls with the same state) for all our image format libraries (libtiff, libwebp, libpng, etc., even imagemagick), so I think requiring a state pointer per image *and* per thread would be an outlier here.

I think I'd vote for 1), perhaps with an extra mutex around `init_simd()`. Would that work? I'm a bit unclear.

> given our project's current funding deficit.

We've been very lucky with donations, I'm embarrassed we've not upstreamed funding to libjpeg-turbo before, let me check with the other maintainers.

**Comment by dcommander** [comment]
A mutex would definitely not work, because I cannot introduce a pthreads dependency into libjpeg-turbo.  So that leaves Option 3, which should solve the problem.  It will just require 2-3 hours of benchmarking to verify that it doesn't create a performance regression.

**Comment by kleisauke** [comment]
Alternatively, perhaps making `init_simd` a constructor would help? For example:
```diff
--- a/simd/x86_64/jsimd.c
+++ b/simd/x86_64/jsimd.c
@@ -31,12 +31,15 @@
 #define IS_ALIGNED_SSE(ptr)  (IS_ALIGNED(ptr, 4)) /* 16 byte alignment */
 #define IS_ALIGNED_AVX(ptr)  (IS_ALIGNED(ptr, 5)) /* 32 byte alignment */
 
-static THREAD_LOCAL unsigned int simd_support = (unsigned int)(~0);
-static THREAD_LOCAL unsigned int simd_huffman = 1;
+static unsigned int simd_support = (unsigned int)(~0);
+static unsigned int simd_huffman = 1;
 
 /*
  * Check what SIMD accelerations are supported.
  */
+#if __GNUC__ > 2 || (__GNUC__ == 2 && __GNUC_MINOR__ >= 7)
+__attribute__((constructor))
+#endif
 LOCAL(void)
 init_simd(void)
 {
```

This would avoid the need to manually call `init_simd()` (on compilers where this is supported) and ensures that `simd_support` and `simd_huffman` are initialized once, which would appease TSan.

**Comment by dcommander** [comment]
I ultimately chose a more brute-force route and simply called `init_simd()`, if `simd_support == ~0U`, prior to attempting to dispatch based on the value of `simd_support`.  I confirmed that that approach is performance-neutral, and it will work with all compilers.  It is only necessary for x86[-64], because none of the other SIMD implementations support multiple instruction sets.

The fix will be in the final 3.0 release of libjpeg-turbo, and I back-ported it to the 2.1.x branch as well, so you can easily build a patched version of 2.1.5.

**Comment by dcommander** [comment]
@kleisauke It's a moot point since I fixed the issue, but for my own edification, why couldn't libvips have called `jpeg_start_decompress()` and `jpeg_finish_decompress()` in the worker thread?  I'm asking this mainly out of curiosity regarding the structure of libvips.

**Comment by kleisauke** [comment]
> why couldn't libvips have called `jpeg_start_decompress()` and `jpeg_finish_decompress()` in the worker thread?

I think because there can be more than one worker thread, it was probably just easier for us to call these functions on the main thread. The standalone reproducer above might be a bit misleading, it's more like this:

<details>
  <summary>Details</summary>

```c
/* compile with:
 *   gcc -g -Wall test.c `pkg-config libjpeg --cflags --libs` -lpthread
 * run with:
 *   ./a.out zebra.jpg
 */

#include <stdio.h>
#include <jpeglib.h>
#include <pthread.h>

#define NUM_THREADS 2

void *threaded_read(void *arg) {
  struct jpeg_decompress_struct *cinfo = (struct jpeg_decompress_struct *)arg;
  JSAMPARRAY buffer;
  unsigned int batch_size, batch_remainder;
  int row_stride, y, thread_num;

  row_stride = cinfo->output_width * cinfo->output_components;
  buffer = (*cinfo->mem->alloc_sarray)((j_common_ptr)cinfo, JPOOL_IMAGE,
                                       row_stride, 1);

  batch_size = cinfo->output_height / NUM_THREADS;
  for (y = 0; y < batch_size; ++y)
    (void)jpeg_read_scanlines(cinfo, buffer, 1);

  thread_num = *((int *)cinfo->client_data);
  if (thread_num != NUM_THREADS - 1)
    return NULL;

  batch_remainder = cinfo->output_height % NUM_THREADS;
  for (y = 0; y < batch_remainder; ++y)
    (void)jpeg_read_scanlines(cinfo, buffer, 1);

  return NULL;
}

int main(int argc, char **argv) {
  struct jpeg_decompress_struct cinfo;
  struct jpeg_error_mgr std_err;
  pthread_t threads[NUM_THREADS];
  FILE *infile;
  int i;
  
  if (argc < 2 || !(infile = fopen(argv[1], "rb"))) {
    printf("Usage: %s filename\n", argv[0]);
    return 1;
  }

  cinfo.err = jpeg_std_error(&std_err);
  jpeg_create_decompress(&cinfo);
  jpeg_stdio_src(&cinfo, infile);
  (void)jpeg_read_header(&cinfo, TRUE);
  (void)jpeg_start_decompress(&cinfo);

  for (i = 0; i < NUM_THREADS; ++i) {
    cinfo.client_data = &i;
    (void)pthread_create(&threads[i], NULL, threaded_read, &cinfo);
    (void)pthread_join(threads[i], NULL);
  }

  (void)jpeg_finish_decompress(&cinfo);
  jpeg_destroy_decompress(&cinfo);
  (void)fclose(infile);

  return 0;
}
```
</details>

> Alternatively, perhaps making `init_simd` a constructor would help?

FWIW, it looks like this is also supported on MSVC via the `.CRT$XCU` sub-section, but it's non-trivial in terms of complexity. For a real-world example, see GLib (where this is a hard requirement):
https://gitlab.gnome.org/GNOME/glib/-/blob/2.75.2/docs/toolchain-requirements.md#constructors-and-destructors
https://gitlab.gnome.org/GNOME/glib/-/blob/2.75.2/glib/gconstructor.h

**Comment by dcommander** [comment]
> I think because there can be more than one worker thread, it was probably just easier for us to call these functions on the main thread. The standalone reproducer above might be a bit misleading, it's more like this:

Huh.  So you're using multiple threads but not concurrently?  I guess I don't see the point.  Why use threads at all in that case?  You could either run everything in the main thread, thus avoiding the needless complexity of creating multiple threads, or you could use a separate libjpeg instance with each thread and thus run the threads concurrently.

> FWIW, it looks like this is also supported on MSVC via the .CRT$XCU sub-section, but it's non-trivial in terms of complexity. For a real-world example, see GLib (where this is a hard requirement):

There are other compilers we have to support, such as Oracle Developer Studio.  Using a constructor could also lead to unexpected behavior if libjpeg-turbo is linked statically with an application (and even more unexpected behavior if it is linked statically with a dynamic library that is then linked with an application.)  In general, it's just not a good idea for a library to execute code outside of the context of its API functions.

**Comment by jcupitt** [comment]
> Huh. So you're using multiple threads but not concurrently? I guess I don't see the point. 

It comes from the way libvips works. 

It's a threaded, demand-driven, pipelined (or chained, they are sometimes called) image processing library, so every operation in a pipeline from the load to the save runs at the same time, and pixels flow through the pipe in small chunks driven by the need to create output. There's a pool of workers executing the thing (every worker runs a shallow copy of the whole pipe).

A few image load libraries allow parallel access, but most are single threaded. Workers arrive at the loader as they need pixels, they get sorted by Y position, and one at a time is allowed through to call off into eg. libjpeg-turbo. So each chunk will be given to a separate thread to decompress, but they will fetch pixels in order, and never concurrently. It has write-behind in a pair of background threads (this is much simpler).

Imagine a pipeline which is load, resize, sharpen, save. The load and save will be single-threaded, in effect (as you say), but the load and save will happen at the same time, and the CPU-intensive middle operations will be able to run with lots of threads.

**Comment by whitslack** [comment]
This issue also affects the Chromium web browser on Gentoo, which links dynamically with the system-installed libjpeg-turbo. When I updated to libjpeg-turbo 2.1.5, my Chromium tabs started crashing when loading certain pages (presumably those containing JPEG images), and the kernel log shows:

    traps: CompositorTileW[11830] trap invalid opcode ip:7f2468e0193e sp:7f241ff55060 error:0 in libjpeg.so.62.3.0[7f2468def000+5f000]

Applying d743a2c12e889f7605a56f5144ae2e3899c9dd4f fixed the problem. Thanks!

**Comment by dcommander** [comment]
I am considering a 2.1.5.1 mini-release to deploy the fix for this issue.

**Comment by dcommander** [comment]
Note that the error could also be worked around on affected systems by setting `JSIMD_FORCESSE2=1` in the environment.

**Comment by dcommander** [comment]
2.1.5.1 and 3.0 beta2 releases have just been pushed to address this issue.

**Comment by dcommander** [comment]
The SIMD dispatchers have been completely overhauled in the dev/3.2 Evolving branch.  They are now initialized on a per-instance basis rather than a per-thread basis, thus eliminating the dependence on TLS.
