### ISSUE TITLE
received signal SIGILL, Illegal instruction

### ISSUE THREAD

**Issue by sunweaver** [libjpeg-turbo/libjpeg-turbo#650]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

Yes. It seems to be a yet unspotted issue.

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

No.

**Clear and concise description of the bug:**

while resizing images through sharp using libvips, upgrading
libjpeg to 2.1.5 made it crash with:

Thread 15 "libvips worker" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7fffd97fc6c0 (LWP 52226)]
0x00007ffff00a109f in jsimd_idct_islow_avx2 () from /lib/x86_64-linux-gnu/libjpeg.so.62

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

Cannot be provided.

**Image(s) needed in order to reproduce the bug (if applicable):**

None.

**Expected behavior:**

No crashes at all in image operations.

**Observed behavior:**

Crash when resizing images.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

Release 2.1.5 (as just uploaded to Debian unstable).

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

It seems that MIYASAKA Masaru copy+pasted a systematic typo in a2e6a9dd47eb10c701a42a16f305ded1a02cd886. It sends a "SIGILL" signal to processes, that probably must read "SIGKILL".

**Additional information:**

None.

**Comment by kleisauke** [comment]
Hello, did you see #649?

**Comment by dcommander** [comment]
Duplicate and already fixed.  Please search issues before posting a new one.  Thanks.
