### ISSUE TITLE
Difference between 2.1.5.1 and 2.1.91?

### ISSUE THREAD

**Issue by AachoLoya** [libjpeg-turbo/libjpeg-turbo#652]
See two different releases within last hour, but no info anywhere about what the difference is between the two?

**Comment by dcommander** [comment]
That's what the change logs are for.  Please read them.  The 2.1.91 change log literally enumerates "Significant changes relative to 2.1.5.1."  If you need more information about how our versioning system works, see https://libjpeg-turbo.org/DeveloperInfo/PreReleases.

**Comment by dcommander** [comment]
Also, you can subscribe to libjpeg-turbo-announce (https://libjpeg-turbo.org/About/MailingLists) for more descriptive release announcements.
