### ISSUE TITLE
TJSAMP_411: Could not determine subsampling level but only when using ROT90

### ISSUE THREAD

**Issue by stefan-it** [libjpeg-turbo/libjpeg-turbo#659]
**Clear and concise description of the bug:**

Hi,

when using a 8-bit JPEG (YCbCr 4:1:1) image, cropping of an area works fine using the `tjbench` tool.

However, when applying a 90 degree rotation, a `Could not determine subsampling level of JPEG image` error message is thrown.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

Compile latest `master` (97df8ea9edf0017f891072845f43ed878be4fcef) on Ubuntu 22.10. Then use the `tjbench` tool to perform cropping:

```bash
$ ./tjbench subsampling.jpg -subsamp 411 -crop 64x100+64+100
JPEG image uses progressive entropy coding

>>>>>  8-bit JPEG (YCbCr 4:1:1) --> BGR (Top-down)  <<<<<

Image size: 2850 x 2550 --> 64 x 100
Decompress    --> Frame rate:         49.767351 fps
                  Throughput:         361.684223 Megapixels/sec
```

This is perfectly working. But when adding a 90 degree rotation, the following error is thrown:

```
$ ./tjbench subsampling.jpg -subsamp 411 -crop 64x100+64+100 -rot90              [16:03:52]

JPEG image uses progressive entropy coding

>>>>>  8-bit JPEG (YCbCr 4:1:1) --> BGR (Top-down)  <<<<<

Image size: 2850 x 2550 --> 64 x 100
Transform     --> Frame rate:         0.199193 fps
                  Output image size:  145305 bytes
                  Compression ratio:  150.046454:1
                  Throughput:         1.447638 Megapixels/sec
                  Output bit stream:  0.231550 Megabits/sec
ERROR in line 212:
tj3SetCroppingRegion(): Could not determine subsampling level of JPEG image
```

**Image(s) needed in order to reproduce the bug (if applicable):**

Use the following image from this [issue comment](https://github.com/dbmdz/imageio-jnr/issues/189#issuecomment-1450246335).

**Expected behavior:**

Error message (`Could not determine subsampling level of JPEG image`). However, the subsampling level of `TJSAMP_411` was detected when using cropping only. Why is this not the case when using a rotation :thinking: 

**Observed behavior:**

Error message:

```
tj3SetCroppingRegion(): Could not determine subsampling level of JPEG image
```

is thrown.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

Ubuntu 20.20 with GCC 12.2.0.

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

Latest 97df8ea9edf0017f891072845f43ed878be4fcef is used and installed.

**Comment by dcommander** [comment]
Blerg.  Yeah, the same thing happened with 4:2:2, which is why I had to explicitly implement 4:4:0 (rotated 4:2:2) in the TurboJPEG API.  I had hoped to implement arbitrary subsampling factors in the TurboJPEG 3 API overhaul but ran out of time.  (As it is, even with greatly reducing the scope of the overhaul, I still exhausted the entire libjpeg-turbo budget for 2023 in order to finish it.  I'm currently borrowing against 2024 just to keep the project running.)  It seems like the API should at least implement symmetric vertical subsampling types for all of the horizontal subsampling types, which would mean implementing 4:4:1 (rotated 4:1:1).
