### ISSUE TITLE
jpegtran: copy: get exif, but lose thumbnails

### ISSUE THREAD

**Issue by jidanni** [libjpeg-turbo/libjpeg-turbo#666]
man    jpegtran says
```
    -copy all
              Copy  all  extra  markers.  This setting preserves miscellaneous
              markers found in the source file, such as JFIF thumbnails,  Exif
              data,  and Photoshop settings.  In some files, these extra mark‐
              ers can be sizable.  Note that this option will copy  thumbnails
              as-is; they will not be transformed.
```
OK, but perhaps mention how to get the Exif, but lose the thumbnails.
OK, one probably will simply need to use a second program.

**Comment by dcommander** [comment]
libjpeg-turbo is not a comprehensive EXIF processing toolkit. It can either copy all markers or none. It doesn't have the ability to actually parse and filter EXIF data. Use exiftran for that.
