### ISSUE TITLE
[question] How do I know the final jpeg size when Yuv2Jpeg

### ISSUE THREAD

**Issue by oranger-lc** [libjpeg-turbo/libjpeg-turbo#687]
Is the final jpeg size always below (width * height) ?

**Comment by dcommander** [comment]
What is Yuv2Jpeg? That is not a program we provide.

**Comment by oranger-lc** [comment]
Thanks for your answer!

Yuv2Jpeg: convert format_Yuv to format_Jpeg;

How much space I should prepare for compressing Jpeg ? Is the final jpeg size always below (width * height) ?

**Comment by dcommander** [comment]
As I said, Yuv2Jpeg is not a program we provide or support. It is impossible for me to answer your question without knowing what that program does. At this point, I have no idea if it even uses libjpeg-turbo. I would suggest contacting the author of that program. I cannot read your mind and determine what you are trying to ask.
