### ISSUE TITLE
Library Takes Almost 3 times as long with the same build on more powerful computer

### ISSUE THREAD

**Issue by RMurphySST** [libjpeg-turbo/libjpeg-turbo#688]
Hi,
I have been using turbojpeg for simple compressing and decompressing of 1024x1024 images. I first installed turbojpeg on a small laptop and was able to compress the images in around .01 seconds an image. However, I copied and pasted the library build to another, more powerful desktop and now it takes .065 seconds per image. Did I miss any speed up dependencies needed to get the runtime back down? Thanks! 

All of this is in Ubuntu and C++ using CMake using the exact same code.

**Comment by RMurphySST** [comment]
I'm just using a simple timer that starts before the encode and ends after it

**Comment by dcommander** [comment]
Can you reproduce the performance difference using tjbench? What are the specific CPUs?

**Comment by dcommander** [comment]
Closing due to lack of response
