### ISSUE TITLE
The saturation about 2 convert type

### ISSUE THREAD

**Issue by limuhai** [libjpeg-turbo/libjpeg-turbo#692]
The saturation of images converted from YUV420SP to JPG is lower than that of YUV420SP ->RGB ->JPG. How can I make the saturation of images converted from these two methods consistent

**Comment by dcommander** [comment]
It is impossible for me to answer your question unless you provide more information.  How exactly are you performing the conversion/compression operations?

**Comment by limuhai** [comment]
李木海先生的美女秘书提示您：您的邮件已收到，董事长稍后阅读，谢谢！
