### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by psmoros** [libjpeg-turbo/libjpeg-turbo#694]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@yairmzr) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by dcommander** [comment]
If the issue is just in 3.0 beta1, then you can simply file a GitHub issue for it. (There is no guarantee of production-readiness provided with beta releases.) Otherwise you can email me here: https://libjpeg-turbo.org/About/Contact. Time is of the essence, as I need to release 3.0 this week.

**Comment by dcommander** [comment]
@psmoros I have updated our security policy and also enabled the new GitHub security advisories feature, which allows people to submit security issues to me privately.  Please submit your issues ASAP if you want them fixed in libjpeg-turbo 3.0.

**Comment by dcommander** [comment]
@psmoros @huntr-helper You have until tomorrow to disclose the vulnerabilities to me. I am holding up the 3.0 release solely because of this issue. It is very unhelpful when people post a GitHub issue and do not respond or follow up. I have done what you asked. I added a security policy to our project, and you now have three ways (two of them secure and encrypted) to report vulnerabilities. The 3.0 release is overdue. Believe me that I will be *very* unhappy if I release 3.0 and you report the vulnerabilities the next day. I am giving you every chance to report them. If you want to help, then help, but silence is not helping.

**Comment by kleisauke** [comment]
FWIW, it's worth noting that this originates from a service named "huntr.dev", which has a disappointingly low signal-to-noise ratio see e.g. https://github.com/lovell/sharp/issues/2782.

**Comment by dcommander** [comment]
@yairmzr See above. If this is a legitimate issue, then it needs to be reported immediately.

**Comment by yairmzr** [comment]
@dcommander Thanks for tagging me.  
Sent a GitHub report via the security advisories feature.

**Comment by psmoros** [comment]
Sorry for the delay in responding @dcommander. I was traveling on the 1st of June and couldn't attend to your message promptly. I also want to express my regret for the invalid report we sent. Our system does generate false positives occasionally as @kleisauke has pointed out but we are enacting a system that blocks submissions if similar ones have been rejected by the maintainer so we won't send you any other reports like this one in the future.

Thank you for contributing your work to the public and for your patience with us as we attempt to solve the problem of open source security funding.

All the best,
Pavlos

**Comment by dcommander** [comment]
I wouldn't say it was invalid.  It was a valid issue.  It just wasn't a security issue, since the code in question is not distributed.  I fixed the issue in order to prevent downstream developers from interpreting **tjexample.c** literally and introducing similar issues into their own code.

**Comment by psmoros** [comment]
Ah! Noted :)
