### ISSUE TITLE
how to install the package in Ubuntu

### ISSUE THREAD

**Issue by chengdonglin** [libjpeg-turbo/libjpeg-turbo#698]
I have not find the  libjpeg-turbo by apt-get?

**Comment by dcommander** [comment]
libjpeg-turbo is provided by all current versions of Ubuntu, so you can install the distribution-packaged version of libjpeg-turbo through the APT repository for your Ubuntu distribution.  (The Ubuntu packages are called [`libjpeg-dev`](https://packages.ubuntu.com/focal/libjpeg-dev) and [`libturbojpeg0-dev`](https://packages.ubuntu.com/focal/libturbojpeg0-dev)).  23.04 also now includes the TurboJPEG Java API in a package called [`libturbojpeg-java`](https://packages.ubuntu.com/lunar/libturbojpeg-java).

If you want the latest official version of libjpeg-turbo, then you have to download the .deb file(s) from https://sourceforge.net/projects/libjpeg-turbo/files and install then using `dpkg -i`.
