### ISSUE TITLE
build.md: nasm needed for Visual C++ IDE build

### ISSUE THREAD

**Issue by DramaMask** [libjpeg-turbo/libjpeg-turbo#70]
I just wanted to leave some feedback on the build.md file. If this is not the correct place to leave my feedback, I'm sorry.

I just built jpeglib-turbo for the first time. I built it using the Visual C++ 2015 IDE. The build.md file was very helpful, but one step was missing. I had to download nasm, and add the install location to my PATH. May I suggest that this step be added to the build.md description?

Thanks.

**Comment by dcommander** [comment]
NASM is definitely listed in the requirements

![screen shot 2016-04-14 at 2 00 49 pm](https://cloud.githubusercontent.com/assets/651941/14540175/59a68862-0249-11e6-9ee4-e98f07282fc1.png)

It is a given that any external build tools used by Visual C++ need to either be in the PATH or configured with full pathnames in the Visual C++ IDE.  That is true of any tools, not just NASM.

**Comment by dcommander** [comment]
I think I see what you mean.  The "... OR ..." is not properly indented, which might cause one to mistakenly think that both MinGW and NASM are the alternatives to Visual C++, rather than just NASM.  I'll move that line up to the top to avoid confusion.

**Comment by DramaMask** [comment]
That was indeed the problem. I had assumed that NASM was part of the OR.

You could also move the NASM line up, to just below the CMake line. That would make it really clear. 
Or center the "OR" (which, as it seems, was the original intent).

Thank you for the quick reply by the way.

**Comment by dcommander** [comment]
The above commit does both (adjusts indentation of ... OR ... and moves the NASM line up.)
