### ISSUE TITLE
Apparent lack of unwind info in asm routines causes crash attempting to capture stacktrace

### ISSUE THREAD

**Issue by alk** [libjpeg-turbo/libjpeg-turbo#707]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

Yes, no signs of similar tickets (not sure why)

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

No

**Clear and concise description of the bug:**

So I got crash report on gperftools (https://github.com/gperftools/gperftools/issues/1405) with stack trace like this:

```
(gdb) where
#0 0x00007fd2b8d602c4 in ?? () from /usr/lib/x86_64-linux-gnu/libunwind.so.8
https://github.com/gperftools/gperftools/issues/1 0x00007fd2b8d60e06 in _ULx86_64_step () from /usr/lib/x86_64-linux-gnu/libunwind.so.8
https://github.com/gperftools/gperftools/pull/2 0x0000000002ed6dce in g3::internal::stackdump[abi:cxx11](char const*) ()
https://github.com/gperftools/gperftools/issues/3 0x0000000002ed7c40 in (anonymous namespace)::signalHandler(int, siginfo_t*, void*) ()
https://github.com/gperftools/gperftools/issues/4
https://github.com/gperftools/gperftools/issues/5 0x00007fd2b8d602c4 in ?? () from /usr/lib/x86_64-linux-gnu/libunwind.so.8
https://github.com/gperftools/gperftools/issues/6 0x00007fd2b8d60e06 in _ULx86_64_step () from /usr/lib/x86_64-linux-gnu/libunwind.so.8
https://github.com/gperftools/gperftools/issues/7 0x00007fd39cf9a323 in ?? () from /usr/lib/libtcmalloc.so.4
https://github.com/gperftools/gperftools/issues/8 0x00007fd39cf9ac6e in GetStackTraceWithContext(void**, int, int, void const*) ()
from /usr/lib/libtcmalloc.so.4
https://github.com/gperftools/gperftools/issues/9 0x00007fd2acc4f920 in CpuProfiler::prof_handler (signal_ucontext=,
cpu_profiler=0x7fd2ace59620, sig=) at src/profiler.cc:353
https://github.com/gperftools/gperftools/issues/10 0x00007fd2acc50493 in ProfileHandler::SignalHandler(int, siginfo_t*, void*) ()
at src/profile-handler.cc:545
https://github.com/gperftools/gperftools/issues/11
https://github.com/gperftools/gperftools/issues/12 0x00007fd2a73becd1 in ?? () from /usr/lib/x86_64-linux-gnu/libjpeg.so.8
https://github.com/gperftools/gperftools/issues/13 0x0000000000000f00 in ?? ()
```

What happens is cpu profiler sets up SIGPROF handler. It happens inside some jpeg routine. And then attempt to grab stacktrace crashes (which libunwind promises to work even from inside signal handlers; but they assume unwind info). And then more stack frames about some unrelated stuff in SIGSEGV signal handler (which also tries capture backtrace with same result; hehe)

I've only spent like 5 minutes in your code, but I do see plausible explanation. You do seem to do fairly non-standard things to stack frames and your asm seem to have no signs of unwind info (you know, those cfa_xxx directives). And I also see that gdb itself is unable to give stacktrace below that libjpeg routine.

Yes, this is arguably a nice to have. But it is very much worth to have. And shouldn't cost you much effort (assuming you do more or less identical stack frame setup which is likely).

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

I apologize I don't know anything about jpeg APIs and what not. And I am unable to provide simple repro. I guess easiest way to confirm (or prove me wrong) is trying to gdb step into those asm routines and see yourself whether backtrace works on every instruction or not. If I am right, it wont work at least on some instructions.

**Image(s) needed in order to reproduce the bug (if applicable):**

**Expected behavior:**

**Observed behavior:**

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

**Comment by dcommander** [comment]
I'm afraid that our project's current funding situation precludes me from working on any nice-to-have items at the moment, unless those items are specifically funded.  This feature would likely be more of a moderate effort than a simple effort, because it will require implementation and testing on all of the x86 platforms that we support.  (Needless to say, Windows doesn't handle unwinding in the same way that Linux does.)

**Comment by alk** [comment]
Sure. Up to you. But at least do consider at least changing you stack frames setup to be completely standard. Seems doable. I guess I can try to contribute that within couple days. (But do give me nack quickly if you're against that for some reason)

**Comment by dcommander** [comment]
Any changes such as that will have to be carefully benchmarked to guard against performance regression.  Feel free to submit a PR.  Just understand that I won't be able to test it immediately.
