### ISSUE TITLE
jpegtran drop patch

### ISSUE THREAD

**Issue by RamKromberg** [libjpeg-turbo/libjpeg-turbo#71]
Was the "Lossless crop 'n' drop (cut & paste)" defining jpegtran -drop left out for a specific reason?
http://jpegclub.org/droppatch.v9b.tar.gz

**Comment by dcommander** [comment]
Uh, first I've heard of it. I do not make a habit of tracking the goings-on of the IJG.  I stopped viewing them as an upstream project of libjpeg-turbo as of the release of jpeg-9, and the reasons why are listed here: http://www.libjpeg-turbo.org/About/Jpeg-9. I do examine each new IJG release and merge in any relevant bug fixes, but I am not going to blindly merge in features from the IJG's software without reviewing them thoroughly, because the IJG post-Tom Lane has a bad habit of introducing features that break compatibility and are of debatable usefulness.

**Comment by RamKromberg** [comment]
Fair enough. Though, to my knowledge, this is the only lossless jpeg merging option on linux. I personally used the feature on and off for years but I understand your reluctance in chasing the feature bloat of semi-abandoned upstream.

Regardless, I'll follow up on the Debian end for the legacy jpeg-9 package. It was requested in the past under debian bug #160390 but was improperly closed despite not being patched in.

Thanks for taking the time to look it up.

**Comment by dcommander** [comment]
The IJG obviously doesn't consider it to be generally useful enough to include it in their releases, so why should we?  This seems like a really esoteric feature to me.  I am open to it, but I need to understand more about why it's necessary.  Are there any prominent applications that use the feature?  Why would someone ever need to combine coefficient blocks from two separate JPEG files?

Seems like it would be straightforward for someone to create a branch on GitHub that includes this feature merged in with our code base, even if we decide not to include it (which is likely, unless I can be convinced of its general utility.)

**Comment by RamKromberg** [comment]
Hmm, well, I can't in good conscious argue for it's general utility as it quite a niche feature... And I also don't feel it's my right to weight the pros and cons on a project I'm not a part of... Still, I'll leave this here for your discretion:
https://github.com/Ensighten/spritesmith
https://photo.stackexchange.com/questions/71841/compress-a-few-small-areas-of-an-image-in-higher-quality/71851 2nd answer

Feel free to ignore or close the issue altogether if you remain unconvinced. I prompted this feature thinking it's simply a trivial matter that might be worth queuing down a TODO wishlist and would at worst be flat out rejected on the spot.

Thank you for your time :)

**Comment by dcommander** [comment]
The StackExchange comments highlight my major concern about the feature, which is that it can only be used to combine images on a block-by-block basis, and if used as described in that article, you will see visual artifacts at the block boundaries.  I think the best approach would probably be for you or someone else to maintain a GitHub fork with the feature, so the few people who need it can easily access it.

**Comment by nicolas-raoul** [comment]
> I am open to it, but I need to understand more about why it's necessary.

Real-world need: Obscure/censor part of a picture (for privacy purposes) while leaving the rest of the picture lossless.
If both crop and drop were available, I would implement such a feature in my popular software.

Thank you for your consideration.

**Comment by dcommander** [comment]
@nicolas-raoul Neither does the TurboJPEG C API. I integrated the relevant code from jpeg-9a and jpeg-9d, but that only affects the libjpeg API. That effort depleted the libjpeg-turbo General Fund for several months. Adding support for this to the TurboJPEG APIs would require funding and would be best integrated as part of #517.

**Comment by dcommander** [comment]
@nicolas-raoul Also, this specific issue was related to a feature that can be used to combine two JPEG images on a block-by-block basis. That is not the same as the `jpegtran -drop` feature that I integrated.

**Comment by RamKromberg** [comment]
I'm not too up-to-date on the issue... But, to my knowledge, the feature was graduated from the patch set into the reference libjpeg and their jpegtran implementation a few years ago. e.g.
```
$ jpegtran --help 2>&1 | grep drop
  -drop +X+Y filename          Drop another image
```
So, with libjpeg's jpegtran at least, you can paste one jpeg into another jpeg by-the-block without losing data over re-compression.

Anyhow, back in the day I used the drop feature to insert date stamps into a hobby time-lapse photography project using the reference library's jpegtran[1] and was wondering why the libjpeg-turbo implementation was missing it so I asked. However, with a minute between every shot, I never needed the performance and only thought it would be a nice feature to have "down a TODO wishlist".

[1] split the bottom, inserted text with imagemagick to the bottom, and dropped the bottom back so only the bottom was recompressed as opposed to the whole image.

**Comment by tntmod54321** [comment]
> Please forgive my early-morning confusion. Yes, the `-drop` feature is in libjpeg-turbo 2.1.x. Adding such features to the TurboJPEG API will be easier once it is refactored.

Hi, I believe the refactoring mentioned has already occurred as I wrote this, is there any chance of this feature getting implemented? It would be amazing.

**Comment by dcommander** [comment]
Even after scaling back my ambitions by about 50% regarding the TurboJPEG 3 API overhaul, that and other libjpeg-turbo 3.0 features put our project into debt. Fortunately the community stepped up and covered the labor retroactively, so we're back in the black, but not so much in the black that I can afford to spend our general fund money to extend a rarely-used jpegtran feature to the TurboJPEG API, which (despite its improvements over the years) remains less popular than the libjpeg API. Implementing the equivalent of `-drop` in the TurboJPEG API would probably require buffer management, which is a major API feature that slipped the TurboJPEG 3 overhaul and was pushed to TurboJPEG 4. (See #646.) Thus, the likely prerequisite for adding an equivalent of `-drop` to the TurboJPEG API doesn't exist yet. The whole lossless transform module in the API needs to be redesigned with buffer management.
