### ISSUE TITLE
Own Visual Studio Project problems with version 3.0

### ISSUE THREAD

**Issue by sati32** [libjpeg-turbo/libjpeg-turbo#712]
I am building the library with my own project in Visual Studio.
I don't use Make files and such things, so I have to build the config headers myself.
With version 3.0 I have a problem.
For example, in jdmaster.c there is a block like
    if (cinfo->data_precision == 12)
      j12init_d_coef_controller(cinfo, use_c_buffer);
    else
      jinit_d_coef_controller(cinfo, use_c_buffer);

j12init_d_coef_controller is defined in jsamplecomp.h, but since I defined 
BITS_IN_JSAMPLE to 8 in jconfig.h, I don't have the 12- and 16-bit define.
So it won't compile.

What can I do to solve this?

**Comment by dcommander** [comment]
Use CMake to generate the Visual Studio project files, as **BUILDING.md** instructs.  I can only support our own build system.  If you choose to hack together your own downstream build system, then it is your responsibility to support it.
