### ISSUE TITLE
How to auto insert or delete block jpeg?

### ISSUE THREAD

**Issue by VQD-BSV** [libjpeg-turbo/libjpeg-turbo#717]
hi
How to auto insert or delete block jpeg?
![image](https://github.com/libjpeg-turbo/libjpeg-turbo/assets/127699283/58394f2e-cd59-4a2c-a6d4-0fade58365fd)

**Comment by dcommander** [comment]
Sorry, I don't understand what you are asking.

**Comment by dcommander** [comment]
Sorry, I still don't understand. Please bear in mind that libjpeg-turbo is a codec library, not a comprehensive image processing/editing package.
