### ISSUE TITLE
JCS_RGB565 as in_color_space results in "Bogus input colorspace" 

### ISSUE THREAD

**Issue by DarwinAnim8or** [libjpeg-turbo/libjpeg-turbo#723]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Searching for RGB565 posts resulted in nothing similar to what I am experiencing. 

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No

**Clear and concise description of the bug:**
Calling jpeg_set_defaults() with JCS_RGB565 as in_color_space results in "Bogus input colorspace" 

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
The following code shows a simple example of encoding a stream of pixels to jpeg. However, the jpeg_set_defaults() will error when it is hit. 

```cpp
typedef struct {
    unsigned short b : 5;
    unsigned short g : 6;
    unsigned short r : 5;
} rgb565_pixel;

// Encode a RGB565 buffer to a JPEG file
void encode_rgb565_to_jpeg(const char* filename, const rgb565_pixel* buffer, int width, int height, int quality) {
    // Create a JPEG compression object
    struct jpeg_compress_struct cinfo;
    struct jpeg_error_mgr jerr;
    cinfo.err = jpeg_std_error(&jerr);
    jpeg_create_compress(&cinfo);

    // Open the output file
    FILE* outfile = fopen(filename, "wb");
    if (outfile == NULL) {
        fprintf(stderr, "Cannot open output file %s\n", filename);
        exit(1);
    }
    jpeg_stdio_dest(&cinfo, outfile);

    // Set the parameters of the compression
    cinfo.image_width = width;
    cinfo.image_height = height;
    cinfo.input_components = 2; // RGB565
    cinfo.in_color_space = JCS_RGB565; // use the RGB565 constant
    jpeg_set_defaults(&cinfo);
    jpeg_set_quality(&cinfo, quality, TRUE);

    // Start the compression
    jpeg_start_compress(&cinfo, TRUE);

    // Write the scanlines
    JSAMPROW row_pointer[1];
    while (cinfo.next_scanline < cinfo.image_height) {
        row_pointer[0] = (JSAMPLE*)&buffer[cinfo.next_scanline * width];
        jpeg_write_scanlines(&cinfo, row_pointer, 1);
    }

    // Finish the compression and close the file
    jpeg_finish_compress(&cinfo);
    fclose(outfile);

    // Free the resources
    jpeg_destroy_compress(&cinfo);
}
```

**Image(s) needed in order to reproduce the bug (if applicable):**
n/a

**Expected behavior:**
It sets the defaults as it does with all the other color spaces available. 

**Observed behavior:**
It reports that it is not a valid color space despite the fact that it does have a listing in the header file for it. 

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
Windows x64

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
stable, 3.0.0

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

**Comment by dcommander** [comment]
RGB 565 is only supported as an output colorspace during decompression. RGB 565 decompression was added solely to support Android. It is a legacy feature that may not even be used very often in Android these days. It makes no sense to compress from an RGB 565 image to a JPEG image, because it would involve upsampling each component to 8-bit. You would essentially be compressing junk data, and that partially defeats the purpose of compression. I will modify the header to make it clear that `JCS_RGB565` is for decompression only.

**Comment by dcommander** [comment]
NOTE: The change log often serves to document lesser-used features:

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/9b704f96b2dccc54363ad7a2fe8e378fc1a2893b/ChangeLog.md?plain=1#L1629-L1631

However, I also modified **jpeglib.h** to indicate that `JCS_RGB565` is only for decompression.
