### ISSUE TITLE
Can't find any turbojpeg.lib after the build of libjpeg-turbo.

### ISSUE THREAD

**Issue by NmkDjecko** [libjpeg-turbo/libjpeg-turbo#733]
I'am trying to build a lua library, a port of Opengl for lua ([https://github.com/vrld/G4L]), and i keep getting this error message 
`CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/MinGW64/x86_64-13.2.0-release-posix-seh-ucrt-rt_v11-rev0/mingw64/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/MinGW64/x86_64-13.2.0-release-posix-seh-ucrt-rt_v11-rev0/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Lua51: C:/Lua/lua5.1.lib (found version "")
-- Found OpenGL: opengl32
-- Found GLUT: C:\Users\Djeck\program\lib\glut\lib\glut32.lib
-- Found ZLIB: C:/Program Files (x86)/zlib/lib/libzlib.dll.a (found version "1.3")
-- Found PNG: C:/Program Files (x86)/libpng/lib/libpng.a (found version "1.6.41.git")
-- Could NOT find TJPEG (missing: TJPEG_LIBRARY)
-- Configuring done (2.6s)
CMake Error at CMakeLists.txt:65 (add_library):
  No SOURCES given to target: G4L`

I then tried to search for the **turbojpeg.lib** but didn't find it after building and installing.
If it's evident don't blame, i just started gamedev and coding in general.

**Comment by dcommander** [comment]
It would be more helpful if you posted the output of the libjpeg-turbo build rather than the output of the lua build.  But please note that, if you built libjpeg-turbo with MinGW, it will not contain **turbojpeg.lib**.  It will contain **libturbojpeg.a**.  (Refer to **BUILDING.md**.)  Note also that you can use one of our pre-built libjpeg-turbo SDKs for Windows.  We provide a pre-built SDK that works with MinGW.

**Comment by NmkDjecko** [comment]
Thanks ! Quick answer, i'm impressed. I will install it using MinGW and i'll come back !
