### ISSUE TITLE
Detailed introduction to the JPEG compression acceleration document of libjpeg turbo

### ISSUE THREAD

**Issue by B-JackMao** [libjpeg-turbo/libjpeg-turbo#750]
Hello,
May I ask if there is any specific file explaining the difference between libjpeg and libjpeg turbo compared to continuous? Or provide a detailed explanation of how libjpeg turbo specifically performs JPEG compression acceleration?

**Comment by dcommander** [comment]
What do you mean by "continuous"? No, there is no such document. libjpeg-turbo simply takes advantage of the modular architecture of libjpeg and the potential for low-level data parallelism in the various JPEG algorithms, and it implements SIMD versions of each of those algorithms for various popular SIMD instruction sets. The SIMD code is well documented using inline comments, so use the code itself as a reference if you need more detail. There are six or seven different SIMD implementations at this point, so if one implementation doesn't make sense, you can refer to another one. (For instance, one of the intrinsics implementations, such as Neon or AltiVec, may be easier to read than the raw assembly code used on x86.)
