### ISSUE TITLE
12-bit encoding ignores value of cinfo.optimize_coding

### ISSUE THREAD

**Issue by steffen-kiess** [libjpeg-turbo/libjpeg-turbo#751]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No

**Clear and concise description of the bug:**
When using 12-bit encoding, the value of `cinfo.optimize_coding` is ignored, even if it is overwritten after calling `jpeg_set_defaults()`. (`jpeg_set_defaults()` will set `cinfo.optimize_coding` to `TRUE` because the default huffman tables won't work for 12-bit encoding.)

This was introduced by changes in e8b40f3c2ba187ba95c13c3e8ce21c8534256df7: <https://github.com/libjpeg-turbo/libjpeg-turbo/commit/e8b40f3c2ba187ba95c13c3e8ce21c8534256df7#diff-7b52aad818fd05b6cd481a2f365db62bdeeb5d561f8467586e1d2861c6810bd4L615>
Here, `jinit_c_master_control()` (which is called by `jinit_compress_master()`, which is called by `jpeg_start_compress()`) overwrites `cinfo->optimize_coding`. This should not be needed because `jpeg_set_defaults()` should already set it to `TRUE` (but allow overwriting by the application).

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
The attached file contains example code which generates a file without any tables. (Note that it does not really anything useful because it uses the default huffman tables with 12-bit encoding).
[example.c.txt](https://github.com/libjpeg-turbo/libjpeg-turbo/files/14465205/example.c.txt)

**Image(s) needed in order to reproduce the bug (if applicable):**

**Expected behavior:**
When running the code:
```
cinfo.optimize_coding: 0
```
When running `hexdump -C test.jpeg`:
```
00000000  ff d8 ff c1 00 0b 0c 00  08 00 08 01 00 11 00 ff  |................|
00000010  da 00 08 01 00 00 00 3f  00 33 2a ff d9           |.......?.3*..|
0000001d
```
The only markers are SOI (`ff d8`), SOF1 (`ff c1`), SOS (`ff da`) and EOI (`ff d9).

**Observed behavior:**
When running the code:
```
cinfo.optimize_coding: 1
```
When running `hexdump -C test.jpeg`:
```
00000000  ff d8 ff c1 00 0b 0c 00  08 00 08 01 00 11 00 ff  |................|
00000010  c4 00 14 00 01 00 00 00  00 00 00 00 00 00 00 00  |................|
00000020  00 00 00 00 0c ff c4 00  14 10 01 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 ff da 00 08 01  |................|
00000040  00 00 00 3f 00 19 93 ff  d9                       |...?.....|
00000049
```
Note that huffman tables are included (`ff c4`).

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
Debian 12, gcc 12.2.0, amd64 CPU.

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
Commit 3202feb08aef2d4d1fb35b5af94f1ac92fb993d0 (current main branch tip).

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**
From what I can see the following code can simply be dropped from `jcmaster.c` because `cinfo->optimize_coding` is already initialized to `TRUE` in `jpeg_set_defaults()`.
```
  if (cinfo->data_precision == 12 && !cinfo->arith_code)
    cinfo->optimize_coding = TRUE; /* assume default tables no good for 12-bit
                                      data precision */
```

**Comment by dcommander** [comment]
If Huffman tables are not explicitly included in the JPEG file, then JPEG decompressors will assume that the default Huffman tables should be used.  However, the default Huffman tables are only valid for 8-bit precision.  If you actually try to compress a real image into a 12-bit JPEG image without Huffman tables, then you will get junk pixels if you try to decompress that JPEG image.  (Our own decompressor will throw a "bad Huffman code" warning.)  12-bit JPEG images must always use optimized Huffman coding, and the code in **jcmaster.c** is there precisely to prevent someone from doing something stupid like your example application does.

**Comment by dcommander** [comment]
OK, but the API doesn't require `jpeg_set_defaults()` to be called, nor does it require that `cinfo->data_precision` be set prior to calling `jpeg_set_defaults()`.  `jpeg_set_defaults()` basically just guesses at the appropriate value of `cinfo->optimize_coding`.  It would be poor API design for the compressor to generate an image that it can't decompress unless the application calls `jpeg_set_defaults()`.  It would be better if the compressor defaults to `cinfo->optimize_coding = TRUE` for 12-bit precision and changes the default only if the Huffman tables are defined by the calling application.  Since those tables must be defined prior to calling `jpeg_start_compress()`, we could simply expand rather than remove the code in `jinit_c_master_control()`.  The [libjpeg v6b API documentation](https://github.com/libjpeg-turbo/ijg/blob/jpeg-6b/libjpeg.doc#L2878-L2881) states:

```
Note that a 12-bit library always compresses in Huffman optimization mode,
in order to generate valid Huffman tables.  This is necessary because our
default Huffman tables only cover 8-bit data.  If you need to output 12-bit
files in one pass, you'll have to supply suitable default Huffman tables.
```

That implies that the library will always compress in Huffman optimization mode unless suitable default Huffman tables are supplied, which is consistent with my proposal above.  If suitable default Huffman tables are supplied, then the calling application could also call `jpeg_suppress_tables()` to generate a 12-bit abbreviated image datastream.

Our of curiosity, what is the application for generating 12-bit JPEG images with custom Huffman tables?  That is certainly not a normal use case.

**Comment by steffen-kiess** [comment]
> Since those tables must be defined prior to calling `jpeg_start_compress()`, we could simply expand rather than remove the code in `jinit_c_master_control()`.

That would be fine with me, as long as there is some way to disable `optimize_coding`.

> Our of curiosity, what is the application for generating 12-bit JPEG images with custom Huffman tables? That is certainly not a normal use case.

I'm compressing 3D volume data. I'm compressing individual blocks separately (so that I can also decompress them separately), but because each individual block is relatively small, I don't want to have the overhead of storing the huffman table (or the quantization table) for each block, so I have to use the same table for all of them.

**Comment by dcommander** [comment]
Test the latest build and see if it does what you need.

**Comment by steffen-kiess** [comment]
Yes, with the current main branch 12-bit compression and decompression is working in my code.

Thank you for fixing this!
