### ISSUE TITLE
Possibly broken integer overflow check.

### ISSUE THREAD

**Issue by moshev** [libjpeg-turbo/libjpeg-turbo#752]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

Yes.

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

No

**Clear and concise description of the bug:**

The overflow checks in turbojpeg.c do nothing on 64-bit Unix platforms (and LP64 platforms in general). On these platforms the types `long` and `long long` are both 64-bit and the check comparing an `unsigned long long` variable to the maximum value representable as a `unsigned long` are tautological, since the types are identical. This is possibly a bug left over from code written for a 32-bit platform.

I'm calling it "possibly broken", because I can't be sure if the intent was to not have an overflow check on LP64 platforms. If that is the case, it would be nice to have a preprocessor guard around the condition a-la `#if ULLONG_MAX > ULONG_MAX` to make it clear.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

Compile with clang 14 and add `-Werror=tautological-type-limit-compare`

**Image(s) needed in order to reproduce the bug (if applicable):**

N/A

**Expected behavior:**

Compiles without error

**Observed behavior:**

```
turbojpeg.c:537:14: error: result of comparison 'unsigned long long' > 18446744073709551615 is always false [-Werror,-Wtautological-type-limit-compare]
  if (retval > (unsigned long long)((unsigned long)-1))
      ~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
turbojpeg.c:555:14: error: result of comparison 'unsigned long long' > 18446744073709551615 is always false [-Werror,-Wtautological-type-limit-compare]
  if (retval > (unsigned long long)((unsigned long)-1))
      ~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
turbojpeg.c:581:14: error: result of comparison 'unsigned long long' > 18446744073709551615 is always false [-Werror,-Wtautological-type-limit-compare]
  if (retval > (unsigned long long)((unsigned long)-1))
      ~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
turbojpeg.c:658:14: error: result of comparison 'unsigned long long' > 18446744073709551615 is always false [-Werror,-Wtautological-type-limit-compare]
  if (retval > (unsigned long long)((unsigned long)-1))
      ~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
turbo/turbojpeg.c:2116:65: error: result of comparison 'unsigned long long' > 18446744073709551615 is always false [-Werror,-Wtautological-type-limit-compare]
  if ((unsigned long long)pitch * (unsigned long long)(*height) >
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
```

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

clang-14, Rocky Linux 8, aarch64 and x86_64.

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

Found in version 2.1.0. The relevant lines do not seem to have been changed in current master.

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

**Comment by dcommander** [comment]
I [go out of my way](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/.github/workflows/build.yml#L152) to support a lot of non-default compiler warning options, but it is impossible to support all of them.  In general, I try to focus on the warning options that identify readability or conformance issues in the code, and tautological comparisons don't really rise to that level.  If the warnings were enabled by `-Wall`, `-Wpedantic`, or `-Wextra`, then I would consider fixing them.

**Comment by moshev** [comment]
I may not have explained it clearly. The problem is not with the warning per se, it's that it seems there is a bug in the code. The lines in question are trying to check for unsigned integer overflow, but the final value is compared with a constant so large, that the condition in the `if` will always be false on 64-bit Linux. Moreover, it has different behaviour on 64-bit Unix and 64-bit Windows, due to the fact that the expression `(unsigned long)-1` is 64-bit on 64-bit Linux, but 32-bit on 64-bit Windows.

I'm not worried about the warning, I'm asking if the code in question is actually functioning as intended.

**Comment by dcommander** [comment]
Ah, OK.  Yes, the code in question is intended to prevent integer overflow on platforms where `unsigned long` or `size_t` are 32-bit.  Since the return value of the functions in question could be passed to `malloc()`, overflowing the return datatype could lead to a smaller-than-expected buffer being allocated.  The code is expected to be tautological on LP64 platforms.  Windows is LLP64, so the code is still relevant there.
