### ISSUE TITLE
jpeg-turbo 3.0.2 Test failures on macOS 13 & 14 ARM with 

### ISSUE THREAD

**Issue by Porkepix** [libjpeg-turbo/libjpeg-turbo#753]
Hi, trying to report these builds failures, as I tried to update the formula when I saw the `libjpeg-turbo` update on my ArchLinux and Homebrew's livecheck couldn't pickup the new version due to the change of location for the reference repo.
Also note that from what I saw in https://github.com/libjpeg-turbo/libjpeg-turbo/issues/709 & https://github.com/libjpeg-turbo/libjpeg-turbo/issues/734 mentioned for specific fixes in the formulas, these issues are supposed to be taken care of by this XCode 15.1, from what I understand?

Bump try is at https://github.com/Homebrew/homebrew-core/pull/161349

**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes.

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No.

**Clear and concise description of the bug:**

Running `ctest --test-dir build --rerun-failed --output-on-failure --parallel 4` produces these errors (the exact same) on both macOS 13 & 14 only on ARM architectures.

```
  99% tests passed, 4 tests failed out of 590
  
  Total Test time (real) =  25.51 sec
  
  The following tests FAILED:
  	135 - djpeg-shared-3x2-float-prog-cmp (Failed)
  	246 - djpeg12-shared-3x2-float-prog-cmp (Failed)
  	430 - djpeg-static-3x2-float-prog-cmp (Failed)
  	541 - djpeg12-static-3x2-float-prog-cmp (Failed)
  Errors while running CTest
```

See full build logs for `14-arm64` at https://github.com/Homebrew/homebrew-core/actions/runs/8207035226/job/22447525332?pr=161349 and `13-arm64` at https://github.com/Homebrew/homebrew-core/actions/runs/8207035226/job/22447525803?pr=161349

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
Can't provide some as I don't have the OS with the issues at hand locally, but I guess the same as in https://github.com/libjpeg-turbo/libjpeg-turbo/issues/709 would apply.

**Image(s) needed in order to reproduce the bug (if applicable):**
N/A

**Expected behavior:**
No failures

**Observed behavior:**
Tests failures

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
macOS 13 & 14, ARM architecture only.
XCode's version is 15.1.0

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
Issue's on release 3.0.2

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**
No way to bisect with no access to a local failure, but `3.0.1` was building in the past.

**Additional information:**
There are mentions to https://github.com/libjpeg-turbo/libjpeg-turbo/issues/709 and https://github.com/libjpeg-turbo/libjpeg-turbo/issues/734 with specific fixes for these issues (see specifically https://github.com/Homebrew/homebrew-core/blob/master/Formula/j/jpeg-turbo.rb#L42 and https://github.com/Homebrew/homebrew-core/blob/master/Formula/j/jpeg-turbo.rb#L47).

Also, completely unrelated, but the CMake starts with this before the build:
``` 
CMake Warning:
    Manually-specified variables were not used by the project:
  
      BUILD_TESTING
```
But nothing in the formula seems to relate to this, so I guess it's still useful to give you a heads up about this.

**Comment by dcommander** [comment]
Should have already been fixed by https://github.com/libjpeg-turbo/libjpeg-turbo/commit/47656a082091f9c9efda054674522513f4768c6c, which is in libjpeg-turbo 3.0.1 and later.

**Comment by dcommander** [comment]
Does the same issue occur with Xcode 14.3?

**Comment by dcommander** [comment]
Looking at the build logs, the actual checksums that are being produced match the expected checksums if `CMAKE_C_COMPILER_ID` is `Clang` and `FLOATTEST8` and `FLOATTEST12` are `fp-contract`. That makes me suspect that maybe Xcode 15 did something that caused `CMAKE_C_COMPILER_ID` to change.  I have no way of testing any of this, because I don't have access to an Apple silicon Mac.  (My Mac isn't even new enough to run Ventura or Xcode 14.3 or later.)  Thus, I need your help with diagnosing it.

**Comment by timsutton** [comment]
Can confirm: I'm not sure when the change was introduced, but `CMAKE_C_COMPILER_ID` is `AppleClang` now.

This naive patch I built on top of the `3.0.2` gets me a passing build on a current macOS that was otherwise failing with the above issue:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index adb0ca45..f818608f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -395,7 +395,7 @@ if(MSVC)
   add_definitions(-D_CRT_NONSTDC_NO_WARNINGS)
 endif()
 
-if(CMAKE_COMPILER_IS_GNUCC OR CMAKE_C_COMPILER_ID STREQUAL "Clang")
+if(CMAKE_COMPILER_IS_GNUCC OR CMAKE_C_COMPILER_ID MATCHES "^(Apple)*Clang$")
   # Use the maximum optimization level for release builds
   foreach(var CMAKE_C_FLAGS_RELEASE CMAKE_C_FLAGS_RELWITHDEBINFO)
     if(${var} MATCHES "-O2")
@@ -468,7 +468,7 @@ if(UNIX)
   endif()
 endif()
 
-if(NOT MSVC OR CMAKE_C_COMPILER_ID STREQUAL "Clang")
+if(NOT MSVC OR CMAKE_C_COMPILER_ID MATCHES "^(Apple)*Clang$")
   check_c_source_compiles("const int __attribute__((visibility(\"hidden\"))) table[1] = { 0 }; int main(void) { return table[0]; }"
     HIDDEN_WORKS)
   if(HIDDEN_WORKS)
@@ -907,7 +907,7 @@ if(CPU_TYPE STREQUAL "x86_64" OR CPU_TYPE STREQUAL "i386")
     set(DEFAULT_FLOATTEST8 no-fp-contract)
   endif()
 elseif(CPU_TYPE STREQUAL "powerpc" OR CPU_TYPE STREQUAL "arm64")
-  if(CMAKE_C_COMPILER_ID STREQUAL "Clang")
+  if(CMAKE_C_COMPILER_ID MATCHES "^(Apple)*Clang$")
     if(CMAKE_C_COMPILER_VERSION VERSION_EQUAL 14.0.0 OR
       CMAKE_C_COMPILER_VERSION VERSION_GREATER 14.0.0)
       set(DEFAULT_FLOATTEST8 fp-contract)
@@ -949,7 +949,7 @@ endif()
 if(CPU_TYPE STREQUAL "x86_64")
   set(DEFAULT_FLOATTEST12 no-fp-contract)
 elseif(CPU_TYPE STREQUAL "powerpc" OR CPU_TYPE STREQUAL "arm64")
-  if(CMAKE_C_COMPILER_ID STREQUAL "Clang")
+  if(CMAKE_C_COMPILER_ID STREQUAL MATCHES "^(Apple)*Clang$")
     if(CMAKE_C_COMPILER_VERSION VERSION_EQUAL 14.0.0 OR
       CMAKE_C_COMPILER_VERSION VERSION_GREATER 14.0.0)
       set(DEFAULT_FLOATTEST12 fp-contract)
@@ -1212,6 +1212,8 @@ foreach(libtype ${TEST_LIBTYPES})
         ${MD5_JPEG_3x2_FLOAT_PROG_NO_FP_CONTRACT})
       if(CMAKE_C_COMPILER_ID MATCHES "^(Apple)*Clang")
         set(MD5_PPM_3x2_FLOAT_FP_CONTRACT 2da9de6ae869e88b8372de815d366b03)
       else()
         set(MD5_PPM_3x2_FLOAT_FP_CONTRACT ${MD5_PPM_3x2_FLOAT_SSE})
       endif()
@@ -1284,6 +1286,8 @@ foreach(libtype ${TEST_LIBTYPES})
         ${MD5_JPEG_3x2_FLOAT_PROG_NO_FP_CONTRACT})
       if(CMAKE_C_COMPILER_ID MATCHES "^(Apple)*Clang$")
         set(MD5_PPM_3x2_FLOAT_FP_CONTRACT ${MD5_PPM_3x2_FLOAT_NO_FP_CONTRACT})
       else()
         set(MD5_PPM_3x2_FLOAT_FP_CONTRACT 0e917a34193ef976b679a6b069b1be26)
       endif()
```

**Comment by cho-m** [comment]
> Looking at the build logs, the actual checksums that are being produced match the expected checksums if `CMAKE_C_COMPILER_ID` is `Clang` and `FLOATTEST8` and `FLOATTEST12` are `fp-contract`. That makes me suspect that maybe Xcode 15 did something that caused `CMAKE_C_COMPILER_ID` to change.

`AppleClang` should have been available since [CMake 3.0](https://cmake.org/cmake/help/latest/policy/CMP0025.html) and automatically used if [`cmake_minimum_required` version enables policy](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html)

So https://github.com/libjpeg-turbo/libjpeg-turbo/commit/1644bdb7d2fac66cd0ce25adef7754e008b5bc1e (v3.0.2) would impact this by adding a `<policy_max>`
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/dfde1f857d5bdc0ff214c5f920f04ea8287005ed/CMakeLists.txt#L1

**Comment by timsutton** [comment]
Nice catch @cho-m! I see https://github.com/libjpeg-turbo/libjpeg-turbo/issues/740 also had at least another unexpected side effect.

@dcommander For this specific issue of the value of `CMAKE_C_COMPILER_ID`, is there a preferred way to achieve the same result as what my diff was doing? (where we just let it walk the same if conditions for either Clang flavor?) If you're good with the idea I'm happy to open a PR and go from there.

**Comment by dcommander** [comment]
<sigh> No good deed goes unpunished, I guess. This is at least the second issue that has surfaced because someone complained about a CMake warning and someone else assured me that it was safe to silence the warning by adding `...3.28` to our minimum version string. No one ever mentioned the little quirk of CMake's behavior whereby specifying a range of supported versions means that you have to be prepared to handle every single policy change that occurred during that range.

Anyway, this is probably fixable by simply comparing `CMAKE_COMPILER_ID` with a regex. I'll look into it on Monday.

**Comment by timsutton** [comment]
Just opened https://github.com/libjpeg-turbo/libjpeg-turbo/pull/755 🙏
