### ISSUE TITLE
PR #756 (add COMPONENT) breaks the cmake exported config

### ISSUE THREAD

**Issue by lgritz** [libjpeg-turbo/libjpeg-turbo#759]
**Clear and concise description of the bug:**

PR #756 (you don't seem to actually merge PRs, just close them?, so it's commit 24e09baaf0 if that helps) adds COMPONENT to all the cmake `install` calls.

I looked at the diffs and I can't quite spot the error, but somehow this turns out to mess with your exported cmake config in unfortunate ways, for example, lines like this show up in libjpeg-turboTargets.cmake:

```
set_target_properties(libjpeg-turbo::turbojpeg PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/COMPONENT;${_IMPORT_PREFIX}/include"
)
```

Notice that one element is `${_IMPORT_PREFIX}/COMPONENT` -- it's adding a directory to the include search path that is *named* COMPONENT, which I really don't think was the intent.

This breaks downstream projects, for example when I do a `find_package(libjpeg-turbo)` to consume your config exports and try to use the targets, I get build errors like this:

```
CMake Error in src/libOpenImageIO/CMakeLists.txt:
  Imported target "libjpeg-turbo::jpeg" includes non-existent path

    "/Users/lg/code/oiio/oiio.lg/ext/dist/COMPONENT"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

Build any test project that consumes your exported cmake config and try to use the targets you provide.

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

Seen first on my project's CI on Linux (I do a test build against the top of main of several important dependencies), but I was also able to reproduce easily on my MacOS laptop.

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

This only happens on the current (as of this moment) top of your tree, not in any release.

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

24e09baaf0

**Additional information:**

**Comment by dcommander** [comment]
I do not merge PRs unless the PR is 100% the way I want it, including formatting, commit message, etc. Since that almost never happens, I usually merge the PR locally, change it to my liking, amend the commit, and push. This project does not work like most projects, because it has quality constraints that most projects do not have. Those constraints come from the ridiculous exposure that this code base has, being used by literally billions of people every day. Corollary: It is very common that, when I do something to help one user, it breaks something for another user, which is why I have to take an extremely conservative approach to modifying the code. But even being extremely conservative isn't sufficient a lot of times. Of course I could not have imagined in my wildest dreams that #756 would break the config files. I will try to reproduce and diagnose it on Monday.

@kleisauke Any idea what might be happening?

**Comment by lgritz** [comment]
@dcommander I wasn't actually trying to criticize how you do the integration of new code, I totally understand (and also run critical projects). I was just trying to cite the PR that seemed to be where the responsible code originated, while pointing out that I know that it wasn't a direct merge on GH.

I haven't really had reason to dig into the jpeg-turbo code base (let alone tests), so please excuse me if what I'm about to say is obvious or something you already do. I'm not at all trying to be patronizing.

It's really easy to have a project's tests, by being part of and driven by the project's build system, fail to be able to detect if the exported cmake configs are broken. I've made that mistake many times myself, and I've gotten in the habit on my critical projects to always have at least one test as part of the CI that independently builds an executable that uses the library, based on the *installed* artifacts (not the temporary build dir), and that is independent of the project's own build and must consume the cmake exports in order to build correctly (mimicking the experience of a downstream project).

**Comment by dcommander** [comment]
I will look into adding an appropriate CI test once I figure out what's wrong and how to fix it. At the moment, I have no clue why adding a `COMPONENT` option to `install()` would affect the config files.

**Comment by kleisauke** [comment]
It looks like `COMPONENT` needs to be removed from the `INCLUDES DESTINATION ...` options, as it is treated differently by CMake, see:
https://cmake.org/cmake/help/latest/command/install.html#signatures
(I incorrectly assumed it was treated the same way as the  `<artifact-kind> <artifact-option>...` group)

Just opened PR #760 for this.

**Comment by dcommander** [comment]
@kleisauke In the future, please do not open PRs for simple fixes. See above. It is easier for me to integrate the fixes myself rather than process a PR.

**Comment by lgritz** [comment]
I can report that the patch completely fixes the issue for my downstream projects. Thanks!
