### ISSUE TITLE
Pixel ratio support

### ISSUE THREAD

**Issue by fabiencastan** [libjpeg-turbo/libjpeg-turbo#77]
Hi,
It seems that there is no way to set the pixel aspect ratio (X_density / Y_density) as we can do with libjpeg. tjCompress2 only expose few arguments and the jpeghandle use blind pointer to [tjinstance defined in the turbojpeg.c](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/turbojpeg.c#L93).
So there is no way to access the "jpeg_compress_struct".

I tried a hack by redefining the tjinstance struct on my side, but in fact the tjCompress2 reset the default values [there](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/turbojpeg.c#L782).

Is there a way to do it?

**Comment by dcommander** [comment]
The TurboJPEG API is designed for the most common use cases, but for more advanced features, you'll need to use the libjpeg API.  Both APIs perform equivalently in libjpeg-turbo, all else being equal.

**Comment by fabiencastan** [comment]
Ok, thanks!

**Comment by dcommander** [comment]
Subsumed by #517

**Comment by dcommander** [comment]
This has been implemented in the new TurboJPEG 3 API, using new parameters (`TJPARAM_XDENSITY`, `TJPARAM_YDENSITY`, and `TJPARAM_DENSITYUNITS`.)  These parameters can be set explicitly when compressing.  They are also set by `tj3LoadImage*()` when loading a Windows BMP file that contains pixel density information and by `tj3DecompressHeader()` when reading a JPEG header that contains such information.  `tj3SaveImage()` stores the values of the parameters to Windows BMP files that it creates, if the density units are in pixels/cm.
