### ISSUE TITLE
Invalid SOS parameters for sequential JPEG (and failed decompression)

### ISSUE THREAD

**Issue by belveder79** [libjpeg-turbo/libjpeg-turbo#778]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

no

**Clear and concise description of the bug:**

Library issues "Invalid SOS parameters for sequential JPEG" warning and fails decompression

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

Just try to use the "example decompress..."

**Image(s) needed in order to reproduce the bug (if applicable):**

https://www.dropbox.com/s/wfyrxu3klzwgdqs/20230927_113631.jpg?dl=0

**Expected behavior:**

Warning is non-fatal, and should give decompressed image.

**Observed behavior:**

Image is just a bluish mess-up

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

Intel MacOS Sonoma

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

certainly 2.x something, but also with latest 3.0.3

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

First of all, thx a lot for your great effort - I know that maintaining a project like this all alone is a huge effort - great job!
I know that the discussion about this SOS parameter came up quite a while ago, and it seems to be related to some Samsung Mobile phones (this is from an S20 I guess) and also some others. The image decompresses fine with regular jpeg library, so the question is why it does not with libjpeg-turbo? Probably you can find out...

**Comment by dcommander** [comment]
djpeg decompressed the image without issue (other than throwing the aforementioned warning, which is non-fatal by default.)  The issue was simply a bug in the example program, which has been fixed.

**Comment by belveder79** [comment]
@dcommander, sorry to bug you again. 

So I have still a question because how should this situation with the warning be handled? It is a warning as you said, therefore retval = -1. Ok, width and height are set correctly. I wanted to check if it is a warning, but the associated call returns FATAL_ERROR, although it should not (?)

Not sure if I'm doing something wrong, but it seems the only way is to check height/width? 

```C++
...
int retval = tjDecompressHeader3(handle, pkt.m_dataPtr, pkt.m_size, &width, &height, &jpegSubsamp, &jpegcolorspace);
int errc = tjGetErrorCode(handle); // <==== this one returns TJERR_FATAL, but it should not (?)
if(height > 0 && width > 0)
{
...
```

**Comment by dcommander** [comment]
`tjGetErrorCode()` is used to determine the severity of an error if an error code is returned from a function.  You need to check `retval` to determine that an error code has been returned before you call `tjGetErrorCode()`.

**Comment by belveder79** [comment]
Yes, but it does not work that way... that's what confuses me.

The SOS parameter is a warning and makes the return value -1 in this line
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/0acb084464a3f40070df19c503203ed99bbe02e2/turbojpeg.c#L1808
right? 
And the following tjGetErrorCode() returns 1, but it should return 0 according to 
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/0acb084464a3f40070df19c503203ed99bbe02e2/turbojpeg.c#L814

**Comment by belveder79** [comment]
forget about that... it seems to work now with if(retval == 0) - don't know why it did not so far... sorry for the noise...

**Comment by dcommander** [comment]
It works perfectly fine with TJBench, which uses the API in the correct and documented manner.  If you use the API in the correct and documented manner, then it will work for you as well.

**Comment by dcommander** [comment]
> forget about that... it seems to work now with if(retval == 0) - don't know why it did not so far... sorry for the noise...

The warning isn't thrown by `tj*DecompressHeader*()`.  It is thrown by `tj*Decompress*()`.

**Comment by belveder79** [comment]
right, my fault... thx
