### ISSUE TITLE
On Mac the library contains @rpath in install name, which is unfortunate with custom install location

### ISSUE THREAD

**Issue by clausmoltkeleth** [libjpeg-turbo/libjpeg-turbo#780]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**
Yes.

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**
No.

**Clear and concise description of the bug:**
I've built latest released version and the tip of the main branch on Mac (Intel and Silicon) using clang 14. In both cases the install location was a custom location. 

The problem is that the install name I get is a relative path, e.g. "@rpath/libjpeg.8.dylib", instead of an absolute path, e.g. {install_location}/lib/libjpeg8.dylib. 

The reason why this is a problem is that the JPEG library may be used by other open source libraries, e.g. QPDF. This means that the executables in the dependent library do not know the absolute path to JPEG library, and this may cause problems when trying to run the executables, especially when the executable is run from a script. For example, when running QPDF test scripts, all of the tests failed because the test programs were unable to locate the JPEG library, e.g. like this:

dyld[56162]: Library not loaded: '@rpath/libjpeg.8.dylib'
  Referenced from: '/System/Volumes/Data/SccsBin/MAC/MACOSX/OpenSource/qpdf-11.9.1/build/libtests/arg_parser'
  Reason: tried: '/usr/local/lib/libjpeg.8.dylib' (no such file), '/usr/lib/libjpeg.8.dylib' (no such file)
/tmp/test.sh: line 1: 56162 Abort trap: 6           ./arg_parser
 
The problem can however be worked around using install_name_tool to manually change the install name of libjpeg.dylib to an absolute path, but it would be nice to avoid having to make a manual workaround.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
In the following the environment variable $PREFIX is a custom installation directory (in my case it is /Users/OpenSource/OpenSource/local4).

- Unpack the source code and step into the source code directory
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DWITH_JPEG8=1 ..
- make
- (make test)
- make install

**Image(s) needed in order to reproduce the bug (if applicable):**

**Expected behavior:**
otool -D libjpeg.dylib should display the absolute path, in this case /Users/OpenSource/OpenSource/local4/libjpeg.8.dylib

**Observed behavior:**
otool -D libjpeg.dylib displayed the relative path @rpath/libjpeg.8.dylib

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
Clang 14.0.0 on macOS 12.7.5, Intel or Silicon architecture.

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
Tried with 3.0.3 and tip of main branch.

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

**Comment by dcommander** [comment]
CMake has several options to control that behavior.
https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling

**Comment by clausmoltkeleth** [comment]
Thank you, I will look into that.
