### ISSUE TITLE
Heap-Buffer-Overflow in tjDecompress2 Function

### ISSUE THREAD

**Issue by YancyLii** [libjpeg-turbo/libjpeg-turbo#782]
**Clear and concise description of the bug:**
A heap-buffer-overflow was detected in the tjDecompress2 function within the fuzzing test case LLVMFuzzerTestOneInput while using the TurboJPEG library. The issue arises due to an incorrect memory allocation size calculation, leading to an out-of-bounds write operation.

**Steps to reproduce the bug (using *only* libjpeg-turbo):**
1.Compile my testing code;
2.Use my input file as testing input;

**Image(s) needed in order to reproduce the bug (if applicable):**
![image](https://github.com/user-attachments/assets/155f2161-1109-45f5-b17d-e16d7c74f1db)

**Expected behavior:**
Not Crash

**Observed behavior:**
==35891==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x502000000011 at pc 0x5586b75c3b03 bp 0x7ffd4b218950 sp 0x7ffd4b218108
WRITE of size 32 at 0x502000000011 thread T0
    #0 0x5586b75c3b02 in memcpy (/volume/libjpeg-turbo/fuzzer/Test_libjpeg-turbo_Id73+0x14bb02) (BuildId: 8bb0102aedcec529a0da084563189eed2ee184ed)
    #1 0x5586b76726a0 in jcopy_sample_rows /volume/PromptDriver/exp/libjpeg-turbo/src/libjpeg-turbo/jutils.c:121:5
    #2 0x5586b771226c in grayscale_convert /volume/PromptDriver/exp/libjpeg-turbo/src/libjpeg-turbo/jdcolor.c:441:3
    #3 0x5586b767161b in sep_upsample /volume/PromptDriver/exp/libjpeg-turbo/src/libjpeg-turbo/jdsample.c:100:3
    #4 0x5586b771e758 in process_data_simple_main /volume/PromptDriver/exp/libjpeg-turbo/src/libjpeg-turbo/jdmainct.c:317:3
    #5 0x5586b766dd69 in jpeg_read_scanlines /volume/PromptDriver/exp/libjpeg-turbo/src/libjpeg-turbo/jdapistd.c:335:3
    #6 0x5586b760c8a6 in tj3Decompress8 /volume/PromptDriver/exp/libjpeg-turbo/src/libjpeg-turbo/turbojpeg-mp.c:270:7
    #7 0x5586b761f11a in tjDecompress2 /volume/PromptDriver/exp/libjpeg-turbo/src/libjpeg-turbo/turbojpeg.c:2005:10
    #8 0x5586b7603d3d in LLVMFuzzerTestOneInput /volume/PromptDriver/results/libjpeg-turbo/driver/Test_libjpeg-turbo_Id73.cc:78:9
    #9 0x5586b750f9d0 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/volume/libjpeg-turbo/fuzzer/Test_libjpeg-turbo_Id73+0x979d0) (BuildId: 8bb0102aedcec529a0da084563189eed2ee184ed)
    #10 0x5586b74f9b22 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/volume/libjpeg-turbo/fuzzer/Test_libjpeg-turbo_Id73+0x81b22) (BuildId: 8bb0102aedcec529a0da084563189eed2ee184ed)
    #11 0x5586b74ff566 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/volume/libjpeg-turbo/fuzzer/Test_libjpeg-turbo_Id73+0x87566) (BuildId: 8bb0102aedcec529a0da084563189eed2ee184ed)
    #12 0x5586b75286d2 in main (/volume/libjpeg-turbo/fuzzer/Test_libjpeg-turbo_Id73+0xb06d2) (BuildId: 8bb0102aedcec529a0da084563189eed2ee184ed)
    #13 0x7ff2b5a6fd8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #14 0x7ff2b5a6fe3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #15 0x5586b74f4b04 in _start (/volume/libjpeg-turbo/fuzzer/Test_libjpeg-turbo_Id73+0x7cb04) (BuildId: 8bb0102aedcec529a0da084563189eed2ee184ed)

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**
llvm 17
ubuntu 20.04

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**
3.0.3

**Additional information:**
Link of code and input:
https://drive.google.com/file/d/1j6xTncSS-CY5eIvZ0Hd3x1fME-y-51VV/view?usp=sharing

**Comment by dcommander** [comment]
The code is clearly incorrect and, in fact, appears to have been automatically generated.  The code allocates a 0-byte output buffer, so of course there will be a buffer overrun.  Correct code should call `tjDecompressHeader()` to figure out the size of the JPEG image so that it can allocate an output buffer of the appropriate size.

Proper fuzz testing involves using properly-written API code with arbitrary inputs.  Arbitrary code cannot be expected to work if it blatantly violates the documented API usage.  Similarly, you cannot expect to successfully write a character into a buffer allocated using `malloc(0)`.  That is what the code is essentially trying to do.  This project has a very limited budget with which to diagnose and fix security issues.  Please do not waste my time with fake security "issues" that you obviously haven't even spent two seconds of your own time investigating.  That is tantamount to spam.
