### ISSUE TITLE
Provides compression for images with YCCK color space

### ISSUE THREAD

**Issue by Ding-yixia** [libjpeg-turbo/libjpeg-turbo#785]
Provides compression for images with YCCK color space. I tried to decompress YCCK type images to CMYK first, and then compress CMYK, but the color of the image will change greatly

**Comment by Ding-yixia** [comment]
First, I used tjDecompressHeader3 to get the color space as TJCS_YCCK (enumeration value is 4).
```cpp
tjDecompressHeader3(Dehandle,jpg_buffer.get(),originImgSize,&imgWidth,&imgHeight,&img_subsamp,&img_colorspace);
```
Then I used tjDecompress2 to decompress the image with YCCK color space and specified the decompressed pixel format as TJPF_CMYK (enumeration value is 11)
```cpp
tjDecompress2(Dehandle,jpg_buffer.get(),originImgSize,outBuffer.get(),imgWidth,rowBytes,imgHeight,TJPF_CMYK,TJFLAG_PROGRESSIVE|TJFLAG_ACCURATEDCT) 
```
Then I compressed the decompressed YCCK image and specified that the image format to be compressed was TJPF_CMYK, and the sampling selected was TJSAMP_444 (in fact, I tried all samplings)

```cpp
tjCompress2(handle,outBuffer.get(),imgWidth,rowBytes,imgHeight,TJPF_CMYK,&outJpgBuffer,&outJpgsize,img_subsamp,ImgQuality,TJFLAG_PROGRESSIVE|TJFLAG_ACCURATEDCT)
```
In order to output the image, I used a function to output the image before and after compression, and found that the image color changed too obviously, and it seemed that the color was lost.
```cpp
writebuffer2file(compressedImgPath,outJpgBuffer,outJpgSize);
```
As you can see, this is my process of compressing YCCK color space images using turbojpeg, but I can't find a way to do it correctly, I hope to get your opinion and help

**Comment by dcommander** [comment]
I don't know what you mean by "the image color changed too obviously."  JPEG is a lossy compression process, so some color loss is inevitable.  TJUnitTest validates that, when using `TJSAMP_444` and a JPEG quality of 100, the loss is minimal (within a tolerance of +/- 1 for all components.)  TJUnitTest tests CMYK --> YCCK --> CMYK as well, and our CI system runs TJUnitTest whenever a new commit is pushed.  Thus, we know that the CMYK pipeline is correct, at least within that context. 
It's impossible for me to know what is going wrong, because you haven't posted a working code sample or images that show the issue.

Note that most image viewers won't display CMYK images correctly.  You have to use a program like Photoshop that has color management capabilities in order to properly display CMYK images.

**Comment by Ding-yixia** [comment]
I used `PDFium` to get the DCTDecode type image in the PDF (the color space of the image can be obtained through pdfxplore software, which is CMYK type).
![image](https://github.com/user-attachments/assets/1f9ec9c3-83b2-46b0-ae12-025666f32b29)
But the color space of the image obtained by `tjDecompressHeader3` is of type `TJCS_YCCK`, so I first used tjDecompress2 to decompress it, and the pixel format obtained was `TJPF_CMYK`. Finally, I used `tjCompress2` to compress the decompressed data, and specified the pixel format as `TJPF_CMYK` obtained in the previous step.

Below I will show two images, first the image before compression (the exported image is not consistent with the image in the PDF, it will change, so I can only provide a reference for color changes)

![1749页-1-1](https://github.com/user-attachments/assets/d061d134-9ba3-417c-bc41-d64b503385dd)

Here is the compressed image:

![1749页-0-0](https://github.com/user-attachments/assets/243ba77e-7ca1-4e44-b205-b716dec98de6)

Sorry, I can't make the full code publicly available, but please provide an email address and I can write some examples for you. Thanks for your help

**Comment by dcommander** [comment]
You can e-mail me here:
https://libjpeg-turbo.org/About/Contact

**Comment by dcommander** [comment]
NOTE: Another way to test CMYK --> YCCK --> CMYK is by using tjbench with the `-cmyk` option.  tjbench only handles RGB input images, so when you test the CMYK pipeline, it uses quick & dirty (i.e. incorrect, non-color-managed) RGB-to-CMYK and CMYK-to-RGB algorithms.  However, you can at least verify that the input and output images look similar, which they do.  Thus, my strong suspicion is a coding error on your end, not a bug in libjpeg-turbo.

**Comment by dcommander** [comment]
Closing due to lack of response.
