### ISSUE TITLE
Configuring libjpeg-turbo fails on Windows when using the LLVM/clang compiler

### ISSUE THREAD

**Issue by qmfrederik** [libjpeg-turbo/libjpeg-turbo#786]
**Have you searched the existing issues (both open and closed) in the libjpeg-turbo issue tracker to ensure that this bug report is not a duplicate?**

Yes

**Does this bug report describe one of the [two known and unsolvable issues with the JPEG format](https://libjpeg-turbo.org/pmwiki/uploads/About/TwoIssueswiththeJPEGStandard.pdf)?**

No

**Clear and concise description of the bug:**

Configuring libjpeg-turbo fails on Windows when using the LLVM/clang compiler

**Steps to reproduce the bug (using *only* libjpeg-turbo):**

1. On Windows, install Clang and the Windows SDK
2. Clone the libjpeg-turbo repository
3. Configure libjpeg-turbo using CMake and the Ninja compiler: `mkdir build && cd build && cmake .. -GNinja`

**Image(s) needed in order to reproduce the bug (if applicable):**

N/A

**Expected behavior:**

Configure to succeed.

**Observed behavior:**

Configure fails with the following output:

```
C:\[..]\libjpeg-turbo\build>cmake .. -GNinja
-- The C compiler identification is Clang 18.1.6 with GNU-like command-line
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/LLVM/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_BUILD_TYPE = Debug
-- VERSION = 3.0.4, BUILD = 20240909
-- 64-bit build (x86_64)
-- CMAKE_INSTALL_PREFIX = c:/libjpeg-turbo-gcc64
-- CMAKE_INSTALL_BINDIR = bin (c:/libjpeg-turbo-gcc64/bin)
-- CMAKE_INSTALL_DATAROOTDIR =  (c:/libjpeg-turbo-gcc64)
-- CMAKE_INSTALL_DOCDIR = doc (c:/libjpeg-turbo-gcc64/doc)
-- CMAKE_INSTALL_INCLUDEDIR = include (c:/libjpeg-turbo-gcc64/include)
-- CMAKE_INSTALL_LIBDIR = lib (c:/libjpeg-turbo-gcc64/lib)
-- Shared libraries enabled (ENABLE_SHARED = 1)
-- Static libraries enabled (ENABLE_STATIC = 1)
-- Arithmetic decoding support enabled (WITH_ARITH_DEC = 1)
-- Arithmetic encoding support enabled (WITH_ARITH_ENC = 1)
-- TurboJPEG API library enabled (WITH_TURBOJPEG = 1)
-- TurboJPEG Java wrapper disabled (WITH_JAVA = 0)
-- Emulating libjpeg API/ABI v6.2 (WITH_JPEG7 = 0, WITH_JPEG8 = 0)
-- libjpeg API shared library version = 62.4.0
-- Compiler flags =  -O0
-- Linker flags =
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Performing Test HIDDEN_WORKS
-- Performing Test HIDDEN_WORKS - Success
-- HIDDEN = __attribute__((visibility("hidden")))
-- Performing Test INLINE_WORKS
-- Performing Test INLINE_WORKS - Success
-- INLINE = __inline__ __attribute__((always_inline)) (FORCE_INLINE = 1)
-- Performing Test HAVE_THREAD_LOCAL
-- Performing Test HAVE_THREAD_LOCAL - Success
-- THREAD_LOCAL = __thread
-- CMAKE_EXECUTABLE_SUFFIX = .exe
-- Looking for a ASM_NASM compiler
-- Looking for a ASM_NASM compiler - NOTFOUND
CMake Warning at simd/CMakeLists.txt:5 (message):
  SIMD extensions disabled: could not find NASM compiler.  Performance will
  suffer.
Call Stack (most recent call first):
  simd/CMakeLists.txt:48 (simd_fail)


-- FLOATTEST8 = no-fp-contract
-- FLOATTEST12 = no-fp-contract
CMake Error: File C:/Users/fredcarl/source/repos/libjpeg-turbo/win/projectTargets-release.cmake.in does not exist.
CMake Error at cmakescripts/BuildPackages.cmake:106 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1820 (include)


-- Configuring incomplete, errors occurred!
```

**Platform(s) (compiler version, operating system version, CPU) on which the bug was observed:**

Windows 10 & 11

Clang 18.1.6:

```
clang version 18.1.6
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

**libjpeg-turbo release(s), commit(s), or branch(es) in which the bug was observed (always test the tip of the main branch or the latest [stable pre-release](https://libjpeg-turbo.org/DeveloperInfo/PreReleases) to verify that the bug hasn't already been fixed):**

`master`

**If the bug is a regression, the specific commit that introduced the regression (use `git bisect` to determine this):**

**Additional information:**

[`BuildPackages.cmake`](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/cmakescripts/BuildPackages.cmake#L69-L80)
checks for the Visual C++ compiler and MinGW (one is a compiler, the other a platform, which supports both clang and GCC), but does not check for the Clang compiler on native Windows.

**Comment by dcommander** [comment]
Referring to the build instructions in **BUILDING.md**, you need to install NASM or Yasm and put it in your `PATH`.

**Comment by qmfrederik** [comment]
@dcommander Sorry, but that's not the issue here, even with nasm installed it fails because [BuildPackages.cmake](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/cmakescripts/BuildPackages.cmake#L69-L80) does not correctly handle the clang compiler on Windows:

```
C:\Users\fredcarl\source\repos\libjpeg-turbo\build2>cmake .. -GNinja
-- The C compiler identification is Clang 18.1.6 with GNU-like command-line
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/LLVM/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_BUILD_TYPE = Debug
-- VERSION = 3.0.4, BUILD = 20240909
-- 64-bit build (x86_64)
-- CMAKE_INSTALL_PREFIX = c:/libjpeg-turbo-gcc64
-- CMAKE_INSTALL_BINDIR = bin (c:/libjpeg-turbo-gcc64/bin)
-- CMAKE_INSTALL_DATAROOTDIR =  (c:/libjpeg-turbo-gcc64)
-- CMAKE_INSTALL_DOCDIR = doc (c:/libjpeg-turbo-gcc64/doc)
-- CMAKE_INSTALL_INCLUDEDIR = include (c:/libjpeg-turbo-gcc64/include)
-- CMAKE_INSTALL_LIBDIR = lib (c:/libjpeg-turbo-gcc64/lib)
-- Shared libraries enabled (ENABLE_SHARED = 1)
-- Static libraries enabled (ENABLE_STATIC = 1)
-- Arithmetic decoding support enabled (WITH_ARITH_DEC = 1)
-- Arithmetic encoding support enabled (WITH_ARITH_ENC = 1)
-- TurboJPEG API library enabled (WITH_TURBOJPEG = 1)
-- TurboJPEG Java wrapper disabled (WITH_JAVA = 0)
-- Emulating libjpeg API/ABI v6.2 (WITH_JPEG7 = 0, WITH_JPEG8 = 0)
-- libjpeg API shared library version = 62.4.0
-- Compiler flags =  -O0
-- Linker flags =
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Performing Test HIDDEN_WORKS
-- Performing Test HIDDEN_WORKS - Success
-- HIDDEN = __attribute__((visibility("hidden")))
-- Performing Test INLINE_WORKS
-- Performing Test INLINE_WORKS - Success
-- INLINE = __inline__ __attribute__((always_inline)) (FORCE_INLINE = 1)
-- Performing Test HAVE_THREAD_LOCAL
-- Performing Test HAVE_THREAD_LOCAL - Success
-- THREAD_LOCAL = __thread
-- CMAKE_EXECUTABLE_SUFFIX = .exe
-- Looking for a ASM_NASM compiler
-- Looking for a ASM_NASM compiler - C:/Program Files/NASM/nasm.exe
-- The ASM_NASM compiler identification is NASM
-- Found assembler: C:/Program Files/NASM/nasm.exe
-- CMAKE_ASM_NASM_COMPILER = C:/Program Files/NASM/nasm.exe
-- CMAKE_ASM_NASM_OBJECT_FORMAT = win64
-- CMAKE_ASM_NASM_FLAGS =  -DWIN64 -D__x86_64__ -g
-- SIMD extensions: x86_64 (WITH_SIMD = 1)
-- FLOATTEST8 = sse
-- FLOATTEST12 = no-fp-contract
CMake Error: File C:/Users/fredcarl/source/repos/libjpeg-turbo/win/projectTargets-release.cmake.in does not exist.
CMake Error at cmakescripts/BuildPackages.cmake:106 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1820 (include)


-- Configuring incomplete, errors occurred!
```

**Comment by dcommander** [comment]
I know that our build system works with clang-cl.  However, you may be the first person who has tested it with the GNU-like clang command line.  The build system relies upon variables that CMake defines in order to tell it which compiler is in use.  If you can tell me more about how you are configuring the build, I can try to reproduce the issue and see what's wrong.

**Comment by qmfrederik** [comment]
Sure, what you need is LLVM (download [LLVM-18.1.8-win64.exe](https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/LLVM-18.1.8-win64.exe) from https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.8) and the Windows SDK.  If you have Visual Studio installed, you should have the Windows SDK installed.

In that setup, you should be able to just run `cmake .. -GNinja`.  It should automatically detect clang for you, and you should get output like this:

```
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/LLVM/bin/clang.exe - skipped
```

which confirms it picked up the Clang compiler.

The problem then is that [BuildPackages](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/cmakescripts/BuildPackages.cmake#L69-L80) does not detect the clang compiler and `INST_ID` is not being set.

The easiest workaround is to run `cmake .. -GNinja -DINST_ID=vc`, but I'm not sure if you'd consider clang an equivalent for vc or if you want to give its own INST_ID.

**Comment by dcommander** [comment]
OK, I'll see what I can do, but the build system as currently implemented has only been tested with Microsoft's Clang implementation, not the generic implementation. Whether or not I can support the generic implementation depends on how well CMake supports it.

**Comment by dcommander** [comment]
Unfortunately, it isn't a simple matter of tweaking **BuildPackages.cmake**.  The native Windows implementation of LLVM doesn't neatly fit into either the Visual C++ or MinGW paradigm.  It generates **.obj**, **.lib**, and **.dll** files like Visual C++, but in other respects it needs to be handled like MinGW.  In order to handle it properly, I really need to be able to detect it using CMake variables, and I'm not sure how to do that at the moment.

**Comment by dcommander** [comment]
It should work now.

**Comment by qmfrederik** [comment]
Yes, it does. Thanks!
