### ISSUE TITLE
[Question] Will libjpeg-turbo support RISC-V's SIMD/Vector in the futher?

### ISSUE THREAD

**Issue by guoyuqi020** [libjpeg-turbo/libjpeg-turbo#794]
I'm trying to use libjpeg-turbo on a riscv64 machine.
I found that the SIMD feature is disabled on RISC-V machines and thus the program ran quite slowly.

I know that libjpeg-turbo does not officially support RISC-V platforms.
I'm just curious whether will you consider adding support to RISC-V's SIMD/Vector in the future.

Thanks.

**Comment by dcommander** [comment]
Duplicate of #620.  Please follow the discussion there.  I added a new comment just now (https://github.com/libjpeg-turbo/libjpeg-turbo/issues/620#issuecomment-2468504444) that explains the current situation.
