### ISSUE TITLE
low memory implementation for lossless transformation

### ISSUE THREAD

**Issue by jaisoc** [libjpeg-turbo/libjpeg-turbo#83]
Hi,
I was looking to open this issue in <https://github.com/komakai/libjpeg-turbo>
But since I was unable to open an issue there, I am opening it here because this is the next closest repository. 
The forked version of the library works great for low memory devices without compromising a great deal on performance.

1.Have the fork being merged into the mainstream libjpeg-turbo?
2.Is there an equivalent low memory implementation for lossless jpeg transformations as well?

**Comment by dcommander** [comment]
1. The low-memory progressive decoding technology cannot be merged in its current state, because it breaks backward API/ABI compatibility in the following areas:
    1. It extends the public jpeg_decompress_struct structure.  It should be possible to move these new structure members into the opaque jpeg_decomp_master struct and provide accessor methods as necessary, but that would be a significant effort.
    2. It extends the public jpeg_source_mgr struct, as well as the public jpeg_memory_mgr struct.  I don't know if there's any way to accommodate that without breaking backward API/ABI compatibility.  Someone would need to figure out how to make these structure extensions opaque.

2. Probably not, but you'd have to ask @komakai, as this is his fork.  I cannot provide any support for downstream forks.

**Comment by komakai** [comment]
> I was looking to open this issue in https://github.com/komakai/libjpeg-turbo

Looks like I didn't have issues enabled. They should be enabled now - please try reposting this there.

> I cannot provide any support for downstream forks.

Sorry for the trouble
