### ISSUE TITLE
Hello，Is TurboJpeg::Compress supporting to compress   one channel TJPF_GRAY image？

### ISSUE THREAD

**Issue by idvr** [libjpeg-turbo/libjpeg-turbo#85]

**Comment by mousomer** [comment]
I use tjCompressFromYUVPlanes - which gives you, among other things, the ability to decide you just want to save the grayscale channel. I personally find the the most convenient and versatile method in the class.

`tjCompressFromYUVPlanes(tjhandle handle,
	unsigned char **srcPlanes, int width, int *strides, int height, int subsamp,
	unsigned char **jpegBuf, unsigned long *jpegSize, int jpegQual, int flags)`

Use `TJSAMP_GRAY` as the `subsamp` flag, and put a pointer to an array of buffer pointers as the `jpegBuf`.

**Comment by dcommander** [comment]
I'm not sure what question is being asked here.  TurboJpeg::Compress is not a class that is part of libjpeg-turbo.  It sounds like a downstream class or a wrapper, not something that we provide.  Our compression methods are:

C:
tjCompress2()

Java:
org.libjpegturbo.turbojpeg.TJCompressor.compress()

Those methods definitely do support grayscale images.  Anything outside of the scope of our code is not something we can address.  Please contact whoever developed the TurboJpeg::Compress method you are using.
